### DISCUSSION TITLE
Summary of Updates as a notification

### DISCUSSION THREAD

**Discussion by rg9400** [containrrr/watchtower#1009] [Feature Requests] [answered]
Right now, Shoutrr/Slack notifications are way too verbose at Info level. They send multiple notifications per container. It sends a notification for found new image, stopping old image, creating new image, starting new image. That is 4 alerts for a single container being updated. If I have many containers requiring updates, then the notifications end up truncated as shown below, which is very cumbersome as it is not readily evident which containers were omitted. Overall, these notifications are not particularly user friendly, even if they look nice. If you reduce the logging level, then you end up not getting notifications for which containers got updated.

My FR is to create a notification level that just sends a summary of the update run (if updates were found). Ideally, in a single message, it just sends which containers were updated which is the most relevant information, though if there is space, I guess you can also include the shortform prior hash -> new hash. This would be much more useful because it would allow me to enable push notifications on these alerts, and from my phone be able to see the summary of the run in a simple message. Right now, if I enable push messages, it means I would be getting 4+ messages per run

![image](https://user-images.githubusercontent.com/39887349/124040745-1f33a980-d9cb-11eb-88ce-c1d19290b93c.png)

**Comment by piksel** [comment, marked as answer]
Yeah, that is what the PR that caused the issue described implemented. Or rather, support for it in the templates. It's an opt-in feature that needs --notification-report to be activated. The default template does not behave the way you describe though, but it can be accomplished with a custom template.

**Reply by rg9400** [reply]
Thanks, I noticed the new flag which I added to my compose. For custom templates, is there a way to configure it using a file? I saw the example using environment variables/arguments, but with compose, it seems complicated to get the below template due to it being multiline, though it seems to be what I am looking for

```go
{{with .Report -}}
  {{len .Scanned}} Scanned, {{len .Updated}} Updated
  {{range .Scanned}}
     - {{.Name}} ({{.ImageName}}): {{.State}}
  {{end}}
{{- end}}
```

**Reply by piksel** [reply]
You don't have to use multi-line but using dict env variable syntax makes it easy:
 ```yaml
env:
  WATCHTOWER_NOTIFICATION_TEMPLATE: |-
    {{with .Report -}}
      {{len .Scanned}} Scanned, {{len .Updated}} Updated
      {{range .Scanned}}
         - {{.Name}} ({{.ImageName}}): {{.State}}
      {{end}}
    {{- end}}
```

**Reply by piksel** [reply]
Oh, and btw. It doesn't send multiple messages, it's just a single message with multiple "parts" for discord.
This was added to mimic how the slack notifications looked, but you can turn it off by adding `?splitLines=no` to your shoutrrr URL.

**Reply by rg9400** [reply]
I was trying to set this up earlier, but I keep getting 400 bad requests from Discord using the below template. Any idea what I am missing?

```yaml
    environment:
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_SCHEDULE: 0 0 * * * *
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: https://discord.com/api/webhooks/${WATCHTOWERWEBHOOK}/slack
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: Watchtower
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_URL: https://raw.githubusercontent.com/containrrr/watchtower/master/logo.png
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{with .Report -}}
          {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed, {{len .Stale}} Stale
          {{range .Updated}}
             - {{.ImageName}}: {{.State}}
          {{end}}
          {{range .Failed}}
            - {{.ImageName}}: {{.State}}
          {{end}}
          {{range .Stale}}
            - {{.ImageName}}: {{.State}}
          {{end}}
        {{- end}}
      DOCKER_CONFIG: /config
 ```
