### DISCUSSION TITLE
Watchtower notification with outlook

### DISCUSSION THREAD

**Discussion by daschmidt1994** [containrrr/watchtower#1017] [Q&A]
When I trie to get notification with outlook, there is an error: 

```
Failed to send notification via shoutrrr (url=smtp://xxxxx%40outlook.at:xxxxxx@smtp-mail.outlook.com:587/?auth=Plain&fromaddress=xxxxxxxx%40outlook.at&fromname=Watchtower&subject=Watchtower+updates+on+2e5656c54cbc&toaddresses=xxxxx%40outlook.at):  failed to send using smtp: timed out
```

My docker-compose is : 
```yaml
version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        WATCHTOWER_NOTIFICATIONS: email
        WATCHTOWER_NOTIFICATION_EMAIL_FROM: xxxx@outlook.at
        WATCHTOWER_NOTIFICATION_EMAIL_TO: xxxx@outlook.at
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp-mail.outlook.com
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: xxxxx@outlook.at
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: xxxx
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
        WATCHTOWER_SCHEDULE: 0 0 5 * * *
        WATCHTOWER_CLEANUP: 'true'
        WATCHTOWER_TIMEOUT: 30s
        WATCHTOWER_NOTIFICATIONS_LEVEL: info
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: 'yes'
        TZ: Europe/Berlin
```

If I change it to my old gmail-account it works whats wrong?
