### DISCUSSION TITLE
Is watchtower scanning any containers ?

### DISCUSSION THREAD

**Discussion by coderunway** [containrrr/watchtower#1042] [Q&A] [answered]
I think Watchtower is not scanning containers. Can anyone tell me what am I doing wrong here.. 

I have 5 containers running. I'm running watchtower also as a container on my Synology NAS.  I configured the watchtower with the below docker-compose file and used the command _**sudo docker-compose up -d_**  to bring up watchtower container. 

```yaml
version: '3'
services:
   watchtower:
      container_name: watchtower
      restart: always
      image: containrrr/watchtower
      environment:
      - TZ=Asia/Kolkata
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      command: --debug true --interval 86400
```

However, when I check the watchtower logs every day, I see the line as below, which states "0 scanned". 

_"time="2021-07-30T01:28:20+05:30" level=debug msg="Session done: 0 scanned, 0 updated, 0 failed"_ 

Here is the log
```
time="2021-07-29T01:28:17+05:30" level=debug msg="Making sure everything is sane before starting",
time="2021-07-29T01:28:17+05:30" level=debug msg="Retrieving running containers",
time="2021-07-29T01:28:20+05:30" level=debug msg="There are no additional watchtower containers",
time="2021-07-29T01:28:20+05:30" level=debug msg="Watchtower HTTP API skipped.",
time="2021-07-29T01:28:20+05:30" level=info msg="Watchtower 1.3.0\nUsing no notifications\nOnly checking containers with name \"true\"\nScheduling first run: 2021-07-30 01:28:20 +0530 IST\nNote that the first check will be performed in 23 hours, 59 minutes, 59 seconds",
time="2021-07-30T01:28:20+05:30" level=debug msg="Checking containers for updated images",
time="2021-07-30T01:28:20+05:30" level=debug msg="Session done: 0 scanned, 0 updated, 0 failed",
time="2021-07-30T01:28:20+05:30" level=debug msg="Retrieving running containers",
time="2021-07-30T01:28:20+05:30" level=debug msg="Scheduled next run: 2021-07-31 01:28:20 +0530 IST"
```
