### DISCUSSION TITLE
set specific run time

### DISCUSSION THREAD

**Discussion by urza-lab** [containrrr/watchtower#1056] [Q&A] [answered]
hi guys. is there a way to set up watchtower to run at a specific time using docker compose environment variables? in https://containrrr.dev/watchtower/arguments/ i read only about intervals, but not time points.

**Comment by urza-lab** [comment, marked as answer]
i have re-read the arguments section and found the solution: add 'WATCHTOWER_SCHEDULE=cronexpression' to the environment

feel free to refer to my docker compose as an example:

```
watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      environment:
         - TZ=Europe/whatever
         - WATCHTOWER_CLEANUP=true
         - WATCHTOWER_SCHEDULE=0 0 3 * * *
```

please note, that the schedule format requires also an input for seconds. if you follow https://crontab-generator.org/, you would have a "0" too little and watchtower running on every hour, minute 3.
