### DISCUSSION TITLE
Failed to send notification via shoutrrr ... response status code 404 Not Found

### DISCUSSION THREAD

**Discussion by ondergur** [containrrr/watchtower#1131] [Q&A]
Hi,
I am getting this interesting error message recently when I restarted or whenever whatchtower finds a new container and updates it.

`Failed to send notification via shoutrrr  (url=teams://https%3A:@<organization>.webhook.office.com):  failed to send notification to teams, response status code 404 Not Found`

When I tried to use the webhook url manually via curl I can push notification to my Teams channel but seems like watchtower can't.

  ```
watchtower:
    image: containrrr/watchtower
    ports:
      - 50415:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./watchtower/config.json:/config.json
      - helper:/go/bin
    environment:
      - WATCHTOWER_NOTIFICATIONS=msteams
      - WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL=https://<org>.webhook.office.com/webhookb2/<blabla>/IncomingWebhook/<blabla>
      - WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA=true
      - HOME=/
      - PATH=$PATH:/go/bin
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=<someKeyHere>
      - AWS_ACCESS_KEY_ID=<someIdHere>
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_LABEL_ENABLE=true
```

I was getting notification until 2 weeks and didn't change any configuration recently. This popped out of nowhere. Do you have any clue?
