### DISCUSSION TITLE
Watchtower use to update my docker hub containers, but now fails with 401 unauthorized error

### DISCUSSION THREAD

**Discussion by pkellner** [containrrr/watchtower#1144] [Q&A] [answered]
**Describe the bug**
I had a simple linux docker server running ubuntu 20 that worked flawlessly with Watchtower.  As I'd check in new images, the would automatically get pulled.

At some point in the past few months, Watchtower has started creating 401 errors checking for the images on the docker hub registry.

I posted more files at SO here:

https://stackoverflow.com/questions/70157157/getting-a-new-auth-error-with-docker-and-watchtower

**Expected behavior**
Expected new container to be updated instead of 401 error

**Comment by github-actions** [comment]
Hi there! 👋🏼 As you're new to this repo, we'd like to suggest that you read our [code of conduct](https://github.com/containrrr/.github/blob/master/CODE_OF_CONDUCT.md) as well as our [contribution guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md). Thanks a bunch for opening your first issue! 🙏

**Comment by piksel** [comment, marked as answer]
That's not an error. It's just part of standard HTTP auth. It first does a request without authentication to query the server for what types it supports.

**Reply by pkellner** [reply]
I have an auth token from Docker Hub, but I can't seem to get Watchtower to send it.  It keeps sending a token from some location I can't find. I have set it in my docker-compose file as shown below.  How can I force Watchtower to use the WATCHTOWER_HTTP_API_TOKEN and ignore any other?

```
services:
    watchtower:
      image: index.docker.io/containrrr/watchtower:latest
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/timezone:/etc/timezone:ro
      environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_LABEL_ENABLE=false
        - WATCHTOWER_INCLUDE_RESTARTING=true
        - WATCHTOWER_DEBUG=true
        - WATCHTOWER_TRACE=true
        - WATCHTOWER_POLL_INTERVAL=20
        - WATCHTOWER_HTTP_API_TOKEN=8a049ba8-xxxxxxxx
        
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
    webgraphql:
```
