### DISCUSSION TITLE
Monitor only not respected.

### DISCUSSION THREAD

**Discussion by mrskizzex** [containrrr/watchtower#1147] [Q&A] [answered]
**Describe the bug**
Monitor only flag is set but is not respected, watchtower updated the image regardless.

**To Reproduce**
watchtower docker-compose.yml :

```yaml
version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_MONITOR_ONLY='true'
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxx@xxx.xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx@xxx.xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=xxx.xxx.xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx@xxx.xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xxx
      - TZ=Europe/Warsaw
networks:
  backend:
    external: true
```

**Expected behavior**
Watchtower should only send notifications via email that there is an updated image availible.

**Screenshots**
```
time="2021-11-26T23:36:34+01:00" level=info msg="Watchtower 1.3.0\nUsing notifications: smtp\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-11-27 23:36:34 +0100 CET\nNote that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
time="2021-11-30T23:37:09+01:00" level=info msg="Found new redis:alpine image (3900abf41552)"
time="2021-11-30T23:37:09+01:00" level=info msg="Stopping /authelia_redis_1 (1b5cf7f57c3e) with SIGTERM"
time="2021-11-30T23:37:16+01:00" level=info msg="Creating /authelia_redis_1"

```
**Environment**
OS Information | linux x86_64 Debian GNU/Linux 11 (bullseye)
Kernel Version | 5.10.0-9-amd64
Docker Version | 20.10.5+dfsg1 (API: 1.41)

**Comment by github-actions** [comment]
Hi there! 👋🏼 As you're new to this repo, we'd like to suggest that you read our [code of conduct](https://github.com/containrrr/.github/blob/master/CODE_OF_CONDUCT.md) as well as our [contribution guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md). Thanks a bunch for opening your first issue! 🙏

**Comment by piksel** [comment, marked as answer]
I *think* this is due to the YAML format. Try using:
```yaml
      WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: xxx@xxx.xxx
      WATCHTOWER_NOTIFICATION_EMAIL_TO: xxx@xxx.xxx
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: xxx.xxx.xxx
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: '587'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: xxx@xxx.xxx
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: xxx
```
or
```yaml
      - WATCHTOWER_MONITOR_ONLY=true
```
