### DISCUSSION TITLE
Not able to exclude containers from watchtower trying to update them

### DISCUSSION THREAD

**Discussion by minifisk** [containrrr/watchtower#1161] [Q&A]
I have a docker-compose file with 4 containers, including the watchtower container. It does a great job at updating my web-container, however when I check the logs for the watchtower container it's FLOODED with other pulls for my other containers. I don't want that. I tried two different ways to exclude the other containers, first one is just putting the name of the only container I want it to monitor (web) in the command section of the watchtower container:

```yaml
version: '3.8'

services:

  web:
    container_name: web
    restart: always
    # ....
  
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    # ....
  
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    # ....

  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower 
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env.prod
    command: --interval 120 web


volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
``` 

This don't work, I still get logs for failing to pull from all the different containers, the other way I've tried is to work with labels, which don't work either:

```yaml
version: '3.8'

services:

  web:
    container_name: web
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # ...
  
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    # ...
  
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    # ...

  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower 
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env.prod
    command: --interval 120  --label-enable


volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
```

This is how my logs look like:

```
time="2021-12-15T10:31:21Z" level=info msg="Stopping /web (d9940153d93d) with SIGTERM"
time="2021-12-15T10:31:22Z" level=info msg="Creating /web"
time="2021-12-15T10:31:23Z" level=info msg="Removing image dbd31b664ef1"
Failed to send notification via shoutrrr (url=smtp://server%40myrepo.se:C8ZBL3_dYUK%40cMf@mymailserver.se:465/?auth=Plain&fromaddress=server%40myrepo.se&fromname=Watchtower&subject=Watchtower+updates+on+7582a1489f37&toaddresses=myemail%40gmail.com):  failed to send using smtp: timed out
time="2021-12-15T10:31:34Z" level=warning msg="Could not do a head request for \"index.docker.io/myusername/myrepo:latest\", falling back to regular pull." container=/web image="index.docker.io/myusername/myrepo:latest"
time="2021-12-15T10:31:34Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:myusername/myrepo:pull\\\"\"" container=/web image="index.docker.io/myusername/myrepo:latest"
time="2021-12-15T10:31:36Z" level=warning msg="Could not do a head request for \"jrcs/letsencrypt-nginx-proxy-companion:latest\", falling back to regular pull." container=/myrepo_nginx-proxy-letsencrypt_1 image="jrcs/letsencrypt-nginx-proxy-companion:latest"
time="2021-12-15T10:31:36Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:jrcs/letsencrypt-nginx-proxy-companion:pull\\\"\"" container=/myrepo_nginx-proxy-letsencrypt_1 image="jrcs/letsencrypt-nginx-proxy-companion:latest"
time="2021-12-15T10:31:38Z" level=warning msg="Could not do a head request for \"containrrr/watchtower:latest\", falling back to regular pull." container=/myrepo_watchtower_1 image="containrrr/watchtower:latest"
time="2021-12-15T10:31:38Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:containrrr/watchtower:pull\\\"\"" container=/myrepo_watchtower_1 image="containrrr/watchtower:latest"
time="2021-12-15T10:31:40Z" level=warning msg="Could not do a head request for \"myrepo_nginx-proxy:latest\", falling back to regular pull." container=/nginx-proxy image="myrepo_nginx-proxy:latest"
time="2021-12-15T10:31:40Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:library/myrepo_nginx-proxy:pull\\\"\"" container=/nginx-proxy image="myrepo_nginx-proxy:latest"
time="2021-12-15T10:31:41Z" level=info msg="Unable to update container \"/nginx-proxy\": Error response from daemon: pull access denied for myrepo_nginx-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
Failed to send notification via shoutrrr (url=smtp://server%40myrepo.se:C8ZBL3_dYUK%40cMf@mymailserver.se:465/?auth=Plain&fromaddress=server%40myrepo.se&fromname=Watchtower&subject=Watchtower+updates+on+7582a1489f37&toaddresses=myemail%40gmail.com):  failed to send using smtp: timed out
time="2021-12-15T10:32:04Z" level=warning msg="Could not do a head request for \"index.docker.io/myusername/myrepo:latest\", falling back to regular pull." container=/web image="index.docker.io/myusername/myrepo:latest"
time="2021-12-15T10:32:04Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:myusername/myrepo:pull\\\"\"" container=/web image="index.docker.io/myusername/myrepo:latest"
time="2021-12-15T10:32:06Z" level=warning msg="Could not do a head request for \"jrcs/letsencrypt-nginx-proxy-companion:latest\", falling back to regular pull." container=/myrepo_nginx-proxy-letsencrypt_1 image="jrcs/letsencrypt-nginx-proxy-companion:latest"
time="2021-12-15T10:32:06Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:jrcs/letsencrypt-nginx-proxy-companion:pull\\\"\"" container=/myrepo_nginx-proxy-letsencrypt_1 image="jrcs/letsencrypt-nginx-proxy-companion:latest"
time="2021-12-15T10:32:08Z" level=warning msg="Could not do a head request for \"containrrr/watchtower:latest\", falling back to regular pull." container=/myrepo_watchtower_1 image="containrrr/watchtower:latest"
time="2021-12-15T10:32:08Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:containrrr/watchtower:pull\\\"\"" container=/myrepo_watchtower_1 image="containrrr/watchtower:latest"
time="2021-12-15T10:32:10Z" level=warning msg="Could not do a head request for \"myrepo_nginx-proxy:latest\", falling back to regular pull." container=/nginx-proxy image="myrepo_nginx-proxy:latest"
time="2021-12-15T10:32:10Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:library/myrepo_nginx-proxy:pull\\\"\"" container=/nginx-proxy image="myrepo_nginx-proxy:latest"
time="2021-12-15T10:32:11Z" level=info msg="Unable to update container \"/nginx-proxy\": Error response from daemon: pull access denied for myrepo_nginx-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
Failed to send notification via shoutrrr (url=smtp://server%40myrepo.se:C8ZBL3_dYUK%40cMf@mymailserver.se:465/?auth=Plain&fromaddress=server%40myrepo.se&fromname=Watchtower&subject=Watchtower+updates+on+7582a1489f37&toaddresses=myemail%40gmail.com):  failed to send using smtp: timed out
```
