### DISCUSSION TITLE
Cannot send e-mail from watchtower but can from shoutrrr

### DISCUSSION THREAD

**Discussion by kwijbrans** [containrrr/watchtower#1166] [Q&A] [answered]
When trying to configure the sending of e-mail in watchtower I get the error:
```
time="2021-12-18T13:26:50Z" level=info msg="Watchtower 1.3.0\nUsing notifications: smtp\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-12-18 13:27:50 +0000 UTC\nNote that the first check will be performed in 59 seconds"
Failed to send notification via shoutrrr (url=smtp://watchtower%40example.com:abc123@mail.example.com:587/?auth=Plain&fromaddress=watchtower%40example.com&fromname=Watchtower&subject=Watchtower+updates+on+05bdc4d8eea0&toaddresses=admin%40example.com):  failed to send using smtp: timed out
```

When I try to send the same via the shoutrrr container, it seems to add a starttls option in the URL it shows. With starttls=No it does not work. If I include startls=Yes in the URL, it does work!
```
$ docker run --network=host 794834b14730 send -u="smtp://watchtower%40example.com:abc123@mail.example.com:587/?auth=Plain&fromaddress=watchtower%40example.com&fromname=Watchtower&subject=Watchtower+updates+on+e80ba93d5794&toaddresses=admin%40example.com" -m="test" -v
URLs:
  smtp://watchtower%40example.com:abc123@mail.example.com:587/?auth=Plain&fromaddress=watchtower%40example.com&fromname=Watchtower&subject=Watchtower+updates+on+e80ba93d5794&toaddresses=admin%40example.com
Message: test
SHOUTRRR 2021/12/18 13:39:44 Mail successfully sent to "admin@example.com"!
Notification sent

```

The configuration in docker-compose for watchtower looks like:
```
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --interval=60
      - --monitor-only
#      - --debug
      - --notifications=email
      - --notifications-level=info
      - --notification-email-from=watchtower@example.com
      - --notification-email-to=admin@example.com
      - --notification-email-server=mail.example.com
      - --notification-email-server-port=587
      - --notification-email-server-user=watchtower@example.com
      - --notification-email-server-password=abc123

```
Using -- debug does not help, it does not show additional information in watchtower. 

To make it even curiouser: it is probably a networking problem. The above docker compose file does not work. The below docker run command does work. Watchtower sends an e-mail when started up via docker run.

```
docker run -v  /var/run/docker.sock:/var/run/docker.sock --name watchtower containrrr/watchtower --interval=60 --monitor-only --notifications=email --notifications-level=info --notification-email-from=watchtower@example.com --notification-email-to=admin@example.com --notification-email-server=mail.example.com  --notification-email-server-port=587 --notification-email-server-user=watchtower@example.com  --notification-email-server-password=abc123
```
