### DISCUSSION TITLE
Question on Linked Containers and "depends_on"

### DISCUSSION THREAD

**Discussion by YanisKyr** [containrrr/watchtower#1216] [Q&A] [answered]
Hi guys, I've got a Stack running 4 containers. One VPN container along with three torrent related containers that need to be routed through VPN. When watchtower updates one (or more) of these, the replicated ones don't start correctly. I need to go back in Portainer and manually re-deploy the Stack to fix them.

So I looked it up and the [Linked Containers](https://containrrr.dev/watchtower/linked-containers/) function seems to be the solution, however I'm not sure how exactly to use that. I've got my compose further down, but first I'm sharing the 2 examples hovering around in my head. Which one would be correct? Maybe both?

The goal is to restart c1, c2, c3, c4 (c=container) preferably in this order when any of them is updated.

**_Example 1_**
c1
c2 /depends_on:c1
c3 /depends_on:c2
c4 /depends_on:c3

**_Example 2_**
c1 /depends_on:c2,c3,c4
c2 /depends_on:c1,c3,c4
c3 /depends_on:c1,c2,c4
c4 /depends_on:c1,c2,c3

```
version: "3"
services:
    gluetun:
        cap_add:
            - NET_ADMIN
        container_name: 1_gluetun
        image: qmcgaw/gluetun:latest
        network_mode: bridge
        environment:
            - VPNSP=nordvpn
            - VPN_TYPE=openvpn
            - OPENVPN_PROTOCOL=udp
            - OPENVPN_USER=***
            - OPENVPN_PASSWORD=***
            - UPDATE_PERIOD=24h
            - REGION=Netherlands
            - TZ=Europe/London
            - PUID=***
            - PGID=***
        ports:
            - 818:80 #ruTorrent
            - 6881:6881/udp #ruTorrent
            - 51413:51413 #ruTorrent
            - 9117:9117 #jackett
            - 8191:8191 #flaresolverr
        devices:
            - /dev/net/tun:/dev/net/tun
        privileged: true
        volumes:
            - /***/gluetun:/config
        restart: unless-stopped

    flaresolverr:
        container_name: 2_flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        network_mode: "service:gluetun"
        environment:
            - LOG_LEVEL=info
            - TEST_URL=https://www.google.com
            - TZ=Europe/London
            - PUID=***
            - PGID=***
        restart: unless-stopped
        depends_on:
            - gluetun

    jackett:
        container_name: 3_jackett
        image: lscr.io/linuxserver/jackett:latest
        network_mode: "service:gluetun"
        volumes:
            - /***/jackett:/config
            - /***/watched:/downloads
        environment:
            - TZ=Europe/London
            - PGID=***
            - PUID=***
        restart: unless-stopped
        depends_on:
            - flaresolverr

    rutorrent:
        container_name: 4_rutorrent
        image: ghcr.io/linuxserver/rutorrent:latest
        network_mode: "service:gluetun"
        volumes:
            - /***/rutorrent:/config
            - /***/rutorrent:/downloads
        environment:
            - TZ=Europe/London
            - PGID=***
            - PUID=***
            - UMASK=002
        restart: unless-stopped
        depends_on:
            - jackett
```

**Comment by piksel** [comment, marked as answer]
I think `depends_on` is docker-compose specific and does not mark the container correctly for watchtower to see them. You could use the label `com.centurylinklabs.watchtower.depends-on` to set up the dependencies (or solve it using another networking type, as you wrote in another issue).

**Comment by YanisKyr** [comment]
Thanks for the quick reply. So instead of 

```
        depends_on:
            - jackett
```

I should add something along these lines?

```
        labels:
            - com.centurylinklabs.watchtower.depends-on: "jackett"
```

The question remains though - do I need to say each container depends on all the rest, or is a chain of dependencies sufficient?

**Reply by piksel** [reply]
the chain should be sufficient, if I remember correctly :)

**Comment by YanisKyr** [comment]
Btw, the label didn't work until the format was like this:

```
        labels:
            - com.centurylinklabs.watchtower.depends-on=3_jackett
```

I tried the chain as discussed, also changed it to reference all other containers in each one, however watchtower still breaks things unfortunately.

This is the result, and further down you can also see the logs.
https://i.imgur.com/wm7TZda.png

```
time="2022-02-18T04:00:22Z" level=info msg="Found new lscr.io/linuxserver/qbittorrent:latest image (6ce20ebf23eb)"
time="2022-02-18T04:00:38Z" level=info msg="Found new lscr.io/linuxserver/jackett:latest image (3f0200c5a277)"
time="2022-02-18T04:00:55Z" level=info msg="Found new hotio/readarr:nightly image (494c6e9e9a09)"
time="2022-02-18T04:01:16Z" level=info msg="Stopping /readarr (a559605d2340) with SIGTERM"
time="2022-02-18T04:01:26Z" level=info msg="Stopping /1_gluetun (e5c3a9abfc91) with SIGTERM"
time="2022-02-18T04:01:30Z" level=info msg="Stopping /3_jackett (50568d5ecb94) with SIGTERM"
time="2022-02-18T04:01:36Z" level=info msg="Stopping /2_flaresolverr (8921c4630334) with SIGTERM"
time="2022-02-18T04:01:39Z" level=info msg="Stopping /4_qbittorrent (5c1bcaa29631) with SIGTERM"
time="2022-02-18T04:01:49Z" level=info msg="Creating /4_qbittorrent"
time="2022-02-18T04:01:50Z" level=error msg="Error response from daemon: No such container: e5c3a9abfc916b54a3cd822f7ec0df5eea0b78554093b38f594357b5cebe282c"
time="2022-02-18T04:01:50Z" level=info msg="Creating /2_flaresolverr"
time="2022-02-18T04:01:51Z" level=error msg="Error response from daemon: No such container: e5c3a9abfc916b54a3cd822f7ec0df5eea0b78554093b38f594357b5cebe282c"
time="2022-02-18T04:01:51Z" level=info msg="Creating /3_jackett"
time="2022-02-18T04:01:52Z" level=error msg="Error response from daemon: No such container: e5c3a9abfc916b54a3cd822f7ec0df5eea0b78554093b38f594357b5cebe282c"
time="2022-02-18T04:01:52Z" level=info msg="Creating /1_gluetun"
time="2022-02-18T04:01:56Z" level=info msg="Creating /readarr"
time="2022-02-18T04:01:59Z" level=info msg="Removing image 04a32cc4dbb6"
time="2022-02-18T04:02:00Z" level=info msg="Removing image 572de02cbea1"
time="2022-02-18T04:02:00Z" level=error msg="Error response from daemon: conflict: unable to delete 572de02cbea1 (cannot be forced) - image is being used by running container dc20184c7b62"
time="2022-02-18T04:02:00Z" level=info msg="Removing image f3b0f312d2a3"
time="2022-02-18T04:02:01Z" level=info msg="Removing image 552981214e78"
time="2022-02-18T04:02:02Z" level=info msg="Removing image b5196bf0d9f8"
time="2022-02-18T04:02:03Z" level=info msg="Session done" Failed=2 Scanned=19 Updated=1 notify=no
```

**Reply by piksel** [reply]
> Btw, the label didn't work until the format was like this:

Yeah, sorry I didn't catch that. The syntax for `docker-compose` is a constant issue (see https://github.com/containrrr/watchtower/issues/390#issuecomment-1032498496)

It's
```yaml
labels:
    com.centurylinklabs.watchtower.depends-on: "jackett"
```
**or**
```yaml
labels:
    - com.centurylinklabs.watchtower.depends-on=jackett
```

> however watchtower still breaks things unfortunately.

Yes, it turns out that there is a bug in the `cleanup`, which wasn't discovered since the `depends-on` resolving was broken earlier.
Ref: #1220

**Reply by piksel** [reply]
Also, maybe the `depends-on` is backwards? It seems like 4, 3 and 2 is looking for container 1:
> "Stopping /1_gluetun (**e5c3a9abfc91**) with SIGTERM"

...

> "Creating /4_qbittorrent"
> "Error response from daemon: No such container: **e5c3a9abfc91**6b54a3cd822f7ec0df5eea0b78554093b38f594357b5cebe282c"
> "Creating /2_flaresolverr"
> "Error response from daemon: No such container: **e5c3a9abfc91**6b54a3cd822f7ec0df5eea0b78554093b38f594357b5cebe282c"
> "Creating /3_jackett"
> "Error response from daemon: No such container: **e5c3a9abfc91**6b54a3cd822f7ec0df5eea0b78554093b38f594357b5cebe282c"

**Reply by YanisKyr** [reply]
Alright thank you, I'll follow #1220 for updates.

**Reply by YanisKyr** [reply]
> Also, maybe the `depends-on` is backwards? It seems like 4, 3 and 2 is looking for container 1:

hmm, hold on.. For each one of the 4 containers, I'm referencing the other 3. Reduced version of the compose file:
```
version: "3"
services:
    gluetun:
	container_name: 1_gluetun
        labels:
            - com.centurylinklabs.watchtower.depends-on=1_gluetun
            - com.centurylinklabs.watchtower.depends-on=2_flaresolverr
            - com.centurylinklabs.watchtower.depends-on=3_jackett

    flaresolverr:
	container_name: 2_flaresolverr
        labels:
            - com.centurylinklabs.watchtower.depends-on=1_gluetun
            - com.centurylinklabs.watchtower.depends-on=3_jackett
            - com.centurylinklabs.watchtower.depends-on=4_qbittorrent

    jackett:
        container_name: 3_jackett
        labels:
            - com.centurylinklabs.watchtower.depends-on=1_gluetun
            - com.centurylinklabs.watchtower.depends-on=2_flaresolverr
            - com.centurylinklabs.watchtower.depends-on=4_qbittorrent

    qbittorrent:
        container_name: 4_qbittorrent
        labels:
            - com.centurylinklabs.watchtower.depends-on=1_gluetun
            - com.centurylinklabs.watchtower.depends-on=2_flaresolverr
            - com.centurylinklabs.watchtower.depends-on=3_jackett
```
