### DISCUSSION TITLE
Container exited with Error for shoutrrr matrix

### DISCUSSION THREAD

**Discussion by unknownFalleN** [containrrr/watchtower#1233] [Q&A] [answered]
**Describe the bug**

Latest Docker Image won't start  with matrix. Failed to login with token and also with username password. Variant 2 with username and Password is a URL Encoded String `matrix://<USERNAME>:<PASSWORD>:@matrix.org/?rooms=<ROOM-ID>:matrix.org`, because symbols in password. Without URL Encoding got a paring error `... invalid URL escape ...`

**To Reproduce**

1. Start docker-compose `docker-compose up`
```
version: '3.8'

networks:
  watchtower:
    name: watchtower

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=matrix://<TOKEN>@matrix.org/?rooms=<ROOM-ID>:matrix.org
      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - watchtower
```

**Expected behavior**

The Docker Container runs and get notifications in matrix room.

**Screenshots**

**Environment**

 - Platform: `4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`
- Docker-compose: `docker-compose version 1.29.2, build 5becea4c`
 - Docker version: `Docker version 20.10.12, build e91ed57`

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

Logs with `WATCHTOWER_NOTIFICATION_URL=matrix://<TOKEN>@matrix.org/?rooms=<ROOM-ID>:matrix.org`
```
watchtower    | time="2022-02-19T15:07:21Z" level=debug
watchtower    | time="2022-02-19T15:07:21Z" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: failed to log in: Bad parameter: password\n"
watchtower exited with code 1
```

Logs with Username and Password (URL Encoded String) `matrix://<USERNAME>:<PASSWORD>:@matrix.org/?rooms=<ROOM-ID>:matrix.org`
```
watchtower    | time="2022-02-19T15:21:28Z" level=debug
watchtower    | time="2022-02-19T15:21:58Z" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: failed to get login flows: Get \"https://matrix.org:8448/_matrix/client/r0/login\": dial tcp 104.20.20.236:8448: i/o timeout\n"
```

</details>

**Additional context**
