### DISCUSSION TITLE
Unable to auth to hub.docker.com

### DISCUSSION THREAD

**Discussion by FlyingPersian** [containrrr/watchtower#1234] [Q&A] [answered]
Hello,

I'm running docker on my Raspberry Pi. I have installed Portainer, which I use to manage my containers using stacks. Watchtower fails to update because it fails to login to hub.docker.com. I'm not using any private images.

docker-compose.yml/portainer stack:
```
version: "3.5"
services:
  watchtower:
    image: containrrr/watchtower:armhf-latest
    restart: unless-stopped
    container_name: watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.docker/config.json:/config.json"
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      #- WATCHTOWER_SCHEDULE=* 4 * * * *
      - WATCHTOWER_POLL_INTERVAL=15
      - WATCHTOWER_DEBUG
```

log:
```
time="2022-02-21T17:11:32+01:00" level=info msg="Watchtower 1.4.0"
time="2022-02-21T17:11:32+01:00" level=info msg="Using notifications: smtp"
time="2022-02-21T17:11:32+01:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2022-02-21T17:11:32+01:00" level=info msg="Scheduling first run: 2022-02-21 17:11:47 +0100 CET"
time="2022-02-21T17:11:32+01:00" level=info msg="Note that the first check will be performed in 14 seconds"
time="2022-02-21T17:11:48+01:00" level=warning msg="Could not do a head request for \"sha256:72324c978d0895316b27fd80cbfe5d0021bd4638a0d6ecefdb4a047caca192ab\", falling back to regular pull." container=/watchtower image="sha256:72324c978d0895316b27fd80cbfe5d0021bd4638a0d6ecefdb4a047caca192ab"
time="2022-02-21T17:11:48+01:00" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:library/sha256:pull\\\",error=\\\"insufficient_scope\\\"\"" container=/watchtower image="sha256:72324c978d0895316b27fd80cbfe5d0021bd4638a0d6ecefdb4a047caca192ab"
time="2022-02-21T17:11:50+01:00" level=info msg="Unable to update container \"/watchtower\": Error response from daemon: pull access denied for sha256, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
```

I first tried without the config.json file. Then I created it using "docker login". Both ways result in the same errro above.

/home/pi/.docker/config.json:
```
 {
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "xxxxx"
                }
        }
}
```

As far as I see it, I shouldn't even need to pass the config.json. It should just run fine using the docker socket. Why is this happening?
