### DISCUSSION TITLE
Can't get email notifications to work

### DISCUSSION THREAD

**Discussion by drtech981** [containrrr/watchtower#1259] [Q&A] [answered]
This is the docker-compose file I'm using : 

```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - WATCHTOWER_LABEL_ENABLE= true
      - WATCHTOWER_NOTIFICATIONS= email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM= watchtower-m01@services.xyzs.cc 
      - WATCHTOWER_NOTIFICATION_EMAIL_TO= admin@@xyzs.cc
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER= mail.services.xyzs.cc 
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT= 25   
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER= xyzs-cc/mx-01
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD= superSecret 
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY= 30
```
However, I'm receiving no notifications when a container updates.

Docker logs is showing : 

```
time="2022-03-26T18:06:17Z" level=info msg="Watchtower 1.4.0"
time="2022-03-26T18:06:17Z" level=info msg="Using no notifications"
time="2022-03-26T18:06:17Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2022-03-26T18:06:17Z" level=info msg="Scheduling first run: 2022-03-27 18:06:17 +0000 UTC"
time="2022-03-26T18:06:17Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
```

**Comment by piksel** [comment, marked as answer]
You are missing the `environment:` key, and I would remove the spaces between `=` and the value (I *think* it might work with the spaces, but I haven't tested it):
```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower-m01@services.xyzs.cc 
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=admin@@xyzs.cc
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.services.xyzs.cc 
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25   
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xyzs-cc/mx-01
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=superSecret 
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
```
