### DISCUSSION TITLE
Suppress timeout errors

### DISCUSSION THREAD

**Discussion by vbezhenar** [containrrr/watchtower#1274] [Q&A]
Hello. We're using watchtower and it works perfectly. However there's one annoying issue. We're using gitlab container registry and very often it times out with watchtower requests which causes it to send an error notification to our discord server and it's like 99% of log lines. It's not a permanent error, but it happens often enough to be annoying and causing people to disable notifications which is not a very good thing.

Is it possible to somehow suppress those errors?

Example of error: `Unable to update container "/robot_eyes_ai_1": Error response from daemon: Get "https://registry.gitlab.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next.`

Configuration:

```
  watchtower:
    image: "containrrr/watchtower"
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://long-url
    secrets:
      - source: watchtower_config.json
        target: /config.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --interval 60 --stop-timeout 300s --no-startup-message
```
