### DISCUSSION TITLE
Pull access denied for docker_nextcloud, repository does not exist

### DISCUSSION THREAD

**Discussion by romprod** [containrrr/watchtower#1295] [Q&A]
**Describe the bug**
Watchtower is unable to provide the correct credentials, I'm presuming because there's no such images as docker_nextcloud:latest

**Expected behavior**
Watchtower logs in and then is able to continue it's process

**docker-compose**
```
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=Europe/London
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=user@user.it
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=user@user.it
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=1.1.1.1
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/.docker/config.json:/config.json
    networks:
      traefik:
    command: nextcloud --interval 30 --trace
```
**Logs**
```
time="2022-05-24T13:06:53+01:00" level=debug
time="2022-05-24T13:06:53+01:00" level=trace msg="created Shoutrrr URL from legacy notifier" URL="smtp://10.10.10.248:25/?auth=None&encryption=None&fromaddress=watchtower%40user.it&fromname=Watchtower&starttls=No&subject=Watchtower+updates+on+28048499ef47&toaddresses=user%40user.it"
time="2022-05-24T13:06:53+01:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2022-05-24T13:06:54+01:00" level=debug msg="Making sure everything is sane before starting"
time="2022-05-24T13:06:54+01:00" level=debug msg="Retrieving running containers"
time="2022-05-24T13:06:54+01:00" level=debug msg="There are no additional watchtower containers"
time="2022-05-24T13:06:54+01:00" level=debug msg="Watchtower HTTP API skipped."
time="2022-05-24T13:06:54+01:00" level=info msg="Watchtower 1.4.0"
time="2022-05-24T13:06:54+01:00" level=info msg="Using notifications: smtp"
time="2022-05-24T13:06:54+01:00" level=info msg="Only checking containers with name \"nextcloud\""
time="2022-05-24T13:06:54+01:00" level=info msg="Scheduling first run: 2022-05-24 13:07:24 +0100 BST"
time="2022-05-24T13:06:54+01:00" level=info msg="Note that the first check will be performed in 29 seconds"
time="2022-05-24T13:06:54+01:00" level=warning msg="Trace level enabled: log will include sensitive information as credentials and tokens"
time="2022-05-24T13:06:55+01:00" level=trace msg="Shoutrrr: Mail successfully sent to \"user@user.it\"!"
time="2022-05-24T13:06:55+01:00" level=trace msg="Shoutrrr: Mail successfully sent to \"user@user.it\"!"
time="2022-05-24T13:07:24+01:00" level=debug msg="Checking containers for updated images"
time="2022-05-24T13:07:24+01:00" level=debug msg="Retrieving running containers"
time="2022-05-24T13:07:24+01:00" level=debug msg="Trying to load authentication credentials." container=/nextcloud image="docker_nextcloud:latest"
time="2022-05-24T13:07:24+01:00" level=debug msg="No credentials for docker_nextcloud:latest found" config_file=/config.json
time="2022-05-24T13:07:24+01:00" level=debug msg="Got image name: docker_nextcloud:latest"
time="2022-05-24T13:07:24+01:00" level=debug msg="Checking if pull is needed" container=/nextcloud image="docker_nextcloud:latest"
time="2022-05-24T13:07:24+01:00" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2022-05-24T13:07:24+01:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2022-05-24T13:07:24+01:00" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2022-05-24T13:07:24+01:00" level=debug msg="Setting scope for auth token" image=docker_nextcloud scope="repository:library/docker_nextcloud:pull"
time="2022-05-24T13:07:24+01:00" level=debug msg="No credentials found."
time="2022-05-24T13:07:25+01:00" level=debug msg="Parsing image ref" host=index.docker.io image=docker_nextcloud normalized="docker.io/library/docker_nextcloud:latest" tag=latest
time="2022-05-24T13:07:25+01:00" level=trace msg="Setting request token" token="Bearer ******"
time="2022-05-24T13:07:25+01:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/library/docker_nextcloud/manifests/latest"
time="2022-05-24T13:07:25+01:00" level=warning msg="Could not do a head request for \"docker_nextcloud:latest\", falling back to regular pull." container=/nextcloud image="docker_nextcloud:latest"
time="2022-05-24T13:07:25+01:00" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:library/docker_nextcloud:pull\\\",error=\\\"insufficient_scope\\\"\"" container=/nextcloud image="docker_nextcloud:latest"
time="2022-05-24T13:07:25+01:00" level=debug msg="Pulling image" container=/nextcloud image="docker_nextcloud:latest"
time="2022-05-24T13:07:27+01:00" level=debug msg="Error pulling image docker_nextcloud:latest, Error response from daemon: pull access denied for docker_nextcloud, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
time="2022-05-24T13:07:27+01:00" level=info msg="Unable to update container \"/nextcloud\": Error response from daemon: pull access denied for docker_nextcloud, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
time="2022-05-24T13:07:27+01:00" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
```

**config.json**
`{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "**"
		}
	}
}`

I think that I've included all useful info, please let me know if not.
