### DISCUSSION TITLE
Update two services with same image (doesn't see 2, only 1)

### DISCUSSION THREAD

**Discussion by temamagic** [containrrr/watchtower#1308] [Q&A] [answered]
Hi there! I'm trying to update two services with same image, but different names, but watchtower updates only one service. Looks like it doesn't see second

My docker-compose below, can you help me? Or watchtower can't update like this?
```
version: '3.8'

services:

  bot:
    image: registry.gitlab.com/myproject/bot:latest
    restart: always
    stop_signal: SIGINT
    network_mode: host
    volumes:
      - ./cfg/:/app/cfg
      - ./logs/:/app/logs
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 1

  worker:
    image: registry.gitlab.com/myproject/bot:latest
    restart: always
    stop_signal: SIGINT
    network_mode: host
    volumes:
      - ./cfg/:/app/cfg
      - ./logs/:/app/logs
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      BOT_WORKER_MODE: "true"
    deploy:
      replicas: 3

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: telegram://TOKEN@telegram?channels=ID&parseMode=HTML
```

logs:
```
watchtower-1  | time="2022-06-16T04:06:33Z" level=debug msg="Checking containers for updated images"
watchtower-1  | time="2022-06-16T04:06:33Z" level=debug msg="Retrieving running containers"
watchtower-1  | time="2022-06-16T04:06:33Z" level=debug msg="Trying to load authentication credentials." container=/folder-bot-1 image="registry.gitlab.com/myproject/bot:latest"
..some working and pulling logs...
watchtower-1  | time="2022-06-16T04:06:35Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
```

as you can see in log, **Scanned=1**, but why 1? Why not 2 (two services has same label)

What i'm doing wrong?
