### DISCUSSION TITLE
SMTP Connection Difficulties

### DISCUSSION THREAD

**Discussion by truthsword** [containrrr/watchtower#1324] [Q&A]
I'm trying to run a docker instance on RPi which is email notification only. I'm presently trying a "@live.com" email without success. My most recent error message is:

`time="2022-07-15T19:25:30-04:00" level=error msg="Failed to send shoutrrr notification" error="error getting SMTP client: error connecting to server: dial tcp :25: connect: connection refused" index=0 notify=no service=smtp`

My docker compose is:
```
version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - WATCHTOWER_MONITOR_ONLY=true
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=abcdefg@live.com
        - WATCHTOWER_NOTIFICATION_EMAIL_TO=qwerty@login.com
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER:smtp-mail.outlook.com
#        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=true
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT:587
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=abcdefgf@live.com
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=secretpwd
        - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG:Docker Container Updates
        - WATCHTOWER_SCHEDULE=0 0 5 * * *
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_DEBUG=true
        - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
        - WATCHTOWER_TIMEOUT=30s
        - WATCHTOWER_NOTIFICATIONS_LEVEL=info
        - TZ=America/Chicago
```
I've tried '=' and ':' for server and port and had no success either way.

I'd welcome any suggestions.
