### DISCUSSION TITLE
Unable to update container "..." Error response from daemon

### DISCUSSION THREAD

**Discussion by yves-chevallier** [containrrr/watchtower#1386] [Q&A]
I ran watchtower with the following docker-compose on my synology:

```yml
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    network_mode: bridge
    env_file:
      - .env
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/watchtower/config.json:/config.json
```

Unfortunately, I get this error which I don't understand. 

```
Unable to update container \"/sonarr\": 
Error response from daemon: Get \"https://lscr.io/v2/\": 
x509: certificate is valid for synology, not lscr.io. Proceeding to next."
```

There is an error because my certificate is valid? What's that?

If I try to do the same from the CLI: 

```
/volume1/docker$ sudo docker run --rm \
r.sock \> -v /var/run/docker.sock:/var/run/docker.sock \
> containrrr/watchtower \
> --run-once sonarr
Password:
time="2022-09-17T16:57:04Z" level=info msg="Watchtower 1.4.0"
time="2022-09-17T16:57:04Z" level=info msg="Using no notifications"
time="2022-09-17T16:57:04Z" level=info msg="Only checking containers with name \"sonarr\""
time="2022-09-17T16:57:04Z" level=info msg="Running a one time update."
time="2022-09-17T16:57:05Z" level=info msg="Unable to update container \"/sonarr\": Error response from daemon: Get \"https://lscr.io/v2/\": x509: certificate is valid for synology, not lscr.io. Proceeding to next."
time="2022-09-17T16:57:05Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
time="2022-09-17T16:57:05Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
```
