### DISCUSSION TITLE
Watchtower notifications gives smtp timeout error

### DISCUSSION THREAD

**Discussion by ultimateguy** [containrrr/watchtower#1422] [Q&A]
I'm running watchtower with the following docker-compose on a raspberry pi:

```
version: '3.7'
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxx@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=apppassword
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_CLEANUP=true
    command: --schedule "30 * * * * *"
```

I receive the following error in the logs:

`level=error msg="Failed to send shoutrrr notification" error="failed to send using smtp: timed out" index=0 notify=no service=smtp`

I'm at a loss. I tried adding ports: '587:587' to the compose file but I get the same error.
