### DISCUSSION TITLE
level=fatal msg="Notification template error" error="template: :1:7: executing \"\" at <.Report>: can't evaluate field Report in type []*logrus.Entry" notify=no

### DISCUSSION THREAD

**Discussion by NonaSuomy** [containrrr/watchtower#1500] [Q&A] [answered]
Trying to use the default notification template from here https://containrrr.dev/watchtower/notifications/ results in the error:

```
time="2022-12-13T06:51:17-05:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2022-12-13T06:51:18-05:00" level=debug msg="Making sure everything is sane before starting"
time="2022-12-13T06:51:18-05:00" level=debug msg="Retrieving running containers"
time="2022-12-13T06:51:18-05:00" level=debug msg="There are no additional watchtower containers"
time="2022-12-13T06:51:18-05:00" level=debug msg="Watchtower HTTP API skipped."
time="2022-12-13T06:51:18-05:00" level=info msg="Watchtower v1.5.1-10-g3a59664"
time="2022-12-13T06:51:18-05:00" level=info msg="Using notifications: smtp"
time="2022-12-13T06:51:18-05:00" level=info msg="Only checking containers using enable label"
time="2022-12-13T06:51:18-05:00" level=info msg="Scheduling first run: 2022-12-14 04:00:00 -0500 EST"
time="2022-12-13T06:51:18-05:00" level=info msg="Note that the first check will be performed in 21 hours, 8 minutes, 41 seconds"
level=fatal msg="Notification template error" error="template: :1:7: executing \"\" at <.Report>: can't evaluate field Report in type []*logrus.Entry" notify=no
```
Which prevents watchtower from running.

```yaml
version: "3.9"
services:
  watchtower:
    container_name: "watchtower"
    hostname: "watchtower"
    image: "containrrr/watchtower:latest-dev"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: "no"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    mac_address: "9e:57:59:8e:5e:30"
    networks:
      - dhcp
    #'0 0 15 ? * FRI' At 03:00 PM, only on Friday (Currently check every day at 4AM)  
    environment:
      WATCHTOWER_LABEL_ENABLE: 'true'
      WATCHTOWER_MONITOR_ONLY: 'false'
      WATCHTOWER_DEBUG: 'true'
      WATCHTOWER_TRACE: 'false'
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_SCHEDULE: '0 0 4 * * *'
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
      WATCHTOWER_NOTIFICATION_TITLE_TAG: 'HQ'
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: 'HQ001'
      WATCHTOWER_NOTIFICATIONS: 'email'
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: 'email@gmail.com'
      WATCHTOWER_NOTIFICATION_EMAIL_TO: 'email@gmail.com'
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: 'HQ'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: 'smtp.gmail.com'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: 'email@gmail.com'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: 'password'
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2

networks:
  dhcp:
    name: "dbrv700"
    external: true
```

Another question there is this note on that page above:
```
There is currently a bug in Viper ([spf13/viper#380](https://github.com/spf13/viper/issues/380)), which prevents comma-separated slices to be used when using the environment variable.
A workaround is available where we instead put quotes around the environment variable value and replace the commas with spaces:


WATCHTOWER_NOTIFICATIONS="slack msteams"
**If you're a docker-compose user, make sure to specify environment variables' values in your .yml file without double quotes ("). This prevents unexpected errors when watchtower starts.**
```

I used single quote marks in the above environment section is this what you are supposed to do or just leave them off totally?

All the examples for compose seem to use double quote marks in the env section so not sure what to do there?
