### DISCUSSION TITLE
Container build up never updates the machine but downloads another version of it old one keeps running.

### DISCUSSION THREAD

**Discussion by NonaSuomy** [containrrr/watchtower#1539] [Q&A] [answered]
Hi,

I have watchtower setup like this:
```yaml
version: "3.9"
services:
  watchtower:
    container_name: "watchtower"
    hostname: "watchtower"
    image: "containrrr/watchtower:latest-dev"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: "no"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    mac_address: "de:ad:be:ef:5e:30"
    networks:
      - dhcp
    #'0 0 15 ? * FRI' At 04:00 AM, only on Friday (Currently Check everyday at 4AM)  
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_MONITOR_ONLY: "true"
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_TRACE: "false"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 16 * * *"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
      WATCHTOWER_NOTIFICATION_TITLE_TAG: "HQ"
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "HQ001"
      WATCHTOWER_NOTIFICATIONS: "email"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "email@domain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "email@domain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: "HQ"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtp.domain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "email@domain.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "KEY"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2

networks:
  dhcp:
    name: "dbrv700"
    external: true
```

I would like watchtower to keep itself updated and always run the latest version.

I have an example of another container setup like this that I want it to update and restart in the new container and remove the old one:
```yaml
# HomeAssistant Container for Docker
version: "3.9"
services:
  homeassistant:
    container_name: "homeassistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
    volumes:
      - /var/lib/libvirt/images/usb001/docker-storage/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    mac_address: "de:ad:be:ef:5e:23"
    networks:
      - dhcp
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: "no"
    privileged: true
    #network_mode: host

networks:
  dhcp:
    name: "dbrv700"
    external: true
```

I have others setup like this that I don't want to be updated:
```
# Cloudflared Container for Docker
version: "3.9"
services:
  cloudflared:
    container_name: "cloudflared"
    image: "cloudflare/cloudflared:latest"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"

    volumes:
      - /var/lib/libvirt/images/usb001/docker-storage/cloudflared:/etc/cloudflared
    mac_address: "de:ad:be:ef:5e:25"
    networks:
      - dhcp
    restart: "no"
    #restart: unless-stopped
    privileged: true
    #network_mode: host
    command: tunnel run
    environment:
    - TUNNEL_TOKEN=TOKEN

networks:
  dhcp:
    name: "dbrv700"
    external: true
```

I have others that I don't want it to touch with:
```
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "com.centurylinklabs.watchtower.monitor-only=false"
```

This is what I see under the containers list:
```
sha256:Sequence... Unused | containrrr/watchtower:<none> | 20.9 MB | 2023-01-22 04:02:07
sha256:Sequence... Unused | containrrr/watchtower:<none> | 20.9 MB | 2023-01-13 19:30:03
sha256:Sequence... Unused | containrrr/watchtower:<none> | 20.9 MB | 2022-12-21 11:19:13
sha256:Sequence... Live       | containrrr/watchtower:<none> | 20.9 MB | 2022-12-09 04:11:10
sha256:Sequence... Unused | containrrr/watchtower:latest-dev | 20.9 MB | 2023-01-25 12:53:34

sha256:Sequence... Live       | eclipse-mosquitto:<none> | 11.9 MB | 2022-10-06 16:25:10
sha256:Sequence... Unused | eclipse-mosquitto:latest | 11.9 MB | 2022-11-12 00:08:06
```

You can see that it is downloading updates just not applying them or deleting the old ones.

I always get emails like this:

```
From: Watchtower <email@domain.com>
Subject: [HQ] Watchtower updates on HQ001
Body:
9 Scanned, 0 Updated, 0 Failed
- /portainer (portainer/portainer-ce:latest): Fresh
- /frigate (blakeblackshear/frigate:stable-amd64): Fresh
- /lms (lmscommunity/logitechmediaserver:latest): Fresh
- /rtlamr2mqtt (allangood/rtlamr2mqtt:latest): Fresh
```

It never seems to say that it updated anything or that anything failed. It says it scanned 9 containers which are correct but it only lists 4 below that.

How do I get these items functioning properly?
What am I doing wrong in the Watchtower configuration or the label configurations with the containers?
Would like these points below to work:
-Watchtower always keeps itself up to date and deletes the old version.
-Watchtower updates containers that have been selected to keep updated and delete the old version.
-Watchtower monitors a container but doesn't update and doesn't download anything but informs you in the email that there is an update.
-Watchtower ignores the container totally downloading nothing but shows that it exists in the email like Container name: SomeContainer, Status: Not watched or updated etc.

Thank you.
