### DISCUSSION TITLE
Problem with 401 and config.json not found

### DISCUSSION THREAD

**Discussion by pkellner** [containrrr/watchtower#1598] [Q&A] [answered]
I'm 99.9% sure I have the correct file automatically created on my linux vm at the location /root/.docker/config.json

It has the following values with key x'd out

```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "xxxxxx"
                }
        }
}
```

I get the error below on all my private containers. I was hoping I could login in with docker exec -it but there seems to be no shell in the container. Othewise, I could look at /config and see if the file is there.

```
time="2023-03-20T21:13:07Z" level=debug msg="Trying to load authentication credentials." container=/svccrscproxy image="pkellner/svccuppercaseproxy:latest"
time="2023-03-20T21:13:07Z" level=debug msg="No credentials for pkellner found" config_file=/config.json
```

My launch is this

```
services:

  watchtower:
    image: index.docker.io/containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=false
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_POLL_INTERVAL=30

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

```
