### DISCUSSION TITLE
Clarification on watchtower metrics and API token for a noob

### DISCUSSION THREAD

**Discussion by nn0de** [containrrr/watchtower#1615] [Q&A] [answered]
I am trying to get watchtower api working on my homepage dashboard, but I'm not going to lie. I am very stuck. 
As far as I can tell, I need to incorporate into my docker compose environmental variables, but I can't quite figure out the appropriate variables and their ='s 
The other thing that I am stuck on is actually creating the API key?
I will attach the homepage doc for reference, but if anyone could assist me in getting this working, I would be forever grateful!

https://gethomepage.dev/en/services/watchtower/

https://containrrr.dev/watchtower/metrics/

**Comment by crispybegs** [comment, marked as answer]
i went through literally this exact situation earlier this morning. In fact I did a double take thinking i'd posted your comment under a different name somehow, it was that similar.

Anyway, after a lot of digging around and fiddling, I got it working. This is my working compose yaml which just notifies of updates instead of automatically updating them (`WATCHTOWER_MONITOR_ONLY=true`), sends updates to my slack channel (you don't have to use this) and is working with homepage:

```yaml
version: "2"

services:
  app:
    image: containrrr/watchtower
    hostname: 192.168.1.64
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/London
      - NO_COLOR=true
      - WATCHTOWER_SCHEDULE=0 0 19 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - DOCKER_TLS_VERIFY=true
      - WATCHTOWER_NOTIFICATIONS=slack 
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/XXXXX
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-2 
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#Crispy
```

my homepage services.yaml entry reads thus:

   ```yaml
 - Watchtower:
        icon: https://github.com/walkxcode/dashboard-icons/raw/main/png/watchtower.png
        href: http://192.168.1.64:8080
        widget:
          type: watchtower
          fields: ["containers_scanned", "containers_updated", "containers_failed"]
          url: http://192.168.1.64:8080
          key: mytoken
```

like you, i was totally stuck on how to create or find a watchtower api key of some kind, until someone explained to me it's just generated in the compose file itself. So in the example above, it's literally "mytoken", in both the compose and the homepages yamls

hope this helps

**Reply by nn0de** [reply]
crispybegs you are my savior.
this worked perfectly! I had the API metrics=true in my compose but just could not figure out where the hell to obtain the API key.
Thank you  so so much for this it is working perfectly now!

**Reply by crispybegs** [reply]
happy to help! it was driving me mad this morning.
one other thing to note, i set this up and got it all working but but homepage stats were showing 0, even after I manually forced watchtower to do a scan and update of all containers.

<img width="352" alt="Screenshot 2023-04-08 at 12 06 40" src="https://user-images.githubusercontent.com/129169122/230722958-133b39e4-5628-4258-afcb-542b2a367e97.png">

apprently this is known behaviour and the stats should start updating after the next run specified in your compose (i think it's 7pm in mine), so i'll wait until later to check it's working ok

It was commented on in this thread - https://github.com/containrrr/watchtower/discussions/1493

glad you made some progress anyway

**Reply by crispybegs** [reply]
oh also i must give all credit to @henkiewie who patiently walked me through this and therefore, by proxy, you also.

**Reply by simonaronsson** [reply]
Good job figuring this out together!

I'm mainly excited by homepage, which I've never heard about or seen before. 😅

**Reply by crispybegs** [reply]
> Good job figuring this out together!
> 
> I'm mainly excited by homepage, which I've never heard about or seen before. 😅

it's the best of the dashboards i've tried by quite some way

<img width="2254" alt="Screenshot 2023-04-08 at 17 37 35" src="https://user-images.githubusercontent.com/129169122/230732873-e0efbc4a-c9e8-47c3-9660-5d6d69a01325.png">

**Reply by piksel** [reply]
The authentication by a key supplied by the user is a bit uncommon, yeah. It's in a way the same as specifying `MYSQL_ROOT_PASSWORD` to the `mysql` container, but probably less obvious since it's worded as an API key (which it is, but still). Perhaps we can clarify this in the docs somehow...

**Reply by crispybegs** [reply]
> The authentication by a key supplied by the user is a bit uncommon, yeah. It's in a way the same as specifying `MYSQL_ROOT_PASSWORD` to the `mysql` container, but probably less obvious since it's worded as an API key (which it is, but still). Perhaps we can clarify this in the docs somehow...

i think a simple _"You choose the API key yourself, the same way you'd choose a password. We don't create one for you so use something secure and memorable"_ would be fine. 

Like the OP here I spent ages hunting around the documentation completely baffled that there didn't seem to be a way of creating or finding an API key like, literally, every other service I self host. If i hadn't searched the archive of issues on github, found the one guy who was having the same problem months ago, asked him if he fixed it and him walking me through it I would have easily just given up.. which seems... suboptimal?

**Comment by crispybegs** [comment]
can confirm this all worked fine in homepage once the schedule ran in watchtower.

<img width="554" alt="Screenshot 2023-04-08 at 17 30 27" src="https://user-images.githubusercontent.com/129169122/230732430-4ce3fe22-b255-44e7-9c82-edda6701fb47.png">

**Reply by nn0de** [reply]
I keep forgetting to reply to this but yes! it all works perfectly for me. Thank you so much for coming to my rescue on this. I was going maaaaaad ahahaha.

**Comment by rcgbret** [comment]
Hi everyone,

I recently installed Watchtower through Portainer on Docker, installed on a Debian based LXC container.
It seems that everything is working (both containers update and email notification) but, following the above posts, I cannot correctly set it in Homepage Dashboard.
Following, the docker-compose code I used
```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Rome
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0/15 * * *
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN="mytoken"
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=myaddress@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=myaddress@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myaddress@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD="mypassword"
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    restart: always
```
and
the Homepage Dashboard code
```
- WatchTower:
        icon: watchtower.png
        href: http://192.168.1.126:8080
        ping: http://192.168.1.126:8080
        description: Portainer PVE WatchTower
        server: my-docker
        container: watchtower-watchtower-1 
        widget:
            type: watchtower
            fields: ["watchtower_containers_scanned", "watchtower_containers_updated", "watchtower_containers_failed"]
            url: http://192.168.1.126:8080
            key: "mytoken"
```
that give me back the following result
![Cattura2](https://github.com/containrrr/watchtower/assets/105563908/c8a1c665-e8ab-4ef0-b017-040df9ecc75c)
I succeeded in obtaining Docker stats with the above string but nothing else.
```
server: my-docker
container: watchtower-watchtower-1
```
but nothing else. I cannot even ping the local address 192.168.1.126:8080.
Another oddity, if I change the url in the widget section as follows
 ```
widget:
    type: watchtower
    fields: ["watchtower_containers_scanned", "watchtower_containers_updated", "watchtower_containers_failed"]
    url: http://192.168.1.126:8080/v1/metrics
    key: "mytoken"
```
something happens because I receive an API Error as shown below
![Cattura](https://github.com/containrrr/watchtower/assets/105563908/4e154046-1d88-4a7a-95c9-4e34669d54e6)
Does anybody have suggestions?
