### DISCUSSION TITLE
Include container names and versions with metrics

### DISCUSSION THREAD

**Discussion by renaudrenaud** [containrrr/watchtower#1631] [Feature Requests]
Guys, thanks a lot for the job.

I have hundred of servers to manage and it would be miraculous if I was enable to build a grafana dashboard with some metrics grabbed by prometheus. Currently we have  metrics but I would like to have the name of each container, the current version and the potential update version.

Thanks

**Comment by piksel** [comment]
I am not sure how you want this to work, the prometheus metrics are all numeric:
https://prometheus.io/docs/concepts/metric_types/
Moreover, there. is no official way to tell what the version is of some software inside an image. There are some community efforts to standardize image labels with versions, but even if your images use those, it's not something that watchtower currently supports (PR welcome!)

**Comment by renaudrenaud** [comment]
Negative, Cadvisor export the list of containers, I write some specific data exportation from Postgresql using some text fields and this is not a GAUGE nor a COUNTER but a LABEL.

I would like to use Watchtower to know the list of the NAMED containers I have to update, and with just this information, it shoulf by great.



<details>
<summary>An example with custom request from postgres-exporter allowing to grab some text info from the database:</summary>

```yaml
pg_atlog_dichotomie_docs_mensuels:
  query: |
    SELECT
    current_database() as datname, 
    al_registre(i_reg_doc_origine),
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now() - interval '6 month', 'YYYY-MM') THEN 1 END) AS "mm6",
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now() - interval '5 month', 'YYYY-MM') THEN 1 END) AS "mm5",
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now() - interval '4 month', 'YYYY-MM') THEN 1 END) AS "mm4",
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now() - interval '3 month', 'YYYY-MM') THEN 1 END) AS "mm3",
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now() - interval '2 month', 'YYYY-MM') THEN 1 END) AS "mm2",
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now() - interval '1 month', 'YYYY-MM') THEN 1 END) AS "mm1",
    COUNT(CASE WHEN to_char(d_creation, 'YYYY-MM') = to_char(now(), 'YYYY-MM') THEN 1 END) AS "mec"
    FROM document
    WHERE d_creation >= date_trunc('month', now() - interval '6 month')
    GROUP BY i_reg_doc_origine
    ORDER BY COUNT(*) DESC;
  metrics:
    - mm6:
        usage: "GAUGE"
        description: "Nombre Mois M-6"
    - mm5:
        usage: "GAUGE"
        description: "Nombre Mois M-5"
    - mm4:
        usage: "GAUGE"
        description: "Nombre Mois M-4"
    - mm3:
        usage: "GAUGE"
        description: "Nombre Mois M-3"
    - mm2:
        usage: "GAUGE"
        description: "Nombre M-2"
    - mm1:
        usage: "GAUGE"
        description: "Nombre M-1"
    - mec:
        usage: "GAUGE"
        description: "Nombre Mois En_COURS"
    - al_registre:
        usage: "LABEL"
        description: "Nom du registre"
    - datname:
        usage: "LABEL"
        description: "Nom de la base de donnees"
```
</details>

<details>
<summary>And CAdvisor showing the name of the containers, in grafana, using simple PromQL:</summary>

![Screenshot_20230421_170322](https://user-images.githubusercontent.com/9823965/233596648-7342fef1-ae77-41fd-98e4-6206e3e93363.png)

</details>
