### DISCUSSION TITLE
Can NOT get Gluetun connected services to relaunch after Gluetun update. "NO SUCH CONTAINER"

### DISCUSSION THREAD

**Discussion by nn0de** [containrrr/watchtower#1642] [Q&A]
So I know there is a bunch of people having the same issues and I have not been able to fix this issue. I have been adding labels and lines of code that I don't fully understand that won't fix this issue. I have read through the documentation and find the "Linked Containers" docs a little bit vague for a newbie like me. Once this failure occurs I have to re-deploy my docker-compose file to recreate sabnzbd and prowlarr
I will attach my Docker Compose file and the logs. If someone could assist me in fixing this I would be greatly appreciative. I have searched all over Google and the other GitHub discussions and have not been able to comprehend and implement a solution.

WATCHTOWER LOGS:
```
time="2023-05-02T21:15:23+10:00" level=info msg="Watchtower 1.5.3"
time="2023-05-02T21:15:23+10:00" level=info msg="Using no notifications"
time="2023-05-02T21:15:23+10:00" level=info msg="Only checking containers using enable label"
time="2023-05-02T21:15:23+10:00" level=info msg="Scheduling first run: 2023-05-03 09:15:23 +1000 AEST"
time="2023-05-02T21:15:23+10:00" level=info msg="Note that the first check will be performed in 11 hours, 59 minutes, 59 seconds"
time="2023-05-03T09:15:39+10:00" level=info msg="Found new qmcgaw/gluetun:latest image (dd820ef99902)"
time="2023-05-03T09:15:39+10:00" level=info msg="Stopping /prowlarr (8905ab80df76) with SIGTERM"
time="2023-05-03T09:15:45+10:00" level=info msg="Stopping /sabnzbd (3c15cbb04cfb) with SIGTERM"
time="2023-05-03T09:15:51+10:00" level=info msg="Stopping /gluetun (6eab0160fec9) with SIGTERM"
time="2023-05-03T09:15:52+10:00" level=info msg="Creating /gluetun"
time="2023-05-03T09:15:53+10:00" level=info msg="Creating /sabnzbd"
time="2023-05-03T09:15:54+10:00" level=error msg="Error response from daemon: No such container: 6eab0160fec9f55b4ce44f91f6af673b0927586a0d7d06d53c61b9ec6b7c7ac4"
time="2023-05-03T09:15:54+10:00" level=info msg="Creating /prowlarr"
time="2023-05-03T09:15:54+10:00" level=error msg="Error response from daemon: No such container: 6eab0160fec9f55b4ce44f91f6af673b0927586a0d7d06d53c61b9ec6b7c7ac4"
time="2023-05-03T09:15:54+10:00" level=info msg="Removing image ae9ce25d6c4b"
time="2023-05-03T09:15:54+10:00" level=info msg="Session done" Failed=0 Scanned=3 Updated=1 notify=no
```

WATCHTOWER COMPOSE:
```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    network_mode: bridge
    environment:
      - TZ=Australia/Melbourne
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8367:8080
    restart: unless-stopped```
```
DOCKER COMPOSE:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: "gluetun"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - TZ=Australia/Melbourne
      - PUID=1000
      - PGID=1000
      - VPNSP=private internet access
      - REGION=Netherlands
      - OPENVPN_USER=pXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXXXX
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
    volumes:
      - /usb1/Configs/Gluetun:/gluetun
    ports:
      - 8084:8080 #SABnzbd
      - 9696:9696 #Prowlarr
      - 8000:8000 #API
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
#    network_mode: "bridge"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /usb1/Configs/SABnzbd:/config
      - /usb1/Media:/Media
#    ports:
#      - 8084:8080
    depends_on:
      - gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.depends-on=/gluetun
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /usb1/Configs/Prowlarr:/config
    depends_on:
      - gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.depends-on=/gluetun
    restart: unless-stopped
```
