### DISCUSSION TITLE
Lifecyclehook post update

### DISCUSSION THREAD

**Discussion by stanthewizzard** [containrrr/watchtower#1674] [Q&A] [answered]
Hello

I think I'm using lifecycle hooks wrongly.

With docker compose

```yaml
version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      WATCHTOWER_LIFECYCLE_HOOKS: 'true'
      LABEL: com.centurylinklabs.watchtower.lifecycle.post-update="/script/wordpress.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/watchtower/script:/script
```

The script apparently is not executed but:
- script is inside container (with volume)
- lifecycle is enabled
- label looks right

Thanks for help

**Comment by piksel** [comment, marked as answer]
Yes, the lifecycle label goes on the container where you want it to run, so something like:

```yaml
version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      WATCHTOWER_LIFECYCLE_HOOKS: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    labels:
      - com.centurylinklabs.watchtower.lifecycle.post-update="/script/wordpress.sh"
    volumes:
      - /root/watchtower/script:/script
```
