### DISCUSSION TITLE
Linked container labels, am I doing it right?

### DISCUSSION THREAD

**Discussion by nigiriemoji** [containrrr/watchtower#1683] [Q&A] [answered]
Please let me know if I'm using the label correctly from this documentation https://containrrr.dev/watchtower/linked-containers/
My intention is if gluetun gets updated by watch tower that I need my qbittorrent and qbittorrentTL containers to restart since it uses the same network from gluetun

```
version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true # Enable automatic cleanup
      - WATCHTOWER_SCHEDULE=0 0 1 * * * # Set schedule to 3am
      - TZ=America/Los_Angeles # Set the timezone to Los Angeles
    restart: always
    cpus: '1'
    mem_limit: 500m
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=America/Los_Angeles
      - WEBUI_PORTS=8080
    network_mode: service:gluetun
    labels:
      - "com.centurylinklabs.watchtower.depends-on: gluetun"
    volumes:
      - ./qbittorrent:/config
      - /srv/dev-disk-by-uuid-DRIVE-ONE/downloads:/14TB/downloads
      - /srv/dev-disk-by-uuid-DRIVE-TWO/downloads:/8TB/downloads
      - /Music:/Music
    restart: unless-stopped
    cpus: '2'
    mem_limit: 2g
  qbittorrentTL:
    container_name: qbittorrentTL
    image: cr.hotio.dev/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=America/Los_Angeles
      - WEBUI_PORTS=8082
    network_mode: service:gluetun
    labels:
      - "com.centurylinklabs.watchtower.depends-on: gluetun"
    volumes:
      - ./qbittorrentTL:/config
      - /srv/dev-disk-by-uuid-DRIVE-ONE/downloads:/14TB/downloads
      - /srv/dev-disk-by-uuid-DRIVE-TWO/downloads:/8TB/downloads
      - /Music:/Music
    restart: unless-stopped
    cpus: '2'
    mem_limit: 2g
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-mullvad
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 8082:8082
      - 6767:6767
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=XXXXXXXXX
      - WIREGUARD_ADDRESSES=XXXXXXXXXXX
      - SERVER_CITIES=Los Angeles CA,Paris,Frankfurt,Amsterdam,Berlin
      - UPDATER_PERIOD=1176h
    restart: always
    cpus: '2'
    mem_limit: 1g
```
