### DISCUSSION TITLE
Issues setting up notifications for discord

### DISCUSSION THREAD

**Discussion by jlengelbrecht** [containrrr/watchtower#1688] [Q&A] [answered]
Tried setting up notifications for discord but I keep getting either a 400 bad request or invalid slack token format. 
I have tried a few different things to troubleshoot but I am not getting anywhere. 

My setup is as follows:
```
./Watchtower
├── docker-compose.yml
└── .env
```

## docker-compose.yml 
```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
           - WATCHTOWER_NOTIFICATIONS=slack
           - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=$DISCORD_WEBHOOK
           - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower-Monitoring1
           - TZ=America/New_York
           - WATCHTOWER_CLEANUP=true
           - WATCHTOWER_INCLUDE_STOPPED=true
           - WATCHTOWER_POLL_INTERVAL=3600
           - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
## .env
```
DISCORD_WEBHOOK=discord://token@webhook
```
