### DISCUSSION TITLE
Mail function not working ?

### DISCUSSION THREAD

**Discussion by jslegers73** [containrrr/watchtower#1689] [Q&A]
Hi,

I want to setup watch tower just to give me notifications when there is a new version of a container via mail.

This is my part of the docker compose file :
```yaml
  watchtower:
    image: containrrr/watchtower:latest
    container_name: Watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=myemail@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=myemail@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myemail@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=gmail app password
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NO_STARTUP_MESSAGE=false
```
But it doesn't send emails. When I check in portainer the logging I see this
```
time="2023-07-06T16:56:51+02:00" level=info msg="Watchtower 1.5.3"
time="2023-07-06T16:56:51+02:00" level=info msg="Using notifications: smtp"
time="2023-07-06T16:56:51+02:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2023-07-06T16:56:51+02:00" level=info msg="Scheduling first run: 2023-07-06 17:56:51 +0200 CEST"
time="2023-07-06T16:56:51+02:00" level=info msg="Note that the first check will be performed in 59 minutes, 59 seconds"
time="2023-07-06T17:57:33+02:00" level=info msg="Found new louislam/uptime-kuma:1 image (8d25e54ee60a)"
time="2023-07-06T17:57:36+02:00" level=info msg="Session done" Failed=0 Scanned=6 Updated=1 notify=no
time="2023-07-06T18:56:54+02:00" level=info msg="Found new louislam/uptime-kuma:1 image (8d25e54ee60a)"
time="2023-07-06T18:56:57+02:00" level=info msg="Session done" Failed=0 Scanned=6 Updated=1 notify=no
```
I see Updated =1 notify=no. Does this mean there is one update but no notification is being send?

I have added WATCHTOWER_NO_STARTUP_MESSAGE=false to see if it send out a test message but that was also not the case. 

I do use 2FA on my gmail account and saw on a YT video that you need to create a app password for it.
