### DISCUSSION TITLE
Creating a Whitelist or Blacklist for Watchtower to Ignore Certain Dockers

### DISCUSSION THREAD

**Discussion by vawaver** [containrrr/watchtower#1697] [Q&A] [answered]
Hello everyone,

I'm wondering if it's possible to create a whitelist or blacklist for Watchtower to ignore or update only certain dockers that are listed in these lists. Specifically, I'm interested in finding out how to get Watchtower to update all dockers except those that start with the string "nextcloud" (this is for Nextcloud AIO, which cannot be updated in the standard way).

Has anyone tried creating a whitelist or blacklist for Watchtower before? If so, could you share your experience and any tips you might have?

Thank you in advance for your help!

**Comment by piksel** [comment]
You can provide a regex as the first argument to watchtower to only update containers matching that expression.

**Comment by vawaver** [comment]
> You can provide a regex as the first argument to watchtower to only update containers matching that expression.

Thank you for your response. 
Although I am not a professional in the IT field or a programmer, I would like to kindly ask you to provide an example of a docker-compose.yml file that reflects these specific requirements. 
In this case, the desired outcome would be to prevent the Docker Nextcloud AIO from being updated on my Ubuntu server, while allowing the Docker containers for the Plex server and Jellyfin to receive updates.
Thank you.

**Comment by Migelo** [comment, marked as answer]
1+ years late, but still. 👋  search engine people.

You can achieve this by restricting watchtowerr to only update labeled containers and then add the labels to containers you want to update

1. Run watchtower with the [enable label feature](https://containrrr.dev/watchtower/arguments/#filter_by_enable_label) turned on,
2. add `com.centurylinklabs.watchtower.enable: "true"` to any container you want watchtower to monitor.

`watchtower/docker-compose.yml`
```
services:
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
```


`mycontainer/docker-compose.yml`
```
services:
  jellyfin:
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```

You can verify if the labels are detected by running and seeing how the number of scanned containers changes.
`docker run -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once --label-enable`
