### DISCUSSION TITLE
Unable to get Discord notification to work

### DISCUSSION THREAD

**Discussion by SpaceFahad** [containrrr/watchtower#1715] [Q&A]
Hello,

I went through the whole docs for watchtower and it is truly helpful, but for some reason I am having this issue and it could be something wrong with my stack, no discord notification and it appears to me that the watchtower container created by my portainer stack is not getting any environment variables from the stack. Can someone check and tell me if I am doing anything wrong?

Portainer Stack:

```yaml
version: '3.8'
services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        environment:
          WATCHTOWER_NOTIFICATIONS_LEVEL: debug
          WATCHTOWER_NOTIFICATIONS: shoutrrr
          WATCHTOWER_NOTIFICATION_URL: discord://1137xxxxx@tQepxxxxxxxxx

        command: --label-enable --cleanup --interval 600 --stop-timeout 30s
        restart: unless-stopped 
```

Watchtower container log:

```
time="2023-08-05T00:51:05Z" level=info msg="Watchtower 1.5.3"
time="2023-08-05T00:51:05Z" level=info msg="Using no notifications"
time="2023-08-05T00:51:05Z" level=info msg="Only checking containers using enable label"
time="2023-08-05T00:51:05Z" level=info msg="Scheduling first run: 2023-08-05 00:51:15 +0000 UTC"
time="2023-08-05T00:51:05Z" level=info msg="Note that the first check will be performed in 9 seconds"
time="2023-08-05T00:51:15Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
time="2023-08-05T00:51:25Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
```

for some reason, I think the environment variables are not passed through to the container when the stack creates it. ( I can see the variables when I go to services in portainer but not when I go to the container)

any help is appreciated!
