### DISCUSSION TITLE
ENV authentication token for gitlab private registry

### DISCUSSION THREAD

**Discussion by spinnaker1** [containrrr/watchtower#1718] [Q&A]
Hello,

I use public docker images from `hub.docker.com` and docker images from a private container registry `https://registry.gitlab.com/username/`.

How do I set the ENV variables for the Authentication Token for gitlab private container repository in watchtower docker-compose.yml?

Using ENV variables `-REPO_USER=spinnaker1` and `-REPO_PASS=my-gitlab-access-token` does not work for authentication.

**Comment by spinnaker1** [comment]
Anybody can help?

**Comment by piksel** [comment]
Are you saying that you are using docker compose and putting the credentials like this?
```yaml
environment:
  - REPO_USER=spinnaker1
  - REPO_PASS=my-gitlab-access-token
```

I think that *should* work, but the recommended approach is to put the credentials into a docker config and mount it, see [Private registries](https://containrrr.dev/watchtower/private-registries/) in the docs.

**Note**: I should also point out, for future readers, that using `REPO_*` will use those credentials for **_all_** repositories, so it would most likely error out when checking for updates on watchtower itself (which is normally pulled from dockerhub).

**Reply by spinnaker1** [reply]
This doesn't give any errors. But Watchtower also doesn't update any containers. I used docker login to create the `config.json` file and also checked with manually creating the base64 auth-string, to match.

----------------------

`root/.docker/config.json`
```json
{
    "auths": {
        "registry.gitlab.com": {
            "auth": "xxx"
        }
    }
}
```

----------------------

`docker-compose.yml`
```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_SCHEDULE=0 0 1 * * *
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://my-gotify-endpoint/
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=xxxx
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_RUN_ONCE=True
```
----------------------
