### DISCUSSION TITLE
End of range (24) above maximum (23): 24

### DISCUSSION THREAD

**Discussion by ItsNik-yaml** [containrrr/watchtower#1742] [Q&A] [answered]
Hi there so i am fairly new to watchtower and i just got this error while i was trying to connect it to "HomePage" via the http API.

Those are the logs from the docker container:
`End of range (24) above maximum (23): 24`
There is nothing more

And here is my docker-compose
```yaml
 watchtower:
    network_mode: host
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      TZ: Europe/Berlin
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: "xxx"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "Raspberry - Pi"
      WATCHTOWER_SCHEDULE: "0 0 24 * * *"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: >
        discord://xxx@xxx
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
