### DISCUSSION TITLE
How to gracefully restart dependent containers when dependency gets updated?

### DISCUSSION THREAD

**Discussion by bbtufty** [containrrr/watchtower#1773] [Q&A]
Hi,

I'm having an issue than when I have network-linked containers, if the top one in the chain gets updated then the others will not reconnect via that network and have to be manually restarted. So, for example, I have:

```
  service1:
    image: image1
    container_name: service1
    network_mode: bridge  
    restart: unless-stopped

  service2:
    image: image2
    container_name: service2
    network_mode: service:service1
    depends_on:
      service1:
         condition: service_started
    labels:
      com.centurylinklabs.watchtower.depends-on: "service1"
    restart: unless-stopped
```

If service1 gets updated, then service2 loses the network and will not reconnect. I'm sure this is simple to fix but I haven't found a way that works, and no answered discussions here either. Any thoughts appreciated!
