### DISCUSSION TITLE
Discord notification twice and NO update notification

### DISCUSSION THREAD

**Discussion by masterwishx** [containrrr/watchtower#1787] [Q&A] [answered]
Using Docker in Oracle cloud + Portainer stack
have twice same notifiation on discord and no notify on containers Update:

![image](https://github.com/containrrr/watchtower/assets/28630321/f97bcd22-4675-4867-9fb9-6cddbfd63927)

![image](https://github.com/containrrr/watchtower/assets/28630321/b99b1aae-6e20-420d-b35b-88e12868d27c)

![image](https://github.com/containrrr/watchtower/assets/28630321/54b190a5-66f6-4218-afbb-57605841e9f3)

**Comment by piksel** [comment]
The notification doesn't look like it was made from the default watchtower template. 
Perhaps there is something going wrong with the `discord` service message splitting. Try disabling the line splitting by adding `&splitlines=no` to your `discord://` URL.
If that fixes the output, this should be reported as a shoutrrr issue.

**Comment by masterwishx** [comment]
> If that fixes the output, this should be reported as a shoutrrr issue.

Sorry what do you mean not from default template, should i change it?

added but same , sending twice ...
i removed quotes also :

![image](https://github.com/containrrr/watchtower/assets/28630321/052fc2c5-b11f-413f-a6f1-10f8ece05c95)

**Reply by piksel** [reply]
You keep posting odd screenshots that does not show much of the config. Try pasting the config as text and just remove your discord token from the URL.

> not from default template, should i change it?

If you are using the default template, then no. The output in your screenshot does not look like how the template should render. If you *do* have a custom template, you should post it so that we can help fixing it.

My suggested fix is to add `&splitlines=no` to your `discord://` URL (`WATCHTOWER_NOTIFICATION_URL`).

**Reply by masterwishx** [reply]
I posted my config (screenshot) from portainer stack.
I can't find template for docker-compose.yml
in github 3 years old and don't have all config.
So I made notification from docs.
Maybe you can post right template?
I added &splitlines=no at end, don't have changed anything.
I removed "" from discord link, now I have twice + half of notification...

**Reply by masterwishx** [reply]
```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
 #     WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: discord://tocken@webhook
 #   ports:
 #     - 3003:3000
 #   networks:
 #    - proxy  
    restart: unless-stopped
    command: --rolling-restart --cleanup --debug --schedule "0 10 10,22 * * *"
 

#networks:
#  proxy:
#    driver: bridge
#    external: true    
```
