### DISCUSSION TITLE
Reg. Synology Support

### DISCUSSION THREAD

**Discussion by simonaronsson** [containrrr/watchtower#1840] [Q&A]
None of us, the maintainers of this project, currently have access to any Synology devices. We've tried using the demo Synology provides, but it's just not cutting it.

If anyone in the community, or the companies using Watchtower in their stack, would like to contribute a Synology device - Please let us know! This would definitely make troubleshooting and helping you out more reasonable for us. Until then, the support for Synology will stay on a best effort-basis.

**Comment by piksel** [comment]
And just to clarify why Synology devices are singled out; they run their own version of the Docker daemon and it doesn't always behave as expected, giving incorrect or partial information of containers. This makes it hard for watchtower to function correctly on them and we have yet to find a reason for why this is happening.

**Comment by juliansteenbakker** [comment]
You could also run DSM in a virtualbox using [xpenology.com](https://xpenology.com/forum/topic/6927-tutorial-install-6x-on-oracle-virtualbox-juns-loader/)!

**Comment by piksel** [comment]
Yeah, I couldn't get xpenology working last time I tried it. It also doesn't seem strictly... legal?

**Comment by juliansteenbakker** [comment]
It's a grey area.. [from the FAQ:](https://xpenology.com/forum/topic/9392-general-faq/?tab=comments#comment-82389)

> Disk Station Manager (DSM) is based on Open Source code and XPE/DSM takes advantage of Open Source sharing and use. You should always use your own jugement and read before installing and using DSM with XPEnology. We cannot be held responsible for your actions.

I think if you don't use any of the services that need a license you'd be fine since it's open source.
[The Synology source can be found here.](https://sourceforge.net/projects/dsgpl/)

**Comment by tammert** [comment]
@simskij @piksel I actually own a DS218+ (it's where I run my `watchtower` instance), so if there's any specific troubleshooting to do I'd be happy to do it

**Comment by TheLastProject** [comment]
Running on Synology worked fine when starting manually through SSH (as there is no way to bind the docker socket from the UI):

```
sudo docker run --name="watchtower" -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower
```

After starting manually through SSH, it does show up in the Synology Docker UI.

Sadly, because labels cannot be set from the Synology UI, there is some functionality that I cannot use (like tagging containers to exclude), but alas.

For some reason, each restart done by Watchtower causes a "Docker container <name> stopped unexpectedly. Go to Docker for more information" notification in Synology, but I don't mind that very much.

![Screenshot 2021-11-18 at 13 48 27](https://user-images.githubusercontent.com/1885159/142418263-09adf561-ddbf-4535-b2ad-ce8f1c26b340.png)

Edit: #968 happens for me for one container (Home Assistant) but not for others. I do not know why.

Edit 2: I stopped using Synology and migrated to a new device running OpenMediaVault. No issues anymore since.

**Comment by halteach** [comment]
So is this the way to start the watchtower on Synology?

> Running on Synology worked fine when starting manually through SSH (as there is no way to bind the docker socket from the UI):
> 
> ```
> sudo docker run --name="watchtower" -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower
> ```
> 
> After starting manually through SSH, it does show up in the Synology Docker UI.
> 
> Sadly, because labels cannot be set from the Synology UI, there is some functionality that I cannot use (like tagging containers to exclude), but alas.
> 
> For some reason, each restart done by Watchtower causes a "Docker container stopped unexpectedly. Go to Docker for more information" notification in Synology, but I don't mind that very much.
> 
> ![Screenshot 2021-11-18 at 13 48 27](https://user-images.githubusercontent.com/1885159/142418263-09adf561-ddbf-4535-b2ad-ce8f1c26b340.png)
> 
> Edit: #968 happens for me for one container (Home Assistant) but not for others. I do not know why.

**Comment by lazou** [comment]
@halteach Yes, this would be one way. Another way would be to use docker-compose, but this still requires a terminal via SSH.
I use the following `docker-compose.yml`
```yaml
version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
This file should be saved into an own folder (e.g. `watchtower`) within your docker directory (e.g. `/volume1/docker`). Then go to your new directoy within your terminal session and use the following commands:

```shell
# create and start container
docker-compose up -d
# stop and remove container
docker-compose down
```

**Comment by newadventure079** [comment]
I get the error too every time watchtower runs
![Screen Shot 2022-03-27 at 8 33 03 PM](https://user-images.githubusercontent.com/84156407/160316937-1873370b-3f71-4dc7-b0d4-545c060c62be.jpg)

**Comment by piksel** [comment]
@newadventure079 have you checked what the "more information" says? We have nothing to go on here.

**Comment by lazou** [comment]
I think this is due to the fact that the synology docker implementation is not familiar with managing the docker containers from the outside. I had the same experience for containers which were created with docker compose via terminal.

**Comment by newadventure079** [comment]
@piksel Here is all the info it gives in the log
![Screen Shot 2022-03-28 at 12 10 20 PM](https://user-images.githubusercontent.com/84156407/160460474-6725da0b-e587-462e-831d-351a16939b57.jpg)

FYI - This didn't used to happen, and it started happening a couple weeks ago or so. I dont think there's been a watchtower update recently so I think it must be from one of the Synology updates.  I'm on DSM 7 btw.

**Comment by MilesTEG1** [comment]
Hello,
I'm using a DS920+ with watchtower to update my containers. I also use Portainer to create and deply my stacks.

If I can be some help, just ask 😃

**Comment by mtoensing** [comment]
Yes, this is a new problem that appeared recently. Maybe because of a watchtower change and/or a Synology Docker update.

**Comment by feron81** [comment]
I would like to install Watchtower on my Synology to update Home Assistant automatically. Can everyone helps me how to set it up?

**Comment by CamelT0E** [comment]
whats your prblem? You can easily install the container via: Control Panel / Task Scheduler / Create / Scheduled Task / User-defined script als root:

docker run -d --name=watchtower \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/localtime:/etc/localtime:ro \
-e TZ=Europe/Berlin \
-e WATCHTOWER_INCLUDE_STOPPED=true \
-e WATCHTOWER_SCHEDULE="0 0 4 * * *" \
--restart always \
containrrr/watchtower:latest --cleanup

**Comment by rdamazio** [comment]
I also successfully use watchtower on Synology, and there's currently one major caveat - there are some containers that Synology DSM itself creates, and those obviously fail to update:

`2023-02-16 07:54:32 (info): Unable to update container /synology_docviewer_2, err='Error response from daemon: manifest for synology/docviewer:1.3.0.0125 not found: manifest unknown: manifest unknown'. Proceeding to next.
2023-02-16 07:54:34 (info): Unable to update container /synology_docviewer_1, err='Error response from daemon: manifest for synology/docviewer:1.3.0.0125 not found: manifest unknown: manifest unknown'. Proceeding to next.`

Since they create it, and docker gives no way to update labels after container creation to exclude them the normal way, this means I get error messages for those every time - I'll file a separate request for having another way to exclude those.

**Comment by My-Random-Thoughts** [comment]
I am running Watchtower on my Synology without issue.  I got around the issue @halteach was having with the `/var/run/docker.sock` by deploying/configuring it via Portainer.

The only thing I notice is that I occasionally get the same `<container> stopped unexpectedly` message.  I can live with it

**Comment by HalfBit-hacks** [comment]
I also am running Watchtower on Synology, as far as I can tell with no issues. I'm still trying to figure out discord notifications, but I think that is layer8 issue more than a Synology issue. I'm still tweaking my settings in a bit of trial and error.

Here's my docker-compose.yaml

```
version: "3"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    secrets:
      - DISCORD_WEBHOOK
    environment:
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "Watchtower1"
      TZ: America/Chicago
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: false
      WATCHTOWER_RUN_ONCE: false
      WATCHTOWER_SCHEDULE: 0 0 5,14,20 * * *
      WATCHTOWER_NOTIFICATION_URL: '/run/secrets/DISCORD_WEBHOOK'
      WATCHTOWER_NOTIFICATION_REPORT: true
      WATCHTOWER_NOTIFICATIONS_LEVEL: info # panic, fatal, error, warn, info (default), debug or trace
#      WATCHTOWER_NOTIFICATION_LOG_STDOUT:
#      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_PORCELAIN: v1
      WATCHTOWER_DEBUG: false
      WATCHTOWER_LOG_FORMAT: Auto # Auto (default), LogFmt, Pretty or JSON
      WATCHTOWER_LOG_LEVEL: info # panic, fatal, error, warn, info (default), debug, or trace
    restart: unless-stopped
```

Here's my log ouput:
```
time="2024-05-18T17:52:25-05:00" level=info msg="Watchtower 1.7.1"
time="2024-05-18T17:52:25-05:00" level=info msg="Using notifications: discord, logger"
time="2024-05-18T17:52:25-05:00" level=info msg="Only checking containers using enable label"
time="2024-05-18T17:52:25-05:00" level=info msg="Scheduling first run: 2024-05-18 17:55:25 -0500 CDT"
time="2024-05-18T17:52:25-05:00" level=info msg="Note that the first check will be performed in 2 minutes, 59 seconds"
time="2024-05-18T17:52:25-05:00" level=info msg="Skipping notification due to empty message" notify=no
```

Then when the check is performed, I get the following in the logs and in Discord:
```
/container1 (image1:latest): Fresh
/container2 (dev2/image2:latest): Fresh
/container3 (image3:latest): Fresh
/portainer (portainer/portainer-ce:latest): Fresh
/pihole (pihole/pihole:latest): Fresh
<...>
```
With everything in monitor_only, I'm not seeing notifications of an image I know has an update. I'm still working through things...
