### DISCUSSION TITLE
Watchtower fails to finalise update to itself in a custom docker image

### DISCUSSION THREAD

**Discussion by dennislapchenko** [containrrr/watchtower#1857] [Q&A]
### Describe the bug

There are some issues about watchtower failing to update itself, but none address specifically this.
Even logically, I did expect that watchtower won't be able to restart itself while keeping up with the update flow.
Existence of PR's to fix this makes me think it should work OOTB but i am missing something..

### Steps to reproduce

- docker-compose.yaml:
```yaml
version: '3'

services:
  watchtower:
    image: 1337.dkr.ecr.eu-central-1.amazonaws.com/watchtower-ecr:latest
    restart: always
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LOG_LEVEL: debug
      WATCHTOWER_NO_STARTUP_MESSAGE: true
      WATCHTOWER_ROLLING_RESTART: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

- pushing an update to `latest` tag results in the sequence described in the log below.

### Expected behavior

Watchtower is able to perform a rolling update on itself

### Environment

- Platform: `amazon linux 2`
- Architecture: `x86_64`
- Docker Version: `Docker version 20.10.25, build b82b9f3`

### Your logs

```text
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=debug msg="Retrieving running containers"
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=debug msg="Got image name: 1337.dkr.ecr.eu-central-1.amazonaws.com/watchtower-ecr:latest"
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=debug msg="Digests did not match, doing a pull."
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=debug msg="Pulling image" container=/app-watchtower-1 image="1337.dkr.ecr.eu-central-1.amazonaws.com/watchtower-ecr:latest"
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=info msg="Found new 1337.dkr.ecr.eu-central-1.amazonaws.com/watchtower-ecr:latest image (0699444d0c70)"
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=debug msg="No pre-update command supplied. Skipping" container=/app-watchtower-1
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=info msg="Stopping /app-watchtower-1 (a597b39e974e) with SIGTERM"
app-watchtower-1  | time="2023-11-09T10:49:07Z" level=info msg="Waiting for running update to be finished..."
app-watchtower-1  | time="2023-11-09T10:49:17Z" level=debug msg="Removing container a597b39e974e"
app-watchtower-1 exited with code 137
```
```


### Additional context

_No response_
