### DISCUSSION TITLE
[SOLVED] Lifecycle hooks: rails db:migrate (Mastodon), docker-compose.yml

### DISCUSSION THREAD

**Discussion by Sieboldianus** [containrrr/watchtower#1873] [Q&A] [answered]
I am running the Mastodon image through the official `docker-compose.yml`.

This has worked great, but I would like to automate point releases (`4.2.*`) with Watchtower. I am very happy with Gitlab and Nextcloud running with watchtower already.

However, with Mastodon I don't know how to integrate `rails db:migrate` that is sometimes necessary after pulling the new image.

Normally, I would run:
```
docker compose run --rm web rails db:migrate
```

Can I use [Lifecycle hooks](https://containrrr.dev/watchtower/lifecycle-hooks/) for this?

.. e.g. maybe adding to the `docker-compose.yml`:
```
labels:
      - 'com.centurylinklabs.watchtower.scope=rails db:migrate'
```

.. but then I would expect that the `web` container will already be started and errors would start to appear right away.

Is there another way to integrate running `rails db:migrate` _before_ the `web` container is fully started?

There is a image linuxserver . This adds a "db:prepare" step, which runs "db:migrate" if the DB already exists. It runs the command when the container starts up. However, I don't want to use a different docker image and I don't want to build/modify the image myself.

**Comment by piksel** [comment]
The label you want to set is `com.centurylinklabs.watchtower.lifecycle.post-update=rails db:migrate` (and not `scope`), but I don't know about how that perticular service ought to be updated.

Perhaps you can just change the run command in the docker-compose.yml to:
```
rails db:migrate && bundle exec puma -C config/puma.rb
```

Which would always try to migrate before starting the main application.

**Reply by Sieboldianus** [reply]
Thank you. I will try and report back!

**Reply by Sieboldianus** [reply]
Well, that did not go well:
```
mastodon-sidekiq    | 2023-12-16T05:35:17.062Z pid=7 tid=5en INFO: Schedules Loaded
mastodon-sidekiq    | 2023-12-16T05:35:17.065Z pid=7 tid=5en uniquejobs=upgrade_locks INFO: Already upgraded to 7.1.29
mastodon-sidekiq    | 2023-12-16T05:35:17.065Z pid=7 tid=5en uniquejobs=reaper INFO: Starting Reaper
mastodon-sidekiq    | 2023-12-16T05:35:17.074Z pid=7 tid=2ij3 uniquejobs=reaper INFO: Nothing to delete; exiting.
mastodon-sidekiq    | 2023-12-16T05:35:17.088Z pid=7 tid=2ij3 uniquejobs=reaper INFO: Nothing to delete; exiting.
mastodon-web exited with code 0
mastodon-web exited with code 0
mastodon-web exited with code 0
```

```
  web:
    image: tootsuite/mastodon:${TAG:-latest}
    container_name: mastodon-web
    restart: always
    env_file: .env.production
    command: rails db:migrate && bundle exec puma -C config/puma.rb
```

**Reply by Sieboldianus** [reply]
I changed my `docker-compose.yml`and will see if this works:

```
version: '3'
services:
  web:
    image: tootsuite/mastodon:${TAG:-latest}
    container_name: mastodon-web
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - /srv/mastodon/data/public/system:/mastodon/public/system
    labels:
      - 'com.centurylinklabs.watchtower.lifecycle.post-update=rails db:migrate'

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
    command: --interval 86400 --enable-lifecycle-hooks
```

`.env:`
```
# the mastodon version tag to use
# e.g. TAG=v4.2.3; defaults to:
# TAG=v4.2.3
# watchtower: only update up to minor
TAG=v4.2
```

logs:
```
docker-watchtower-1  | time="2023-12-16T06:07:06Z" level=info msg="Watchtower 1.7.1"
docker-watchtower-1  | time="2023-12-16T06:07:06Z" level=info msg="Using no notifications"
docker-watchtower-1  | time="2023-12-16T06:07:06Z" level=info msg="Checking all containers (except explicitly disabled with label)"
docker-watchtower-1  | time="2023-12-16T06:07:06Z" level=info msg="Scheduling first run: 2023-12-17 06:07:06 +0000 UTC"
docker-watchtower-1  | time="2023-12-16T06:07:06Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
```
