### DISCUSSION TITLE
Docker Compose Scheduling

### DISCUSSION THREAD

**Discussion by Lockie85** [containrrr/watchtower#1878] [Q&A]
Hey,

I want watchtower to check and update containers at 01:00 in the morning. I've defined the following in docker compose:

```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 1 * * *
```

However, when I look in the logs I see this:
> time="2023-12-12T17:25:49Z" level=info msg="Watchtower 1.7.1"
> time="2023-12-12T17:25:49Z" level=info msg="Using no notifications"
> time="2023-12-12T17:25:49Z" level=info msg="Checking all containers (except explicitly disabled with label)"
> time="2023-12-12T17:25:49Z" level=info msg="Scheduling first run: 2023-12-12 18:01:00 +0000 GMT"
> time="2023-12-12T17:25:49Z" level=info msg="Note that the first check will be performed in 35 minutes, 10 seconds"

Meaning the update isn't running at 01:00. What have I done wrong?

Many Thanks
