### DISCUSSION TITLE
Is it possible to update images and notify for specific containers?

### DISCUSSION THREAD

**Discussion by binderth** [containrrr/watchtower#1930] [Q&A] [answered]
I have a bunch of containers running and I'd like to update all of them automatically - except one container. But I'd like to receive a notification for that one.

What I did so far:
```
version: "3.5"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=false
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NO_RESTART=false
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_DEBUG=false
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xx@yyy.de
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xx@yyy.de
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.yyy.de
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xx@yy.de
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=***
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Homeserver
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - TZ=Europe/Berlin
    network_mode: bridge
```

on the only container I'd like to update manually (cause it regularly has breaking changes) I configured: 
```
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

That one doesn't get updated as configured - but I'd like to receive a notification, if there's a new image available for it nevertheless.
Is this possible?
