### DISCUSSION TITLE
Discord Notifications returning 404

### DISCUSSION THREAD

**Discussion by AlexBrightwater** [containrrr/watchtower#1933] [Q&A] [answered]
Hello, I am new to this whole watchtower thing and have a few questions. I have read the Docs, they aren't very comprehensive though.

1. I mostly use docker compose with tags on images e.g nextcloud:27-fpm. Are those tags respected by watchtower?
2. When using notifications for discord, what is meant by token@channel. I suppose token from the bot and channel id, but the notifs don't work rn.
The Container crashes after sending this last log entry: 
```
time="2024-02-21T18:55:12Z" level=error msg="Failed to send shoutrrr notification" error="failed to send discord notification: response status code 404 Not Found" index=0 notify=no service=discord
```

This is my docker-compose.yml:
```
version: "3"
services:
  app:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: >
        discord://<bot token redacted>@<channel id redacted>
      WATCHTOWER_NOTIFICATION_TEMPLATE: '{{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}'
```

In case its important: I use Portainer Stacks.

**Comment by AlexBrightwater** [comment, marked as answer]
I read more through the documentation of **[shoutrrr](https://containrrr.dev/shoutrrr/v0.5/services/discord/)** and found out, that what they want is a webhook.

1. Create a webhook at discord server > channel > edit channel > integrations > webhooks > new webhook
2. Give it a name
3. Copy the webhook url
The URL looks like: https://discord.com/api/webhooks/< numbers >/< random shit >
< numbers > is the ID and < random shit > is the token. 


New watchtower docker-compose.yml:
```
version: '3'
services:
  app:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://<token>@<id>
      - WATCHTOWER_NOTIFICATION_TITLE="Watchtower Updates"
      - WATCHTOWER_MONITOR_ONLY=true
    command: --interval 30
 ```
