### DISCUSSION TITLE
How to Healthcheck on Watchtower?

### DISCUSSION THREAD

**Discussion by moutasem1989** [containrrr/watchtower#1949] [Q&A]
[containrrr/watchtower](https://containrrr.dev/watchtower/arguments/#health_check) has implemented health check since 1.6.0. Sadly I could not find a guid to implement it in Docker Compose. I have tried variants of this code but the results always Unhealthy. 

```
    healthcheck:
      test: ['CMD', '--health-check']
      interval: 600s
      timeout: 30s
      retries: 3
      start_period: 60s
```

Can someone tell me where I am going wrong?

**Comment by moutasem1989** [comment]
> [containrrr/watchtower](https://containrrr.dev/watchtower/arguments/#health_check) has implemented health check since 1.6.0. Sadly I could not find a guid to implement it in Docker Compose. I have tried variants of this code but the results always Unhealthy.
> 
> ```
>     healthcheck:
>       test: ['CMD', '--health-check']
>       interval: 600s
>       timeout: 30s
>       retries: 3
>       start_period: 60s
> ```
> 
> Can someone tell me where I am going wrong?

Tis worked:

```
healthcheck:
      test: ["CMD", "/watchtower", "--health-check"]
      interval: 600s
      timeout: 30s
      retries: 3
      start_period: 60s
```
