### DISCUSSION TITLE
Help - Can't pull from private GHCR

### DISCUSSION THREAD

**Discussion by yalihart** [containrrr/watchtower#1972] [Q&A]
```
time="2024-04-30T21:14:02Z" level=warning msg="Could not do a head request for \"ghcr.io/yalihart/redacted-project-name:e7c02f961274d359e326cee5e7d1d9f1c5811a7b\", falling back to regular pull." container=/redacted-project-name image="ghcr.io/yalihart/redacted-project-name:e7c02f961274d359e326cee5e7d1d9f1c5811a7b"
time="2024-04-30T21:14:02Z" level=warning msg="Reason: registry responded to head request with \"403 Forbidden\", auth: \"not present\"" container=/redacted-project-name image="ghcr.io/yalihart/redacted-project-name:e7c02f961274d359e326cee5e7d1d9f1c5811a7b"
time="2024-04-30T21:14:02Z" level=info msg="Unable to update container \"/redacted-project-name\": Error response from daemon: Head \"https://ghcr.io/v2/yalihart/redacted-project-name/manifests/e7c02f961274d359e326cee5e7d1d9f1c5811a7b\": unauthorized. Proceeding to next."
time="2024-04-30T21:14:02Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
```
I did docker login successfully and verified that the auth does appear in the config file. 

Watchtower still fails to pull the image, why? 

My Stack: 
```
version: "3.4"

services: 
  watchtower:
    image: containrrr/watchtower
    environment:

        WATCHTOWER_POLL_INTERVAL: 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ```

Im also getting no creds found
