### DISCUSSION TITLE
scoped instances get killed by unscoped instance

### DISCUSSION THREAD

**Discussion by jolly-jump** [containrrr/watchtower#1991] [Q&A]
Following this:
https://containrrr.dev/watchtower/running-multiple-instances/

I have three instances of watchtower:
- one (scope=weekly_and_restart) updates weekly all with the corresp. label
- one (scope=daily_and_restart) updates daily all with the corresp. label
- one (scope=none) updates daily all that have no label

The scoped ones work nicely together when there is no "unscoped" instance.

However, the "unscoped" instance kills the other two when started/restarted. It even kill itself once.

What am I doing wrong?

```  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCOPE: daily_and_restart
      WATCHTOWER_SCHEDULE: 0 35 20 ? * *

watchtower-weekly:
    image: containrrr/watchtower
    container_name: watchtower-weekly
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCHEDULE: 0 20 20 ? * 0   # every Sunday, every month, at 20:20:00, regardless of the day of month
      WATCHTOWER_SCOPE: weekly_and_restart

watchtower-unscoped:
   image: containrrr/watchtower
   restart: unless-stopped
   container_name: watchtower-unscoped
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   environment:
     #WATCHTOWER_SCOPE: none
     WATCHTOWER_MONITOR_ONLY: 'true'
     WATCHTOWER_POLL_INTERVAL: 86400 # daily
   command: --scope none watchtower mailcowdockerized-php-fpm-mailcow-1
```

- I tried the `WATCHTOWER_SCOPE: none` variant as well as the commandline argument shown.
- I tried explicit containers as shown as well as "no containers" meaning to watch over all unlabelled containers.
