### DISCUSSION TITLE
Why doesn't the rolling restart: false work?

### DISCUSSION THREAD

**Discussion by meza** [containrrr/watchtower#1992] [Q&A]
Hey all,

I've got the following setup with Watchtower

```
services:
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_LABEL_TAKE_PRECEDENCE=true
      - WATCHTOWER_TIMEOUT=900s
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
```

My independent services are set up with the labels as follows:

```
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.stop-signal: SIGUSR1
```

Based on the documentation my expectation would be that all containers that get updated, would get updated at the same time, in parallel. However, what is happening is that Watchtower is waiting on one before killing the next.
If I had the rolling restart configured, I'd understand it but I don't. What am I doing wrong?
