### DISCUSSION TITLE
Schedule confusion

### DISCUSSION THREAD

**Discussion by ZuluPilgrim** [containrrr/watchtower#2009] [Q&A] [answered]
I have the following set, which to my understanding should mean that Watchtower will run each Monday at midnight.
` WATCHTOWER_SCHEDULE: 0 0 * * 1`

It is now Thursday and my terminal is saying
`watchtower-watchtower-1  | time="2024-07-31T21:42:03+12:00" level=info msg="Note that the first check will be performed in 3673 hours, 17 minutes, 56 seconds" notify=no`

3673 hours is in over a hundred and fifty days time.

What am I doing wrong?

```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:8080
    environment:
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_SCHEDULE: 0 0 * * 1
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: me@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: me@email.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: me@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: mypasswd
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "465"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: Dockge-LAN
      TZ: mytimezone
      WATCHTOWER_NO_STARTUP_MESSAGE: true
      WATCHTOWER_HTTP_API_TOKEN: mytoken
      WATCHTOWER_HTTP_API_UPDATE: true
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: true
      WATCHTOWER_TIMEOUT: 30s
networks: {}

```
