### DISCUSSION TITLE
Multiple Remote Endpoints

### DISCUSSION THREAD

**Discussion by jershbytes** [containrrr/watchtower#2013] [Q&A]
Hello All,

First of all thank you for this wonderful tool, it has been great. 

I'm Wondering if there is a way to do Multiple Remote Endpoints. I've read the docs and currently have it configured like this 
```
watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Detroit
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE= 0 0 3 * * *
      - DOCKER_HOST= tcp://x.x.x.x:2375
      - DOCKER_HOST_1= tcp://x.x.x.x:2375
    restart: unless-stopped
```
`DOCKER_HOST_1` was my guess at trying to get multiple but that did not work. I tried how Dozzle does it as well as a hail mary and i don't think that worked either. Any Help would be appreciated. Also if this should not go there let me know.

**EDIT**: I forgot to mention my end goal. I'd like to be able to monitor the local instance itself and then the 3 other nodes I have.
