### DISCUSSION TITLE
Gotify extras text/markdown

### DISCUSSION THREAD

**Discussion by chiragkrishna** [containrrr/watchtower#2022] [Notification Templates]
i am not able to figure out how to include the title, priority, extras, message and text/markdown properly
i know i can include the priority and title in url : gotify://gotify.com/token/?title=title&priority=priority

i am trying this template
```yaml
      WATCHTOWER_NOTIFICATION_URL: "gotify://gotify.com/token/"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
            {{- if gt (len .Failed) 0 -}}
            {
              "title": "❌ Watchtower Updates ❌",
              "priority": 10,
              "extras": {"client::display": {"contentType": "text/markdown"}},
              "message": "--------------\n\n**Scanned:** {{len .Scanned}}/{{len .Scanned}} \n\n**Updated:** {{len .Updated}} {{- range .Updated}} \n\n - {{.Name}} ({{.ImageName}}){{- end }}\n\n**Skipped:** {{len .Skipped}} {{- range .Skipped}} \n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}\n\n**Failed:** {{len .Failed}} {{- range .Failed}} \n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}"
            }
            {{- else -}}
            {
              "title": "✅ Watchtower Updates ✅",
              "priority": 5,
              "extras": {"client::display": {"contentType": "text/markdown"}},
              "message": "--------------\n\n**Scanned:** {{len .Scanned}}/{{len .Scanned}} \n\n**Updated:** {{len .Updated}} {{- range .Updated}} \n\n - {{.Name}} ({{.ImageName}}){{- end }}\n\n**Skipped:** {{len .Skipped}} {{- range .Skipped}} \n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}\n\n**Failed:** {{len .Failed}} {{- range .Failed}} \n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}"
            }
            {{- end -}}
          {{- end -}}
        {{- end }}
```

i get this as notification
```
            {
              "title": "✅ Watchtower Updates ✅",
              "priority": 5,
              "extras": {"client::display": {"contentType": "text/markdown"}},
              "message": "--------------\n\n**Scanned:** {{len .Scanned}}/{{len .Scanned}} \n\n**Updated:** {{len .Updated}} {{- range .Updated}} \n\n - {{.Name}} ({{.ImageName}}){{- end }}\n\n**Skipped:** {{len .Skipped}} {{- range .Skipped}} \n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}\n\n**Failed:** {{len .Failed}} {{- range .Failed}} \n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}"
            }
```

**Comment by chiragkrishna** [comment]
Finallly was able to solve this using generic
```yaml
WATCHTOWER_NOTIFICATION_URL: "generic://gotifyURL/message?token=token"
WATCHTOWER_NOTIFICATION_REPORT: "true"
WATCHTOWER_NOTIFICATION_TEMPLATE: |
          {{- if .Report }}
              {{- with .Report }}
                  {{- if gt (len .Failed) 0 }}
                      {
                        "title": "❌ Watchtower BlackBox ❌",
                        "priority": 10,
                        "extras": {"client::display": {"contentType": "text/markdown"}},
                        "message": "--------------\n\n**Scanned:** {{len .Scanned}}/{{len .Scanned}}\n\n**Updated:** {{len .Updated}}{{- range .Updated }}\n\n - {{.Name}} ({{.ImageName}}){{- end }}\n\n**Skipped:** {{len .Skipped}}{{- range .Skipped }}\n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}\n\n**Failed:** {{len .Failed}}{{- range .Failed }}\n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}"
                      }
                  {{- else }}
                      {
                        "title": "✅ Watchtower BlackBox ✅",
                        "priority": 5,
                        "extras": {"client::display": {"contentType": "text/markdown"}},
                        "message": "--------------\n\n**Scanned:** {{len .Scanned}}/{{len .Scanned}}\n\n**Updated:** {{len .Updated}}{{- range .Updated }}\n\n - {{.Name}} ({{.ImageName}}){{- end }}\n\n**Skipped:** {{len .Skipped}}{{- range .Skipped }}\n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}\n\n**Failed:** {{len .Failed}}{{- range .Failed }}\n\n - {{.Name}} ({{.ImageName}})\n\n**Reason:** {{.Error}}{{- end }}"
                      }
                  {{- end }}
              {{- end }}
          {{- end }}
```
![Screenshot from 2024-09-18 07-06-17](https://github.com/user-attachments/assets/26811536-c975-4f89-ab66-bd71c8a6e7d3)
