### DISCUSSION TITLE
Monitor Only flag doesn't seem to be respected

### DISCUSSION THREAD

**Discussion by Rigel09** [containrrr/watchtower#2058] [Q&A]
Just tried out watchtower to get updates on when my containers need updated. Goal for now is just to get notifications only and then update manually. As the future progresses Ill add labels to have certain containers upgrade automatically.

I started out with this compose file and watched the logs. Expected to see which containers need updated but instead watchtower upgraded all my containers.

How do I get the monitor only flag to work? I tried it as an environment variable and in the command section but saw it still trying to do updates.
 
The couple other forum / reddit post I found about this didn't really have a solution other than swapping to DUIN.

Thanks in advance.

```
services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_DEBUG=true
      # - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      # - WATCHTOWER_POLL_INTERVAL=3600
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --monitor-only
```
