### DISCUSSION TITLE
run-once parameter executes multiple times, does not stop, does not give out info mails

### DISCUSSION THREAD

**Discussion by phit42** [containrrr/watchtower#568] [Q&A] [answered]
Starting watchtower with --run-once does not check all images once, but runs it multiple times (until I stopped the container manually).
Additionally, email notifications about updates in info mode are not generated, but instead the message "Running a one time update." is sent out multiple times via email.

Interestingly enough, a weekly schedule ("--schedule "@weekly" ") does not work either. Every single time, watchtower finds "multiple instances" after the first week, restarts itself and resets the timer, thus never updating the actual images.
(This is why I ran run-once in the first place.)

Only an interval setting appears to work correctly.

Here is the docker-compose.yml
```yml
version: '2'
services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower:latest
    environment:
      - TZ=Europe/Berlin
    env_file:
      - watchtower_notifications_settings.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: watchtower nzbhydra nzbhydra2 lidarr radarr sonarrv3 --run-once --stop-timeout 300s --cleanup --debug    ### run once
```
```
# watchtower container notification settings environment file
WATCHTOWER_NOTIFICATIONS=email
WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
WATCHTOWER_NOTIFICATIONS_LEVEL=info
```
(removed the server and user settings)

Watchtower is running on a Synology diskstation. Server: Engine: Version: 18.09.8, API version: 1.39, Go version: go1.11, Git commit: 3a371f3, Built: Fri Mar 13 06:44:35 2020, OS/Arch: linux/amd64

[watchtower.txt](https://github.com/containrrr/watchtower/files/4729634/watchtower.txt)
