### DISCUSSION TITLE
Using Watchtower with github packages

### DISCUSSION THREAD

**Discussion by sindreslungaard** [containrrr/watchtower#569] [Q&A] [answered]
Githubs docker registry does not allow tagged images to be modified or deleted, thus preventing watchtower from finding new images. I know there's an API that can be enabled to let watchtower know when to update, but afaik it does not let me specify what image tag to look for.

What is the recommended way of using watchtower with githubs package registry?

**Comment by victorcmoura** [comment]
I don't quite understand why Watchtower wouldn't work with GitHub's Docker Registry. Could you make it more clear? What is your use case?

**Reply by sindreslungaard** [reply]
Hey Victor

From what I understand, the way Watchtower checks for updates to images in any registry is by pulling down the image that was used to create the container it is checking. So if I start a container `example/some-application` then Watchtower will attempt to pull down `example/some-application:latest` and compare it to the current version. Please correct me if I got that wrong.

My problem with using Watchtower with Github's registry is that `example/some-application:latest` will never change and can't be overwritten by pushing a new image with the same tag. Using Docker Hub, pushing a new image with the latest tag will override the previous one, allowing Watchtower to find it and update the running container.

From what I have found this is intended behavior by Github, so I am not sure how Watchtower is suppose to find the latest image as the tag will always be different.

**Reply by sindreslungaard** [reply]
@victorcmoura It turns out that logging into the docker registry with my github username and password was the problem. This for some reason does not have the permissions required to overwrite images. I solved it by logging in to the registry with a personal token with delete rights on packages.

Works fine with Watchtower :)

**Reply by samru-rai** [reply]
I am still struggling with this. Maybe you can spot where I am making mistake? 

1. I used my personal token to authenticate myself with docker using their [instructions](https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages#authenticating-with-a-personal-access-token). This process created `$HOME/.docker/config.json`. 
2. I provided this file to my docker-compose as 
```
services:
  my-service:
   image: docker.pkg.github.com/OWNER/REPOSITORY/IMAGE_NAME:TAG
   ....
  watchtower:
    image: index.docker.io/containrrr/watchtower:latest
    volumes:
      - $HOME/.docker/config.json/:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
```
3. When I run my docker-compose, everything runs without error but the latest build for my particular tag doesn't get pulled.

Can you help me with this issue?

**Reply by piksel** [reply]
Hm, something seems a bit off, the github PACKAGE registry uses:
`docker.pkg.github.com/OWNER/REPOSITORY/IMAGE_NAME:TAG`
and the github CONTAINER registry uses:
`ghcr.io/OWNER/IMAGE-NAME`

**Reply by simonaronsson** [reply]
And with the packages registry, unfortunately, all bets are off.

**Reply by samru-rai** [reply]
> Hm, something seems a bit off, the github PACKAGE registry uses:
> `docker.pkg.github.com/OWNER/REPOSITORY/IMAGE_NAME:TAG`
> and the github CONTAINER registry uses:
> `ghcr.io/OWNER/IMAGE-NAME`

You are right. I had the format you mentioned but didn't write it correctly here. 

I fixed it by using labels as shown below. It is now pulling the latest image.

```
version: '3.7'
services:
  my-service:
    image: docker.pkg.github.com/OWNER/REPOSITORY/IMAGE_NAME:TAG
    ...
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --cleanup --label-enable
```
