### DISCUSSION TITLE
How do I schedule watchtower to run updates using cron expressions?

### DISCUSSION THREAD

**Discussion by oxy-32** [containrrr/watchtower#579] [Q&A] [answered]
I want watchtower to check for new updates every night at 4am. I'm using the .yml file below. I use the
  -WATCHTOWER_SCHEDULE: 0 0 4 * * * what am I doing wrong? Watchtower continues to monitor every 5 minutes. thank you in advance!

```
version: "3"

services:
  watchtower:
    container_name: watchtower
    restart: always

    environment:
      
      #WATCHTOWER_NOTIFICATIONS: email 
      #WATCHTOWER_NOTIFICATION_EMAIL_FROM: fromaddress@gmail.com
      #WATCHTOWER_NOTIFICATION_EMAIL_TO: toaddress@gmail.com 
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com 
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: fromaddress@gmail.com 
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: app_password
      -WATCHTOWER_SCHEDULE: 0 0 4 * * *
      -TZ: Europe/Brussels
      -WATCHTOWER_CLEANUP=true
      -WATCHTOWER_DEBUG=true
  
    image: containrrr/watchtower
     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by github-actions** [comment]
Hi there! 👋🏼 As you're new to this repo, we'd like to suggest that you read our [code of conduct](https://github.com/containrrr/watchtower/blob/master/CODE_OF_CONDUCT.md) as well as our [contribution guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md). Thanks a bunch for opening your first issue! 🙏

**Comment by tammert** [comment]
So, I can think of two things when looking at your YAML:
1) Remove the `-` before all environment variables -> `TZ` instead of `-TZ`
2) Quote the schedule string: `-WATCHTOWER_SCHEDULE: 0 0 4 * * *` -> `WATCHTOWER_SCHEDULE: "0 0 4 * * *"`

**Comment by oxy-32** [comment]
Thanks for your response! I did this but gives the same result:

`watchtower    | time="2020-06-14T00:26:06+02:00" level=info msg="Starting Watchtower and scheduling first run: 2020-06-14 00:31:06 +0200 CEST m=+300.960627480"`

**Comment by tammert** [comment, marked as answer]
It's working for me with the following `docker-compose.yaml`:
```
version: "3"

services:
  watchtower:
    container_name: watchtower
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      TZ: Europe/Brussels
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

From your given YAML, I had to change:
* `=` to `:` for CLEANUP and DEBUG
* double-quote the `true` values

How are you running this? I would expect you to see the same errors I'm seeing...

**Reply by oxy-32** [reply]
Dear Tammert I have made this change. And now it works as it should. I learned something again for which many thanks!.

**Reply by tammert** [reply]
Good to hear, you're very welcome :)

**Reply by frostbox42** [reply]
> It's working for me with the following `docker-compose.yaml`:
> 
> ```
> version: "3"
> 
> services:
>   watchtower:
>     container_name: watchtower
>     restart: always
>     environment:
>       WATCHTOWER_SCHEDULE: 0 0 4 * * *
>       TZ: Europe/Brussels
>       WATCHTOWER_CLEANUP: "true"
>       WATCHTOWER_DEBUG: "true"
>     image: containrrr/watchtower
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
> ```
> 
> From your given YAML, I had to change:
> 
> * `=` to `:` for CLEANUP and DEBUG
> * double-quote the `true` values
> 
> How are you running this? I would expect you to see the same errors I'm seeing...

It might be worth mentioning that the cron expression uses the Spring syntax, hence it has six fields, as opposed to the UNIX syntax. Cost me a good 30 minutes figuring that out as I kept getting weird settings when trying to use just 5 digits ;-)

**Reply by ERisEPR** [reply]
Thank you for the cron "SPRING" format mention, just solved a day and a half of going nuts.

**Comment by devops-abdullah** [comment]
```yaml
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=5 * * * * *
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_DEBUG=true
```
