### DISCUSSION TITLE
Watchtower ignoring disable labels and updating containers anyway

### DISCUSSION THREAD

**Discussion by spencerskinner99** [containrrr/watchtower#605] [Q&A] [answered]
I have two containers which I do not want to have watchtower auto-updating, so I used the filter flags with the intent of watchtower not updating these containers. An example of how I have deployed these containers is below -

```yaml
jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: GB
    network_mode: "service:transmission-openvpn"
    volumes:
    - /Docker_Configs/Jackett/config:/config
    - /media/VMRoot/VMMedia/:/downloads
    tty: true
    restart: unless-stopped
    depends_on:
      - "transmission-openvpn"
    labels:
      - com.centurylinklabs.watchtower.enable = "false"
```

My watchtower deployment is shown below too - 

```yaml
watchtower:
    image: containrrr/watchtower
    hostname: watchtower
    container_name: watchtower
    network_mode: le_bridge
    #environment:
     # WATCHTOWER_MONITOR_ONLY: "transmission-openvpn,jackett"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
    restart: unless-stopped
    
  
```

Ignore the monitor only section as that has been quoted out. 

Despite having the above configuration the Jackett container is still updating, this causes a 502 bad gateway error and means all other containers which require access to this container cant really function  as intended. 

I also have a hunch that I may have not interpreted the documentation correctly, should I have the WATCHTOWER_LABEL_ENABLE set to FALSE in the environment variables?

I am running Docker 18.06.5

**Comment by zoispag** [comment]
Hi there,

in order for the `com.centurylinklabs.watchtower.enable` label to be taken into account, you need to either pass the `--label-enable` flag to the watchtower command or set the `WATCHTOWER_LABEL_ENABLE` environment variable.

[Container selection](https://containrrr.dev/watchtower/container-selection/)

**Comment by spencerskinner99** [comment]
I have update my watchtower deployment as such - 

```yaml
watchtower:
    image: containrrr/watchtower
    hostname: watchtower
    container_name: watchtower
    network_mode: le_bridge
    environment:
      WATCHTOWER_LABEL_ENABLE: "enable"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
    restart: unless-stopped
```

Will I see anything in the logs to indicate that this has worked or will I have to wait until Jackett next updates?

Thanks
Spencer

**Comment by zoispag** [comment]
Although it _might_ have the same result, `WATCHTOWER_LABEL_ENABLE` expects a boolean value. For the object yml notation, you should write it as `WATCHTOWER_LABEL_ENABLE: 1`

Example from my `docker-compose.yml` file:

```yml
version: '3.5'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: Europe/Amsterdam
      WATCHTOWER_POLL_INTERVAL: 300       # Poll interval in seconds
      WATCHTOWER_INCLUDE_STOPPED: 1       # Include stopped containers
      WATCHTOWER_REVIVE_STOPPED: 1        # Restart stopped containers
      WATCHTOWER_CLEANUP: 1               # Delete unused image
      WATCHTOWER_LABEL_ENABLE: 1          # Only include containers with enable label
      WATCHTOWER_LIFECYCLE_HOOKS: 1       # Enable pre/post-update scripts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    labels:
      com.centurylinklabs.watchtower.enable: true

```

**Comment by spencerskinner99** [comment]
Oh yes, my mistake, I have changed it now

**Comment by spencerskinner99** [comment]
To clarify 

I have `WATCHTOWER_LABEL_ENABLE: 1 ` and on my container which i dont want to update I have -  

```yaml
labels:
      - com.centurylinklabs.watchtower.enable= "false"
```

Is this correct as my containers were updated again last night

I am using compose version 2 by the way

**Comment by KobesM** [comment]
Correct notation of labels with docker compose v2 is:

```yaml
labels:
    com.example.description: "Accounting webapp"
    com.example.department: "Finance"
    com.example.label-with-empty-value: ""
```

So you should probably use:
```yaml
labels:
    com.centurylinklabs.watchtower.enable: "false"
```

See: https://docs.docker.com/compose/compose-file/compose-file-v2/

**Comment by spencerskinner99** [comment]
I made the changes to the syntax as you have shown last night to 

```yaml
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: GB
    network_mode: "service:transmission-openvpn"
    volumes:
    - /Docker_Configs/Jackett/config:/config
    - /media/VMRoot/VMMedia/:/downloads
    tty: true
    restart: unless-stopped
    depends_on:
      - "transmission-openvpn"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
```
And of course my Watchtower looks like this 
```yaml

watchtower:
    image: containrrr/watchtower
    hostname: watchtower
    container_name: watchtower
    network_mode: le_bridge
    environment:
      WATCHTOWER_LABEL_ENABLE: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
    restart: unless-stopped
```
  
Jackett was again updated last night causing it to 502 error. This has me confused now as surely with the labels set like they are, the container shouldnt be updating?

**Comment by piksel** [comment]
Not sure if the types matter, but you are passing "false" as a string to the label. Maybe try removing the quotes?

**Comment by spencerskinner99** [comment]
Portainer refuses to deploy it when the quotes are removed, from what I can see, all that adding those flags has done is meant that only Jackett gets updates and my other containers are no longer touched

**Comment by the-lazy-fox** [comment]
From what I see in the documentation:
"Do not update containers that have com.centurylinklabs.watchtower.enable label set to false and no --label-enable argument is passed. Note that only one or the other (targeting by enable label) can be used at the same time to target containers."

So you should remove WATCHTOWER_LABEL_ENABLE: 1 and try again as you changed your label to exclude.

https://containrrr.dev/watchtower/arguments/#filter_by_disable_label

**Comment by simonaronsson** [comment, marked as answer]
There are two ways of doing this, and usually, you'd pick the one which gives you to the least amount of duplication in your config:

Exclude everything except when the enable label is set to true:

```yaml
  watchtower:
    [...]
    environment:
      WATCHTOWER_LABEL_ENABLE: 1
  included:
    [...]
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  excluded:
    [...]
```

Include everything except when the enable label is set to false:

```yaml
  watchtower:
    [...]
  included:
    [...]
  excluded:
    [...]
    labels:
      com.centurylinklabs.watchtower.enable: "false"    
```

Additional details in https://containrrr.dev/watchtower/arguments/#filter_by_disable_label and https://containrrr.dev/watchtower/container-selection/

If portainer refuses to read common yaml, I'd suggest opening an issue with them. This is perfectly valid when using `docker-compose` directly

**Reply by KevoM** [reply]
It throws me an error when updating the stack through Portainer. I had to write label**s** in **plural** in my `docker-compose` like so : 
```
labels:
      - "com.centurylinklabs.watchtower.enable=false"

**Reply by piksel** [reply]
Yeah, updated the example to align with docker-compose YAML (also quoted the values, as the YAML types for label values are `string`, but bare `true` is interpeted as boolean).

**Reply by Trufax** [reply]
Hi sorry for digging this up but i think its not worth a separate request. If i want to get notifications for ALL containers, but only automatically update a subset of them, would this work?

Set the label: `com.centurylinklabs.watchtower.monitor-only=true` on all containers i just want to be notified. Set NO label on the containers i want to auto update. 
Do i need to set : `WATCHTOWER_LABEL_ENABLE=true` on the watchtower container for this or not ? 

Thanks

**Reply by piksel** [reply]
@Trufax yeah, that's the intended way. No need to use `WATCHTOWER_LABEL_ENABLE=true`.

**Comment by Silversurfer79** [comment]
What a pain in the a*%e to get this to working, espicially on patching specfic containers. 

I found a way to get it to work, try this:

```
version: '3.5'


services:
  watchtower:
    image: containrrr/watchtower
    hostname: watchtower
    container_name: Watchtower
    environment:
      TZ: Europe/London
#     WATCHTOWER_RUN_ONCE: 1
      WATCHTOWER_POLL_INTERVAL: 86400        # Poll interval in seconds
#     WATCHTOWER_MONITOR_ONLY: 1             # Monitoring Only
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     command: --debug true Bazarr Firefox Gluetun Jellyfin Lidarr      #Add all your apps here to be updated
```
Source
https://www.youtube.com/watch?v=BRpUlNmI4wM&t=479s
