### DISCUSSION TITLE
Docker image to be used as a Watchtower HTTP API client in GitLabCI

### DISCUSSION THREAD

**Discussion by victorcmoura** [containrrr/watchtower#608] [Show and tell]
Greetings, everyone!

Lately, I've been using the HTTP API mode in one of my running instances and I thought a single CI job with a `curl` call wasn't elegant enough. That's why, inspired by [cdrx/rancher-gitlab-deploy](https://github.com/cdrx/rancher-gitlab-deploy), I created [victorcmoura/watchtower-gitlab-deploy](https://github.com/victorcmoura/watchtower-gitlab-deploy) to enable cleaner pipelines in GitLabCI.

Currently, the only feature is the single `v1/update` endpoint, and can be easily configured in a `.gitlab-ci.yml` job:
```yml
trigger_watchtower_update:
  stage: deploy
  image: victorcmoura/watchtower-gitlab-deploy
  script:
    - update
  only:
    - master
```

By setting a few env variables, the job is able to connect to the instance, authenticate and trigger an update.

It's still an initial idea and any suggestions will be appreciated =)
