### DISCUSSION TITLE
Does watchtower preserve local container data during upgrade?

### DISCUSSION THREAD

**Discussion by j-ktz** [containrrr/watchtower#635] [Q&A] [answered]
I just installed Watertower as a container in Docker and it updated Radarr and Tautulli and Sonarr. Radarr and Tautulli appear fine but Sonnar now is empty? No indexers, no download client, no series or settings. Any idea on how to fix this or do I have to start from scratch? 😬

**Comment by piksel** [comment]
My spontaneous guess is that the volumes where changed, but I  don't know enough about Sonarr. If that's the case, then the old data should still be present in a docker volume until it's cleaned up. I think the configuration is usually mounted from outside to prevent settings getting reset on update.

**Comment by zoispag** [comment, marked as answer]
I have my Sonarr volume mounted in the host machine for persistency.

From my docker-compose file:

```yml
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```
