### DISCUSSION TITLE
Prune volume after update

### DISCUSSION THREAD

**Discussion by mc-supply** [containrrr/watchtower#644] [Q&A] [answered]
I'm starting to investigate using Watchtower to automate updates.  The process works fine as I update my Docker Hub images; it reaches out and updates the local image.  However, the volume doesn't change (which makes sense).  Following this post: https://github.com/containrrr/watchtower/issues/383, I see it's possible to do a "docker volume prune" as a post update event.  When I do this, it executes the command and exits with a 127 error code, and does not do the prune.  I tried putting the absolute path to Docker in the command, but continues with the same error.  Here is my docker-compose.yml file:

```
version: "3.4"

services:
    php:
        build:
            context: ./docker/php
        volumes:
            - static-volume:/usr/share/nginx/html
            - ./screen:/screen/
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            BRANCH: ${BRANCH}
            HOST_IP: ${HOST_IP}
        healthcheck:
            test: "php -q /usr/share/nginx/html/health-check.php && php -q /usr/share/nginx/html/sync-files.php"
            interval: 60s
        restart: always
        labels:
        - "com.centurylinklabs.watchtower.enable=false"
    web:
        image: docker.io/mcsupply/tv-display:latest
        ports:
            - "443:443"
        volumes:
            - static-volume:/usr/share/nginx/html
            - ./ssl:/ssl/
            - ./screen:/screen/
        depends_on:
            - php
        restart: always
        labels:
            - "com.centurylinklabs.watchtower.lifecycle.post-update=docker volume prune"
            - "com.centurylinklabs.watchtower.enable=true"
    mysql:
        image: mariadb:latest
        ports:
            - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql            
            - mysql-volume:/var/lib/mysql
        restart: always
        labels:
        - "com.centurylinklabs.watchtower.enable=false"        
    watchtower:
        image: index.docker.io/containrrr/watchtower:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --debug --remove-volumes --enable-lifecycle-hooks
        labels:
        - "com.centurylinklabs.watchtower.enable=false"        
        restart: always
volumes:
    static-volume:
    mysql-volume:
```
