### DISCUSSION TITLE
Watchtower didn't find any other container

### DISCUSSION THREAD

**Discussion by warhammer73** [containrrr/watchtower#673] [Q&A] [answered]
My configuration looks like:
```
       watchtower:
                image: containrrr/watchtower
                container_name: watchtower
                volumes:
                       - /var/run/docker.sock:/var/run/docker.sock
                command: watchtower --interval 60 --cleanup --debug
                environment:
                         - TZ='Europe/Berlin'
                         #- REPO_USER='githubuser'
                         #- REPO_PASS='password'
                         - WATCHTOWER_NOTIFICATIONS=email
                         - WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXX                         - 
                         - WATCHTOWER_NOTIFICATION_EMAIL_TO=XXXX
                         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
                         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXXX
                         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXXX
                         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
                restart: always
```

I have some other containers running like `mariadb` or `nginx-proxy`,

My logfile looks like this:

```bash
$ docker logs 662d36ffe6b2
WARNING: Error loading config file: /root/.docker/config.json: EOF
time="2020-11-07T13:46:11Z" level=debug
time="2020-11-07T13:46:11Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-11-07T13:46:12Z" level=debug msg="Retrieving running containers"
time="2020-11-07T13:46:12Z" level=debug msg="There are no additional watchtower containers"
time="2020-11-07T13:46:12Z" level=info msg="Starting Watchtower and scheduling first run: 2020-11-07 13:47:12 +0000 UTC m=+60.588456543"
Failed to send notification email:  535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials t5sm6872277wmg.19 - gsmtp
time="2020-11-07T13:47:12Z" level=debug msg="Checking containers for updated images"
time="2020-11-07T13:47:12Z" level=debug msg="Retrieving running containers"
time="2020-11-07T13:47:12Z" level=debug msg="Pulling containrrr/watchtower:latest for /watchtower"
time="2020-11-07T13:47:12Z" level=debug msg="No credentials for containrrr in /config.json"
time="2020-11-07T13:47:12Z" level=debug msg="Got image name: containrrr/watchtower:latest"
time="2020-11-07T13:47:13Z" level=debug msg="No new images found for /watchtower"
time="2020-11-07T13:47:13Z" level=debug msg="This is the watchtower container /watchtower"
time="2020-11-07T13:47:13Z" level=debug msg="Scheduled next run: 2020-11-07 13:48:12 +0000 UTC"
```

I didn't understand the `config.json` warning - But I think that is not the problem.
The mail notification problem looks like google will not accept watchtower as a third-party app for sending mail. Don't know why - But I think that's also a different kind of problem.

My real problem: Why watchtower is not checking the other container for new images?

**Comment by simonaronsson** [comment]
Looks like watchtower doesn't have access to your config.json.
That might very well be the reason for your issues.

Does watchtower find any other containers if you don't mount the config?

**Comment by warhammer73** [comment]
The config.json is empty.

I don't know how "not to mount the config" because I don't know why watchtower is trying to read the config.json.
As you can see in the config there is no entry to read the config.json...


Thanks

**Reply by simonaronsson** [reply]
My bad, didn't notice that 😂

**Comment by warhammer73** [comment]
So, i changed two things:
1) My config.json is not empty anymore (https://github.com/containrrr/watchtower/issues/99)
2) I changed to another mail provider instead of gmail (hopefully will fix that later)

Now the logfile does not have any errors or warnings:
time="2020-11-07T21:31:00Z" level=debug
time="2020-11-07T21:31:00Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-11-07T21:31:01Z" level=debug msg="Retrieving running containers"
time="2020-11-07T21:31:01Z" level=debug msg="There are no additional watchtower containers"
time="2020-11-07T21:31:01Z" level=info msg="Starting Watchtower and scheduling first run: 2020-11-07 21:32:01 +0000 UTC m=+60.612511815"
time="2020-11-07T21:32:01Z" level=debug msg="Checking containers for updated images"
time="2020-11-07T21:32:01Z" level=debug msg="Retrieving running containers"
time="2020-11-07T21:32:01Z" level=debug msg="Pulling containrrr/watchtower:latest for /watchtower"
time="2020-11-07T21:32:01Z" level=debug msg="No credentials for containrrr in /config.json"
time="2020-11-07T21:32:01Z" level=debug msg="Got image name: containrrr/watchtower:latest"
time="2020-11-07T21:32:04Z" level=debug msg="No new images found for /watchtower"
time="2020-11-07T21:32:04Z" level=debug msg="This is the watchtower container /watchtower"
time="2020-11-07T21:32:04Z" level=debug msg="Scheduled next run: 2020-11-07 21:33:01 +0000 UTC"
time="2020-11-07T21:33:01Z" level=debug msg="Checking containers for updated images"
time="2020-11-07T21:33:01Z" level=debug msg="Retrieving running containers"
time="2020-11-07T21:33:01Z" level=debug msg="Pulling containrrr/watchtower:latest for /watchtower"
time="2020-11-07T21:33:01Z" level=debug msg="No credentials for containrrr in /config.json"
time="2020-11-07T21:33:01Z" level=debug msg="Got image name: containrrr/watchtower:latest"
time="2020-11-07T21:33:02Z" level=debug msg="No new images found for /watchtower"
time="2020-11-07T21:33:02Z" level=debug msg="This is the watchtower container /watchtower"
time="2020-11-07T21:33:02Z" level=debug msg="Scheduled next run: 2020-11-07 21:34:01 +0000 UTC"

But the problem is still: No other containers....

**Reply by simonaronsson** [reply]
Ah! I see the error now!

Remove `watchtower` from the command. You're now instructing watchtower to only monitor watchtower as the argument array you may give it is a list of containers to monitor.

As watchtower is running on a `scratch` image, `watchtower` is the entry point, and whatever you set as the `command` will be treated as arguments and/or flags.

Didn't notice it until reading it through a second time! 😅

**Reply by piksel** [reply]
Haha, of all the answers in this discussion, the one I would argue should actually be marked as the Answer is the only one that is a REPLY 😁

**Comment by warhammer73** [comment]
Well thx - Bit stupid from my side. 👍 

But I think I didn't understand something.
Now the logfile looks like:

```bash
time="2020-11-07T22:06:54Z" level=debug
time="2020-11-07T22:06:54Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-11-07T22:06:55Z" level=debug msg="Retrieving running containers"
time="2020-11-07T22:06:55Z" level=debug msg="There are no additional watchtower containers"
time="2020-11-07T22:06:55Z" level=info msg="Starting Watchtower and scheduling first run: 2020-11-07 22:07:55 +0000 UTC m=+60.833122914"
time="2020-11-07T22:07:55Z" level=debug msg="Checking containers for updated images"
time="2020-11-07T22:07:55Z" level=debug msg="Retrieving running containers"
time="2020-11-07T22:07:55Z" level=debug msg="Scheduled next run: 2020-11-07 22:08:55 +0000 UTC"
```
Which means the removal of "watchtower" helps to remove th "pulling" messages.
But I expected now to see all the containers with the "pulling" information. How can I check which container will be checked for updates by watchtower?


For a double check I changed the command line again:
`command: nextcloud --interval 60 --cleanup true --debug true`

Now i expected to get the same messages as at the beginning but with nextcloud instead of watchtower.
But that is not happen, messages looks are the same as without "nextcloud".

**Comment by simonaronsson** [comment]
no `true`s needed, as those also add to the container watch list. are you sure the container is actually named `nextcloud` and that it's not only the key you've used in docker-compose?

If you don't mind, pasting the input from `docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Networks}}"` would help tremendously.

**Comment by warhammer73** [comment, marked as answer]
Crazy thing, tried this direct from commandline instead of docker-compose:
```
$ docker run -d \
    --name watchtower3 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --debug
```

... and it's working.

Next step:
I removed all additional configuration (as mail, aso) from the `compose.xml` file 
... and it's also working.

Now it's more or less back to the old config (With schedule instead of interval, but interval worked also and without timezone because it's not changed to german local time):
```
        watchtower:
                image: containrrr/watchtower
                container_name: watchtower
                volumes:
                       - /var/run/docker.sock:/var/run/docker.sock
                command:  --schedule "0 0 11 * * *" --cleanup --debug
                environment:
                       - WATCHTOWER_NOTIFICATIONS=email
                       - WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXX
                       - WATCHTOWER_NOTIFICATION_EMAIL_TO=XXX
                       - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=XXX
                       - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXX
                       - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXX
                       - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=XXX
                restart: always
```
... and what should i say: It's working...


And yes: you are right, the correct name for the container was nextcloud-nextcloud - But it also not worked earlier.
Maybe something went wrong inside of docker, after some tests I had a lot of watchtowerX container, so I finally cleaned up docker and delete old containers, networks aso.

**Reply by simonaronsson** [reply]
How about:

```yaml
watchtower:
  image: containrrr/watchtower
  container_name: watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --interval 60 --cleanup --debug
  environment:
    - WATCHTOWER_NOTIFICATIONS=email
    - WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXX
    - WATCHTOWER_NOTIFICATION_EMAIL_TO=XXX
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=XXX
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXX
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXX
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=XXX
  restart: always
```

Does this work as well?
