### DISCUSSION TITLE
Update git repo on host before restarting container

### DISCUSSION THREAD

**Discussion by geraintwhite** [containrrr/watchtower#678] [Q&A] [answered]
I run my application in docker-compose and I use flyway to migrate the database using a mounted volume from my git repo.

I publish a new docker image from my CI setup and I'm trying to have the application auto-update to the new image while also pulling the new db migrations.

Is it possible to use the pre-update script to update my git repo so the latest db migrations are pulled before restarting the docker containers?

My docker-compose.yml is below:

```
version: '3.3'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope qa-web --no-restart
    labels:
      - 'com.centurylinklabs.watchtower.scope=qa-web'

  flyway:
    image: flyway/flyway
    command: migrate
    environment:
      - FLYWAY_USER=qa_user
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_SCHEMAS=qa_db
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_URL=jdbc:mysql://qa-db
    volumes:
      - ./database/migrations:/flyway/sql:ro
      - ./secrets/flyway.conf:/flyway/flyway.conf:ro
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    depends_on:
      - qa-db

  qa-web:
    image: qa-web:latest
    command:
      bash -c "while ping -c1 flyway &>/dev/null; do sleep 1; done; echo "Done";
      node main.js"
    restart: unless-stopped
    environment:
      - NODE_EXTRA_CA_CERTS=/ssl/BTCorporateRootCA.pem
    volumes:
      - ./config.docker.json:/usr/src/app/config.json
      - ./BTCorporateRootCA.pem:/ssl/BTCorporateRootCA.pem:ro
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    depends_on:
      - qa-db
      - flyway
    labels:
      - 'com.centurylinklabs.watchtower.scope=qa-web'
      - 'com.centurylinklabs.watchtower.lifecycle.pre-update="git pull"'

  qa-db:
    image: 'docker.io/bitnami/mariadb:10.4'
    volumes:
      - 'qaweb_mariadb-data:/bitnami/mariadb'
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_master_root_pwd
      - MARIADB_USER=qa_user
      - MARIADB_PASSWORD_FILE=/run/secrets/db_qa_user_pwd
      - MARIADB_DATABASE=qa_db
    secrets:
      - db_master_root_pwd
      - db_qa_user_pwd
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

secrets:
  db_master_root_pwd:
    file: ./secrets/db_master_root_pwd.txt
  db_qa_user_pwd:
    file: ./secrets/db_qa_user_pwd.txt

volumes:
  qaweb_mariadb-data:

```

**Comment by simonaronsson** [comment, marked as answer]
Should be perfectly possible. Are you experiencing any errors or undesired behavior?

**Reply by geraintwhite** [reply]
The docs say `It is possible to execute pre/post-check and pre/post-update commands inside every container updated by watchtower.` and it doesn't look like it is possible to have the commands run on the host (which I suppose makes sense Docker's security model). I think the best option for me is to embed the flyway migrations within an image rather than bind mounting it in.

**Reply by zoispag** [reply]
@grit96 please read this answer from @simskij as well: [use lifecycle hooks with a sidecar container](https://github.com/containrrr/watchtower/discussions/644#discussioncomment-79137)

**Reply by simonaronsson** [reply]
Is this a private or public repo? If it's a public repo, I'd just clone the repo as part of the Dockerimage build process instead, which would solve the problem altogether. If it's a private repo, I'd clone it on the CI runner (just to avoid having credentials in a Dockerfile), mount the repo and build it from there. No need to use watchtower at all for this use case from what I can tell.

Does that make sense or did I misinterpret your intentions?

**Reply by geraintwhite** [reply]
My issue was that my db migrations were mounted from a git repo on the host machine, and I wanted to fetch the latest migrations and run the `flyway` container whenever the `qa-web` container was updated by watchtower.

I ended up solving it by embedding the migrations into the `qa-web` container at build time (on the CI runner) and then mounting them into the `flyway` container via a named volume. I am now using a `healthcheck` and [`autoheal`](https://github.com/willfarrell/docker-autoheal) to automatically run the `flyway` container whenever the `qa-web` container was updated by watchtower.

```
version: '3.3'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_SCOPE=qa-web
      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'com.centurylinklabs.watchtower.scope=qa-web'

  autoheal:
    restart: always
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flyway:
    image: flyway/flyway
    entrypoint: sh -c 'flyway migrate && tail -f /dev/null'
    environment:
      - FLYWAY_USER=qa_user
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_SCHEMAS=qa_db
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_URL=jdbc:mysql://qa-db
    volumes:
      - 'qaweb_mariadb-migrations:/flyway/sql:ro'
      - ./secrets/flyway.conf:/flyway/flyway.conf:ro
    labels:
      - 'autoheal=true'
    healthcheck:
      test: 'curl -f http://qa-web:3000'
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    depends_on:
      - qa-web
      - qa-db

  qa-web:
    image: qa-web:latest
    command:
      sh -c 'rm /migrations/* && cp /usr/src/app/migrations/* /migrations &&
      sleep 30 && node main.js'
    restart: unless-stopped
    environment:
      - NODE_EXTRA_CA_CERTS=/usr/src/app/BTCorporateRootCA.pem
    volumes:
      - 'qaweb_mariadb-migrations:/migrations'
    labels:
      - 'com.centurylinklabs.watchtower.scope=qa-web'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

  qa-db:
    image: 'docker.io/bitnami/mariadb:10.4'
    volumes:
      - 'qaweb_mariadb-data:/bitnami/mariadb'
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_master_root_pwd
      - MARIADB_USER=qa_user
      - MARIADB_PASSWORD_FILE=/run/secrets/db_qa_user_pwd
      - MARIADB_DATABASE=qa_db
    secrets:
      - db_master_root_pwd
      - db_qa_user_pwd
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

secrets:
  db_master_root_pwd:
    file: ./secrets/db_master_root_pwd.txt
  db_qa_user_pwd:
    file: ./secrets/db_qa_user_pwd.txt

volumes:
  qaweb_mariadb-data:
  qaweb_mariadb-migrations:
```
