### DISCUSSION TITLE
Include hostname in shoutrrr notifications

### DISCUSSION THREAD

**Discussion by svengo** [containrrr/watchtower#717] [Q&A] [answered]
Hi,

is it possible to include the machine's hostname in shoutrrr notifications using `--notification-template`? I would like to send notifications from a few docker hosts to only one telegram chat. It would be pointless if I could not distinguish the source.

Thanks!

**Comment by svengo** [comment, marked as answer]
I solved the problem myself using docker-compose on-board tools: First I put `HOSTNAME=docker-prod01` in the .env file, then I used the environment variable in `docker-compose.yml`:

```yaml
version: '2.3'

services:
  watchtower:
    image: containrrr/watchtower
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_POLL_INTERVAL=28800      # 8 hours
      - WATCHTOWER_CLEANUP=true
      - "WATCHTOWER_NOTIFICATION_TEMPLATE={{range .}}${HOSTNAME}: {{.Message}}{{println}}{{end}}"
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://SECRET_TOKEN@telegram?channels=CHANNEL_ID
    restart: "${RESTART:-unless-stopped}"
```

It's working like a charm.
