### DISCUSSION TITLE
Remote host connection

### DISCUSSION THREAD

**Discussion by SAOPP** [containrrr/watchtower#781] [General] [answered]
Guys, I try to connect my remote host for updating one of container, my stack looks like this:

```
version: "2"
services:
  watchtower-adguard:
    image: containrrr/watchtower:latest
    container_name: watchtower-adguard
    hostname: watchtower-adguard
    restart: unless-stopped
    command: adguard
    environment:
      - TZ=Europe/Kiev
      - DOCKER_HOST="tcp://192.168.0.19:2375"
      - WATCHTOWER_DEBUG=true
```
In log I has see the next:

```
time="2021-01-16T00:16:00+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized.",
time="2021-01-16T00:16:01+02:00" level=debug msg="Retrieving running containers",
time="2021-01-16T00:16:01+02:00" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1,
time="2021-01-16T00:16:01+02:00" level=fatal msg="error during connect: Get \"http://192.168.0.19:2375\\\"/v%221.25%22/containers/json?filters=%7B%22status%22%3A%5B%22running%22%5D%7D&limit=0\": dial tcp: lookup 192.168.0.19:2375\": no such host"
```

What I do wrong?

curl to my remote host:
```
curl http://192.168.0.19:2375/images/json
[{"Containers":-1,"Created":1609156360,"Id":"sha256:725eacbaa59cba77974fbbdac1f590314bc202bc112b46f922bca03a6f851ebd","Labels":{"maintainer":"AdGuard Team <devteam@adguard.com>","org.opencontainers.image.created":"2020-12-28T11:45:53Z","org.opencontainers.image.description":"Network-wide ads & trackers blocking DNS server","org.opencontainers.image.licenses":"GPL-3.0","org.opencontainers.image.revision":"ace7c1c8","org.opencontainers.image.source":"https://github.com/AdguardTeam/AdGuardHome","org.opencontainers.image.title":"AdGuard Home","org.opencontainers.image.url":"https://adguard.com/adguard-home.html","org.opencontainers.image.vendor":"AdGuard","org.opencontainers.image.version":"v0.105.0-SNAPSHOT-ace7c1c8"},"ParentId":"","RepoDigests":["adguard/adguardhome@sha256:d9d20581f0904ce4f7318de5ea7cfcdbaa51a6b4bd22b6a8655702868ef8c4e8"],"RepoTags":null,"SharedSize":-1,"Size":48107937,"VirtualSize":48107937},{"Containers":-1,"Created":1598527421,"Id":"sha256:6b367a5c4fe3e272ae9fb6cf8393856562c99a6eb41d2922c8ab75a3e37d1813","Labels":null,"ParentId":"","RepoDigests":["portainer/agent@sha256:372dd13917381fb98560c44db66e54b5f6b3a2087e6ae9777fdc101485cb8fc7"],"RepoTags":["portainer/agent:latest"],"SharedSize":-1,"Size":89848087,"VirtualSize":89848087}]
```
