### DISCUSSION TITLE
Watchtower with Gotify

### DISCUSSION THREAD

**Discussion by SAOPP** [containrrr/watchtower#783] [General] [answered]
Guys, I have an this stack:

```
version: "2"
services:
  watchtower-adguard:
    image: containrrr/watchtower:latest
    container_name: watchtower-adguard
    hostname: watchtower-adguard
    restart: unless-stopped
    command: adguard
    environment:
      - TZ=Europe/Kiev
      - DOCKER_HOST=tcp://192.168.0.19:2375
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://192.168.0.29:6688
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=AwyN9Ak44Wr7Os_
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
```

Strange, but in log I see failed shoutrrr's notify, but I don't have this service yet, and watchtower can't connect to my gotify server also, with strange issue, WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY is not working property like.

```
Failed to send notification via shoutrrr (url=gotify://192.168.0.29:6688/AwyN9Ak44Wr7Os_):  failed to send notification to Gotify: Post "https://192.168.0.29/message?token=AwyN9Ak44Wr7Os_": x509: cannot validate certificate for 192.168.0.29 because it doesn't contain any IP SANs,time="2021-01-16T13:35:04+02:00" level=debug,
time="2021-01-16T13:35:04+02:00" level=warning msg="Using an HTTP url for Gotify is insecure",
time="2021-01-16T13:35:04+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized.",
time="2021-01-16T13:35:05+02:00" level=debug msg="Retrieving running containers",
time="2021-01-16T13:35:05+02:00" level=debug msg="There are no additional watchtower containers",
time="2021-01-16T13:35:05+02:00" level=debug msg="Watchtower HTTP API skipped.",
time="2021-01-16T13:35:05+02:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-17 13:35:05 +0200 EET m=+86400.427736061"
```
