### DISCUSSION TITLE
msteams notificaton on Windows

### DISCUSSION THREAD

**Discussion by Grunskin** [containrrr/watchtower#803] [Q&A] [answered]
Hi,

I'm trying to get `msteams` notification to work on my Windows Server host.
I created my own image with the latest build (https://github.com/containrrr/watchtower/releases/download/v1.1.6/watchtower_windows_amd64.zip) like this:

```
FROM mcr.microsoft.com/windows/nanoserver:20H2

COPY "watchtower.exe" /

ENTRYPOINT ["watchtower.exe"]

```

My `docker-compose.yml` looks like this:

```
version: "3.5"

services:
  watchtower:
    container_name: watchtower
    image: hub.mydomain.com/docker/watchtower
    volumes:
    - source: '\\.\pipe\docker_engine'
      target: '\\.\pipe\docker_engine'
      type: npipe
    network_mode: nat
    environment:
      - DOCKER_HOST=npipe:////./pipe/docker_engine
      - REPO_USER=watchtower
      - REPO_PASS=password
      - WATCHTOWER_NOTIFICATIONS=msteams
      - WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL=https://mycompany.webhook.office.com/webhookb2/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/IncomingWebhook/yyyyyyyyyyyyyyyy/zzzzzzzzzzzzzzzzzz
```

When I start the container I get the following message and the container stops:

```
time="2021-01-27T10:54:58+01:00" level=fatal msg="open https://mycompany.webhook.office.com/webhookb2/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/IncomingWebhook/yyyyyyyyyyyyyyy/zzzzzzzzzzzzzzzzzz: The filename, directory name, or volume label syntax is incorrect."
```

I have tried with `email` as notification and it works just fine and is sending me emails when it updates the container.
But as soon as I add `msteams` it crashes.

Does anyone have any idea what I'm doing wrong here? Or if it's a bug in watchtower itself?
