### DISCUSSION TITLE
Monitor Only doesnt work?

### DISCUSSION THREAD

**Discussion by 1mfaasj** [containrrr/watchtower#805] [Q&A] [answered]
Hello
I used the following YML to launch watchtower, but then NOTHING happens when it needs to do something. Am I missing something?

```
version: "3.4"
services:
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NO_PULL=true
      - WATCHTOWER_NOTIFICATIONS=email
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=myemail@gmail.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=myemail@gmail.com"
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myemail@gmail.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=mypassword"
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

the logging:
```
time="2021-01-26T07:36:56+01:00" level=warning msg="Using `WATCHTOWER_NO_PULL` and `WATCHTOWER_MONITOR_ONLY` simultaneously might lead to no action being taken at all. If this is intentional, you may safely ignore this message."                             
time="2021-01-26T07:37:00+01:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-27 07:37:00 +0100 CET m=+86403.440599214"                                                                                                                 
                                                 
```                                                                                                                                                                                                                
but nothing happens at the given time ???
