### DISCUSSION TITLE
Using Watchtower with Docker Compose.

### DISCUSSION THREAD

**Discussion by SimonBurfield** [containrrr/watchtower#818] [Q&A] [answered]
I am fairly new to docker and have just found Watchtower.  From what I have read, Watchtower can monitor docker images and when they change, download the latest from DockerHub and fire them up.

I have setup DockerHub to automatically build my images when I commit to Github, and my images are public.

My images are getting built and set to be the latest however I am not seeing any updates in Docker (Docker ps)

```
version: '3.2'

services:

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  burf-search:
    image: burf2000/burf-search
    restart: always
    ports:
      - "8888:80"
    networks:
        - skynet

  burf-ai:
    image: burf2000/burf-ai
    restart: always
    ports:
      - "8181:80"
    networks:
        - skynet
    
networks:
  skynet:
    driver: bridge
```

**Comment by simonaronsson** [comment, marked as answer]
From your configuration, the intended behavior would be that watchtower once a day checks for new images, and in case there are any, downloads them and recreates the container using the new image digest. Is this not what you're seeing?

**Reply by SimonBurfield** [reply]
Good morning, why is it once a day, is there a way to make it every 10 mins?

**Reply by SimonBurfield** [reply]
I have updated it to

```
 watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600
    restart: unless-stopped
```
