### DISCUSSION TITLE
Email alert testing and monitor only labels

### DISCUSSION THREAD

**Discussion by callahan22** [containrrr/watchtower#823] [Q&A] [answered]
Hi,

I'd like to test the email config of my watchtower docker-compose file as I'm not receiving emails. I notice there is a notification tester here: [here](https://github.com/containrrr/watchtower/blob/40ab6fd5ba9b7ba03536f556c556dc38e69c61c0/pkg/notifications/notifier_test.go) and I was wondering how I would use that in my docker-compose file to isolate the issues as the log files don't show anything with sudo docker logs -f watchtower

Note the need for an additional $ in my password to escape the $ that is actually in my password. No idea if this has any effect on the failure to email me but without the ability to debug, it's hard to tell.

My 2nd question is why watchtower updated my containers and ignored the monitor-only label. My docker-compose config looks like this:

```
watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@mydomain.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=me@myaddress.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp-relay"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=1234"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=smtp-email-server"
      # The "$" in the password needs to be escaped by adding an additional "$". The real password only has one "$" in it.
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=my_password_with_a_dollar_sign_in_it"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Docker-Host-1-"
    command: --schedule "0 8 * * *" --debug --include-restarting --cleanup
```

One of my containers is set up as follows:

```
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/tautulli/config:/config
      - ./docker/tautulli/logs:/logs:ro
      - ./docker/shared:/shared
    ports:
      - "8006:8181"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=999
    # Exclude from Watchtower auto upgrades - monitor and report only
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
```

The log files of watchtower reads:

```
$ sudo docker logs -f watchtower
time="2021-02-13T18:04:54Z" level=info msg="Starting Watchtower and scheduling first run: 2021-02-13 18:02:24 +0000 UTC m=+30.137118174"
time="2021-02-13T18:04:58Z" level=info msg="Starting Watchtower and scheduling first run: 2021-02-13 18:05:28 +0000 UTC m=+30.564573722"
time="2021-02-13T18:06:20Z" level=info msg="Found new linuxserver/tautulli:latest image (sha256:5159efac2aa5dd7a98efe998f9f6e4e2f6e26c3dcae1a35d430bf4e8cb8c3c81)"
time="2021-02-13T18:06:26Z" level=info msg="Stopping /tautulli (6bca106e0fa6bcec1da03812e7d60347b65042ebcd88f66ea803cab1c23f98ea) with SIGTERM"
time="2021-02-13T18:06:30Z" level=info msg="Creating /tautulli"
```
I didn't receive an email notification (hence the requirement to be able to send a test email to check config is correct). Additionally to that, when I then stopped the docker stack with sudo docker-compose down then brought it back up with sudo docker-compose up -d, the tautulli container was updated. I was under the impression that with the label I had assigned, I would just be emailed about there being an available updated but the update would not take place.

What am I missing?
