### DISCUSSION TITLE
Watchtower restarting every minute, not updating any containers, nothing happens?

### DISCUSSION THREAD

**Discussion by joq3** [containrrr/watchtower#824] [Q&A] [answered]
Hi,

I set up Watchtower with this line:
`sudo docker run -d -v /var/run/docker.sock:/var/run/docker.sock --restart unless-stopped --name watchtower v2tec/watchtower --rm=true --cleanup --schedule "0 0 4 * * *"`

That way it would run every night at 4AM, does this mean 04.00 in 24H format? Just making sure?

When I check the container I can see that Watchtower restarts every minute, and it seems to do nothing at all.

So I ran it again, but with the --debug flag, and this is the log file:
https://pastebin.com/LzPyvz0A

I don't understand what is happening, or why it isn't working.
When I check the /etc/cron.daily/ or /etc/cron.d/ I cannot find it either?

Help is appreciated!

**Comment by stffabi** [comment, marked as answer]
Hi,

The problem seems to be related to the `--rm` flag, it's a flag that is not supported by watchtower.

`{"log":"Incorrect Usage. flag provided but not defined: -rm\n","stream":"stdout","time":"2017-11-08T07:29:31.397819155Z"}`

I think you wanted to pass it to docker, therefore your command should look like this.

`sudo docker run -d -v /var/run/docker.sock:/var/run/docker.sock --rm --restart unless-stopped --name watchtower v2tec/watchtower --cleanup --schedule "0 0 4 * * *"`

All behind the image name will be passed as command line parameters to watchtower.

Your cron expressions looks good for 4AM, it's in 24H format, [see](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format)

**Comment by joq3** [comment]
Okey, thank you for the help, but somehow I managed to solve that. I created it as I wrote in my first post.
Then I went and edited it with OpenMediaVault Docker plugin (without changing anything) and saving. Now it runs. But I am having another issue.
Check this image:
https://imgur.com/a/iVLMQ

The old images are still there? Without a name.
The containers updated fine (except Ombi which I cannot connect to any longer), everything else work.

And another problem, I cannot find this in /etc/cron.daily/ or /etc/cron.d/?
I don't know how to check if it will run every night?

**Comment by stffabi** [comment]
Hmm, with --cleanup it should delete those old images. Maybe you could run it with `--debug`, so we have more output what's going on.

Cron is internally handled into in watchtower, it's not run by crontab.

**Comment by joq3** [comment]
How do I run it with debug? I don't know how to edit it, if I try to run it with the same line as before, it will tell me it is already existing?

Okey, great, so it should work then? Is there any way to verify this?

**Comment by joq3** [comment]
This is how it is setup now:
https://imgur.com/a/VRc01

I would like to run as debug, but the only way I know how is to delete the old Container and start over?

EDIT: I deleted the old one and tried to run it as you said:
`sudo docker run -d -v /var/run/docker.sock:/var/run/docker.sock --rm --restart unless-stopped --name Watchtower v2tec/watchtower --cleanup --schedule "0 0 4 * * *"`
This is the result:
`docker: Conflicting options: --restart and --rm.
See 'docker run --help'.`

**Comment by 1activegeek** [comment]
Explanation posted [HERE](https://forum.openmediavault.org/index.php/Thread/18220-Docker-Pull-Restart-Script-SOLVED/?postID=159194#post159194) for the conflict with --rm and --restart. These options can not be used together as --restart implies the container can be stopped/started and still exist, while the --rm flag implies the container and volumes should be deleted as soon as the container is stopped. 

I would also suggest now closing this issue as it's not truly an issue related to Watchtower. It was simply docker stuck in a restart loop for the container due to some issue upon launching based on the commands passed to it. The secondary issue with --rm and --restart has been explained now as well.

**Comment by fizcris** [comment]
I experienced the same issue with docker-compose using the following configuration:

```
version: "3"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: "Europe/Paris"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --cleanup --schedule "0 0 9 * * *"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
```

Simply change the `version: "2"` and it should fix the issue.

**Comment by antgustech** [comment]
I still have this issue, restarts every few seconds or so

```
version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - WATCHTOWER_MONITOR_ONLY=true      # Determines if only notifying or also updating.
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE="05 14 * * 0" # 14:05 every sunday
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxxx
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xxxx
```
