### DISCUSSION TITLE
Is the Shoutrrr update to 4.0 not in latest-dev?

### DISCUSSION THREAD

**Discussion by rg9400** [containrrr/watchtower#874] [Q&A]
I was using the `latest-dev` tag for Watchtower, but noticed I was not getting the new notifications everyone on `latest` was getting. It seems like Shoutrrr 4.0 is not available in this tag? If so, what is the purpose of this tag if it is not ahead of `latest`?

**Comment by piksel** [comment]
Both latest and latest-dev use v0.4.1 of shoutrrr. Check the logs for any errors and/or enable debug logs.

**Reply by rg9400** [reply]
Here are the debug logs on `latest-dev`

```
today at 3:39 PM  time="2021-03-31T15:39:34-05:00" level=debug
today at 3:39 PM  time="2021-03-31T15:39:34-05:00" level=debug msg="Detected a discord slack wrapper URL, using shoutrrr discord service"
today at 3:39 PM  time="2021-03-31T15:39:34-05:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
today at 3:39 PM  time="2021-03-31T15:39:35-05:00" level=debug msg="Retrieving running, stopped, restarting and exited containers"
today at 3:39 PM  time="2021-03-31T15:39:36-05:00" level=debug msg="There are no additional watchtower containers"
today at 3:39 PM  time="2021-03-31T15:39:36-05:00" level=debug msg="Watchtower HTTP API skipped."
today at 3:39 PM  time="2021-03-31T15:39:36-05:00" level=info msg="Starting Watchtower and scheduling first run: 2021-03-31 16:00:00 -0500 CDT"
```

Here are the debug logs on `latest`

```
today at 3:40 PM  time="2021-03-31T15:40:44-05:00" level=debug
today at 3:40 PM  time="2021-03-31T15:40:44-05:00" level=debug msg="Detected a discord slack wrapper URL, using shoutrrr discord service"
today at 3:40 PM  discord://<redacted>@<redacted>?avatar=&color=0x406170&colordebug=0x0&colorerror=0x0&colorinfo=0x0&colorwarn=0x0&splitlines=Yes&title=Watchtower+updates+on+Stormlight&username=Watchtower
today at 3:40 PM  time="2021-03-31T15:40:44-05:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
today at 3:40 PM  time="2021-03-31T15:40:45-05:00" level=debug msg="Retrieving running, stopped, restarting and exited containers"
today at 3:40 PM  time="2021-03-31T15:40:46-05:00" level=debug msg="There are no additional watchtower containers"
today at 3:40 PM  time="2021-03-31T15:40:46-05:00" level=debug msg="Watchtower HTTP API skipped."
today at 3:40 PM  time="2021-03-31T15:40:46-05:00" level=info msg="Watchtower v0.0.0-unknown\nUsing notifications: discord\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-03-31 16:00:00 -0500 CDT\nNote that the first check will be performed in 19 minutes, 13 seconds"
```
Here is the notification on `latest-dev`
![image](https://user-images.githubusercontent.com/39887349/113208667-b146dd00-9237-11eb-85e4-6ac9ebd83c2e.png)

Here is the notification on `latest`
![image](https://user-images.githubusercontent.com/39887349/113208716-bc017200-9237-11eb-9f41-68f26da3674a.png)

Here is my compose. Note the only thing I am doing is changing the image tag when testing both versions

```yaml
  watchtower:
    image: containrrr/watchtower:latest-dev
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://discord.com/api/webhooks/${WATCHTOWERWEBHOOK}/slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower
      - "WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=:whale:"
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_URL=https://raw.githubusercontent.com/containrrr/watchtower/master/logo.png
      - DOCKER_CONFIG=/config
    volumes:
      - ${CONFDIR}/watchtower:/config
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: ${HOSTNAME}
    logging: *default-logging
    restart: unless-stopped
```
