### DISCUSSION TITLE
Configure Discord notification with Docker-Compose

### DISCUSSION THREAD

**Discussion by Whisper40** [containrrr/watchtower#886] [Q&A] [answered]
I would like to receive notification for each update on my discord channel.

I added that to my docker-compose.yml
```
- WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL="discord://${DISCORD_TOKEN}@${DISCORD_ID} "
      - WATCHTOWER_NOTIFICATION_TEMPLATE="{{range .}}{{.Time.Format '12-01-2020 15:04:05'}} ({{.Level}})':' {{.Message}}{{println}}{{end}}"
```

In logs i get : 
```
time="2021-04-07T09:05:16Z" level=error msg="Could not use configured notification template: template: :1: malformed character constant: '12-01-2020 15:04:05'. Using default template"
time="2021-04-07T09:05:16Z" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"\\\"discord://1WXXXXvnqHZf0YT7Uo85flxNxigGOxSB-0iOrpY8dnmXXXXXXXHc@X28XXXXXXX065\": first path segment in URL cannot contain colon\n"
```

Does someone have a docker-compose example ?
The format in the documentation with docker run is not compatible with compose.
Thanks

**Comment by piksel** [comment, marked as answer]
You cannot use `'` for strings in the templates, which is why the error message complains about it being a character constant.
The docker-compose syntax for environment variables is confusing, since it's a list of strings, which themselves will be internally parsed.
But this should work:
```yaml
      - 'WATCHTOWER_NOTIFICATIONS=shoutrrr'
      - 'WATCHTOWER_NOTIFICATION_URL=discord://${DISCORD_TOKEN}@${DISCORD_ID}'
      - 'WATCHTOWER_NOTIFICATION_TEMLATE={{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})\':\' {{.Message}}{{println}}{{end}}'
```

You could also use the dict format for `environment:` which is less confusing, and allows you to use block scalars (with no backslash-escapes):
```yaml
    environment:
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_ID}"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})':' {{.Message}}{{println}}{{end}}

      WATCHTOWER_NOTIFICATIONS: shoutrrr
```
(note that I put the "shoutrrr" variable last in this example to show that the block scalar ends with an empty line)
