### DISCUSSION TITLE
Correct Email Monitoring Config

### DISCUSSION THREAD

**Discussion by Enissay** [containrrr/watchtower#890] [Q&A] [answered]
Hi,

I am using the config below and I was expecting daily emails with the list of containers to update (I guess), instead I am getting this so I am wondering if my config needs to be corrected:

![image](https://user-images.githubusercontent.com/794673/114173391-64e65600-9937-11eb-9aef-02d06a6a847b.png)

Config snippet:
```yaml
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_MONITOR_ONLY=true      # Due to Docker API limitations the latest image will still be pulled from the registry
      - WATCHTOWER_CLEANUP=true           # Removes old images after updating
      - TZ=Europe/Brussels
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      #####################################################################
      # Use Either SCHEDULE or INTERVAL (this last one in sec)
      # Cron help: https://crontab.guru/#0_0_8_*_*
      # cron: s | m | h | dom | m | dow
      - WATCHTOWER_SCHEDULE=0 0 8 * * *
      #- WATCHTOWER_POLL_INTERVAL=3000
      #####################################################################
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=e1@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=e1@gmail.com,e2@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=[DockerContainerUpdate]
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=e1@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xyz
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
      #####################################################################
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Any idea what needs ot be adpated in order to get only info about which containers can be updated ?
