### DISCUSSION TITLE
How to stop pulling image that is updated each day ?

### DISCUSSION THREAD

**Discussion by Whisper40** [containrrr/watchtower#891] [Q&A] [answered]
Hello, I'm using atmoz/sftp which has a new version each day without any changes, so i would like to stop pulling this image.
I read the documentation and i added to my docker compose this : 
```
labels:
      - com.centurylinklabs.watchtower.enable="false"
```

But this morning, i received this "Found new atmoz/sftp:latest image....".
I don't know if it's a bug or just something that i don't have found in the doc..

Thanks for any idea !

**Comment by zoispag** [comment, marked as answer]
This is not really a watchtower issue. Atmoz indeed pushed a new image an hour ago, even though there are no new commits on [GitHub](https://github.com/atmoz/sftp) since August 20, which is strange, so I guess they have an automation to rebuild the image every now and then maybe to get new security patches?)

In any case, if you want to use the `com.centurylinklabs.watchtower.enable="false"` label, you need to add this label to atmoz docker-compose service. Is that what you did?

**Reply by zoispag** [reply]
Is it indeed a scheduled build
![image](https://user-images.githubusercontent.com/21138205/114186527-a2ef7400-994f-11eb-8a92-6ce5bb52722d.png)

**Reply by Whisper40** [reply]
Yes sure i added this to the docker service only , like that : 

```
sftp:
    image: atmoz/sftp
    container_name: sftp
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable="false"
      - .....
```
