### DISCUSSION TITLE
Use monitor_only & label_enable to monitor by default, update the exceptions

### DISCUSSION THREAD

**Discussion by zilexa** [containrrr/watchtower#902] [Q&A] [answered]
Just wondering if the two can be used in conjunction like this, because the documentation does not say `WATCHTOWER_MONITOR_ONLY` would override `WATCHTOWER_LABEL_ENABLE`: 

```
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    networks: 
      - management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ: $TZ
      - WATCHTOWER_SCHEDULE: "0 0 * * 7"
      - WATCHTOWER_CLEANUP: 'true'
      - WATCHTOWER_LABEL_ENABLE: 'true'
      - WATCHTOWER_MONITOR_ONLY: 'true' 
```

Reason: 23 of my 26 containers I definitely do not want to auto-update, but I would like to receive notifications. With the above example, I would only need to add labels to the 3 containers that can be auto-updated.
