### DISCUSSION TITLE
running multiple instances to update some containers while just monitoring the rest?

### DISCUSSION THREAD

**Discussion by glc650** [containrrr/watchtower#962] [Q&A] [answered]
Here's my current watchtower config:

````
version:` "3.8"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_SCHEDULE=0 0 10,20 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=myemail
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=myemail
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=myemailserver
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myuser
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=mypass
    network_mode: "host"
````

As you can see I'm just monitoring all containers, checking twice a day for updates and sending an email notification when an update is found.

I now have a need to auto update (and clean up images/volumes) on some containers while still just monitoring the others.

I assume I should use multiple instances to do this?  If so, would this work?

```
version: "3.8"
services:
  monitor-only:
    image: containrrr/watchtower:latest
    #container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCOPE=monitor-only
      - TZ=America/Los_Angeles
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_SCHEDULE=0 0 10,20 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=myemail
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=myemail
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=myemailserver
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myuser
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=mypass
    labels:
      - "com.centurylinklabs.watchtower.scope=monitor-only"
    network_mode: "host"
  monitor-and-update:
    image: containrrr/watchtower:latest
    #container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCOPE=monitor-and-update
      - TZ=America/Los_Angeles
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 10,20 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=myemail
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=myemail
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=myemailserver
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myuser
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=mypass
    labels:
      - "com.centurylinklabs.watchtower.scope=monitor-and-update"
    network_mode: "host"
````
