### DISCUSSION TITLE
Watchtower does nothing

### DISCUSSION THREAD

**Discussion by dawid-woitaschek** [containrrr/watchtower#971] [Q&A] [answered]
Hi folks,

I was recently setting up Watchtower - sadly unsuccessful 'til now.

At every restart of the Watchtower container it will send an email telling me, when the next check will start.

"docker logs watchtower" is showing me that line and that's basically it:
```
time="2021-05-28T06:50:50+02:00" level=info msg="Watchtower 1.3.0\nUsing notifications: smtp\nOnly checking containers using enable label\nScheduling first run: 2021-05-28 06:51:20 +0200 CEST\nNote that the first check will be performed in 29 seconds"
```

My compose file looks like:

```
version: '3.7'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    security_opt:
            - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=user@domain.net
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=user@domain.net
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=someserver
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=user@domain.net
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXX
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_LEVEL=debug
    command: -i 30 --include-stopped --label-enable --stop-timeout 30s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
```

Do you have an idea of what's going on here? The label was added to the containers, of course...

Thanks in advance!
Dawid
