### DISCUSSION TITLE
Depends on and restarts on update

### DISCUSSION THREAD

**Discussion by pkly** [containrrr/watchtower#974] [Q&A]
Hi, I have a setup like so:
```yaml
nginx:
  image: whatever
  depends_on:
    - php-fpm

php-fpm:
  image: whatever

watchtower:
  image: containerrr/watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
   command: php-fpm --interval 600
```

Which _does_ work and my image for php-fpm is updated, but then I run into an issue.
Following a restart the nginx container will always throw 503s until I fully restart the compose, this is because of a config which says that php-fpm is an upstream server (typical config for this kinda thing)
How can I force a restart of my nginx service along with fpm? It does not update, but must start _after_ fpm is already up, otherwise it keeps returning invalid responses.

I looked at https://containrrr.dev/watchtower/linked-containers/ and it seems like it'd do the trick, but I'm kind of unable to figure out how it's supposed to be used.

**Comment by piksel** [comment]
Since you have specified that only `php-fpm` should be updated it doesn't restart nginx. Otherwise that should work. I assume that the reason you put it there is to avoid having nginx being updated? If so, you could pin nginx to stable (or 1.20) and add it to the watchtower command:
```yaml
   command: php-fpm nginx --interval 600
```

**Reply by pkly** [reply]
So as long any of the images are being updated all of the ones specified will be brought down, or just ones that have dependencies on each other?
My nginx image is a custom one, but it doesn't really change, so assuming I put both php-fpm and nginx in the command then if php-fpm is being restarted nginx will be brought down even though no update was found for it?

**Reply by piksel** [reply]
Yeah. Watchtower tries to stop all dependent containers before updating a stale one (and restarts them afterwards). But if you explicitly pass it a list of containers, it treats it as "don't touch anything else" basically.

**Reply by pkly** [reply]
Ah, cheers, I'll try it out and see if it works as expected.

**Reply by pkly** [reply]
@piksel okay so I added the nginx to my command and it doesn't seem like that's being shut down at all? I have the following messages in compose logs
```
found new config (my fpm image)
Stopping php_fpm with SIGTERM
Creating php_fpm
```
So, still kinda not really?
I could just run it without a command I suppose, maybe that'd help?

**Reply by piksel** [reply]
I guess docker-compose's `depends-on` doesn't translate into docker `docker run --link`s. Couldn't find anything about it in the documentation... 
Try adding the label to nginx:
```yaml
    labels:
      com.centurylinklabs.watchtower.depends-on: php-fpm
```

**Reply by pkly** [reply]
nope, nothing, same effect, image(s) get pulled, containers restart, the nginx container does nothing

**Reply by pkly** [reply]
Some additional info, I'm also using a volume that is bound in the php service and then also used in the server service, could that be causing issues?
```yaml
volumes:
  public-volume:

services:
  php_fpm:
    volumes:
      - public-volume:/var/www/public

  nginx:
    volumes:
      - public-volume:/var/www:ro # yes, the paths are fine
```

**Reply by piksel** [reply]
Could you show the watchtower logs, preferably with `--debug` added to the command. It should give some insight in what is going on.

**Reply by pkly** [reply]
Okay, so this is the output with debug:
Startup
```
shino_watchtower    | time="2021-06-01T18:09:29Z" level=debug
shino_watchtower    | time="2021-06-01T18:09:29Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
shino_watchtower    | time="2021-06-01T18:09:30Z" level=debug msg="Making sure everything is sane before starting"
shino_watchtower    | time="2021-06-01T18:09:30Z" level=debug msg="Retrieving running containers"
shino_watchtower    | time="2021-06-01T18:09:30Z" level=debug msg="There are no additional watchtower containers"
shino_watchtower    | time="2021-06-01T18:09:30Z" level=debug msg="Watchtower HTTP API skipped."
shino_watchtower    | time="2021-06-01T18:09:30Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nOnly checking containers with name \"shino_php_fpm\" or \"shino_bot\" or \"shino_nginx\"\nScheduling first run: 2021-06-01 18:19:30 +0000 UTC\nNote that the first check will be performed in 9 minutes, 59 seconds"
```
Update
```
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Checking containers for updated images"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Retrieving running containers"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Trying to load authentication credentials." container=/shino_nginx image="ghcr.io/pkly/shinobu-bot/shinobu-nginx:latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="No credentials for ghcr.io found" config_file=/config.json
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Got image name: ghcr.io/pkly/shinobu-bot/shinobu-nginx:latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Checking if pull is needed" container=/shino_nginx image="ghcr.io/pkly/shinobu-bot/shinobu-nginx:latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Building challenge URL" URL="https://ghcr.io/v2/"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:user/image:pull\"" status="401 Unauthorized"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Checking challenge header content" realm="https://ghcr.io/token" service=ghcr.io
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Setting scope for auth token" image=ghcr.io/pkly/shinobu-bot/shinobu-nginx scope="repository:ghcr.io/pkly/shinobu-bot/shinobu-nginx:pull"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="No credentials found."
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Parsing image ref" host=ghcr.io image=pkly/shinobu-bot/shinobu-nginx normalized="ghcr.io/pkly/shinobu-bot/shinobu-nginx:latest" tag=latest
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://ghcr.io/v2/pkly/shinobu-bot/shinobu-nginx/manifests/latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Found a remote digest to compare with" remote="sha256:5c946d938aa7547e51529f1d571760e7b853c9b49395740fce6527ac48f2228b"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg=Comparing local="sha256:5c946d938aa7547e51529f1d571760e7b853c9b49395740fce6527ac48f2228b" remote="sha256:5c946d938aa7547e51529f1d571760e7b853c9b49395740fce6527ac48f2228b"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Found a match"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="No pull needed. Skipping image."
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="No new images found for /shino_nginx"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Trying to load authentication credentials." container=/shino_bot image="ghcr.io/pkly/shinobu-bot/shinobu-bot:latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="No credentials for ghcr.io found" config_file=/config.json
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Got image name: ghcr.io/pkly/shinobu-bot/shinobu-bot:latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Checking if pull is needed" container=/shino_bot image="ghcr.io/pkly/shinobu-bot/shinobu-bot:latest"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Building challenge URL" URL="https://ghcr.io/v2/"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:user/image:pull\"" status="401 Unauthorized"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Checking challenge header content" realm="https://ghcr.io/token" service=ghcr.io
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="Setting scope for auth token" image=ghcr.io/pkly/shinobu-bot/shinobu-bot scope="repository:ghcr.io/pkly/shinobu-bot/shinobu-bot:pull"
shino_watchtower    | time="2021-06-01T18:19:30Z" level=debug msg="No credentials found."
shino_watchtower    | time="2021-06-01T18:19:31Z" level=debug msg="Parsing image ref" host=ghcr.io image=pkly/shinobu-bot/shinobu-bot normalized="ghcr.io/pkly/shinobu-bot/shinobu-bot:latest" tag=latest
shino_watchtower    | time="2021-06-01T18:19:31Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://ghcr.io/v2/pkly/shinobu-bot/shinobu-bot/manifests/latest"
shino_watchtower    | time="2021-06-01T18:19:31Z" level=debug msg="Found a remote digest to compare with" remote="sha256:881511c9618124d5f29188d9fc7e3cf37f892d44cc8bace05a399506397913fd"
shino_watchtower    | time="2021-06-01T18:19:31Z" level=debug msg=Comparing local="sha256:0b8d96e2868cbda9be1912dd4d1161d94587de84f5990a934ed92da36e8f141f" remote="sha256:881511c9618124d5f29188d9fc7e3cf37f892d44cc8bace05a399506397913fd"
shino_watchtower    | time="2021-06-01T18:19:31Z" level=debug msg="Digests did not match, doing a pull."
shino_watchtower    | time="2021-06-01T18:19:31Z" level=debug msg="Pulling image" container=/shino_bot image="ghcr.io/pkly/shinobu-bot/shinobu-bot:latest"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=info msg="Found new ghcr.io/pkly/shinobu-bot/shinobu-bot:latest image (abe435b6286c)"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Trying to load authentication credentials." container=/shino_php_fpm image="ghcr.io/pkly/shinobu-bot/shinobu-config:latest"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="No credentials for ghcr.io found" config_file=/config.json
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Got image name: ghcr.io/pkly/shinobu-bot/shinobu-config:latest"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Checking if pull is needed" container=/shino_php_fpm image="ghcr.io/pkly/shinobu-bot/shinobu-config:latest"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Building challenge URL" URL="https://ghcr.io/v2/"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:user/image:pull\"" status="401 Unauthorized"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Checking challenge header content" realm="https://ghcr.io/token" service=ghcr.io
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="Setting scope for auth token" image=ghcr.io/pkly/shinobu-bot/shinobu-config scope="repository:ghcr.io/pkly/shinobu-bot/shinobu-config:pull"
shino_watchtower    | time="2021-06-01T18:19:36Z" level=debug msg="No credentials found."
shino_watchtower    | time="2021-06-01T18:19:37Z" level=debug msg="Parsing image ref" host=ghcr.io image=pkly/shinobu-bot/shinobu-config normalized="ghcr.io/pkly/shinobu-bot/shinobu-config:latest" tag=latest
shino_watchtower    | time="2021-06-01T18:19:37Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://ghcr.io/v2/pkly/shinobu-bot/shinobu-config/manifests/latest"
shino_watchtower    | time="2021-06-01T18:19:37Z" level=debug msg="Found a remote digest to compare with" remote="sha256:f0944649ca00e3ebc829d8312d226dc8d94da236c38314b7a32cc46128226140"
shino_watchtower    | time="2021-06-01T18:19:37Z" level=debug msg=Comparing local="sha256:994f3877c846aeca8ec590773cad1290133c3677a42b8d080560e676179d58e8" remote="sha256:f0944649ca00e3ebc829d8312d226dc8d94da236c38314b7a32cc46128226140"
shino_watchtower    | time="2021-06-01T18:19:37Z" level=debug msg="Digests did not match, doing a pull."
shino_watchtower    | time="2021-06-01T18:19:37Z" level=debug msg="Pulling image" container=/shino_php_fpm image="ghcr.io/pkly/shinobu-bot/shinobu-config:latest"
shino_watchtower    | time="2021-06-01T18:19:46Z" level=info msg="Found new ghcr.io/pkly/shinobu-bot/shinobu-config:latest image (ad766047fc89)"
shino_watchtower    | time="2021-06-01T18:19:46Z" level=info msg="Stopping /shino_php_fpm (05ee49cf12c9) with SIGTERM"
shino_php_fpm       | [01-Jun-2021 18:19:46] NOTICE: Terminating ...
shino_php_fpm       | [01-Jun-2021 18:19:46] NOTICE: exiting, bye-bye!
shino_php_fpm exited with code 0
shino_watchtower    | time="2021-06-01T18:19:46Z" level=debug msg="Removing container 05ee49cf12c9"
shino_watchtower    | time="2021-06-01T18:19:46Z" level=info msg="Stopping /shino_bot (ded1b45d80b8) with SIGTERM"
shino_watchtower    | time="2021-06-01T18:19:56Z" level=debug msg="Removing container ded1b45d80b8"
shino_bot exited with code 137
shino_watchtower    | time="2021-06-01T18:19:57Z" level=info msg="Creating /shino_bot"
shino_watchtower    | time="2021-06-01T18:19:57Z" level=debug msg="Starting container /shino_bot (1bdfca15da82)"
shino_bot           | /usr/bin/docker-entrypoint.sh: line 4: ip: command not found
shino_watchtower    | time="2021-06-01T18:19:57Z" level=info msg="Creating /shino_php_fpm"
shino_watchtower    | time="2021-06-01T18:19:57Z" level=debug msg="Starting container /shino_php_fpm (3ad0486a92a4)"
shino_watchtower    | time="2021-06-01T18:19:58Z" level=debug msg="Session done: 3 scanned, 2 updated, 0 failed"
shino_watchtower    | time="2021-06-01T18:19:58Z" level=debug msg="Scheduled next run: 2021-06-01 18:29:30 +0000 UTC"
```
It appears as if the update mechanism works fine, but simply doesn't even bother checking dependencies?

**Reply by pkly** [reply]
I've removed specified containers from the command, only leaving in interval, checking if this works as expected...

**Reply by pkly** [reply]
Nope, that also has the same issue. It actually updated another unrelated image running in a different compose file as well, I'm guessing because of the lack of restrictions to which ones I actually wanna check.

**Reply by pkly** [reply]
Could there actually be a bug that if you run it in a docker-compose it does not correctly realize what containers should it bring up and down and in what order?

**Reply by piksel** [reply]
It shouldn't matter as it's talking directly to the docker daemon. But yeah, it definitely looks like it just doesn't see the label. 

Oh, wait... did you specify
```yaml
    labels:
      com.centurylinklabs.watchtower.depends-on: shino_php_fpm
```

docker-compose adds a namespace to the container names which must be included.

**Reply by pkly** [reply]
@piksel that should be on the nginx container, yes?
yeah I added it before, it's the same as what you wrote here.
Here's the exact file I'm using
```yaml
version: "3.0"

# this just binds the images so nginx can serve them properly
volumes:
  public-volume:

# for proxies
networks:
  default:
    external:
      name: shino_network

services:
  shino_maria_db:
    container_name: shino_maria_db
    image: mariadb:10.5.5
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mariadblib:/var/lib/mysql

  shino_php_fpm:
    container_name: shino_php_fpm
    image: ghcr.io/pkly/shinobu-bot/shinobu-config:latest
    restart: unless-stopped
    depends_on:
      - shino_maria_db
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@shino_maria_db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.5.5
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - public-volume:/var/www/public

  shino_nginx:
    container_name: shino_nginx
    image: ghcr.io/pkly/shinobu-bot/shinobu-nginx:latest
    restart: unless-stopped
    depends_on:
      - shino_php_fpm
    volumes:
      - public-volume:/var/www/public:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      - VIRTUAL_HOST=config.shinobu.chat
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=config.shinobu.chat
    labels:
      com.centurylinklabs.watchtower.depends-on: shino_php_fpm

  shino_bot:
    container_name: shino_bot
    image: ghcr.io/pkly/shinobu-bot/shinobu-bot:latest
    depends_on:
      - shino_maria_db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PREFIX=${BOT_PREFIX}
      - EMBED_COLOR=${BOT_COLOR}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - EMOTE_DEAD=${EMOTE_DEAD}
      - EMOTE_LOADING=${EMOTE_LOADING}
      - EMOTE_VERIFIED=${EMOTE_VERIFIED}
      - EMOTE_DANCE=${EMOTE_DANCE}
      - EMOTE_PLUS=${EMOTE_PLUS}
      - EMOTE_MINUS=${EMOTE_MINUS}
      - EMOTE_NEUTRAL=${EMOTE_NEUTRAL}
      - EMOTE_COINFLIP=${EMOTE_COINFLIP}
      - MIN_LOG_LEVEL=${MIN_LOG_LEVEL:-Verbose}
      - OWNER_IDS=${OWNER_IDS}
    volumes:
      - ./logs/bot:/home/bot/logs

  shino_watchtower:
    container_name: shino_watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: shino_php_fpm shino_bot shino_nginx --interval 600
```
