### DISCUSSION TITLE
How do I instruct watchtower to only update specific containers while running HTTP API mode?

### DISCUSSION THREAD

**Discussion by yuvrajalpha** [containrrr/watchtower#988] [General] [answered]
Hello All,

I have tried to update container using Http api mode and it is  succeeded for all containers but i tried to test update one container among 10 container then its work but again update all containers and we dont want this result.

Below docker compose file i have used for testing update container 

```
version: '3'
services:
  ota:
    image: docker.io/containrrr/watchtower:latest
    container_name: watchtower
    environment:
       - WATCHTOWER_HTTP_API_TOKEN=mytoken
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /user_location/.docker/config.json:/config.json
    
    command: --debug --http-api-update  
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
    restart : unless-stopped

  app1:
   image: index.docker.io/abc/test_w1
   container_name: test1
   environment:
    - PYTHONUNBUFFERED=1    
   labels:
      - "com.centurylinklabs.watchtower.enable=false"

  app2:
    image: index.docker.io/abc/test_w2
    container_name: test2
    environment:
     - PYTHONUNBUFFERED=1    
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

-------------****************----------

is above definition is correct to test update single container.
