### DISCUSSION TITLE
Watchtower email notification issue in combination with pi-hole?

### DISCUSSION THREAD

**Discussion by therealmaass** [containrrr/watchtower#989] [Q&A] [answered]
Hi folks,

i have a problem regarding watchtower in combination with pi-hole running in another container. I want to get notifications via email from Watchtower but I always get the same error. I thinks its a issue with dns but I'm not sure.
I also tried multiple Mail-Accounts (gmail and another mail) with different smpt servers. But both server don't work.

My docker-compose file:

```
version: '2.1'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    dns: 1.1.1.1
    #    dns: 192.168.178.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_MONITOR_ONLY= true
      - WATCHTOWER_SCHEDULE= 0 55 13 ? * SUN
        #- WATCHTOWER_SCHEDULE= 0 0 16 ? * THU
      - WATCHTOWER_CLEANUP= true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=info@example.org
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=user@example.org
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.example.org
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT= 587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=info
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSOWRD=test1234
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Pi Server Container Updates
      - WATCHTOWER_DEBUG= true
```
My log file:
`❯ docker logs watchtower -f
time="2021-06-10T17:23:40+02:00" level=info msg="Watchtower 1.3.0\nUsing notifications: smtp\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-06-13 13:55:00 +0200 CEST\nNote that the first check will be performed in 68 hours, 31 minutes, 19 seconds"
Failed to send notification via shoutrrr (url=smtp://info@smtp.example.org:0/?auth=Plain&fromaddress=info%40example.org&fromname=Watchtower&subject=Pi+Server+Container+Updates+Watchtower+updates+on+0d613d437c8c&toaddresses=user%40example.org):  failed to send using smtp: timed out`

Thank you!

**Comment by piksel** [comment, marked as answer]
You have a space between your port env key and value (`WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT= 587`), which get interpreted as port 0 (you can see the port in the generated URL: `...smtp://info@smtp.example.org:0/?auth...`)

**Reply by therealmaass** [reply]
Thank you! You're right. I fixed this but stumbled again to another error regarding gmail. I created a app password in my Google-Account and run into this error:

`docker logs watchtower -f
time="2021-06-12T07:58:00+02:00" level=info msg="Watchtower 1.3.0\nUsing notifications: smtp\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-06-13 13:55:00 +0200 CEST\nNote that the first check will be performed in 29 hours, 56 minutes, 59 seconds"
Failed to send notification via shoutrrr (url=smtp://example%40gmail.com@smtp.gmail.com:587/?auth=Plain&fromaddress=example%40gmail.com&fromname=Watchtower&subject=Pi+Server+Container+Updates+Watchtower+updates+on+c0a0f9362992&toaddresses=user%40gmail.com):  error authenticating: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials f8sm2719728ejw.75 - gsmtp`

My docker-compose file:

```
version: '2.1'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    dns: 1.1.1.1
    #    dns: 192.168.178.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_MONITOR_ONLY= true
      - WATCHTOWER_SCHEDULE= 0 55 13 ? * SUN
        #- WATCHTOWER_SCHEDULE= 0 0 16 ? * THU
      - WATCHTOWER_CLEANUP= true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=example@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=user@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=example@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSOWRD=ockbfttwplkveshr
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Pi Server Container Updates
      - WATCHTOWER_DEBUG= true
```
