### DISCUSSION TITLE
User mis match during docker pull images from private docker hub

### DISCUSSION THREAD

**Discussion by yuvrajalpha** [containrrr/watchtower#992] [General]
Hello All,

We saw the different user was trying to pull latest docker image from docker hub repo.

For example ,
	 We used below login credential for docker login on my system,

            sudo docker login -u abcd -p abcd123#
            
     and verify it using below command

         sudo docker system info | grep -E 'Username|Registry'
         
     Response to above command :
            Username: abcd
            Registry: https://index.docker.io/v1/

We expected that abcd user need to pull latest image from docker hub during Scheduled time ,But We found below message in watchtower debug logs
that xyz_name user trying to pull latest image from docker hub

-----------------******************----------------------
watchtower       | time="2021-06-10T13:08:48Z" level=debug msg="Loaded auth credentials {xyz_name xyz123$     } for repo/image_name"

-----------------******************----------------------

Can you please tell us from where that xyz_name user is in picture?

Even though abcd is user or owner on docker hub, we observed same behaviour.

**Comment by piksel** [comment]
You are mounting the docker config into watchtower right? That file holds the credentials and watchtower uses whatever user defined for the repo to authenticate. Perhaps you have more than one docker config?

**Reply by yuvrajalpha** [reply]
Yes , i am mounting docker config into watchtower.

Sorry to informed you that we are using Watchtower v0.3.11(containrrr/watchtower:0.3.11)and below is watchtower service  that we were modify for our use
```yaml
version: '3'
services:
  ota:
    image: containrrr/watchtower:0.3.11
    container_name: watchtower
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/user_dir/.docker/config.json:/config.json \
    
   command : --cleanup -i 600
    restart : unless-stopped
```
