### ISSUE TITLE
Docker containers with hash-only image cannot be updated

### ISSUE THREAD

**Issue by piksel** [containrrr/watchtower#1050]
Recently, containers without an image tag has been encountered by watchtower users:
 - #1019
 - #1026
 - #1037
 - https://github.com/containrrr/watchtower/issues/796#issuecomment-894812345

Since the containers' configurations does not contain the necessary information for updating, watchtower cannot check for updates or recreate them.
Since #1027 (available in `watchtower:latest-dev`) it should at least no longer crash, but just skip said containers.

One source of these containers seem to be `docker compose` (with no dash), but it's unclear whether they can be created in some other fashion (you could of course just manually specify the `sha256:xxx` hash in `docker run`, but then, what would you expect?)

To verify that containers does not have any named image, you can run `docker ps`:
```
$ docker ps
CONTAINER ID   IMAGE             COMMAND                  CREATED          STATUS          PORTS                                       NAMES
fb0c2a735c38   4cdc5dd7eaad      "/docker-entrypoint.…"   18 minutes ago   Up 20 seconds   80/tcp         
```

In the second column (`IMAGE`), instead of the image tag, it shows just a short image id hash.

I made a PoC attempting to retrieve the image tag based on the ID, and it **is** possible to do so under *some* conditions, but it's highly volatile.
If this is a permanent change in future Docker versions, it may render watchtower unusable... 😩

Add a comment if you know anything more about the source of these containers!

**Comment by piksel** [comment]
Thanks to @amarcu5 filing https://github.com/docker/compose-cli/issues/1983, this should be solved (merged in https://github.com/docker/compose-cli/pull/1997) in upcoming releases.

Until then, use the "vanilla" `docker-compose` command to enable watchtower support. 
**Note**: If you have enabled `Docker Compose V2` in Docker Desktop, use `docker-compose disable-v2` to disable it.

**Comment by Tiritibambix** [comment]
I'm sorry, I'm a real noob.

How can I solve this with my RPi4 ? What's the "vanilla" docker compose ?

I have the exact same stack running on an amd64 in portainer and it works great


```
version: "3"
services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Europe/Paris
            - WATCHTOWER_MONITOR_ONLY=true
            - WATCHTOWER_SCHEDULE=0 0 10 ? * SAT
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxx
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=xxx
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xxx
            - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=xxx
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=xxx
        restart: unless-stopped


```
