### ISSUE TITLE
Disable notifications per container

### ISSUE THREAD

**Issue by michael-robbins** [containrrr/watchtower#1069]
**Describe the solution you'd like**
To be able to set a label per container, and have watchtower not notify when that container is updated with a new image.

For example:
```
com.centurylinklabs.watchtower.enable="true"
com.centurylinklabs.watchtower.notify="false"
```

I have a few containers that I want to keep on the latest version and they update 'often enough' that it's annoying to get pings in slack daily.

Only other alternatives I can think about is running two watchtower instances and have scopes to notify on one and not the other.

**Comment by piksel** [comment]
With the changes in #1010 it would also be possible to filter the containers in the notification template.

**Comment by kevdogg** [comment]
@piksel 

Does you code alteration change notifications for email as well?  I'd like to eliminate the emails I receive that are blank or have no content.

**Comment by piksel** [comment]
Yeah, all notifications. I assume you are using `latest-dev`? In `latest` there should not be any empty emails afaik.

**Comment by kevdogg** [comment]
Dang -- you are right -- I am running latest-dev and not latest.  Is your PR now available in latest-dev?

**Comment by kevdogg** [comment]
@piksel 

Ok I changed from the development to latest branch, however I still getting empty notifications.  Perhaps its because I'm running two watchtower instances -- here is relevant section of my compose file:

```
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.scope=archzfsproxy"
    restart: always
    networks:
      - net
    command: --schedule "0 0 */4 * * *" --scope archzfsproxy
    secrets:
      - watchtower_notification_email_server_secret
    volumes:
       - /etc/ssl/self-signed-certs/archzfsproxy/client:/etc/ssl/docker:ro
    environment:
      - TZ
      - DOCKER_HOST="tcp://archzfsproxy:2376
      - DOCKER_CERT_PATH=/etc/ssl/docker
      #- WATCHTOWER_DEBUG=true
      # Possible values for notifications level are panic, fatal, error, warn, info, debug, and trace
      - WATCHTOWER_SCOPE=archzfsproxy
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - DOCKER_API_VERSION=1.40
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=/run/secrets/watchtower_notification_email_server_secret
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Server - ${HOSTNAME} -

  watchtower-ubuntumc:
    image: containrrr/watchtower:latest
    container_name: watchtower-ubuntumc
    labels:
      - "com.centurylinklabs.watchtower.scope=ubuntumc"
    restart: always
    networks:
      - watchtower-ubuntumc
    command: --schedule "0 0 */4 * * *" --scope ubuntumc
    secrets:
      - watchtower_notification_email_server_secret
    volumes:
       - /etc/ssl/self-signed-certs/ubuntumc/client:/etc/ssl/docker:ro
    environment:
      - TZ
      - DOCKER_HOST="tcp://ubuntumc:2376
      - DOCKER_CERT_PATH=/etc/ssl/docker
      #- WATCHTOWER_DEBUG=true
      # Possible values for notifications level are panic, fatal, error, warn, info, debug, and trace
      - WATCHTOWER_SCOPE=ubuntumc
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - DOCKER_API_VERSION=1.40
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=/run/secrets/watchtower_notification_email_server_secret
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Server - UbuntuMC -
```

The emails I'm getting for notifications look like this:
<img width="563" alt="Screen Shot 2021-09-19 at 1 51 04 PM" src="https://user-images.githubusercontent.com/5242583/133939322-0f417ba0-8dc9-4981-b805-99b55b95b5c7.png">
