### ISSUE TITLE
Not updating ghcr.io images

### ISSUE THREAD

**Issue by bruvv** [containrrr/watchtower#1072]
**Description**
When using ghcr.io images watchtower isn't finding any updates for it. For example
`image: ghcr.io/linuxserver/plex`
https://github.com/linuxserver/docker-plex
Will not be updated by watchtower.

**Steps to reproduce the issue:**
1. https://github.com/linuxserver/docker-plex use that docker-compose file
2. wait for a new latest update (at the time of write it is: https://github.com/linuxserver/docker-plex/pkgs/container/plex/7446206)
3. see watchtower not finding the new images

**Describe the results you received:**
Still running an older container

**Describe the results you expected:**
Updatte the older container

**Output of `docker-compose --version`:**

```
docker-compose version 1.28.5, build 324b023a
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        b455053
 Built:             Mon Jun 21 02:03:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       a3bc36f
  Built:            Mon Jun 21 02:05:07 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 20
  Running: 12
  Paused: 0
  Stopped: 8
 Images: 30
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc version: 31cc25f16f5eba4d0f53e35374532873744f4b31
 init version: ed96d00 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 4.4.180+
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.619GiB
 Name: Asdf
 ID: 27CN:SHVQ:5KBG:MNLU:HKWJ:RDVI:JVFV:V6LI:F74I:4HPP:SQAB:U6VR
 Docker Root Dir: /volume1/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Synology DSM7 with latest docker package.

**Comment by piksel** [comment]
Probably due to sticky https://github.com/containrrr/watchtower/issues/923

The watchtower logs should state that it was skipped due to missing config data (if you run it with `--debug` or `WATCHTOWER_DEBUG`)

**Comment by bruvv** [comment]
Running now with debug on, is there a way to force a check?
![afbeelding](https://user-images.githubusercontent.com/3063928/133229231-1ec4dce1-25e0-4efc-b51b-ba083d063ab5.png)

**Comment by bruvv** [comment]
Thanks for linking it, as everything updates just as it should i do not think that it is related to synology (it even updated docker with DSM7 to a v20).
Anyway I ran it with debug enabled and if finds all the containers (22) but misses the Plex one (number 23). I made sure it is running:
`a4225257c900   ghcr.io/linuxserver/plex                         "/init"                  7 weeks ago          Up 2 weeks`
Which it is, when searching in the log there is nothing mention `ghcr` nor `plex` like watchtower isn't finding the container. I even ran it with `WATCHTOWER_INCLUDE_STOPPED=true` to make sure it gets everything but even that doesn't help.
This is my docker-compose.yml:
```yaml
version: '3'
services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - TZ=Europe/Berlin
      - WATCHTOWER_DEBUG=true
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 30
```

**Comment by piksel** [comment]
Could you include the watchtower startup message ( the first `info` message after start ) and the summary after a session ( `debug` level, X scanned X updated etc )?
I presume you don't want to include the full log (which of course would be much better).
There is nothing in watchtower itself that singles out ghcr.io repos, so I don't see why only that one would be ignored...

**Comment by bruvv** [comment]
I do not mind posting everything it is just a very large log file. Here it is:
https://pastebin.com/PViKGicc

**Comment by bruvv** [comment]
I do not mind posting everything it is just a very large log file. Here it is:
https://pastebin.com/0VFFwU6G
And the docker inspect:
https://pastebin.com/EPdHZgHC (mind you this is with debug off, this is how I am normally running it)

I have 27 containers. And as far as I can see there is nothing in the logs that shows the containers is there. But I can tell you it is.
Here is the docker inspect of the plex container: https://pastebin.com/YRV7MZGj
Perhaps the docker-compose that I am running for plex is usefull:
```yaml
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    devices:
        - /dev/dri:/dev/dri
    #privileged: true
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
        - PUID=1026
        - PGID=100
        - VERSION=latest
        - PLEX_CLAIM=claim-*********
    volumes:
        - /volume1/docker/plex:/config:rw
        - /volume1/downloads/movies:/movies:rw
        - /volume1/downloads/series:/tv:rw    
    restart: unless-stopped
```
