### ISSUE TITLE
"com.centurylinklabs.watchtower.monitor-only=true" label is not working

### ISSUE THREAD

**Issue by methatronc** [containrrr/watchtower#1092]
Hello, 

I am using the latest stable image of watchtower ( from 2021-04-24 ) wich works very fine on updating the containers labeled :
`"com.centurylinklabs.watchtower.enable=true"`
However I do not receive notifications from updatable containers labeled as such :
`"com.centurylinklabs.watchtower.monitor-only=true"`

My watchtower env configuration is the following :
```     
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
```

It runs on debian buster, docker version 20.10.9, build `c2ea9bc`

Thanks for your help.

**Comment by markfrancisonly** [comment]
"com.centurylinklabs.watchtower.monitor-only=true" label function isn't working without the WATCHTOWER_LABEL_ENABLE=true environment variable in my setup either

**Comment by mptpro** [comment]
doesn't work for me either. I have a Conainter that is built from a local image, and thus can't be updated. The problem is I have Watchtower set to notify via Telegram and I'm getting multiple messages daily of the "failed" update.

**Comment by janusn** [comment]
The "com.centurylinklabs.watchtower.monitor-only=true" doesn't work on mine either.

- Watchtower version: v1.5.3
- Docker version 20.10.3, build 55f0773
- Host OS: DSM 7.1.1-42962 Update 5

The container.yaml is:
```
---
# github page: https://github.com/khakers/go-subgen
version: "3.8"
services:
  subgen:
    container_name: subgen
    # image: ghcr.io/khakers/go-subgen:master
    build:
      context: https://github.com/khakers/go-subgen.git
    restart: unless-stopped
    ports:
      - "8095:8095"
    volumes:
      # Path must be identical to the path in your other services
      - "/volume2/Shared:/volume2/Shared:rw"
      # Models will be downloaded to this directory
      - "./config/models:/models:rw"
    environment:
      - MODEL_TYPE=small_en
      - TARGET_LANG=en
      - IGNORE_IF_EXISTING=true
      - MAX_CONCURRENCY=1
      - MODEL_DIR="/models/"
      - LOG_LEVEL=info
      - PORT=8095
      - SUBTITLE_NAME_TEMPLAT="{{.FileName}}.subgen.{{.Lang}}.{{.FileType}}"
      - WHISPER_CONF_THREADS=2
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

It failed with the following message:
```
Could not do a head request for "subgen-subgen:latest", falling back to regular pull.
Reason: registry responded to head request with "401 Unauthorized", auth: "Bearer realm=\"[https://auth.docker.io/token\](https://auth.docker.io/token%5C)",service=\"[registry.docker.io](http://registry.docker.io/)\",scope=\"repository:library/subgen-subgen:pull\",error=\"insufficient_scope\""
Unable to update container "/subgen": Error response from daemon: pull access denied for subgen-subgen, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next.
```
