### ISSUE TITLE
No such container and name already in use

### ISSUE THREAD

**Issue by kevdogg** [containrrr/watchtower#1101]
I'm referencing this original issue: https://github.com/containrrr/watchtower/issues/235

I use watchtower to update my containers and periodically receive notification of No such container and name already in use.  An example of this error is show below for one of my containers however other containers also have this issue:

```
Error response from daemon: Cannot kill container: 328db49d7530b4e81fd35d2ad56ed8fe3f5994ce61e60fe089b867944f73fe67: Container 328db49d7530b4e81fd35d2ad56ed8fe3f5994ce61e60fe089b867944f73fe67 is not running
Error response from daemon: Conflict. The container name "/pg_admin" is already in use by container "328db49d7530b4e81fd35d2ad56ed8fe3f5994ce61e60fe089b867944f73fe67". You have to remove (or rename) that container to be able to reuse that name.
```

I'm using Arch Linux Host with Docker version 20.10.9, build c2ea9bc90b.

An example taken from my compose file for watchtower is shown below:

```
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.scope=archzfsproxy"
    restart: always
    networks:
      - net
    command: --schedule "0 0 */4 * * *" --scope archzfsproxy
    secrets:
      - watchtower_notification_email_server_secret
    volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
       - /etc/ssl/self-signed-certs/archzfsproxy.gohilton.com/client:/etc/ssl/docker:ro
    environment:
      - TZ
      - DOCKER_HOST="tcp://archzfsproxy.gohilton.com:2376
      - DOCKER_CERT_PATH=/etc/ssl/docker
      #- WATCHTOWER_DEBUG=true
      # Possible values for notifications level are panic, fatal, error, warn, info, debug, and trace
      - WATCHTOWER_SCOPE=archzfsproxy
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - DOCKER_API_VERSION=1.40
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=/run/secrets/watchtower_notification_email_server_secret
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Server - ${HOSTNAME} -
```

The containers I'm running are the following:

```
CONTAINER ID   IMAGE                          COMMAND                  CREATED        STATUS                PORTS                                                                          NAMES
428ec7820263   dpage/pgadmin4:snapshot        "/entrypoint.sh"         4 hours ago    Up 4 hours            443/tcp, 0.0.0.0:5050->80/tcp, :::5050->80/tcp                                 pg_admin
24364edbd733   bitnami/redis:latest           "/opt/bitnami/script…"   12 hours ago   Up 12 hours           6379/tcp                                                                       redis
4cbc501d5dbc   authelia/authelia:latest       "/app/entrypoint.sh …"   9 days ago     Up 9 days (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 9091/tcp                            authelia
294d68835da2   phpmyadmin/phpmyadmin:latest   "/docker-entrypoint.…"   10 days ago    Up 10 days            0.0.0.0:8081->80/tcp, :::8081->80/tcp                                          phpmyadmin
c68a221d7a3a   linuxserver/mariadb:latest     "/init"                  10 days ago    Up 10 days            3306/tcp                                                                       mariadb
d16083796412   osixia/phpldapadmin:latest     "/container/tool/run…"   11 days ago    Up 11 days            443/tcp, 0.0.0.0:6443->80/tcp, :::6443->80/tcp                                 phpldapadmin
7e285f1cac3b   containrrr/watchtower:latest   "/watchtower --sched…"   11 days ago    Up 11 days            8080/tcp                                                                       watchtower-ubuntumc
521035d4484d   containrrr/watchtower:latest   "/watchtower --sched…"   11 days ago    Up 11 days            8080/tcp                                                                       watchtower
ba11dd4f2c00   authelia_openldap              "/container/tool/run…"   11 days ago    Up 11 days            0.0.0.0:389->389/tcp, :::389->389/tcp, 0.0.0.0:636->636/tcp, :::636->636/tcp   openldap
```

An example of the error messages from the docker logs are the following:

```
time="2021-10-19T12:00:37-05:00" level=info msg="Found new bitnami/redis:latest image (655ad3c7a4f2)"
time="2021-10-19T12:00:39-05:00" level=info msg="Stopping /redis (d53edd5f9692) with SIGTERM"
time="2021-10-19T12:00:39-05:00" level=error msg="Error response from daemon: Cannot kill container: d53edd5f969210830c23eff92b74e56663165bdc0b8ddf37af2cdda1a6695bc3: Container d53edd5f969210830c23eff92b74e56663165bdc0b8ddf37af2cdda1a6695bc3 is not running"
time="2021-10-19T12:00:39-05:00" level=info msg="Creating /redis"
time="2021-10-19T12:00:39-05:00" level=error msg="Error response from daemon: Conflict. The container name \"/redis\" is already in use by container \"24364edbd733270bfc75b0b5129e99a80119276ee57f5bcad7d77d4aa5512bbe\". You have to remove (or rename) that container to be able to reuse that name."
time="2021-10-19T12:00:39-05:00" level=info msg="Removing image b24f5cfaef15"
time="2021-10-19T20:00:31-05:00" level=info msg="Found new dpage/pgadmin4:snapshot image (3cc328b63fa4)"
time="2021-10-19T20:00:33-05:00" level=info msg="Stopping /pg_admin (328db49d7530) with SIGTERM"
time="2021-10-19T20:00:36-05:00" level=error msg="Error response from daemon: Cannot kill container: 328db49d7530b4e81fd35d2ad56ed8fe3f5994ce61e60fe089b867944f73fe67: Container 328db49d7530b4e81fd35d2ad56ed8fe3f5994ce61e60fe089b867944f73fe67 is not running"
time="2021-10-19T20:00:36-05:00" level=info msg="Creating /pg_admin"
time="2021-10-19T20:00:36-05:00" level=error msg="Error response from daemon: Conflict. The container name \"/pg_admin\" is already in use by container \"328db49d7530b4e81fd35d2ad56ed8fe3f5994ce61e60fe089b867944f73fe67\". You have to remove (or rename) that container to be able to reuse that name."
time="2021-10-19T20:00:36-05:00" level=info msg="Removing image 269dbfbd09ee"
```
