### ISSUE TITLE
alibaba Cloud private warehouse cannot pull the image and automatically upgrade

### ISSUE THREAD

**Issue by j2ee-haydon** [containrrr/watchtower#1140]
my docker-compose.yml

```yaml
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    depends_on:
      - mj-admin-service
      - mj-admin-portal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: mj-admin-service --cleanup --interval 10
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
```
the log shows that it is always ready, and there is no more log output：
![image](https://user-images.githubusercontent.com/12794749/142966581-3095f521-3754-4491-8350-68331ec6636e.png)
