### ISSUE TITLE
private registry in gcloud

### ISSUE THREAD

**Issue by sdorosz** [containrrr/watchtower#119]
I need some advice on how I can setup watchtower to monitor changes in images in my private gcloud registry.

i don't know how to setup the authentification for pulling.

at the moment I log into the gcloudregistry every time i pull an image.

thank you for your advice

**Comment by nomukaiki** [comment]
This might help you: https://cloud.google.com/container-registry/docs/advanced-authentication

**Comment by Jacobh2** [comment]
Following the steps for JSON file, and updating my compose file to:
(Having the service account's JSON file one one line for the password)
```
  watchtower:
    image: v2tec/watchtower
    environment:
      - REPO_USER=_json_key
      - REPO_PASS={"type":"service_account", ..... 
```
yields a problem with watchtower when it is (what I presume) checking itself:
```
watchtower_1  | time="2018-07-26T09:11:04Z" level=info msg="Unable to update container /watchtower_watchtower_1, err='Error response from daemon: Get https://registry-1.docker.io/v2/v2tec/watchtower/manifests/latest: unauthorized: incorrect username or password'. Proceeding to next."
```
It is able to successfully check my private repo at gcloud and pull down and update my container, but not itself. 

Is it possible for watchtower to still use the default cred when checking itself? Or is the solution that I host a version of watchtower in my container repo also?

EDIT:
Seems like #55 is related to this?

**Comment by lokeshh** [comment]
@Jacobh2 Following your solution, I'm getting following error

```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 32, column 9
expected <block end>, but found ','
  in "./docker-compose.yml", line 32, column 45


```
Could you help?

**Comment by Jacobh2** [comment]
@lokeshh Could you post the content of your `docker-compose.yaml` file? Just make sure to remove the actual content of the `REPO_PASS` value 😉 

My first guess is that there is something wrong with the `REPO_PASS` env value. Make sure you have the json content on one line!

**Comment by lokeshh** [comment]
@Jacobh2 Following are the contents of my `docker-compose.yml`:

```
version: '3.2'
services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
    environment:
      - REPO_USER=_json_key
      - REPO_PASS={  "type": "service_account",  "project_id": "xxx",  "private_key_id": "xxx",  "private_key": "-----BEGIN PRIVATE KEY-----\nxxx==\n-----END PRIVATE KEY-----\n",  "client_email": "xxx",  "client_id": "xxx",  "auth_uri": "https://accounts.google.com/o/oauth2/auth",  "token_uri": "https://oauth2.googleapis.com/token",  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",  "client_x509_cert_url": "xxx"}
```

I get the following error when I run `docker-compose up`:

```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 10, column 9
expected <block end>, but found ','
  in "./docker-compose.yml", line 10, column 47
```
Line 10, column 9 is the letter `R` of `REPO_PASS` and column 47 is first comma (`,`).

**Comment by lokeshh** [comment]
@Jacobh2 I removed all the spaces and it worked. Many thanks :+1:

**Comment by leandrocruz** [comment]
Do you have to replace "_json_key" by some value or should it be used literally?

**Comment by lokeshh** [comment]
@leandrocruz It has to be used literally.

**Comment by leandrocruz** [comment]
Thanks @lokeshh . I wonder if this authentication method still works. I created a service account with all privileges, but watchtower still can't pull the images. I have pasted the complete content of the json key (no new lines and no spaces) into the REPO_PASS environment variable, but it didn't work.

**Comment by leandrocruz** [comment]
I have also tried to share the "config.json" , but no luck.

**Comment by Jacobh2** [comment]
@leandrocruz I have actually updated the way I use this to instead mount my `.docker/config.json` file directly!

My docker-compose file now looks something like this:
```yaml
version: '3'
services:
  watchtower:
    image: <image>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/client/.docker/config.json:/config.json
    command: --interval 10
    restart: always
```
where `/home/client/.docker/config.json` is the path to your user's config.json file. The `config.json` file was created by running
```
docker login -u _json_key --password-stdin https://eu.gcr.io < gcloudauth.json
```
where `gcloudauth.json` is the gcloud service-account's json file. More info [here](https://cloud.google.com/container-registry/docs/advanced-authentication)
