### ISSUE TITLE
New version of watchtower sends an empty notification via shoutrrr every session

### ISSUE THREAD

**Issue by Loskir** [containrrr/watchtower#1198]
**Describe the bug**
After updating to v1.4.0 my watchtower instance started sending empty notifications to my telegram channel (containing only the header and no messages) every minute (this is my update interval)

**To Reproduce**
My docker-compose file:
```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: telegram://132:abc@telegram?channels=-100123&parseMode=HTML
      WATCHTOWER_NOTIFICATION_TEMPLATE: "<b>Watchtower@hetzner</b>{{println}}{{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
```
Start the container and wait for a minute.

**Expected behavior**
I expect it won't send any messages if pull didn't happen. Or at least the message should contain the actual logged info.

**Screenshots**
<img width="368" alt="изображение" src="https://user-images.githubusercontent.com/21295738/150651041-9eeb2693-a05f-4579-9299-56ed81ff34a6.png">

**Environment**

linux, x86_64, docker 20.10.7

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
*** a lot of messages regarding parsing images***
time="2022-01-22T18:36:31Z" level=info msg="Session done" Failed=0 Scanned=15 Updated=0 notify=no
time="2022-01-22T18:36:31Z" level=debug msg="Scheduled next run: 2022-01-22 18:37:21 +0000 UTC"
```

</details>

**Additional context**
