### ISSUE TITLE
Unable to authenticate to home-network SMTP server

### ISSUE THREAD

**Issue by thibmart1** [containrrr/watchtower#1235]
Hello, I have some problem with the email notification configuration.
Here is my docker-compose file where every mail arguments are set :
```
  version: "3.1"
  services:
    watchtower:
      image: containrrr/watchtower:latest
      container_name: watchtower
      environment:
        - TZ=Europe/Paris
        - WATCHTOWER_SCHEDULE=0 */1 * * * *
        - WATCHTOWER_INCLUDE_STOPPED=true
        - WATCHTOWER_INCLUDE_RESTARTING=true
        - WATCHTOWER_MONITOR_ONLY=true
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=sender@mail.com
        - WATCHTOWER_NOTIFICATION_EMAIL_TO=receiver@mail.com
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=192.168.X.X
        #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=true
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=1025
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=user
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=password
        - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      command: --cleanup
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
```

And yet I continuesly have this error log message :
```
time="2022-02-22T19:41:21+01:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: unencrypted connection" index=0 notify=no service=smtp
```

I also tried with WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY set to "true" and I have other containers which can successfully send email to the same SMTP server.

The SMTP server runs on a Rpi inside my local home network. The containers run on another machine (see environment below) also inside my local home network.

Thank you guys for your help !

**Expected behavior**

Watchtower connecting to SMTP server.

**Environment**
* OpenMediaVault 5.6.25-1
* Linux 5.4.162-1-pve
* Docker 5:20.10.12
