### ISSUE TITLE
Use Watchtower with version labels

### ISSUE THREAD

**Issue by mklemme1** [containrrr/watchtower#1243]
**Describe the bug**
For some containers I would like to stay on a minor version for now.
I have therefore added a label to the `docker-compose.yml`:
```
services:
  nextcloud-db:
    image: mariadb:10.7
```
I would still like Watchtower to update this container within this version label.

But Watchtower then ignores this container:
```
Unable to update container "/nextcloud-db": Error: No such image: mariadb:10.7. Proceeding to next.
```

**Expected behavior**

Watchtower should know about labels and check also this container within the label provided

**Environment** 
 - Platform: Ubuntu 20.04.3 LTS
 - Architecture: Intel
 - Docker version: Docker version 20.10.8, build 3967b7d
 
<details>
 <summary><b> Logs from running watchtower </summary>

```
watchtower_1  | time="2022-03-07T08:45:00+01:00" level=debug msg="Checking containers for updated images"
...
watchtower_1  | time="2022-03-07T08:45:02+01:00" level=debug msg="Trying to load authentication credentials." container=/nextcloud-db image="mariadb:10.7"
watchtower_1  | time="2022-03-07T08:45:02+01:00" level=debug msg="No credentials for mariadb:10.7 found" config_file=/config.json
watchtower_1  | time="2022-03-07T08:45:02+01:00" level=debug msg="Got image name: mariadb:10.7"
watchtower_1  | time="2022-03-07T08:45:02+01:00" level=debug msg="Checking if pull is needed" container=/nextcloud-db image="mariadb:10.7"
watchtower_1  | time="2022-03-07T08:45:02+01:00" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.d\
ocker.io\"" status="401 Unauthorized"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Setting scope for auth token" image=mariadb scope="repository:library/mariadb:pull"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="No credentials found."
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Parsing image ref" host=index.docker.io image=mariadb normalized="docker.io/library/mariadb:10.7" tag=10.7
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/library/mariadb/manifests/10.7"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Found a remote digest to compare with" remote="sha256:6b27df78e91348af6ac28e120a9d3f2852bb4c17d427365a4dad01b\
206616271"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg=Comparing local="sha256:6b27df78e91348af6ac28e120a9d3f2852bb4c17d427365a4dad01b206616271" remote="sha256:6b27d\
f78e91348af6ac28e120a9d3f2852bb4c17d427365a4dad01b206616271"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="Found a match"
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=debug msg="No pull needed. Skipping image."
watchtower_1  | time="2022-03-07T08:45:03+01:00" level=info msg="Unable to update container \"/nextcloud-db\": Error: No such image: mariadb:10.7. Proceeding to next."
```

</details>

**Comment by piksel** [comment]
This seems weird... using a tag is definitely supported. 

It correctly parses the tag and finds the image:
```
Parsing image ref
    host=index.docker.io 
    image=mariadb 
    normalized="docker.io/library/mariadb:10.7" 
    tag=10.7
Comparing 
    local="sha256:6b27df78e91348af6ac28e120a9d3f2852bb4c17d427365a4dad01b206616271" 
    remote="sha256:6b27df78e91348af6ac28e120a9d3f2852bb4c17d427365a4dad01b206616271"
Found a match
No pull needed. Skipping image.
```
...and *then* it says that it's skipping the container with the error  `No such image: mariadb:10.7.`
Not sure what is going here.

**Comment by mklemme1** [comment]
Well, the issue reported has now disappeared.
A possible reason is that Watchtower does not find any container anymore. 
```
watchtower_1  | time="2022-03-16T04:45:00+01:00" level=debug msg="Checking containers for updated images"
watchtower_1  | time="2022-03-16T04:45:00+01:00" level=debug msg="Retrieving running containers"
watchtower_1  | time="2022-03-16T04:45:00+01:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
```
The only change was that I added `WATCHTOWER_TRACE`

```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: watchtower@XXXX.de
      WATCHTOWER_NOTIFICATION_EMAIL_TO: XXX@xxx.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: server.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: watchtower@XXXX.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: XXXX
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_LEVEL: debug
      WATCHTOWER_WARN_ON_HEAD_FAILURE: auto  # never
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: "Watchtower on server1"
      WATCHTOWER_LABEL_ENABLE: 1
      WATCHTOWER_TRACE: 1
    command:  --schedule "0 45 */4 * * *" --cleanup --debug
    #--include-stopped -label-enable -stop-timeout 30s
```
