### ISSUE TITLE
Watchtower fails to update containers with `network_mode: "container:[container name]"`

### ISSUE THREAD

**Issue by Draxter** [containrrr/watchtower#1269]
**Describe the bug**
Watchtower errors with `Container_ID is not connected to the network my_network` when trying to update containers with the `container:container_name` network_mode. Even despite being on the same, additional `my_network` host network. In my scenario I have a `gluetun` container that provides networking via a VPN, and a `sabnzbd` container that connects to the `gluetun` container. See scenario below.

**To Reproduce**
Create the following scenario in a `docker-compose.yml` file:

```
  watchtower:
    image: containrrr/watchtower:1.4.0
    container_name: watchtower
    command: --cleanup --schedule "0 50 3 * * *"
    networks:
      my_network:
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "container:gluetun"
    networks:
      my_network:
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:v3.28
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080
    environment:
      - VPN_SERVICE_PROVIDER=vyprvpn
      - OPENVPN_USER=someuser
      - OPENVPN_PASSWORD=somepass
      - VPN_TYPE=openvpn
      - TZ=Europe/London
    networks:
      my_network:
    restart: unless-stopped

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
```

**Expected behavior**
I would expect Watchtower to update all containers with the `latest` tag, no matter what network configuration they have

**Environment**
 - x86_64
 - Docker version: 20.10.12
 - Watchtower version: 1.4.0

**Watchtower Logs**
```
time="2022-04-09T03:50:21Z" level=info msg="Found new linuxserver/sabnzbd:latest image (f40da21248a2)"
time="2022-04-09T03:50:31Z" level=info msg="Stopping /sabnzbd (a86717bea54c) with SIGTERM"
time="2022-04-09T03:50:36Z" level=info msg="Creating /sabnzbd"
time="2022-04-09T03:50:36Z" level=error msg="Error response from daemon: container ffb9f7ce1aba8f5011b7ae74db592bcec855d005f4065487b8693d4f6745090f is not connected to the network my_network"
time="2022-04-09T03:50:36Z" level=info msg="Removing image 05a0ffcaa701"
```

**Docker API Logs**
```
10.10.0.20:54702 [09/Apr/2022:03:50:36.601] dockerfrontend dockerbackend/dockersocket 0/0/0/15/15 204 178 - - ---- 1/1/0/0/0 0/0 "DELETE /v1.25/containers/a86717bea54cda2ea59ddf7a1718f1298e0c5956abf3041f24eb9e51f40d641b?force=1 HTTP/1.1"
10.10.0.20:54702 [09/Apr/2022:03:50:36.616] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 404 327 - - ---- 1/1/0/0/0 0/0 "GET /v1.25/containers/a86717bea54cda2ea59ddf7a1718f1298e0c5956abf3041f24eb9e51f40d641b/json HTTP/1.1"
10.10.0.20:54702 [09/Apr/2022:03:50:36.617] dockerfrontend dockerbackend/dockersocket 0/0/0/52/52 201 315 - - ---- 1/1/0/0/0 0/0 "POST /v1.25/containers/create?name=%2Fsabnzbd HTTP/1.1"
10.10.0.20:54702 [09/Apr/2022:03:50:36.669] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 500 393 - - ---- 1/1/0/0/0 0/0 "POST /v1.25/networks/my_network/disconnect HTTP/1.1"
10.10.0.20:54702 [09/Apr/2022:03:50:36.670] dockerfrontend dockerbackend/dockersocket 0/0/0/339/339 200 1106 - - ---- 1/1/0/0/0 0/0 "DELETE /v1.25/images/sha256:05a0ffcaa7014d641453b7a63b116dff2111289db1a0b5729c19eb8d9301517e?force=1&noprune=1 HTTP/1.1"
```
