### ISSUE TITLE
Support for proxy server

### ISSUE THREAD

**Issue by eingemaischt** [containrrr/watchtower#1283]
In our infrastructure, we need to use a proxy server to connect to "the internet". While docker pull works without a problem (http_proxy and https_proxy are set, furthermore 
```
[Service]
Environment="HTTP_PROXY=http://proxy:3128"
Environment="HTTPS_PROXY=http://proxy:3128"
```
in the dockers systemd-definition, watchtowr seems to ignore this setting:
`level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp 54.84.243.136:443: i/o timeout" container=/tmp_watchtower_1 image="containrrr/watchtower:latest"`

Is it possible to make watchtowr obey the enviromentally set proxy?

**Comment by eingemaischt** [comment]
Oh, I had a look at the code - there was a GetProxyFromEnvironment-Call (or so).

I added the HTTP_PROXY and HTTPS_PROXY to the docker compose file:
```
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=my@adress
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=other@address
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mailserver
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=watchtower
      - HTTP_PROXY=http://proxy:3128
      - HTTPS_PROXY=http://proxy:3128
      - http_proxy=http://proxy:3128
      - https_proxy=http://proxy:3128
      - WATCHTOWER_SCHEDULE=13 45 4 * * *
```

and it worked - you may add it in the docs ;-)
