### ISSUE TITLE
Schedule broken on latest dev build

### ISSUE THREAD

**Issue by ksurl** [containrrr/watchtower#1362]
**Describe the bug**

Running latest dev at time of this bug report, 2022-08-24. Setting the schedule no longer works and defaults to 24hr from container startup.

**To Reproduce**

start via docker compose:

```yaml
services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest-dev
    container_name: watchtower
    network_mode: bridge
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=$url
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_NOTIFICATION_SKIP_TITLE=true
      - TZ=$TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
```
**Expected behavior**

watchtower checks and updates containers at 4am daily

**Environment**:
 - Platform: debian
 - Architecture: x86_64
 - Docker version: 20.10.17 

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2022-08-24T16:45:44-07:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2022-08-24T16:45:45-07:00" level=debug msg="Making sure everything is sane before starting"
time="2022-08-24T16:45:45-07:00" level=debug msg="Retrieving running, stopped and exited containers"
time="2022-08-24T16:45:45-07:00" level=debug msg="Retrieving running, stopped and exited containers"
time="2022-08-24T16:45:45-07:00" level=debug msg="There are no additional watchtower containers"
time="2022-08-24T16:45:45-07:00" level=debug msg="Watchtower HTTP API skipped."
time="2022-08-24T16:45:45-07:00" level=info msg="Watchtower v1.4.0-30-g6b2ef10"
time="2022-08-24T16:45:45-07:00" level=info msg="Using notifications: discord"
time="2022-08-24T16:45:45-07:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2022-08-24T16:45:45-07:00" level=info msg="Scheduling first run: 2022-08-25 16:45:45 -0700 PDT"
time="2022-08-24T16:45:45-07:00" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
```

</details>

**Additional context**
I updated the container manually in the past week. The previous dev version I updated from that worked was probably from july but I don't have the exact build.
