### ISSUE TITLE
Exempt container from auto-update not working

### ISSUE THREAD

**Issue by qazero** [containrrr/watchtower#1372]
**Describe the bug**
Watchtower is successfully updating all my docker containers, but I am trying to exempt only 1 container (named "znc") from being updated. I tried applying the following label in my docker-compose for the znc container as seen in the snippet below:

```
services:
  znc:
    labels:
      - com.centurylinklabs.watchtower.enable="false"
```

I then recreated the containers but the znc container is still auto updating.

I then added the environment line to watchtower in my docker-compose as per the snippet below:

```
services:
  znc:
    labels:
      - com.centurylinklabs.watchtower.enable="false"
  watchtower:
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
```

I re-created the containers again and this time none of my containers updated. What am I doing wrong?

**Expected behavior**
I would like to have all containers auto update except my znc container. Instead of manually setting which containers to update, I would like to only set which container not to update.

**Environment**
  - Operating System: Ubuntu 22.04.1 LTS
  - Kernel: Linux 5.15.0-46-generic
  - Architecture: x86-64
 - Docker version 20.10.17, build 100c701

<details>
 <summary><b> Logs from running watchtower</b></summary>

```
time="2022-08-16T14:02:09-05:00" level=info msg="Watchtower 1.4.0"
time="2022-08-16T14:02:09-05:00" level=info msg="Using no notifications"
time="2022-08-16T14:02:09-05:00" level=info msg="Only checking containers using enable label"
time="2022-08-16T14:02:09-05:00" level=info msg="Scheduling first run: 2022-08-17 04:00:00 -0500 CDT"
time="2022-08-16T14:02:09-05:00" level=info msg="Note that the first check will be performed in 13 hours, 57 minutes, 50 seconds"
time="2022-08-17T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-18T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-19T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-20T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-21T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-22T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-23T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-24T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-25T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-26T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-27T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-28T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-29T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-30T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-08-31T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-09-01T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-09-02T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
```

</details>

**Comment by piksel** [comment]
Well, using that environment variable you set watchtower to "explicit opt in", so it will only update containers with the label `enable=true`:

> level=info msg="Only checking containers using enable label"

It seems like it should work using your initial attempt though.

**Comment by qazero** [comment]
Yes, it "should" but for some reason it doesn't. Any idea why or do you have it working on your end?

**Comment by qazero** [comment]
Any update on this one @piksel ? Was hoping to have it triaged to be fixed for the next update if possible.

**Comment by piksel** [comment]
Could you show the logs with the correct configuration? It's not something I can reproduce, so I don't know of any fix we can do.

**Comment by qazero** [comment]
I provided logs in my initial post, is something missing? What would you like me to change in my configuration to test and provide new logs for?

**Comment by piksel** [comment]
> time="2022-08-16T14:02:09-05:00" level=info msg="Only checking containers using enable label"

This is the log where you only update containers with `com.centurylinklabs.watchtower.enable="true"`, from running with `WATCHTOWER_LABEL_ENABLE: "true"`.
That one "correctly" does not update any containers, so it's not helpful in diagnosing your issue.

**Comment by qazero** [comment]
I just tried again but still can't get it to work. This time I tried to explicitly define which containers to update and which ones not to update. Please see the snippet from my docker-compose.yml below:

```
services:
  znc:
    labels:
      - com.centurylinklabs.watchtower.enable="false"
  watchtower:
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  swag:
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  jackett:
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  guacamole:
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  glances:
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  portainer:
    labels:
      - com.centurylinklabs.watchtower.enable="true"
```

In the example above, I am trying to auto update all containers except the `znc` container. However, none of the containers are updating. Please see the logs below:

```
time="2022-09-15T12:49:13-05:00" level=info msg="Watchtower 1.4.0"
time="2022-09-15T12:49:13-05:00" level=info msg="Using no notifications"
time="2022-09-15T12:49:13-05:00" level=info msg="Only checking containers using enable label"
time="2022-09-15T12:49:13-05:00" level=info msg="Scheduling first run: 2022-09-16 04:00:00 -0500 CDT"
time="2022-09-15T12:49:13-05:00" level=info msg="Note that the first check will be performed in 15 hours, 10 minutes, 46 seconds"
time="2022-09-16T04:00:00-05:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
```

What am I doing wrong?
