### ISSUE TITLE
Allow sensitive environment variables to be the path to a file that contains the value

### ISSUE THREAD

**Issue by aentwist** [containrrr/watchtower#1390]
In Docker, environment variables are not truly secure as they exist in images and are not masked. The only truly secure method to incorporate secrets is by mounting files containing them through to containers. Docker Swarm, and now Compose, implement this with [`secrets`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#secrets).

Some applications allow configuration to be specified as the path to a file containing a value instead of the value directly for this kind of reason. I would like this to be possible with Watchtower, particularly regarding SMTP credentials.

This would be implemented with a new set of configuration environment variables to avoid dual-purposing existing ones, breaking changes, etc. New environment variables would have the same names as their direct-valued counterparts, besides the addition of a meaningful suffix, likely _FILE or _PATH.

For example,

```yaml
services:
  watchtower:
    secrets:
      - smtp_password
    environment:
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD_FILE: /run/secrets/smtp_password

secrets:
  smtp_password:
    file: .secrets/smtp-password.txt
```

SMTP host, port, username, and password are a good minimum for this idea, although it should not be hard to extend it generically and allow this for all configuration environment variables.

**Comment by piksel** [comment]
This is already supported, but without any `_FILE` suffix.

**Comment by aentwist** [comment]
*For SMTP password only, it seems. Would extending it be considered at all? At leasttt to SMTP username.

**Comment by aentwist** [comment]
If it was to be made generic, here is a concise implementation example

https://github.com/dani-garcia/vaultwarden/commit/9824d94a1cc039d1e0ac62301abf0b6fbb148709

**Comment by aentwist** [comment]
Looking at the source code, making this generic seems fairly straightforward. So, the question becomes whether it is desirable.

Currently, file checks are performed on a select few hardcoded variables https://github.com/containrrr/watchtower/blob/main/internal/flags/flags.go#L461.

If instead of this pattern a similar pattern to the one in Vaultwarden was used, then the idea could be made generic. All [`viper` calls](https://github.com/containrrr/watchtower/blob/main/internal/flags/flags.go#L27) could be wrapped with a function f(string) -> string that resolves the variable from env var value or from the file at env var value.

As for the naming, dual-purposing the existing environment variables (not choosing to add a suffix) is probably okay, but it can only lead to complications. The process behind choosing to use the value directly or instead as a path to a file with the value would have to be rock solid for arbitrary env var values.

**Comment by piksel** [comment]
If you use `WATCHTOWER_NOTIFICATION_URL`, you can keep your entire notification configuration as a secret. For SMTP it would be something like: `smtp://username:password@host/?from=watchtower@example.com&to=recipient1@example.com`.
See [shoutrrr/email](https://containrrr.dev/shoutrrr/v0.5/services/email/) for more information.

Note that this is not supported yet in v1.4.0 (the current `latest` on docker), but we should be able to release a new version soon.

**Comment by include** [comment]
I am using the secrets method in a swarm cluster but loading from memory and not file (1) and I get the error bellow (2). Am I doing something wrong? Thanks in advance.

(1)

```yaml
version: "3.9"

secrets:
  mygpwd:
    external: true

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      # ...
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "/run/secrets/mygpwd"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - mygpwd
    deploy:
      mode: global
```

(2)

```txt
watchtower_watchtower.0.mq61gh6u9144@ubuntu01    | time="2022-09-28T21:22:00+01:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: 534 5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor bh27-20020a05600c3d1b00b003b476bb2624sm2572199wmb.6 - gsmtp" index=0 notify=no service=smtp```
