### ISSUE TITLE
Faulty description in log

### ISSUE THREAD

**Issue by DockerComposeFiles** [containrrr/watchtower#1396]
By typing a correct URL in
WATCHTOWER_NOTIFICATION_GOTIFY_URL="https://my.url"
I get always the error
`time="2022-09-27T20:21:59Z" level=fatal msg="Gotify URL must start with \"http://\" or \"https://\""`

My compose:
```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: wt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED
      - WATCHTOWER_REVIVE_STOPPED # start stopped containers after update
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_RESTARTING=true

      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL="https://gotify.my.url.de"
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN="myToken"
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
     command: --interval 21600
```

I believe the syntax \"http://\" should be "http://"

The Solution was to remove the ""
WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://gotifys.my.url.de
WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=myToken

future when I write an false url I expect an "invalid url" or "connection failed" failure, but get:

time="2022-09-27T20:31:06Z" level=error msg="Failed to send shoutrrr notification" error="invalid gotify token \"mytoken\"" index=0 notify=no service=gotify

By deploy with shell script I get also
`ERRO[0001] Failed to send shoutrrr notification          error="invalid gotify token \"myToken\"" index=0 notify=no service=gotify`

**Comment by piksel** [comment]
The syntax for docker compose files is **either**:
```yaml
services:
  watchtower:
    environment:
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "myToken"
```
or
```yaml
services:
  watchtower:
    environment:
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=myToken
```
Don't mix them. It's either a list of `key=value` or a map of `key: "value"`
