### ISSUE TITLE
Watchtower updates even though a monitor is set

### ISSUE THREAD

**Issue by Roei639** [containrrr/watchtower#1414]
### Describe the bug

I set in the container under labels: 
- com.centurylinklabs.watchtower.monitor-only="true"
but Watchtower continues to update.

### Steps to reproduce

1.Definition under container: - com.centurylinklabs.watchtower.monitor-only="true"

### Expected behavior

Just a notification and not an update to the container

### Environment

- Docker Version

### Your logs

```text
There is no log
```

**Comment by piksel** [comment]
Wrong YAML syntax.

Use either 
```yaml
labels:
- com.centurylinklabs.watchtower.monitor-only=true
```
or
```yaml
labels:
  com.centurylinklabs.watchtower.monitor-only: "true"
```

See https://docs.docker.com/compose/compose-file/compose-file-v3/#labels-2

**Comment by Roei639** [comment]
I set it up as you mentioned, it does not update nor does it send a notification

container home assistant:
```
labels:
 - com.centurylinklabs.watchtower.monitor-only=true
```

container Watchtower:
```
  watchtower:
      container_name: watchtower
      image: containrrr/watchtower:latest
      restart: always
      network_mode: bridge
      environment:
        - WATCHTOWER_DEBUG=TRUE
        - WATCHTOWER_CLEANUP=TRUE
        - WATCHTOWER_TRACE=FALSE
        - WATCHTOWER_SCHEDULE=0 0 5 * * *
        - WATCHTOWER_NOTIFICATIONS_LEVEL=info
        - WATCHTOWER_NOTIFICATION_REPORT=true
        - WATCHTOWER_NOTIFICATIONS=shoutrrr
        - WATCHTOWER_NOTIFICATION_URL=telegram:/xxxx
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
```
