### ISSUE TITLE
[Feature Request] Only use custom credentials for certain labels

### ISSUE THREAD

**Issue by LostOnTheLine** [containrrr/watchtower#1502]
### Is your feature request related to a problem? Please describe.

When running watchtower I have the option of using custom credentials
```
REPO_USER=username
REPO_PASS=password
```

But I, like I assume most users, don't pull all my images from my private repo, most are pulled from Docker Hub.

As it stands if I set custom Repo credentials all the Docker ones give an error
If I don't set it all the private ones do

So as of how I have to set up 2 Towers, & set them each with a label to monitor on on one & off on the other. But then you can't have some that actually get ignored.

### Describe the solution you'd like

It would be nice to have a `com.centurylinklabs.watchtower.custom` or `com.centurylinklabs.watchtower.credentials` label to make it so that those labeled will use the custom credentials while those not labeled will not.
Either that or let us use user-defined labels so I could have something like `watchtower.credentials.johnny` for ones that update using the custom credentials argument or `watchtower.credentials.docker` to act as though no custom arguments are set.

I'm sure this is less of an issue if using the Docker `config.json` but running under Docker Desktop that isn't an option.

Ideally it'd be nice to be able to specify credentials for multiple custom repos, though not something I personally would use I'm sure there are those who would.

Perhaps
```yaml
version: "3"
services:
  portainer_agent:
    image: portainer/agent:latest
    network_mode: "host"
    ports:
      - 9001:9001
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.michelangelo=true"

  mosquitto:
    image: eclipse-mosquitto
    container_name: buzzbuzz
    ports:
      - 1883:1883
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.salvador=true"

  registry: # Custom Docker Repo Container
    container_name: putstuffhere
    image: registry:latest
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.steve=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=43200
      - CUSTOM_REPOS=michelangelo, salvador, picasso, steve
      - REPO_michelangelo_USER=Madonna
      - REPO_michelangelo_PASS=OfBurge$$
      - REPO_salvador_USER=Persistence
      - REPO_salvador_PASS=NoClocks!
      - REPO_picasso_USER=Pablo
      - REPO_picasso_PASS=WeepingW0man
      - REPO_steve_USER=steve
      - REPO_steve_PASS=ilikefootball
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
```

I'm not exactly sure how it would need to be for watchtower to use the arguments, I just gave an example to something I know I could make work in python.

### Describe alternatives you've considered

The only alternative is having 2 watchtowers & using 1 with `WATCHTOWER_LABEL_ENABLE` set to `true` & the other with `WATCHTOWER_LABEL_ENABLE` set to `false` & I'm not even sure that would work properly, plus it leaves no way to have ones ignored completely
