### ISSUE TITLE
Prometheus metrics - server misbehaving

### ISSUE THREAD

**Issue by Corfucinas** [containrrr/watchtower#1511]
### Describe the bug

Trying to add the metrics feature as described on the documentation fails on prometheus with `lookup watchtower on 127.0.0.11:53: server misbehaving`

docker-compose
```yml
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    command:
      - --cleanup=true
      - --include-restarting=true
      - --include-stopped=true
      - --rolling-restart=true
      - --http-api-metrics=true
      - --notification-report=true
    environment:
      WATCHTOWER_NOTIFICATION_URL: discord://${DISCORD_TOKEN}@${DISCORD_CHANNEL}
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_API_TOKEN}
    expose:
      - 8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      org.label-schema.group: monitoring
```

prometheus
```yml
  - job_name: watchtower
    metrics_path: /v1/metrics
    bearer_token: __secret__  # it's the same as in WATCHTOWER_HTTP_API_TOKEN
    static_configs:
      - targets:
          - watchtower:8080
```

### Steps to reproduce

[Follow this section of the documentation](https://containrrr.dev/watchtower/metrics/)

### Expected behavior

Prometheus is able to scrape succesfully the metrics

### Screenshots

![image](https://user-images.githubusercontent.com/53630064/208737351-0bfc08c1-238b-407a-baab-102a2aa5382d.png)

### Environment

- Platform: Ubuntu 22.10 
- Kernel: 5.19.0
- Architecture: x86
- Docker Version: 20.10.22, build 3a2c30b

### Your logs

```text
time="2022-12-20T18:19:15Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2022-12-20T18:19:16Z" level=debug msg="Making sure everything is sane before starting"
time="2022-12-20T18:19:16Z" level=debug msg="Retrieving running, stopped, restarting and exited containers"
time="2022-12-20T18:19:17Z" level=debug msg="Retrieving running, stopped, restarting and exited containers"
time="2022-12-20T18:19:18Z" level=debug msg="There are no additional watchtower containers"
time="2022-12-20T18:19:18Z" level=info msg="Watchtower 1.5.1"
time="2022-12-20T18:19:18Z" level=info msg="Using notifications: discord"
time="2022-12-20T18:19:18Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2022-12-20T18:19:18Z" level=info msg="Scheduling first run: 2022-12-21 18:19:18 +0000 UTC"
time="2022-12-20T18:19:18Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
```

**Comment by piksel** [comment]
That error message is regarding the DNS not responding to the domain name `watchtower`. Are you running watchtower and Prometheus in the same docker compose? How is your container networking set up?

**Comment by Corfucinas** [comment]
> That error message is regarding the DNS not responding to the domain name `watchtower`. Are you running watchtower and Prometheus in the same docker compose? How is your container networking set up?

Yup, while reorganizing `services` in the docker-compose I accidentally left out the `networks` entry for `watchtower`. Working now.

For reference,

docker-compose
```yml
watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    command:
      - --cleanup=true
      - --include-restarting=true
      - --include-stopped=true
      - --rolling-restart=true
      - --http-api-metrics=true
      - --notification-report=true
    environment:
      WATCHTOWER_NOTIFICATION_URL: discord://${DISCORD_TOKEN}@${DISCORD_CHANNEL}
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_API_TOKEN}
    networks: # Forgot to add this one
      - backend
    expose:
      - 8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      org.label-schema.group: monitoring
```
