### ISSUE TITLE
deployment: SCHEDULE from docker-compose will be ignored

### ISSUE THREAD

**Issue by leisefuxX** [containrrr/watchtower#1585]
### Describe the bug

Hello everyone,

when I deploy watchtower using a docker-compose.yml, the environment variable "WATCHTOWER_SCHEDULE" causes an error (see below) and the container does not start. However, if I start the same container via docker run, watchtower accepts the schedule. 
If I give the same docker-compose.yml to portainer business, the container does not start with the same error. However, if I omit the WATCHTOWER_SCHEDULE environment variable, I can add it back later in the running container and redeploy it. Here the variable is then accepted. 
The funny thing (for me): the docker-compose.yml has been in use for a year and has never been changed. With it, watchtower has already been deployed on several instances. Since the day before yesterday, it no longer works.

I also had to observe the day before yesterday that watchtwower once created itself a network, in the address range 192.168.0.0/24 and thus attached itself to the bridge, which led to a non-accessibility of the Docker instance, but could only sleepily fix the process and not document it. Shame on me. 

here is the error message if you give watchtower the environment variable "WATCHTOWER_SCHEDULE= "0 0 4 * * *" in docker-compose.yml in docker-compose and in portainer business 

`time="2023-03-10T07:35:13Z" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"
`

### Steps to reproduce

run docker-compose.yml with docker-compose or portainer stack

### Expected behavior

schedule will be accepted, container runs

### Environment

- Docker version 20.10.15, build fd82621
- docker-compose version 1.29.2
- Linux 5.15.0-67-generic #74-Ubuntu x86_64
- Ubuntu 22.04.2 LTS ("jammy")
- Portainer Business Edition 2.17.1
- containrrr/watchtower@sha256:f847e1adb570c2cc11d1e613cad97baf3cdfe83ddd3c1a29ada848cfbd4f7f3f

### Your logs

```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - TZ='Europe/Berlin'
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_RESTARTING=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE
      - WATCHTOWER_SCHEDULE= "0 0 4 * * *"
      - WATCHTOWER_TIMEOUT="30s"
```

### Additional context

thx in advance
