### ISSUE TITLE
Docker Compose support

### ISSUE THREAD

**Issue by 7imbrook** [containrrr/watchtower#16]
I don't know if you can do this or now, but I'd like to be able to specify the docker compose defined container name to watch, then have it do a rolling update on that. I could do this is regex matching or something, but I don't believe that's implemented. We can discuss this more more if you're interested.

**Comment by shyd** [comment]
Hi,
I successfully integrated watchtower into docker compose by specifying containers in  the `command` section like this:

```yml
watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: watchtower nginx nginx-gen pma --interval 30
    restart: unless-stopped
```

Like this only the containers `watchtower`, `nginx`, `nginx-gen` and `pma`will be automatically updated.

Cheers

**Comment by olivierHa** [comment]
@shyd  docker-compose is creating container with a "custom" name (based on the current repository for example)
What @7imbrook wanted to do, is a way to "support" this custom name with watchtower, like putting a regexp instead of a container name for example.

**Comment by nderjung** [comment]
I had success with watchtower observing containers defined within a `docker-compose.yml` context by enabling the `--label-enable` flag. Here's an example:

```yaml
services:
  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower:0.2.1
    command: --cleanup --label-enable
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/watchtower/config.json:/config.json:ro
  
  watchme:
    container_name: 'watchme'
    image: registry.example.com/watchme:latest
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

where `./etc/watchtower/config.json` is a copy of the `~/.docker/config.json` authentication configuration created after logging in to a registry with `docker login registry.example.com`.
