### ISSUE TITLE
WatchTower upadate image used by x container

### ISSUE THREAD

**Issue by rFond** [containrrr/watchtower#1637]
### Is your feature request related to a problem? Please describe.

Hello,

I have 1 image docker used with 2 container (for my exemple).

My docker compose :

```yaml
  mcdLeds:
    image: clauger3e.azurecr.io/mcd/leds:dev-latest
    container_name: mcdleds
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/sys/class/leds/user-led1-green/brightness:/sys/class/leds/user-led1-green/brightness"
      - "/sys/class/leds/user-led2-green/brightness:/sys/class/leds/user-led2-green/brightness"
      - "/sys/class/leds/user-led1-red/brightness:/sys/class/leds/user-led1-red/brightness"
      - "/sys/class/leds/user-led2-red/brightness:/sys/class/leds/user-led2-red/brightness"
    env_file: ./MyClaugerDetect_Leds/.env
    networks:
      vpcbr_leds:

  mcdLeds2:
    image: clauger3e.azurecr.io/mcd/leds:dev-latest
    container_name: mcdleds2
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/sys/class/leds/user-led1-green/brightness:/sys/class/leds/user-led1-green/brightness"
      - "/sys/class/leds/user-led2-green/brightness:/sys/class/leds/user-led2-green/brightness"
      - "/sys/class/leds/user-led1-red/brightness:/sys/class/leds/user-led1-red/brightness"
      - "/sys/class/leds/user-led2-red/brightness:/sys/class/leds/user-led2-red/brightness"
    env_file: ./MyClaugerDetect_Leds/.env
    networks:
      vpcbr_leds2:
```

Watchtower update only one.
```
time="2023-04-26T09:22:59+02:00" level=info msg="Found new clauger3e.azurecr.io/mcd/leds:dev-latest image (1b1b444cf68a)"
time="2023-04-26T09:31:01+02:00" level=info msg="Stopping /mcdleds (8dbec57bf10a) with SIGTERM"
time="2023-04-26T09:31:12+02:00" level=info msg="Creating /mcdleds"
time="2023-04-26T09:31:13+02:00" level=info msg="Removing image b2a6457d44cb"
```

### Describe the solution you'd like

I would like if possible, (with option in conf).
WatchTower check all container, stop, restart 2 or more same processus.

### Describe alternatives you've considered

Use another image ?

**Comment by piksel** [comment]
Hmm, that should be the normal behaviour of watchtower... Not sure how it misses the second one. How are you running watchtower, and what does the report say after a session (the number of checked/updated/skipped containers)?

**Comment by rFond** [comment]
I m in last version 1.5.3, Watchtower is dockerised.


This is configuration of my WatchTower :

```yaml
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:1.5.3
    restart: always
    environment:
      TZ: "Europe/Paris"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 86400
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_REVIVE_STOPPED: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      WATCHTOWER_REVIVE_STOPPED: "true"
      WATCHTOWER_SCHEDULE : "0 * * * * *"
      #WATCHTOWER_RUN_ONCE: "true"
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_TOKEN: "xxxxxxxxxxx"
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: "true"
    volumes:
      - /root/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      vpcbr_external:
        ipv4_address: 172.18.0.7
      vpcbr_watchtower:
```

all message :

```
time="2023-04-26T09:22:04+02:00" level=info msg="Updates triggered by HTTP API request."
time="2023-04-26T09:22:59+02:00" level=info msg="Found new clauger3e.azurecr.io/mcd/leds:dev-latest image (1b1b444cf68a)"
time="2023-04-26T09:31:01+02:00" level=info msg="Stopping /mcdleds (8dbec57bf10a) with SIGTERM"
time="2023-04-26T09:31:12+02:00" level=info msg="Creating /mcdleds"
time="2023-04-26T09:31:13+02:00" level=info msg="Removing image b2a6457d44cb"
time="2023-04-26T09:31:13+02:00" level=error msg="Error response from daemon: conflict: unable to delete b2a6457d44cb (cannot be forced) - image is being used by running container 0d7ca5478a47"
time="2023-04-26T09:31:13+02:00" level=info msg="Session done" Failed=0 Scanned=19 Updated=1 notify=no
```

**Comment by simonaronsson** [comment]
> ```
> time="2023-04-26T09:31:13+02:00" level=error msg="Error response from daemon: conflict: unable to delete b2a6457d44cb (cannot be forced) - image is being used by running container 0d7ca5478a47"
> ```

This seems like it could be an issue. It should probably recreate both before trying to remove the image. This could very well be the source of the issues you are experiencing.

**Comment by rFond** [comment]
I think the watchtower should do:
- Step 1 : Check repos and image différence
- Step 2 : Download new image
- Step 3 : Check all docker container with image used
- Step 4 : Stop and remove all containers
- Step 5 : Restart all containers with a new image
- Step 6 : Delete old image

**Comment by piksel** [comment]
Well, it seems like it just ignores the second container for some reason, and then when it tries to remove the old image for container 1 it can't since it's still in use by container 2. 

Watchtower is actually doing it the way you describe above (although it checks every container's image for updates, not checking all images and then containers). 

You could try running with:
 ```yaml
  watchtower:
    command: "mcleds2?"
    environment:
      WATCHTOWER_DEBUG: "true"
```
It should show why it's skipping it...
