### ISSUE TITLE
Auth issues with an up-to-date private GitLab instance

### ISSUE THREAD

**Issue by mgcrea** [containrrr/watchtower#1654]
### Describe the bug

I have trouble making watchtower work against a private GitLab instance using a personal access token. Encountering auth errors. Manual `docker compose pull` do work fine.

### Steps to reproduce

1. Generate a personal access token on the GitLab instance with the `read_registry` scope.
2. Use `docker login` to generate the `.docker/config.json`
3. Trigger an update via an API call and check the logs 
4. See errors

### Expected behavior

No auth errors

### Environment

- Platform `Ubuntu 22.04.2 LTS`
- Architecture `x64`
- Docker Version `Docker version 23.0.6, build ef23cbc`

### Your logs

```text
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Trying to load authentication credentials." container=/bar-frontend-1 image="registry.foo.io/bar/bar-frontend:master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Loaded auth credentials for user baz, on registry registry.foo.io/bar/bar-frontend:master, from file /config.json"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Got image name: registry.foo.io/bar/bar-frontend:master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Credentials loaded"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Checking if pull is needed" container=/bar-frontend-1 image="registry.foo.io/bar/bar-frontend:master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Building challenge URL" URL="https://registry.foo.io/v2/"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://gitlab.foo.io/jwt/auth\",service=\"container_registry\"" status="401 Unauthorized"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Checking challenge header content" realm="https://gitlab.foo.io/jwt/auth" service=container_registry
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Setting scope for auth token" image=registry.foo.io/bar/bar-frontend scope="repository:registry.foo.io/bar/bar-frontend:pull"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Credentials found."
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Parsing image ref" host=registry.foo.io image=bar/bar-frontend normalized="registry.foo.io/bar/bar-frontend:master" tag=master
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://registry.foo.io/v2/bar/bar-frontend/manifests/master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Could not do a head request for \"registry.foo.io/bar/bar-frontend:master\", falling back to regular pull." container=/bar-frontend-1 image="registry.foo.io/bar/bar-frontend:master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://gitlab.foo.io/jwt/auth\\\",service=\\\"container_registry\\\",scope=\\\"repository:bar/bar-frontend:pull\\\"\"" container=/bar-frontend-1 image="registry.foo.io/bar/bar-frontend:master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Pulling image" container=/bar-frontend-1 image="registry.foo.io/bar/bar-frontend:master"
watchtower  | time="2023-05-15T11:53:29+02:00" level=debug msg="Error pulling image registry.foo.io/bar/bar-frontend:master, Error response from daemon: Head \"https://registry.foo.io/v2/bar/bar-frontend/manifests/master\": unauthorized: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.foo.io/help/user/profile/account/two_factor_authentication#troubleshooting"
watchtower  | time="2023-05-15T11:53:29+02:00" level=info msg="Unable to update container \"/bar-frontend-1\": Error response from daemon: Head \"https://registry.foo.io/v2/bar/bar-frontend/manifests/master\": unauthorized: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.foo.io/help/user/profile/account/two_factor_authentication#troubleshooting. Proceeding to next."
```

### Additional context

- docker-compose.yml:

```yaml
version: '3'

services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    expose:
      - '8080'
    volumes:
      - /root/.docker/config.json:/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: --debug --http-api-update
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      TZ: ${TZ:-Europe/Paris}
    env_file: .env
    networks:
      - nginx

networks:
  nginx:
    name: nginx-proxy_default
```
