### ISSUE TITLE
Scoped setup Scanned=0

### ISSUE THREAD

**Issue by davidrot** [containrrr/watchtower#1665]
### Describe the bug

I have some containers from my private repository and some from the docker hub.
I noticed when I have both mixed, some of the containers are not found. Therefore, I thought let's make two instances of watchtower, one for private and one for public containers. This pushed me that I have to use scopes.

After running with scopes, no container is found anymore... if I remove the scopes it is working.

### Steps to reproduce

```
services:
  watchtower-private:
    image: containrrr/watchtower:latest
    container_name: watchtower-private
    restart: always
    environment: 
      - "REPO_USER=xx"
      - "REPO_PASS=xx"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_POLL_INTERVAL=30"
      - "WATCHTOWER_WARN_ON_HEAD_FAILURE=never"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: xa xb xc xd --scope privat


  watchtower-public:
    image: containrrr/watchtower:latest
    container_name: watchtower-public
    restart: always
    environment:
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_POLL_INTERVAL=30"
      - "WATCHTOWER_WARN_ON_HEAD_FAILURE=never"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ya yb yc --scope public
```

### Expected behavior

```
watchtower-public     | time="2023-05-31T09:48:36Z" level=info msg="Session done" Failed=0 Scanned=2 Updated=0 notify=no
watchtower-private    | time="2023-05-31T09:36:36Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
```

### Environment

- Platform: ubuntu
- Architecture: x86
- Docker Version: Docker version 20.10.12, build e91ed57

### Your logs

```text
watchtower-public     | time="2023-05-31T09:48:36Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
watchtower-public     | time="2023-05-31T09:49:06Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
watchtower-public     | time="2023-05-31T09:49:36Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
watchtower-private    | time="2023-05-31T09:36:36Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
watchtower-private    | time="2023-05-31T09:37:06Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
watchtower-private    | time="2023-05-31T09:37:36Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
```
```


### Additional context

_No response_
