### ISSUE TITLE
No credentials found for public repo.

### ISSUE THREAD

**Issue by lordraiden** [containrrr/watchtower#1676]
### Describe the bug

I get the errors below for all the containers I have

```
time="2023-06-19T01:00:10+02:00" level=debug msg="No credentials for tecnativa found" config_file=/config.json
time="2023-06-19T01:00:10+02:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
```

With all the containers I get the same error but these are public containers, so no credentials are required. my config.json file is empty.

```
###############################################################
# Watchtower 
###############################################################

version: '3.8'

# Services ####################################################

services:

  watchtower:
    image: containrrr/watchtower
    container_name: Watchtower
    restart: unless-stopped
    networks:
      br1:
        ipv4_address: 10.10.40.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/Docker/Watchtower:/config
    environment:
      - TZ
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_LIFECYCLE_HOOKS=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_SCHEDULE=0 0 1 * * *
    secrets:
      - WATCHTOWER_NOTIFICATION_URL
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# Networks ####################################################

networks:
  br1:
    driver: macvlan
    external: true

# Secrets ##############################################

secrets:
  # WATCHTOWER_NOTIFICATION_URL
  WATCHTOWER_NOTIFICATION_URL:
    file: $DOCKERDIR/WATCHTOWER_NOTIFICATION_URL
```

### Steps to reproduce

Just let the program run

### Expected behavior

don't require credentials

### Environment

- Platform
- Architecture
- Docker Version

### Your logs

```text
time="2023-06-19T01:00:10+02:00" level=debug msg="Trying to load authentication credentials." container=/ProxyDMZ-SocketProxy image="tecnativa/docker-socket-proxy:latest"
time="2023-06-19T01:00:10+02:00" level=debug msg="No credentials for tecnativa found" config_file=/config.json
time="2023-06-19T01:00:10+02:00" level=debug msg="Got image name: tecnativa/docker-socket-proxy:latest"
time="2023-06-19T01:00:10+02:00" level=debug msg="Checking if pull is needed" container=/ProxyDMZ-SocketProxy image="tecnativa/docker-socket-proxy:latest"
time="2023-06-19T01:00:10+02:00" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2023-06-19T01:00:10+02:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2023-06-19T01:00:10+02:00" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2023-06-19T01:00:10+02:00" level=debug msg="Setting scope for auth token" image=tecnativa/docker-socket-proxy scope="repository:tecnativa/docker-socket-proxy:pull"
time="2023-06-19T01:00:10+02:00" level=debug msg="No credentials found."
time="2023-06-19T01:00:10+02:00" level=debug msg="Parsing image ref" host=index.docker.io image=tecnativa/docker-socket-proxy normalized="docker.io/tecnativa/docker-socket-proxy:latest" tag=latest
time="2023-06-19T01:00:10+02:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/tecnativa/docker-socket-proxy/manifests/latest"
```
