### ISSUE TITLE
Support GCP Artifact Registry

### ISSUE THREAD

**Issue by K4pper** [containrrr/watchtower#1681]
### Is your feature request related to a problem? Please describe.

Currently you cannot authenticate against the google artifact registry with the config.json file in watchtower.
The reason for watchtower failing authentication is because of the expected strings in the www-authenticate header. Currently watchtower expects both a **realm** and a **service** string but the artifact registry does not send any **service** string when sending a HTTP GET request.
example below:
![image](https://github.com/containrrr/watchtower/assets/76392392/f276dfb0-7620-4111-b865-380c5ce2c84f)
![image](https://github.com/containrrr/watchtower/assets/76392392/e5ebbc40-61fd-4cd1-b8c1-39dd311a6b0f)

This is not an issue when creating a config.json and authenticating against the artifact registry manually.

### Describe the solution you'd like

Watchtower should be able to authenticate against the google artifact registry using the config.json file by not expecting a **service** string.

### Describe alternatives you've considered

An alternative would be to build a container that have gcloud installed, this however would be a very bloated container compared to making the config.json file work

**Comment by piksel** [comment]
Are you sure this doesn't work? The code you are thinking of is only used for HEAD requests (which I don't even know if GCP support?). It should just fall back to doing a pull as normal if it cannot perform a HEAD request. And, when pulling it's not watchtower that does the authentication, it's the docker daemon itself.

**Comment by K4pper** [comment]
@piksel 
When i look into the watchtower logs it gives me the following:
![image](https://github.com/containrrr/watchtower/assets/76392392/a2649f6b-ff4d-40be-89fc-c974945eadd9)

So it seems that it does try a normal pull but that fails and says authentication failed.
i have tried creating an ubuntu container with docker in docker (DIND) and tried using the exact same config.json file within that container and it works, so it is only when using watchtower it seems to have an authentication error.

Hope this gives more insight into the problem (:

**Comment by Kerwood** [comment]
Can confirm, Watchtower does not work on Google Artifact Registry.
Is it possible to force Watchtower use the Docker daemon to do the pull instead of injecting credentials into Watchtower?

**Comment by piksel** [comment]
Like I said, it's **always** the docker daemon that does the pull and authentication. The error even contains `Error response from daemon: `. 
That being said, something is clearly different. How are you authenticating against the repo?

**Comment by K4pper** [comment]
We authenticate with the repo by following the steps in the watchtower docs: https://containrrr.dev/watchtower/private-registries/

Where it says to authenticate with GCloud you would base64 encode the value of your service account key and insert that into a config.json, then mount that into the container.

However when we do this watchtower errors out. When i try to authenticate manually it pulls the image just fine.

**Comment by piksel** [comment]
Hm, it says that you should base64 encode it as `_json_key:<JSON>`, where `<JSON>` is the full contents of a key file in JSON format. Is this what you are doing?

This is the GCP docs for reference:
https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key

**Comment by K4pper** [comment]
Yes the whole thing is base64 encoded as described in the docs

**Comment by piksel** [comment]
What do you mean by:

> This is not an issue when creating a config.json and authenticating against the artifact registry manually.

Are you saying that using the same config.json as you mount in the container can be used to authenticate with the `docker` cli, without using any credentials helpers?

**Comment by K4pper** [comment]
Yes exactly, when i use the same config.json to authenticate with the docker CLI it works as expected

**Comment by simonaronsson** [comment]
> Yes exactly, when i use the same config.json to authenticate with the docker CLI it works as expected

Can you please post a redacted version of your `config.json`? This doesn't add up for me.

**Comment by K4pper** [comment]
@simskij Yeah sure i have posted it below:
```
{
    "auths": {
        "europe-west3-docker.pkg.dev": {
            "auth": "BASE64-encoded-value"
        }
    }
}
```

**Comment by Kerwood** [comment]
> @simskij Yeah sure i have posted it below:
> 
> ```
> {
>     "auths": {
>         "europe-west3-docker.pkg.dev": {
>             "auth": "BASE64-encoded-value"
>         }
>     }
> }
> ```

And the `BASE64-encoded-value` is generated with below command ?
```sh
bash echo -n "_json_key:$(cat gcloudauth.json)" | base64 -w0
```

**Comment by K4pper** [comment]
@Kerwood
Yes I used that exact command

**Comment by simonaronsson** [comment]
> > @simskij Yeah sure i have posted it below:
> > ```
> > {
> >     "auths": {
> >         "europe-west3-docker.pkg.dev": {
> >             "auth": "BASE64-encoded-value"
> >         }
> >     }
> > }
> > ```
> 
> And the `BASE64-encoded-value` is generated with below command ?
> 
> ```shell
> bash echo -n "_json_key:$(cat gcloudauth.json)" | base64 -w0
> ```

And in your container config, have you prefixed your container image names with the registry they will be fetched from (and does it match `europe-west3-docker.pkg.dev`)?

**Comment by victormacedo996** [comment]
I know this issue is one year old, however I am struggling to authenticate with artifact registry. I have the following `docker-compose` file:

```yaml

services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    image: us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1
    container_name: "Go-backend"
    environment:
      - DB_URL=postgres
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_DATABASE=postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  watchtower:
    image: containrrr/watchtower:latest-dev
    command: --interval 10

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./watchtower/config.json:/config.json
```

I have already generated the `config.json` file like @simskij described and guarantee that the service account I am using has all the privileges it need to pull images from artifact registry.

These are the debug logs watchtower gives me:

```
watchtower-1  | time="2024-12-27T20:28:27Z" level=debug msg="Scheduled next run: 2024-12-27 20:28:31 +0000 UTC"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Checking containers for updated images"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Retrieving running containers"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Trying to load authentication credentials." container=/Go-backend image="us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Loaded auth credentials for user _json_key, on registry us-east1-docker.pkg.dev, from file /config.json"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Got image name: us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Credentials loaded"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Checking if pull is needed" container=/Go-backend image="us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Built challenge URL" URL="https://us-east1-docker.pkg.dev/v2/"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://us-east1-docker.pkg.dev/v2/token\"" status="401 Unauthorized"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Checking challenge header content" realm="https://us-east1-docker.pkg.dev/v2/token" service=
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Could not do a head request for \"us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1\", falling back to regular pull." container=/Go-backend image="us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Reason: challenge header did not include all values needed to construct an auth url" container=/Go-backend image="us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1"
watchtower-1  | time="2024-12-27T20:28:31Z" level=debug msg="Pulling image" container=/Go-backend image="us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1"
watchtower-1  | time="2024-12-27T20:28:33Z" level=debug msg="Error pulling image us-east1-docker.pkg.dev/PROJ_ID/victormacedosite-back/victormacedo-back:v0.0.1, Error response from daemon: Head \"https://us-east1-docker.pkg.dev/v2/PROJ_ID/victormacedosite-back/victormacedo-back/manifests/v0.0.1\": unauthorized: authentication failed"
watchtower-1  | time="2024-12-27T20:28:33Z" level=info msg="Unable to update container \"/Go-backend\": Error response from daemon: Head \"https://us-east1-docker.pkg.dev/v2/PROJ_ID/victormacedosite-back/victormacedo-back/manifests/v0.0.1\": unauthorized: authentication failed. Proceeding to next."
``` 

I know it seems that watchtower cannot authenticate to artifact registry, however I can't find out why.

**Comment by Kerwood** [comment]
I don't believe this issues was ever resolved.
As far as I know, the conclusion is that Google Artifact Registry is not supported.

**Comment by dp-dandy** [comment]
I'm running into the same issue

> Like I said, it's **always** the docker daemon that does the pull and authentication. The error even contains `Error response from daemon: `. That being said, something is clearly different. How are you authenticating against the repo?

@piksel does this mean that if 
```shell
docker pull us-docker.pkg.dev/<my_app>
```
Succeeds pulling from my artifact registry and then I have a `docker-compose.yml` file of
```yaml
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=15
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - ~/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: us-docker.pkg.dev/<my_app>
```

The expectation would be that watchtower should not have any issues authenticating/pulling said image hosted in my private artifact registry?
