### ISSUE TITLE
Watchtower messes up the linking

### ISSUE THREAD

**Issue by davidsarkany** [containrrr/watchtower#171]
Hello!
I'm currently running two sites based on LEMP using the following docker-compose config:
```
version: "3"
services:
  nginx:
    container_name: sts_domain_com-NGINX
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "64122:80" 
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./log:/var/log/www
      - ./www:/var/www/html
    networks:
      - www
  
  php:
    container_name: sts_domain_com-PHPFPM
    image: davidsarkany/php:7-fpm-alpine3.7
    restart: unless-stopped
    volumes:
      - ./config/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./log:/var/log/www
      - ./www:/var/www/html
    networks:
      - www

networks:
  www:
    external:
      name: www
```

```
version: "3"
services:
  nginx:
    container_name: kornyezetbarat_domain_com-NGINX
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "127.0.0.1:64121:80" 
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./log:/var/log/www
      - ./www:/var/www/html
    networks:
      - www
  
  php:
    container_name: kornyezetbarat_domain_com-PHPFPM
    image: davidsarkany/php:7-fpm-alpine3.7
    restart: unless-stopped
    volumes:
      - ./config/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./log:/var/log/www
      - ./www:/var/www/html
    networks:
      - www

networks:
  www:
    external:
      name: www
```

One of them is kornyezetbarat_domain_com and the other is sts_domain_com
The watchtower updates the PHP containers but when doings so, it seemingly mixes them.
Basically sts_domain_com-NGINX starts using the kornyezetbarat_domain_com-PHPFPM container, while kornyezetbarat _domain_com-NGINX uses the sts_domain_com-PHPFPM container.
Once this happens, I have to manually run 'docker-compose down' and 'docker-compose up -d' which fixes the issue.
Watchtower debug output:

```
time="2018-02-27T06:05:34Z" level=debug msg="Scheduled next run: 2018-02-27 06:05:54 +0000 UTC" 
time="2018-02-27T06:05:54Z" level=debug msg="Checking containers for updated images" 
time="2018-02-27T06:05:54Z" level=debug msg="Retrieving running containers" 
time="2018-02-27T06:05:54Z" level=debug msg="Pulling v2tec/watchtower:latest for /watchtower" 
time="2018-02-27T06:05:54Z" level=debug msg="No credentials for v2tec in /config.json" 
time="2018-02-27T06:05:54Z" level=debug msg="No authentication credentials found for v2tec/watchtower:latest" 
time="2018-02-27T06:05:55Z" level=debug msg="No new images found for /watchtower" 
time="2018-02-27T06:05:55Z" level=debug msg="Pulling nginx:stable for /kornyezetbarat_domain_com-NGINX" 
time="2018-02-27T06:05:55Z" level=debug msg="No credentials for nginx in /config.json" 
time="2018-02-27T06:05:55Z" level=debug msg="No authentication credentials found for nginx:stable" 
time="2018-02-27T06:05:58Z" level=debug msg="No new images found for /kornyezetbarat_domain_com-NGINX" 
time="2018-02-27T06:05:58Z" level=debug msg="Pulling davidsarkany/php:7-fpm-alpine3.7 for /kornyezetbarat_domain_com-PHPFPM" 
time="2018-02-27T06:05:58Z" level=debug msg="No credentials for davidsarkany in /config.json" 
time="2018-02-27T06:05:58Z" level=debug msg="No authentication credentials found for davidsarkany/php:7-fpm-alpine3.7" 
time="2018-02-27T06:06:02Z" level=info msg="Found new davidsarkany/php:7-fpm-alpine3.7 image (sha256:5b0d49496a2bc4771e49aec8cdc15184802cad56625bf7f85a4e86970998ec89)" 
time="2018-02-27T06:06:02Z" level=debug msg="Pulling nginx:stable for /sts_domain_com-NGINX" 
time="2018-02-27T06:06:02Z" level=debug msg="No credentials for nginx in /config.json" 
time="2018-02-27T06:06:02Z" level=debug msg="No authentication credentials found for nginx:stable" 
time="2018-02-27T06:06:04Z" level=debug msg="No new images found for /sts_domain_com-NGINX" 
time="2018-02-27T06:06:04Z" level=debug msg="Pulling davidsarkany/php:7-fpm-alpine3.7 for /sts_domain_com-PHPFPM" 
time="2018-02-27T06:06:04Z" level=debug msg="No credentials for davidsarkany in /config.json" 
time="2018-02-27T06:06:04Z" level=debug msg="No authentication credentials found for davidsarkany/php:7-fpm-alpine3.7" 
time="2018-02-27T06:06:05Z" level=info msg="Found new davidsarkany/php:7-fpm-alpine3.7 image (sha256:5b0d49496a2bc4771e49aec8cdc15184802cad56625bf7f85a4e86970998ec89)" 
time="2018-02-27T06:06:05Z" level=debug msg="Pulling buonzz/php-production-cli:latest for /modest_franklin" 
time="2018-02-27T06:06:05Z" level=debug msg="No credentials for buonzz in /config.json" 
time="2018-02-27T06:06:05Z" level=debug msg="No authentication credentials found for buonzz/php-production-cli:latest" 
time="2018-02-27T06:06:06Z" level=debug msg="No new images found for /modest_franklin" 
time="2018-02-27T06:06:06Z" level=debug msg="Pulling mariadb:latest for /mariadb" 
time="2018-02-27T06:06:06Z" level=debug msg="No credentials for mariadb in /config.json" 
time="2018-02-27T06:06:06Z" level=debug msg="No authentication credentials found for mariadb:latest" 
time="2018-02-27T06:06:08Z" level=debug msg="No new images found for /mariadb" 
time="2018-02-27T06:06:08Z" level=info msg="Stopping /sts_domain_com-PHPFPM (f31298edc9c1907e68cdab3c5eaaa7e9ee2867dfe9bd5efd2f236bd22a74ab5f) with SIGTERM" 
time="2018-02-27T06:06:09Z" level=debug msg="Removing container f31298edc9c1907e68cdab3c5eaaa7e9ee2867dfe9bd5efd2f236bd22a74ab5f" 
time="2018-02-27T06:06:09Z" level=info msg="Stopping /kornyezetbarat_domain_com-PHPFPM (2379b61098c19c1bfb4a2822c1e3c1a97559c6095b6fdf7c204de93f2e8bb908) with SIGTERM" 
time="2018-02-27T06:06:10Z" level=debug msg="Removing container 2379b61098c19c1bfb4a2822c1e3c1a97559c6095b6fdf7c204de93f2e8bb908" 
time="2018-02-27T06:06:10Z" level=info msg="Creating /kornyezetbarat_domain_com-PHPFPM" 
time="2018-02-27T06:06:10Z" level=debug msg="Starting container /kornyezetbarat_domain_com-PHPFPM (4c91ace98b99989a8d7ab1fd2003565444bc3fb5934f4aaebdb3740ff107d81c)" 
time="2018-02-27T06:06:11Z" level=info msg="Creating /sts_domain_com-PHPFPM" 
time="2018-02-27T06:06:11Z" level=debug msg="Starting container /sts_domain_com-PHPFPM (a86269d9bd2a86043aef283252624efa44f73ebefbbee0c7a48699a18cbd9fce)" 
```
