### ISSUE TITLE
Metrics not being updated

### ISSUE THREAD

**Issue by modem7** [containrrr/watchtower#1710]
### Describe the bug

Metrics don't seem to update.

Except:

```go
# HELP watchtower_containers_failed Number of containers where update failed during the last scan
# TYPE watchtower_containers_failed gauge
watchtower_containers_failed 0
# HELP watchtower_containers_scanned Number of containers scanned for changes by watchtower during the last scan
# TYPE watchtower_containers_scanned gauge
watchtower_containers_scanned 0
# HELP watchtower_containers_updated Number of containers updated by watchtower during the last scan
# TYPE watchtower_containers_updated gauge
watchtower_containers_updated 0
# HELP watchtower_scans_skipped Number of skipped scans since watchtower started
# TYPE watchtower_scans_skipped counter
watchtower_scans_skipped 0
# HELP watchtower_scans_total Number of scans since the watchtower started
# TYPE watchtower_scans_total counter
watchtower_scans_total 0
```

### Steps to reproduce

Compose:

```yaml
  # WatchTower - Automatic Docker Container Updates and cleanup
  watchtower:
    image: containrrr/watchtower
    container_name: Watchtower
    hostname: Watchtower
    networks:
      isonet:
    ports:
      - 26525:8080
    labels:
      - autoheal=true
      ## Homepage
      - homepage.group=System
      - homepage.name=Watchtower
      - homepage.icon=https://containrrr.dev/watchtower/images/favicon.ico
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://$SERVER_IP:26525
      - homepage.widget.key=$WATCHTOWER_API_TOKEN
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      TZ: $TZ
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: false
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_NO_STARTUP_MESSAGE: true
      WATCHTOWER_WARN_ON_HEAD_FAILURE: never
      WATCHTOWER_TIMEOUT: 30s
      WATCHTOWER_SCHEDULE: "0 0 6 * * *" # Everyday at 06:00
      WATCHTOWER_HTTP_API_TOKEN: $WATCHTOWER_API_TOKEN
      WATCHTOWER_HTTP_API_METRICS: true
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "telegram://$TGRAM_BOT_TOKEN@telegram?channels=$TGRAM_CHAT_ID"
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    mem_limit: 250m
    mem_reservation: 60m
```

### Expected behavior

For metrics to show scanned/updated/failed

### Environment

- Platform: Ubuntu
- Architecture: x64
- Docker Version: 24.0.5

### Your logs

```text
Logs:


time="2023-07-27T06:02:31+01:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2023-07-27T06:02:31+01:00" level=info msg="Scheduling first run: 2023-07-28 06:00:00 +0100 BST" notify=no
time="2023-07-27T06:02:31+01:00" level=info msg="Note that the first check will be performed in 23 hours, 57 minutes, 28 seconds" notify=no
time="2023-07-28T06:00:04+01:00" level=info msg="Found new amir20/dozzle:latest image (6226fe8d36e4)"
time="2023-07-28T06:00:52+01:00" level=info msg="Stopping /Dozzle (79141a8b6feb) with SIGTERM"
time="2023-07-28T06:00:53+01:00" level=info msg="Creating /Dozzle"
time="2023-07-28T06:00:54+01:00" level=info msg="Removing image 97d2337cb22b"
time="2023-07-28T06:00:54+01:00" level=info msg="Session done" Failed=0 Scanned=50 Updated=1 notify=no
time="2023-07-28T06:00:54+01:00" level=fatal msg="Notification template error" error="template: :1:7: executing \"\" at <.Report>: can't evaluate field Report in type []*logrus.Entry" notify=no
time="2023-07-28T06:00:56+01:00" level=info msg="Watchtower 1.5.3" notify=no
time="2023-07-28T06:00:56+01:00" level=info msg="Using notifications: telegram" notify=no
time="2023-07-28T06:00:56+01:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2023-07-28T06:00:56+01:00" level=info msg="Scheduling first run: 2023-07-29 06:00:00 +0100 BST" notify=no
time="2023-07-28T06:00:56+01:00" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 3 seconds" notify=no
time="2023-07-28T12:13:46+01:00" level=info msg="Waiting for running update to be finished..."
time="2023-07-28T12:20:46+01:00" level=info msg="Watchtower 1.5.3" notify=no
time="2023-07-28T12:20:46+01:00" level=info msg="Using notifications: telegram" notify=no
time="2023-07-28T12:20:46+01:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2023-07-28T12:20:46+01:00" level=info msg="Scheduling first run: 2023-07-29 06:00:00 +0100 BST" notify=no
time="2023-07-28T12:20:46+01:00" level=info msg="Note that the first check will be performed in 17 hours, 39 minutes, 13 seconds" notify=no
time="2023-07-29T06:00:37+01:00" level=info msg="Found new linuxserver/plex-meta-manager:latest image (b883fdb42ada)"
time="2023-07-29T06:00:50+01:00" level=info msg="Found new linuxserver/sonarr:latest image (146be78b446b)"
time="2023-07-29T06:01:06+01:00" level=info msg="Stopping /Sonarr (49032b6c55e7) with SIGTERM"
time="2023-07-29T06:01:11+01:00" level=info msg="Stopping /PMM (ac34a765d8e3) with SIGTERM"
time="2023-07-29T06:01:17+01:00" level=info msg="Creating /PMM"
time="2023-07-29T06:01:17+01:00" level=info msg="Creating /Sonarr"
time="2023-07-29T06:01:18+01:00" level=info msg="Removing image 6c4c5b9245be"
time="2023-07-29T06:01:18+01:00" level=info msg="Removing image 1bfa5956bc5c"
time="2023-07-29T06:01:19+01:00" level=info msg="Session done" Failed=0 Scanned=51 Updated=2 notify=no
time="2023-07-29T06:01:19+01:00" level=fatal msg="Notification template error" error="template: :1:7: executing \"\" at <.Report>: can't evaluate field Report in type []*logrus.Entry" notify=no
time="2023-07-29T06:01:21+01:00" level=info msg="Watchtower 1.5.3" notify=no
time="2023-07-29T06:01:21+01:00" level=info msg="Using notifications: telegram" notify=no
time="2023-07-29T06:01:21+01:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2023-07-29T06:01:21+01:00" level=info msg="Scheduling first run: 2023-07-30 06:00:00 +0100 BST" notify=no
time="2023-07-29T06:01:21+01:00" level=info msg="Note that the first check will be performed in 23 hours, 58 minutes, 38 seconds" notify=no
time="2023-07-30T06:00:41+01:00" level=info msg="Found new linuxserver/xbackbone:latest image (79331f005c72)"
time="2023-07-30T06:00:57+01:00" level=info msg="Stopping /XBackbone (af8db7b76143) with SIGTERM"
time="2023-07-30T06:01:03+01:00" level=info msg="Creating /XBackbone"
time="2023-07-30T06:01:04+01:00" level=info msg="Removing image 4c16ccd4c3fe"
time="2023-07-30T06:01:04+01:00" level=info msg="Session done" Failed=0 Scanned=50 Updated=1 notify=no
time="2023-07-30T06:01:04+01:00" level=fatal msg="Notification template error" error="template: :1:7: executing \"\" at <.Report>: can't evaluate field Report in type []*logrus.Entry" notify=no
time="2023-07-30T06:01:07+01:00" level=info msg="Watchtower 1.5.3" notify=no
time="2023-07-30T06:01:07+01:00" level=info msg="Using notifications: telegram" notify=no
time="2023-07-30T06:01:07+01:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2023-07-30T06:01:07+01:00" level=info msg="Scheduling first run: 2023-07-31 06:00:00 +0100 BST" notify=no
time="2023-07-30T06:01:07+01:00" level=info msg="Note that the first check will be performed in 23 hours, 58 minutes, 52 seconds" notify=no
time="2023-07-31T06:00:40+01:00" level=info msg="Found new linuxserver/radarr:latest image (f3ce1a53ea02)"
time="2023-07-31T06:00:51+01:00" level=info msg="Found new ghcr.io/benphelps/homepage:latest image (38703d38561e)"
time="2023-07-31T06:01:04+01:00" level=info msg="Stopping /Homepage (7936b88da645) with SIGTERM"
time="2023-07-31T06:01:35+01:00" level=info msg="Stopping /Radarr (e6ea496a3c7f) with SIGTERM"
time="2023-07-31T06:01:40+01:00" level=info msg="Creating /Radarr"
time="2023-07-31T06:01:41+01:00" level=info msg="Creating /Homepage"
time="2023-07-31T06:01:41+01:00" level=info msg="Removing image cf58b5ffddb8"
time="2023-07-31T06:01:41+01:00" level=info msg="Removing image 1dafb1b92e1b"
time="2023-07-31T06:01:42+01:00" level=info msg="Session done" Failed=0 Scanned=50 Updated=2 notify=no
time="2023-07-31T06:01:42+01:00" level=fatal msg="Notification template error" error="template: :1:7: executing \"\" at <.Report>: can't evaluate field Report in type []*logrus.Entry" notify=no
time="2023-07-31T06:01:44+01:00" level=info msg="Watchtower 1.5.3" notify=no
time="2023-07-31T06:01:44+01:00" level=info msg="Using notifications: telegram" notify=no
time="2023-07-31T06:01:44+01:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2023-07-31T06:01:44+01:00" level=info msg="Scheduling first run: 2023-08-01 06:00:00 +0100 BST" notify=no
time="2023-07-31T06:01:44+01:00" level=info msg="Note that the first check will be performed in 23 hours, 58 minutes, 15 seconds" notify=no
```
```


### Additional context

_No response_
