### ISSUE TITLE
[Feature Request] Specify `WATCHTOWER_HTTP_API_TOKEN` as docker secret

### ISSUE THREAD

**Issue by lonix1** [containrrr/watchtower#1711]
### Is your feature request related to a problem? Please describe.

When using the ["HTTP API mode"](https://containrrr.dev/watchtower/http-api-mode), the `WATCHTOWER_HTTP_API_TOKEN` is included in the compose file. That is a security risk:
- it is committed to source control
- it is an environment variable, so is leaked in logs

### Describe the solution you'd like

Please allow us to specify the token as a docker secret. It's quite simple:

```yml
secrets:
  access_token:
    file: access_token

services:
  watchtower:
    secrets:
      - access_token
    environment:
      - WATCHTOWER_HTTP_API_TOKEN_FILE=/run/secrets/access_token
    # ...
```

Docker mounts the secret at `/run/secrets/access_token`; that container file contains the content of the `access_token` host file.

It is customary to add a new environment variable `WATCHTOWER_HTTP_API_TOKEN_FILE`, which contains the path of the secret file. The app should then read the secret from that file into memory (but never into an environment variable).

*From a development perspective, the only change is to read the secret from a file instead of an env var.* Everything else is handled by docker automatically.

### Describe alternatives you've considered

Accepting poor security. ;)

### Additional context

Thank you!
