### ISSUE TITLE
[Docs] Use watchtower with docker socket proxy

### ISSUE THREAD

**Issue by lonix1** [containrrr/watchtower#1713]
### Is your feature request related to a problem? Please describe.

The [docs](https://containrrr.dev/watchtower/usage-overview/) show that the watchtower container needs access to the docker socket. It's good practice to use a proxy instead of exposing the entire socket. The most common is the ["tecnativa proxy"](https://github.com/Tecnativa/docker-socket-proxy).

I assume that at the very least, watchtower needs the ability to stop and start containers, so needs access to the "containers" endpoint. Presumably it needs other endpoints too, e.g. for pulling images.

### Describe the solution you'd like

Please consider *documenting which parts of the docker api are needed by watchtower*. Then we could use the docker socket proxy to allow those and restrict the others.

### Describe alternatives you've considered

The status quo.

### Additional context

These are [the docker api's endpoints](https://github.com/Tecnativa/docker-socket-proxy#grant-or-revoke-access-to-certain-api-sections):
- typically allowed:
  - EVENTS
  - PING
  - VERSION
- security-critical and so typically not allowed:
  - AUTH
  - SECRETS
  - POST
- other
    - BUILD
    - COMMIT
    - CONFIGS
    - CONTAINERS
    - DISTRIBUTION
    - EXEC
    - GRPC
    - IMAGES
    - INFO
    - NETWORKS
    - NODES
    - PLUGINS
    - SERVICES
    - SESSION
    - SWARM
    - SYSTEM
    - TASKS
    - VOLUMES

**Comment by brettinternet** [comment]
As a starting place, I believe this works:

```yaml
version: "3"

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    environment:
      CONTAINERS: 1
      DELETE: 1
      IMAGES: 1
      NETWORKS: 1
      CONTAINERS_CREATE: 1
      CONTAINERS_START: 1
      CONTAINERS_UPDATE: 1
      CONTAINERS_DELETE: 1
      IMAGES_DELETE: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  watchtower:
    image: containrrr/watchtower
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      WATCHTOWER_CLEANUP: "true"
```

**Comment by saftl** [comment]
why the volume is mounted only ro? It should be rw to give the environment settings the access they need, right?

**Comment by CountCypher** [comment]
> why the volume is mounted only ro? It should be rw to give the environment settings the access they need, right?

Agreed. I had to remove the `:ro` after `/var/run/docker.sock` and also had to add the `POST` permission to get watchtower to work with socket-proxy. This is my working docker compose file:

```
services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: watchtower_socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      DELETE: 1
      IMAGES: 1
      NETWORKS: 1
      CONTAINERS_CREATE: 1
      CONTAINERS_START: 1
      CONTAINERS_UPDATE: 1
      CONTAINERS_DELETE: 1
      IMAGES_DELETE: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      - DOCKER_HOST=tcp://socket-proxy:2375
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

But I still don't know whether all these permissions are needed for watchtower to work or whether I could be more restrictive. A small addition to documentation could help here.
