### ISSUE TITLE
Notifications to Gotify Erroring Out Due to Invalid Character

### ISSUE THREAD

**Issue by uninvitedguest** [containrrr/watchtower#1752]
### Describe the bug

Watcher used to run and send notifications. It stopped a few weeks back and I only just noticed. The compose.yaml hasn't changes from the time it was working.

```
version: '1'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Toronto      
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=172800 #86400 (24 hours)
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://<secret>
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=<secret>
      - WATCHTOWER_DEBUG=true
```

### Steps to reproduce

1. Run `docker compose up -d`
2. Check logs
3. See error

### Expected behavior

I expect to see notifications on my Gotify server.

### Environment

- Debian
- AMD64
- Docker Version 1.5.3

### Your logs

```text
time="2023-09-05T21:26:24Z" level=error msg="Failed to send shoutrrr notification" error="failed to send notification to Gotify: invalid character '<' looking for beginning of value" index=0 notify=no service=gotify
```
