### ISSUE TITLE
Watchtower instance closing if one instance with one without scope

### ISSUE THREAD

**Issue by SciLor** [containrrr/watchtower#1788]
### Describe the bug

I have one watchtower instance that should update all containers once a day. Two specific containers should be updated every minute.
The first watchtower is closing itself, if the second is already running.
If first is started before the second one it works fine..

### Steps to reproduce

```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --include-restarting --schedule "0 0 20 * * *" --stop-timeout 60s
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
  watchtower-dev:
    depends_on:
      - watchtower
    image: containrrr/watchtower:latest
    container_name: watchtower-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --include-restarting --schedule "* * * * *" --scope dev --stop-timeout 60s
    labels:
      - "com.centurylinklabs.watchtower.scope=dev"
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
```

### Expected behavior

Both watchtower instances should run in parallel. I cannot set a scope for all other containers.

### Environment

Latest docker 

### Your logs

```text
time="2023-10-04T23:39:45+02:00" level=info msg="Waiting for running update to be finished..."
time="2023-10-04T23:39:47+02:00" level=info msg="Found multiple running watchtower instances. Cleaning up."
time="2023-10-04T23:39:47+02:00" level=info msg="Stopping /watchtower (629cc3cb148c) with SIGTERM"
```
