### ISSUE TITLE
[Notifications] certificate signed by unknown authority

### ISSUE THREAD

**Issue by phikai** [containrrr/watchtower#179]
I'm getting the following error when trying to setup notifications:

`Failed to send notification email:  x509: certificate signed by unknown authority`

I'm using Mailgun for SMTP and tried various port settings (25, 465, 587)... all of them return that error. I also tried adding in `WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY` and that didn't work either.

Relevant configs:

docker-compose -
```
watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: unless-stopped
        environment:
            - TZ=${TZ}
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
        network_mode: 'bridge'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: portainer --schedule @midnight --cleanup
```

environment -
```
WATCHTOWER_EMAIL=
SMTP_FROM=
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
```
