### ISSUE TITLE
API Token not working on 1.6.0

### ISSUE THREAD

**Issue by Phil57** [containrrr/watchtower#1790]
### Describe the bug

WATCHTOWER_HTTP_API_TOKEN seems not working on 1.6.0. API calls returns 401 errors. Metrics are not working either.

### Steps to reproduce

Define WATCHTOWER_HTTP_API_TOKEN in the docker compose
Use the API with the defined token
Returns 401

### Expected behavior

Respond to API call

### Environment

Docker
Portainer

### Your logs

```text
401 Unauthorized
```

### Additional context

Same docker compose is working with 1.5.3.

**Comment by Crakleurs** [comment]
Hello, I tried to reproduce the bug with the following docker-compose:
```
services:
  watchtower:
    image: containrrr/watchtower:1.6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080 
 ```
 
Unfortunately I was unable to reproduce the bug. My server is running Debian GNU/Linux 11 (bullseye) and x86_64.

I usde this command to test  `curl -H "Authorization: Bearer mytoken" localhost:8080/v1/update`
