### ISSUE TITLE
Can't shut down the container and restart it

### ISSUE THREAD

**Issue by leic4u** [containrrr/watchtower#1805]
### Describe the bug

There is a update of this container, watchtower only pulls the new images and modify the image tag, can't shut down the container and restart it.
![image](https://github.com/containrrr/watchtower/assets/32786903/b2526a75-fd9f-492c-a07e-466edb54c260)

![image](https://github.com/containrrr/watchtower/assets/32786903/d8b31254-18fb-44ce-9b53-2497fd55897c)

My watchtower's compose file:(my server is arm64)
```
version: '3.7'
  
services:
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ***@***.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ***@***.com
      # you have to use a network alias here, if you use your own certificate
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.***.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ***@***com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ***
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    command: --cleanup
```

### Expected behavior

shut down the container and restart it successfully

### Environment

- Platform ubuntu: 20.04.5 LTS
- Architecture: Arm64
- Docker Version: Docker version 23.0.1, build a5ee5b1

### Your logs

```text
there is only info logs

time="2023-10-17T07:56:14Z" level=info msg="Watchtower 1.6.0"
time="2023-10-17T07:56:14Z" level=info msg="Using notifications: smtp"
time="2023-10-17T07:56:14Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2023-10-17T07:56:14Z" level=info msg="Scheduling first run: 2023-10-18 07:56:14 +0000 UTC"
time="2023-10-17T07:56:14Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
time="2023-10-18T07:56:35Z" level=info msg="Session done" Failed=0 Scanned=15 Updated=0 notify=no
time="2023-10-19T07:56:31Z" level=info msg="Found new whyour/qinglong:latest image (a50899cee6e1)"
time="2023-10-19T07:56:42Z" level=info msg="Session done" Failed=0 Scanned=15 Updated=1 notify=no
```
```


### Additional context

_No response_
