### ISSUE TITLE
None-scoped instances clean up scoped ones

### ISSUE THREAD

**Issue by piksel** [containrrr/watchtower#1814]
> I am noticing that on a restart of my watchtower with scope `none` it is cleaning up my other watchtower instances that have defined scopes.

_Originally posted by @owine in https://github.com/containrrr/watchtower/pull/1800#issuecomment-1781948671_

**Comment by piksel** [comment]
I cannot reproduce this problem locally:

**docker-compose.yaml:**
```yaml
version: '3.7'

services:
  watchtower-foo:
    container_name: watchtower-foo
    image: containrrr/watchtower:latest-dev
    volumes: [ /var/run/docker.sock:/var/run/docker.sock:ro ]
    command: --debug -lpretty --scope foo
    labels:
      com.centurylinklabs.watchtower.scope: foo
  watchtower-none:
    container_name: watchtower-none
    image: containrrr/watchtower:latest-dev
    volumes: [ /var/run/docker.sock:/var/run/docker.sock:ro ]
    command: --debug -lpretty --scope none
    labels:
      com.centurylinklabs.watchtower.scope: none
    depends_on: [ watchtower-foo ]  # To make sure this starts after `foo`
```

**log output:**
```text
watchtower-foo   | DEBU[0000] Using scope "foo"
watchtower-foo   | DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized.
watchtower-none  | DEBU[0000] Using scope "none"
watchtower-none  | DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized.
watchtower-foo   | DEBU[0001] Making sure everything is sane before starting
watchtower-foo   | DEBU[0001] Retrieving running containers
watchtower-foo   | DEBU[0001] There are no additional watchtower containers
watchtower-foo   | DEBU[0001] Watchtower HTTP API skipped.
watchtower-foo   | INFO[0001] Watchtower v1.6.0-18-g097df11
watchtower-foo   | INFO[0001] Using no notifications
watchtower-foo   | INFO[0001] Only checking containers in scope "foo"
watchtower-foo   | INFO[0001] Scheduling first run: 2023-11-12 14:25:14 +0000 UTC
watchtower-foo   | INFO[0001] Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds
watchtower-none  | DEBU[0001] Making sure everything is sane before starting
watchtower-none  | DEBU[0001] Retrieving running containers
watchtower-none  | DEBU[0001] There are no additional watchtower containers
watchtower-none  | DEBU[0001] Watchtower HTTP API skipped.
watchtower-none  | INFO[0001] Watchtower v1.6.0-18-g097df11
watchtower-none  | INFO[0001] Using no notifications
watchtower-none  | INFO[0001] Only checking containers without a scope,
watchtower-none  | INFO[0001] Scheduling first run: 2023-11-12 14:25:14 +0000 UTC
watchtower-none  | INFO[0001] Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds
```

Both instances filter out each other:
```
watchtower-foo   | DEBU[0001] There are no additional watchtower containers
watchtower-none  | DEBU[0001] There are no additional watchtower containers
```


@owine Perhaps the problem was due to the scoped watchtower instances not having labels set?
Considering this to be closed until I can reproduce the issue.
