### ISSUE TITLE
Update local base images built from local Dockerfile

### ISSUE THREAD

**Issue by jzazo** [containrrr/watchtower#1824]
### Is your feature request related to a problem? Please describe.

I use caddy base image inside a Dockerfile and add plugins to it. My docker compose is similar to this:
```yaml
services:
  caddy:
    build: .
    restart: unless-stopped
```
with a local Dockerfile:
```
FROM caddy:builder AS builder
RUN xcaddy build --with github.com/caddy-dns/cloudflare
FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

### Describe the solution you'd like

I would like to track `caddy:latest` and rebuild my Dockerfile image when a new image is published.

### Describe alternatives you've considered

Maybe a pre-hook script on watchtower or a cron-job on building this docker image once per day or per week.

**Comment by snakwu** [comment]
I also need this feature and hope it can be implemented. Thank you

**Comment by cellulosa** [comment]
Same here. This is my `docker-compose.yml`:

```
version: "3.8"

services:

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    container_name: caddy
    image: caddy:latest
    depends_on:
      - cloudflared
    build:
      context: .
      dockerfile: ${DOCKER_CONFIG_DIR}/caddy/Dockerfile
    volumes:
      - ${DOCKER_CONFIG_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_CONFIG_DIR}/caddy:/data
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
```

and caddy uses the following to implement some plugins:

```
FROM caddy:builder AS builder

RUN xcaddy build \
	--with github.com/caddy-dns/cloudflare

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

which is built when running docker-compose with `docker-compose up --build`.

I just run watchtower for the first time and realised it updated caddy without re-building it:

```
INFO[86413] Found new caddy:latest image (2cbdde935029)  
INFO[86416] Stopping /caddy (9a1bebc8e378) with SIGTERM  
INFO[86417] Creating /caddy                              
INFO[86418] Session done
```

Which meant caddy became unusable for how I set it up.

Is there a way around it? Or should we just set watchtower to [exclude caddy](https://containrrr.dev/watchtower/container-selection/#full_exclude) for the time being?

Thanks

**Comment by piksel** [comment]
You could use https://github.com/crazy-max/diun to watch for changes and rebuild the local image whenever caddy is updated.

Then you can just put a `no-pull` label on the container, which would make watchtower compare the local image with the current one:

```Dockerfile
LABEL "com.centurylinklabs.watchtower.no-pull"="true"
```

**Comment by jzazo** [comment]
Thanks for the suggestion. This has been more complicated than I expected because I wanted to run Diun from docker, but I think I managed to get it working. For reference, I added the label as you suggest to the container to monitor.

This is my diun container:
```
version: "3"
services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    user: "990:990"  # optional
    command: serve
    volumes:
      - /var/lib/diun:/data
      - /my-path/Dockerfile:/my-path/Dockerfile:ro
      - /my-path/pipe:/my-path/pipe
      - /my-path/launch_build.sh:/my-path/launch_build.sh:ro
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKERFILE_PATTERNS=/my-path/Dockerfile
      - DIUN_NOTIF_SCRIPT_CMD=/my-path/launch_build.sh
    restart: unless-stopped
```
Note that I am running the container as user 990.

Then, I created a named pipeline as described [here](https://stackoverflow.com/a/63719458/4807847).
This involved creating a pipe file owned by user 990, which you would need to have created first, or just run as root.
```
mkfifo /my-path/pipe
```
I also created a `docker buildx` script owned by root `execpipe.sh`
```
#!/bin/sh
pipe=/my-path/pipe
[ -p "$pipe" ] || mkfifo -m 0600 "$pipe" || exit 1
while :; do
    while read -r cmd; do
        if [ "$cmd" ]; then
            printf 'Running %s ...\n' "$cmd"
            docker buildx build -t local/caddy:latest -f /my-path/Dockerfile /my-path  # add tag to build & compose yml
        fi
    done <"$pipe"
done
```
and the command that diun executes `launch_build.sh` with read-only access:
```
#!/bin/sh
echo "docker build" > /my-path/pipe
```

Finally, I added the root executable to crontab with `sudo crontab -e` and the line:
```
@reboot /my-path/execpipe.sh >> /my-path/output.txt 2>&1
```

I have tested the pipe, the executables and tested from the container and it seems to work. I will monitor the crontab and hope it will work next time there is an update.

If anyone has suggestions on how to improve this flow, don't be shy. I have aimed not to `eval` any command to minimize security risks. I will leave this thread open a while longer, and if there are no better suggestions I will close the ticket.
