### ISSUE TITLE
Raspberry pi 4 not supported?

### ISSUE THREAD

**Issue by asyba** [containrrr/watchtower#1838]
### Describe the bug

Error docker execution
```
 ! watchtower The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
```

docker-compose
```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    #command: 
    environment:
      - TZ=America/Argentina/Cordoba
      - PUID=1000
      - PGID=1000
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:xxxxx@xxxx/?devices=[xxxx,xxx]&title=Actualizo+docker+image&priority=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```

### Steps to reproduce

docker compose up -d

### Expected behavior

Working watchtower

### Environment

- Raspberry pi 4
Linux raspberrypi 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux
 Static hostname: raspberrypi
       Icon name: computer
      Machine ID: xxx
         Boot ID: xxxx
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.1.0-rpi4-rpi-v8
    Architecture: arm64

### Your logs

```text
exec /watchtower: exec format error
exec /watchtower: exec format error
```
