### ISSUE TITLE
cron: panic running job: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [containrrr/watchtower#1864]
### Describe the bug

Scheduling panic

### Expected behavior

check will be performed

### Environment

- Platform
linux
- Architecture
x64
- Docker Version
Docker Desktop 4.25.2 (129061)

### Your logs

```text
time="2023-11-30T19:06:45+01:00" level=info msg="Watchtower 1.7.1"
time="2023-11-30T19:06:46+01:00" level=info msg="Using no notifications"
time="2023-11-30T19:06:46+01:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2023-11-30T19:06:46+01:00" level=info msg="Scheduling first run: 2023-11-30 19:06:46 +0100 CET"
time="2023-11-30T19:06:46+01:00" level=info msg="Note that the first check will be performed in 0 seconds"
2023/11/30 19:06:53 cron: panic running job: duplicate metrics collector registration attempted
goroutine 82 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1()
        /home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69
panic({0xaec580, 0xc0003ae1a0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0001bb770?, {0xc0003a8870?, 0x1, 0x1?})
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:405 +0x7f
github.com/prometheus/client_golang/prometheus/promauto.Factory.NewGauge({{0xc80de0?, 0xc0001bb770?}}, {{0x0, 0x0}, {0x0, 0x0}, {0xb7d533, 0x1d}, {0xb94759, 0x4b}, ...})
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/promauto/auto.go:297 +0xd3
github.com/prometheus/client_golang/prometheus/promauto.NewGauge(...)
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/promauto/auto.go:191
github.com/containrrr/watchtower/pkg/metrics.Default()
        /home/runner/work/watchtower/watchtower/pkg/metrics/metrics.go:55 +0x8d
github.com/containrrr/watchtower/pkg/metrics.RegisterScan(...)
        /home/runner/work/watchtower/watchtower/pkg/metrics/metrics.go:85
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
        /home/runner/work/watchtower/watchtower/cmd/root.go:329 +0x105
github.com/robfig/cron.FuncJob.Run(0x0?)
        /home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:92 +0x1a
github.com/robfig/cron.(*Cron).runWithRecovery(0x0?, {0xc7e060?, 0xc0001cc5a0?})
        /home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62
created by github.com/robfig/cron.(*Cron).run
        /home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x79f
```

**Comment by piksel** [comment]
Please fill in the form. What configuration are you using? How are you starting watchtower? Did this work on a previous version?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```yaml

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    environment:
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_WARN_ON_HEAD_FAILURE=never
      - WATCHTOWER_TIMEOUT=15m
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=***
      - WATCHTOWER_SCOPE=none
    expose:
      - 8080


```

```rust
level=info msg="Watchtower v1.7.1-17-g76f9cea"
level=info msg="Using no notifications"
level=info msg="Only checking containers without a scope,"
cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 3629769 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1()
 /go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x65
panic({0xa9e940?, 0x10d3250?})
 /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/containrrr/watchtower/pkg/metrics.NewMetric({0x0, 0x0})
 /go/watchtower/pkg/metrics/metrics.go:31 +0x1c
github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc000317590)
 /go/watchtower/cmd/root.go:377 +0x165
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
 /go/watchtower/cmd/root.go:325 +0xc6
github.com/robfig/cron.FuncJob.Run(0xc00012ce00?)
 /go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:92 +0x12
github.com/robfig/cron.(*Cron).runWithRecovery(0xc000bd27d0?, {0xc6b8c0?, 0xc0000be5a0?})
 /go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x53
created by github.com/robfig/cron.(*Cron).run in goroutine 75
 /go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x779
```
