### ISSUE TITLE
error msg="Error response from daemon: conflicting options: hostname and the network mode"

### ISSUE THREAD

**Issue by jonatronnn** [containrrr/watchtower#188]
I believe this issue happens when containers that are routed through my VPN container (dperson/openvpn) using --net=container:vpn are updated and then restart is attempted but fails due to trying to reuse the old network mode entry which seems to change when the OpenVPN container is restarted also.

Is it possible to set Watchtower to just use a full Docker run command as this is all I have to do to get the container working properly again?

**Comment by cameron-doherty** [comment]
Just adding in that I am also experiencing this same issue.

**Comment by azinchen** [comment]
I'm also experiencing this issue when uses compose file

```yaml
version: '3'

services:
  vpn:
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    ...

  transmission:
    image: linuxserver/transmission:latest
    network_mode: service:vpn
    depends_on:
      - vpn
    ...
```

Also the problem with this compose file is that when vpn container is updating, transmission is not stopped.

**Comment by IvanJosipovic** [comment]
+1

**Comment by TommyE123** [comment]
I'm also seeing this error.

**Comment by willfurstenau** [comment]
I'm having the same issue.

docker-compose is as follows

```
    jackett:
        image: 'linuxserver/jackett:latest'
        container_name: jackett
        volumes:
            - '/data/jackett:/config'
            - '${NAS}/media/downloads:/downloads'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        labels:
            - traefik.enable=true
            - traefik.backend=jackett
            - 'traefik.frontend.rule=Host:jackett.${DOMAIN}'
            - traefik.docker.network=traefik
            - traefik.port=9117
        depends_on:
            - vpnclient
        network_mode: 'service:vpnclient'

    vpnclient:
        image: dperson/openvpn-client
        container_name: vpnclient
        cap_add:
            - net_admin
        security_opt:
            - 'label:disable'
        volumes:
            - /dev/net:/dev/net:z
            - /data/vpnclient:/vpn
        environment:
            - TZ:${TZ}
            - FIREWALL:''
        networks:
            - default
        read_only: true
        tmpfs:
            - /tmp
        restart: always
        stdin_open: true
        tty: true
```

**Comment by rshackleton** [comment]
Also experiencing this problem:

```
  jackett:
    image: linuxserver/jackett
    depends_on:
      - vpn
    env_file:
      - .env
    network_mode: "service:vpn"
    restart: always
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      TZ: 'Europe/London'
    restart: always
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn
```
