### ISSUE TITLE
Parsed container image ref has no tag

### ISSUE THREAD

**Issue by plague-doctor** [containrrr/watchtower#1892]
### Describe the bug

This may be related to #1050, but it is different somehow...

I get those errors:
```
time="2023-12-29T01:09:47Z" level=warning msg="Could not do a head request for \"bohdans/sungather:latest@sha256:bdbbc78f0ebf969e2e14dee01e39a72d9ddbde3d83f85cbb43bde29124e8a2d1\", falling back to regular pull." container=/hass_hass_solar1.1.p8t4wksigphc7wgkrvovalts0 image="bohdans/sungather:latest@sha256:bdbbc78f0ebf969e2e14dee01e39a72d9ddbde3d83f85cbb43bde29124e8a2d1"
time="2023-12-29T01:09:47Z" level=warning msg="Reason: Parsed container image ref has no tag: docker.io/bohdans/sungather@sha256:bdbbc78f0ebf969e2e14dee01e39a72d9ddbde3d83f85cbb43bde29124e8a2d1" container=/hass_hass_solar1.1.p8t4wksigphc7wgkrvovalts0 image="bohdans/sungather:latest@sha256:bdbbc78f0ebf969e2e14dee01e39a72d9ddbde3d83f85cbb43bde29124e8a2d1"
time="2023-12-29T01:09:52Z" level=warning msg="Could not do a head request for \"influxdb:1.8-alpine@sha256:d29e9e5a816afcc5ab2cc62f82e86b72089339a35d80dd9f72a0754343d30817\", falling back to regular pull." container=/hass_hass_influxdb.1.64ig4hplbpvrlnrrjzr9022vp image="influxdb:1.8-alpine@sha256:d29e9e5a816afcc5ab2cc62f82e86b72089339a35d80dd9f72a0754343d30817"
time="2023-12-29T01:09:52Z" level=warning msg="Reason: Parsed container image ref has no tag: docker.io/library/influxdb@sha256:d29e9e5a816afcc5ab2cc62f82e86b72089339a35d80dd9f72a0754343d30817" container=/hass_hass_influxdb.1.64ig4hplbpvrlnrrjzr9022vp image="influxdb:1.8-alpine@sha256:d29e9e5a816afcc5ab2cc62f82e86b72089339a35d80dd9f72a0754343d30817"
time="2023-12-29T01:10:04Z" level=warning msg="Could not do a head request for \"prom/node-exporter:latest@sha256:4cb2b9019f1757be8482419002cb7afe028fdba35d47958829e4cfeaf6246d80\", falling back to regular pull." container=/monitoring_node-exporter-2.1.c7kkv6wnzdw5yrxqcdu8nlx39 image="prom/node-exporter:latest@sha256:4cb2b9019f1757be8482419002cb7afe028fdba35d47958829e4cfeaf6246d80"
time="2023-12-29T01:10:04Z" level=warning msg="Reason: Parsed container image ref has no tag: docker.io/prom/node-exporter@sha256:4cb2b9019f1757be8482419002cb7afe028fdba35d47958829e4cfeaf6246d80" container=/monitoring_node-exporter-2.1.c7kkv6wnzdw5yrxqcdu8nlx39 image="prom/node-exporter:latest@sha256:4cb2b9019f1757be8482419002cb7afe028fdba35d47958829e4cfeaf6246d80"

[...]
```
however `docker ps` has got all information available:

```
$docker ps

CONTAINER ID   IMAGE                                        COMMAND                  CREATED             STATUS                PORTS                                 NAMES
26bdc57c2b18   bohdans/sungather:latest                     "python sungather.py…"   About an hour ago   Up About an hour                                            hass_hass_solar1.1.p8t4wksigphc7wgkrvovalts0
ec41bb010c57   influxdb:alpine                              "/entrypoint.sh infl…"   2 days ago          Up 2 days             8086/tcp                              monitoring_influxdb.1.nly6bfqourpytd6n6bcxiajx6
c8de88805b68   freshrss/freshrss:latest                     "./Docker/entrypoint…"   2 days ago          Up 2 days             80/tcp                                freshrss_freshrss.1.lmc4makrget8curvn8tzglxa6
[...]
```

### Steps to reproduce

```
docker run --rm --name watchtower --volume /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:latest --run-once
```
also
```
docker run --rm --name watchtower --volume /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:latest-dev --run-once
```

### Expected behavior

I expect watchtower does what it supposed to.

### Environment

- Docker Swarm
- Docker version 24.0.7, build afdd53b

### Your logs

```text
as above
```

**Comment by piksel** [comment]
Watchtower does not work with swarm. Try using https://GitHub.com/containrrr/shepherd

**Comment by GAS85** [comment]
Has the same issue

```shell
Could not do a head request for "aacebedo/dnsdock@sha256:4c2d2773837cb436ddc7c835187fffc27d1df8e58b64e0a7e204ff92382180ae", falling back to regular pull.
Reason: Parsed container image ref has no tag: docker.io/aacebedo/dnsdock@sha256:4c2d2773837cb436ddc7c835187fffc27d1df8e58b64e0a7e204ff92382180ae
Could not do a head request for "containrrr/watchtower@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038", falling back to regular pull.
Reason: Parsed container image ref has no tag: docker.io/containrrr/watchtower@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
Could not do a head request for "willfarrell/autoheal@sha256:a2e5e76d239b127081f8f96041a21f9747015b23af439c23ee60de0350c06880", falling back to regular pull.
Reason: Parsed container image ref has no tag: docker.io/willfarrell/autoheal@sha256:a2e5e76d239b127081f8f96041a21f9747015b23af439c23ee60de0350c06880
```

My compose config is like this:

```yaml
  dnsdock:
    # Version v1.17.0-amd64
    image: aacebedo/dnsdock@sha256:4c2d2773837cb436ddc7c835187fffc27d1df8e58b64e0a7e204ff92382180ae
    container_name: dnsdock
    command: --nameserver="192.168.9.9:53"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount nslookup
      - /usr/bin/nslookup:/usr/bin/nslookup:ro
      # Mount sh to be able to execute nslookup
      - /bin/sh:/bin/sh:ro
      - /lib:/lib:ro
      - /lib64:/lib64:ro
    ports:
      - "11053:53/udp" # Local Docker DNS
    labels:
      - autoheal=true
    healthcheck:
      test: nslookup mydomain 127.0.0.1
      interval: 5m
      timeout: 3s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
```

And this is not a swarm.
