### ISSUE TITLE
API error when using hostname

### ISSUE THREAD

**Issue by louisonsarlinmagnus** [containrrr/watchtower#1905]
### Describe the bug

I was trying to use the watchtower widget for my Homepage dashboard, but I keep getting the same problem.
When homepage trying to do his thing to fulfill the widgets' information, it returns "connection refused".

The watchtower and homepage containers are on the same docker-compose file (so, in the same network) : 

```yaml
    version: "3.8"
     
    services:
      homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        ports:
         - 3000:3000
        volumes:
         - ./homepage/config:/app/config
          - /var/run/docker.sock:/var/run/docker.sock
     
      watchtower:
        image: containrrr/watchtower
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
        ports:
         - 8080:8080
        environment:
          WATCHTOWER_DEBUG: true
          WATCHTOWER_HTTP_API_METRICS: true
          WATCHTOWER_HTTP_API_TOKEN: "mytoken"
        labels:
         - homepage.group=My First Group
          - homepage.name=Watchtower
          - homepage.icon=watchtower.png
          - homepage.widget.type=watchtower
          - homepage.widget.url=http://watchtower:8080
          - homepage.widget.key=mytoken
          - homepage.widget.fields=["containers_scanned", "containers_updated", "containers_failed"]
``` 

This error only appears when I'm using the hostname "watchtower" to retrieve the metrics.

From the host, I can curl using `curl -H "Authorization: Bearer mytoken" http://localhost:8080/v1/metrics` so the API config and metric enabling is OK.

From the homepage container, I can ping the watchtower container with `docker exec -it homepage ping watchtower` so the hostname is OK.
But if in the homepage container, I `wget --header="Authorization: Bearer mytoken"  --output-document -  http://localhost:8080/v1/metrics` I get `wget: can't connect to remote host: Connection refused`

Finally, using Traefik to expose watchtower to watchtower.mydomain.com, I can curl `curl -H "Authorization: Bearer mytoken" https://watchtower.mydomain.com`

### Steps to reproduce

1. copy the docker-compose.yaml I dropped above.
2. `docker compose up -d`
3. Uncomment ./homepage/config/docker.yaml lines 9 and 10 (to set the docker sock)
4. Go to localhost:3000 to see the error in the dashboard
5. `docker exec -it homepage wget --header="Authorization: Bearer mytoken" --output-document - http://localhost:8080/v1/metrics` to get the connection refused
6. `docker exec -it homepage ping watchtower` to see homepage pinging watchtower

### Expected behavior

I'm expecting the same behavior using ip or hostname

### Screenshots

When using the host name as is the docker-compose file
![image](https://github.com/containrrr/watchtower/assets/70757160/79050848-2ae6-48d4-b233-381db0ede4d5)

When exposing watchtower through Traefik
![image](https://github.com/containrrr/watchtower/assets/70757160/1532e379-b404-4577-83dc-2eb2841e8896)

The only change between the picture is going `https://watchtower.mydomain.com` instead of `http://watchtower:8080`

### Environment

- OS : Ubuntu 22.04.3 LTS
- Docker Version: 24.0.7

### Your logs

```text
Nothing appears on the log, even with the debug
```
