### ISSUE TITLE
Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"

### ISSUE THREAD

**Issue by knuurr** [containrrr/watchtower#1919]
### Describe the bug

Upon starting container, I get error from title in logs.

Below you'll find my docker-compose file.

Some context: I try to use my internal apprise-api container as notification sinkhole together with Shoutrrr `generic` handler, this is why You'll se it configured.

### Steps to reproduce

1. Prepare docker-compose with my config
2. Launch it and observe logs

### Expected behavior

Watchtower container launches and additionaly sends notification to endpoint.

### Environment

- Platform 
Ubuntu 22.04.3 LTS
- Architecture 
x64
- Docker Version 
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

### Your logs

```text
watchtower  | time="2024-02-04T03:37:04+01:00" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"
watchtower  | time="2024-02-04T03:37:54+01:00" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"
watchtower  | time="2024-02-04T03:39:13+01:00" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"
watchtower  | time="2024-02-04T03:40:42+01:00" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"
```

### Additional context

Docker compose I use for launching:

```yml
version: '3.7'


networks:
  backend:
    external: true 


services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      # Ensure proper timezones
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Docker Socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCHTOWER_SCHEDULE="0 0 19 * * *"
      # Will only monitor for new images, send notifications and invoke the pre-check/post-check hooks, but will not update the containers.
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_MONITOR_ONLY=true
      # Gotify notifications
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      # Apprise workaround shenanigans
      - WATCHTOWER_NOTIFICATION_URL=generic+http://apprise-api:8000/notify/apprise?messageKey=body&$$tag=watchtower
    networks:
      - backend
      
  
```
