### ISSUE TITLE
Unable to Update Containers - i/o Timeout via DNS Lookup?

### ISSUE THREAD

**Issue by phikai** [containrrr/watchtower#192]
I'm getting the following error on a container update:

```
time="2018-05-17T23:48:48-05:00" level=info msg="Unable to update container /portainer, err='Error response from daemon: Get https://registry-1.docker.io/v2/portainer/portainer/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Aportainer%2Fportainer%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on xxx.xxx.xxx.xxx:53: read udp xxx.xxx.xxx.xxx:45264->xxx.xxx.xxx.xxx:53: i/o timeout'. Proceeding to next." 
```

Docker-Compose to launch Watchtower is:

```
# ----------------------------------------
    # WATCHTOWER
    # Automatic Update Service for Docker VMs
    # ----------------------------------------
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: unless-stopped
        environment:
            - TZ=${TZ}
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
        network_mode: 'bridge'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/ssl/certs:/etc/ssl/certs'
        command: portainer --schedule @midnight --cleanup
```

Potentially the only thing I can see here is that I run Pi-Hole in front of my DNS, but I don't see anything being blocked there...
