### ISSUE TITLE
Watchtower not applying docker-compose `configs:` after update

### ISSUE THREAD

**Issue by Nick2253** [containrrr/watchtower#1988]
### Describe the bug

I have a container created through `docker-compose` that is configured with a [`configs:` attribute](https://docs.docker.com/compose/compose-file/05-services/#configs) in the compose file.  After updating this container, the new container did not have the files specified in `configs:`, and therefore failed to run appropriately.

I had to redeploy the stack in order for the `configs` to be applied.

### Steps to reproduce

1. Create a container via docker-compose that is configured with the `configs:` attribute.
2. Confirm that the deployed container contains the appropriate files.
3. Update the container with Watchtower.
4. Observe that the new container does not contain the appropriate files.
5. Re-deploy the container `docker compose up`, and observe that the redeployed container now contains the appropriate files.

### Expected behavior

The newly created containers will be configured exactly as specified in the compose file.

### Environment

- CoreOS 40.20240602.3.0
- Docker 24.0.5

### Your logs

```text
time="2024-06-21T00:47:23-07:00" level=info msg="Watchtower 1.7.1"
time="2024-06-21T00:47:23-07:00" level=info msg="Using no notifications"
time="2024-06-21T00:47:23-07:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2024-06-21T00:47:23-07:00" level=info msg="Scheduling first run: 2024-06-21 04:00:00 -0700 PDT"
time="2024-06-21T00:47:23-07:00" level=info msg="Note that the first check will be performed in 3 hours, 12 minutes, 36 seconds"
time="2024-06-21T04:00:09-07:00" level=info msg="Found new nginx:alpine image (96e3e4fd2098)"
time="2024-06-21T04:00:32-07:00" level=info msg="Stopping /merginmaps-proxy (8fbca3069d77) with SIGTERM"
time="2024-06-21T04:00:33-07:00" level=info msg="Creating /merginmaps-proxy"
time="2024-06-21T04:00:34-07:00" level=info msg="Removing image f597a450f464"
time="2024-06-21T04:00:34-07:00" level=info msg="Session done" Failed=0 Scanned=19 Updated=1 notify=no
```

### Additional context

Minimal working example `docker-compose.yaml` file:

```yaml
version: '3.9'
services:
  web:
    image: nginx:alpine
    configs:
      - source: 01-config-test.sh
        target: /docker-entrypoint.d/01-config-test.sh
        mode: 0777
configs:
  01-config-test.sh:
    content: |
      #!/bin/sh
      echo "$$ME: info: docker-compose config applied correctly"
```

If the `configs` is applied correctly, you should see the following in your nginx container log:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/01-config-test.sh
01-config-test.sh: info: docker-compose config applied correctly
...
```
