### ISSUE TITLE
Container does not get updated

### ISSUE THREAD

**Issue by realies** [containrrr/watchtower#1999]
### Describe the bug

When the image of a docker compose service is updated, it gets pulled, but the docker container does not get recreated or stopped. I'm not sure if it's related to compose.

### Steps to reproduce

```yaml
version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 20 5 * * *
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_DISABLE_CONTAINERS=wake-on-lan-service
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=x
      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 ```

### Expected behavior

The container stops and gets recreated with the latest image

### Environment

- rpi4
- arm64
- Docker version 27.0.3, build 7d4bcd8

### Your logs

```text
watchtower  | time="2024-07-14T05:26:03Z" level=debug msg="Parsing image ref" host=index.docker.io image=zoeyvid/npmplus normalized=docker.io/zoeyvid/npmplus tag=latest
watchtower  | time="2024-07-14T05:26:03Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/zoeyvid/npmplus/manifests/latest"
watchtower  | time="2024-07-14T05:26:03Z" level=debug msg="Found a remote digest to compare with" remote="sha256:661f67996f2293717f8f82dfc7b546494d63bea5689c30aa90aa1bd71b4abeb4"
watchtower  | time="2024-07-14T05:26:03Z" level=debug msg=Comparing local="sha256:adb7e1f2d47724ceb27e494a1f2db3d21401b08311ccba2393b2b9e79017fdfa" remote="sha256:661f67996f2293717f8f82dfc7b546494d63bea5689c30aa90aa1bd71b4abeb4"
watchtower  | time="2024-07-14T05:26:03Z" level=debug msg="Digests did not match, doing a pull."
watchtower  | time="2024-07-14T05:26:03Z" level=debug msg="Pulling image" container=/npmplus image="zoeyvid/npmplus:latest"
watchtower  | time="2024-07-14T05:26:04Z" level=info msg="Found new zoeyvid/npmplus:latest image (43ff4b4c4210)"
watchtower  | time="2024-07-14T05:26:04Z" level=debug msg="Trying to load authentication credentials." container=/dpaste image="darrenofficial/dpaste:latest"
watchtower  | time="2024-07-14T05:26:04Z" level=debug msg="No credentials for index.docker.io found" config_file=/config.json
watchtower  | time="2024-07-14T05:26:04Z" level=debug msg="Got image name: darrenofficial/dpaste:latest"
watchtower  | time="2024-07-14T05:26:04Z" level=debug msg="Checking if pull is needed" container=/dpaste image="darrenofficial/dpaste:latest"
...
watchtower  | time="2024-07-14T05:26:10Z" level=info msg="Session done" Failed=0 Scanned=7 Updated=1 notify=no
```
