### ISSUE TITLE
SMTP notification using "auth login"

### ISSUE THREAD

**Issue by nikolaiiii** [containrrr/watchtower#2061]
### Describe the bug

Hello,
I'd like to send notifications using a mail server (mail.mailo.com) which has only these authentication mechanism:

250-AUTH LOGIN

I tried every kind of option possible, but they all fail.
What option do I have?

### Steps to reproduce

I am using these settings:

```
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_TRACE='false'
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_CLEANUP='true'
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      - WATCHTOWER_NOTIFICATION_URL=smtp://user@domain.org:key@mail.mailo.com:587/?auth=Unknown&encryption=Auto&fromaddress=fromaddr@domain.org&fromname=Watchtower&starttls=Yes&subject=Watchtower_updates_on_Nas&toaddresses=toaddr@domain.org&usehtml=No
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

### Expected behavior

E-mails are sent.

### Environment

- Openmediavault
- x86_64
- `docker-ce                            5:27.3.1-1~debian.11~bullseye`

```
================================================================================
= OS/Debian information
================================================================================
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
```
================================================================================
= openmediavault information
================================================================================
Release: 6.9.16-1
Codename: Shaitan
```

### Your logs

- None

```
watchtower  | time="2024-06-21T10:24:58+02:00" level=error msg="Failed to send shoutrrr notification" error="error sending message to recipient: error setting RCPT: 530 Authentication required" index=0 notify=no service=smtp
```

- OAuth2

```
watchtower  | time="2024-06-21T10:27:33+02:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: 504 Unknown mechanism <XOAUTH2>" index=0 notify=no service=smtp
```

- Unknown

```
watchtower  | time="2024-06-21T10:28:59+02:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: 504 Unknown mechanism <PLAIN>" index=0 notify=no service=smtp
```

- CRAMMD5

```
watchtower  | time="2024-06-21T10:30:45+02:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: 535 Authentication mechanism CRAM-MD5 not available" index=0 notify=no service=smtp
```

- Plain

```
watchtower  | time="2024-06-21T10:34:55+02:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: 504 Unknown mechanism <PLAIN>" index=0 notify=no service=smtp
```
