### ISSUE TITLE
Scheduled restarts

### ISSUE THREAD

**Issue by rcarmo** [containrrr/watchtower#2064]
### Is your feature request related to a problem? Please describe.

I would like to have an easy way to schedule restarts of specific containers - possibly using labels

### Describe the solution you'd like

Something like this added to each service I would like to restart:

```yaml
 labels:
      com.centurylinklabs.watchtower.daily_restart: "true"
      com.centurylinklabs.watchtower.restart_time: "05:00"
```

I don't see a need for anything as elaborate as a cron expression, but that might be another way

### Describe alternatives you've considered

I've been using additional containers with an inline script to do it like so:

```yaml
version: "3"
services:

  myservice:
    container_name: myservice

  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          current_epoch=$$(date +%s)
          target_epoch=$$(( $$(date -d "05:00" +%s) + 86400 ))
          sleep_seconds=$$(( target_epoch - current_epoch ))
          echo "$$(date) + $$sleep_seconds seconds"
          sleep $$sleep_seconds

          docker restart myservice
        done
```
