### ISSUE TITLE
Max --interval is 300s?

### ISSUE THREAD

**Issue by RyanRamchandar** [containrrr/watchtower#207]
My `docker-compose.yml` file sets the `--interval` to 3600s (1 hour) but it appears the interval is still 300s (5 min) based on debug logs from the container.  Is the max interval 300?

**`docker logs app_watchtower_1`**
```
time="2018-07-12T20:40:10Z" level=info msg="First run: 2018-07-12 20:45:10 +0000 UTC" 
time="2018-07-12T20:45:20Z" level=info msg="Unable to update container /dashboard, err='Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:60127->127.0.0.53:53: i/o timeout'. Proceeding to next." 
time="2018-07-12T20:50:20Z" level=info msg="Unable to update container /dashboard, err='Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:43078->127.0.0.53:53: i/o timeout'. Proceeding to next." 
```
Note: network errors due to no internet connection during the test

**`docker inspect --format='{{.Config.Cmd}}' app_watchtower_1`**
```
[dashboard --interval 3600 --cleanup --debug]
```

**docker-compose.yml**
```
version: "3"
services:
  watchtower:
    image: v2tec/watchtower:armhf-0.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["dashboard", "--interval", "3600", "--cleanup"]
```

**Comment by connormcmk** [comment]
Hi @RyanRamchandar, I'll try running mine with a 10 minute timer to see if i'm having any trouble. I'm also running an armhf image. One sec

**Comment by connormcmk** [comment]
Here's what I'm running:

```
docker run -it   --name watchtower   -v /home/pi/.docker/config.json:/config.json   -v /var/run/docker.sock:/var/run/docker.sock   --env-file ./env.list v2tec/watchtower:armhf-latest --interval 600 --debug
```

It seems like it's working for me:
```
DEBU[0000] Retrieving running containers                
INFO[0000] First run: 2018-07-16 17:04:33 +0000 UTC     
DEBU[0599] Checking containers for updated images       
DEBU[0599] Retrieving running containers                
DEBU[0599] Pulling repo/name:latest for /thirsty_easley 
DEBU[0599] Loaded auth credentials { } for repo/name 
DEBU[0601] No new images found for /thirsty_easley      
DEBU[0601] Pulling v2tec/watchtower:armhf-latest for /watchtower 
DEBU[0601] Loaded auth credentials { } for v2tec/watchtower:armhf-latest 
DEBU[0602] No new images found for /watchtower          
DEBU[0602] Scheduled next run: 2018-07-16 17:14:33 +0000 UTC 
```

**Comment by RyanRamchandar** [comment]
Okay, thanks for testing. I'll check again and report back.

**Comment by connormcmk** [comment]
```
DEBU[0602] Scheduled next run: 2018-07-16 17:14:33 +0000 UTC 
...
DEBU[1202] Scheduled next run: 2018-07-16 17:24:33 +0000 UTC 
```
checked further, seems to work. 

Maybe try using `v2tec/watchtower:armhf-latest`. I don't know how the versioning works exactly, but it's working for me. 

Could you give me your `uname -a`?

Also, if it still doesn't work for you, you can always use a chron instead. For hourly check the syntax is:
`--schedule "0 0 * * * *"` in place of the --interval flag

**Comment by RyanRamchandar** [comment]
```
# uname -a
Linux umbrela-bridge 4.15.0-23-generic #25-Ubuntu SMP 
Wed May 23 17:59:52 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

If `--interval` doesn't work I'll try `--schedule`. Thanks for the pro tip!

**Comment by RyanRamchandar** [comment]
Hmm seems like neither command is working for me now even when I reduce the interval to 30s. Also, adding `--debug` doesn't seem to output any debug messages. 

Reduced interval to 30s w/ `--debug`
```
version: "3"
services:
  watchtower:
    image: v2tec/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["dashboard", "--interval", "30", "--cleanup",  "--debug"]
```

Trying `--schedule`
```
version: "3"
services:
  watchtower:
    image: v2tec/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ['dashboard', '--schedule', '"30 * * * * *"', '--cleanup',  '--debug']
```

In both cases, I see a similar log:
```
# docker logs app_watchtower_1 -f
time="2018-07-17T20:41:51Z" level=info msg="First run: 2018-07-17 20:46:51 +0000 UTC" 
```

Could this be an error in my docker-compose.yml formatting?

Or, could this be because my device is arm64v8 yet the image is armhf. Maybe there is some incompatibility here. See #206
