### ISSUE TITLE
Mqtt support

### ISSUE THREAD

**Issue by DeltaTango69** [containrrr/watchtower#2098]
### Describe the bug

Gemini or chatgpt gives me following configuration for MQTT messages for example for Homeassistant. 

```
version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATION_MQTT_ENABLE=true
      - WATCHTOWER_NOTIFICATION_MQTT_BROKER_HOST=DEINE_MQTT_BROKER_IP
      - WATCHTOWER_NOTIFICATION_MQTT_BROKER_PORT=1883 # Standard MQTT Port, ggf. anpassen
      - WATCHTOWER_NOTIFICATION_MQTT_BROKER_USERNAME=DEIN_MQTT_USERNAME # Optional
      - WATCHTOWER_NOTIFICATION_MQTT_BROKER_PASSWORD=DEIN_MQTT_PASSWORT # Optional
      - WATCHTOWER_NOTIFICATION_MQTT_TOPIC=watchtower/events
      - WATCHTOWER_NOTIFICATION_MQTT_CLIENT_ID=watchtower-$(hostname) # Optional, erzeugt eine eindeutige Client-ID
      - WATCHTOWER_NOTIFICATION_MQTT_TLS_ENABLE=false # Optional, für TLS-Verschlüsselung
      # - WATCHTOWER_NOTIFICATION_MQTT_TLS_CA_CERTS=/path/to/ca.crt # Optional, Pfad zum CA-Zertifikat
    command: deine_container_namen_oder_alle --interval 300 # Beispiel: alle 5 Minuten prüfen
    restart: unless-stopped

```
But I find no official support for that. Also it is not working?! Was this implemented before and not more yet?

### Expected behavior

Mqtt support

### Environment

- Platform
- Architecture
- Docker Version

### Your logs

```text
.
```
