### ISSUE TITLE
Secret for WATCHTOWER_HTTP_API_TOKEN is passed as file path

### ISSUE THREAD

**Issue by bHub** [containrrr/watchtower#2111]
### Describe the bug

The value of the environment variable WATCHTOWER_HTTP_API_TOKEN is wrongly assigned when using docker secret: the file path **run/secrets/wt_token**  is considered the value of the variable.

Watchtower yaml file:

```yaml
services:
  wtr:
    container_name: wt
    image: containrrr/watchtower
    networks:
        - prox
    restart: always
    command: -H tcp://proxy:2375
    environment:
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=/run/secrets/wt_token 
    secrets:
      - wt_token
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

secrets:
  wt_token:
    file: ../secrets/wt_token
```

/run/secrets/wt_token :
`RandomGeneratedBlobString`

### Steps to reproduce

1. To check if the token is set correctly I use wget:
` wget --header="Authorization: Bearer RandomGeneratedBlobString" --output-document - http://container_ip:8080/v1/metrics --debug`

2. The test fails with error message **HTTP/1.1 401 Unauthorized**

3. Check again with:`wget --header="Authorization: Bearer /run/secrets/wt_token" --output-document - http://container_ip:8080/v1/metrics --debug`

4. Test **OK** and information printed

### Expected behavior

I expect that the WATCHTOWER_HTTP_API_TOKEN would be populated with the value inside the secrete file and not the path to it.

### Environment

- Debian 6.1.137-1 (2025-05-07) x86_64 GNU/Linux

- Docker version 28.2.2, build e6534b4

### Your logs

```text
time="2025-06-06T16:45:21+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."

time="2025-06-06T16:45:22+02:00" level=debug msg="Making sure everything is sane before starting"

time="2025-06-06T16:45:22+02:00" level=debug msg="Retrieving running and restarting containers"

time="2025-06-06T16:45:22+02:00" level=debug msg="There are no additional watchtower containers"

time="2025-06-06T16:45:22+02:00" level=info msg="Watchtower 1.7.1"

time="2025-06-06T16:45:22+02:00" level=info msg="Only checking containers using enable label"

time="2025-06-06T16:45:22+02:00" level=info msg="Scheduling first run: 2025-06-07 02:45:22 +0200 CEST"

time="2025-06-06T16:45:22+02:00" level=info msg="Note that the first check will be performed in 24 hours, 59 minutes, 59 seconds"
```
