### ISSUE TITLE
Failed to send notification email...no such host

### ISSUE THREAD

**Issue by bendwyer** [containrrr/watchtower#220]
My `watchtower` container is able to successfully update the other containers in my environment, but cannot seem to send the notification emails. I'm using G Suite's built-in SMTP relay to attempt to send the messages.

`Failed to send notification email:  dial tcp: lookup stmp-relay.gmail.com on 127.0.0.11:53: no such host`

This is the `docker-compose.yml` that I used to build the container.
```
version: '3.5'

services: 
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --schedule "0 0 4 * * *" --cleanup
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=from_email@domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=to_email@domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=stmp-relay.gmail.com
```
