### ISSUE TITLE
How to access debug level logs when using Docker Compose

### ISSUE THREAD

**Issue by lokeshh** [containrrr/watchtower#231]
I'm using Docker Compose and want to see the debug level logs for watchtower. How can I do that? I know there's an option `--debug` but can it be used with docker compose?

**Comment by lokeshh** [comment]
I just found out that it can be done with `command: --debug`. For example

```
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      --interval 10 --debug

```

Resolved!
