### ISSUE TITLE
Could watchtower refresh the env variables from .env file?

### ISSUE THREAD

**Issue by lokeshh** [containrrr/watchtower#233]
My `docker-compose.yml` looks as follows:
```
version: '3'
services:
  myimage:
    build: .
    privileged: true
    network_mode: host
    restart: unless-stopped
    env_file:
      - env.env
  watchtower:
    image: v2tec/watchtower:0.3.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      --interval 30
    environment:
      - REPO_USER=_json_key
      - REPO_PASS=xxx

```

When I run `docker-compose up`, it loads the environment variables from `my.env` to my container. Is it possible that when watchtower updates the container, the environment variables are reloaded from `my.env`?
