### ISSUE TITLE
Slack notifications not working with error: Failed to fire hook: Post : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by jeremiahkjones** [containrrr/watchtower#245]
Watchtower is working great, minus Slack notifications.

I've already reviewed Issue #177 but the resolution of not including quotes is not solving the problem for me.  Here is the compose section:
```
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    command: --interval 30
    environment:
      WATCHTOWER_NOTIFICATIONS: ${WATCHTOWER_NOTIFICATIONS:-slack}
      WATCHTOWER_NOTIFICATIONS_SLACK_IDENTIFIER: ${WATCHTOWER_NOTIFICATIONS_SLACK_IDENTIFIER:-watchtower}
      WATCHTOWER_NOTIFICATIONS_SLACK_HOOK_URL: # Read from host environment
```
I've already verified (and triple-checked) that the WATCHTOWER_NOTIFICATIONS_SLACK_HOOK_URL is being passed through to the compose file correctly (via docker-compose config).  I've also confirmed that there are no quotes around the URL (the resolution proposed in issue #177).  I've also confirmed that the webhook works outside of watchtower.

I've also removed any references to host environment variables and "hard-coded" the proper values in my compose file, but that did not work either.

Here is a complete log from a recent update indicating that watchtower is working/running, but notifications never go out.
```
watchtower_1                | Failed to fire hook: Post : unsupported protocol scheme ""
watchtower_1                | time="2018-11-29T07:44:18Z" level=info msg="Found new ****:latest image (sha256:****)"
watchtower_1                | Failed to fire hook: Post : unsupported protocol scheme ""
watchtower_1                | time="2018-11-29T07:44:21Z" level=info msg="Stopping /****_1 (****) with SIGTERM"
watchtower_1                | Failed to fire hook: Post : unsupported protocol scheme ""
watchtower_1                | time="2018-11-29T07:44:31Z" level=info msg="Creating /****_1"
```
