### ISSUE TITLE
BUG: "--interval value" or "-i 30" doesn't works in docker compose

### ISSUE THREAD

**Issue by SeLoRBIS** [containrrr/watchtower#248]
When I add 3 commands in my docker-compose file one of the 3 doesn't works : --interval value or -i value
The docker-compose looks like : 
```
watchtower:
    container_name: watchtower-home
    image: v2tec/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.watchtower.env
    command: ["--cleanup", "--label-enable", "--interval 30"]
    restart: always
```

The error message is : 
`... level=fatal msg="flag provided but not defined: -interval 30"` 
or 
`... level=fatal msg="flag provided but not defined: -i 30"`
