### ISSUE TITLE
What are the specific requirements for Watchtower to run on Synology DSM?

### ISSUE THREAD

**Issue by rfgamaral** [containrrr/watchtower#252]
My question is relative to the need to symlink `/var/run/docker.sock` to `/volume1/docker/docker.sock` because per the Wiki:

> Synology Docker GUI will not be able to run it when it's pointed directly to `/var/run/docker.sock`

However, this is not true for my Synology. I'm running the latest DSM 6.2 (at the time of writing) instead of 6.0/6.1 (as the Wiki states). In other words, I'm creating my container with the volume `/var/run/docker.sock:/var/run/docker.sock` without any issues. I can stop/start the watchtower container via the Synology GUI, I can restart my Synology and everything keeps working as expected.

Should the Wiki be updated to mention this is no longer an issue with DSM 6.2 or is something else going on with my NAS making this thing working without the symlink?

**Comment by boexler** [comment]
Could you provide your docker-compose.yml file? 

```
 watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: watchtower synology-docker-radicale-server --interval 1
    restart: unless-stopped

```

```
watchtower_watchtower_1 is up-to-date
Attaching to watchtower_watchtower_1
watchtower_1  | WARNING: no logs are available with the 'db' log driver
```

This is my output and the watchtower is not updating or doing anything..

**Comment by rfgamaral** [comment]
I don't use `docker-compose.yml` I ran this directly through SSH:

```
docker run -d \
    --name watchtower \
    --restart always \
    --network host \
    -v /var/run/docker.sock:/var/run/docker.sock \
    v2tec/watchtower -i 43200
```

**Comment by niXta1** [comment]
> I don't user `docker-compose.yml` I ran this directly through SSH:
> 
> ```
> docker run -d \
>     --name watchtower \
>     --restart always \
>     --network host \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     v2tec/watchtower -i 43200
> ```
I do the same, -v /var/run/docker.sock:/var/run/docker.sock on DSM 6.2. No issues, been running like this for a long time.

**Comment by nairbspace** [comment]
My last Synology setup I haven't had to do anything either, but I have in the past. I've had some weird issues with Synology's version of Docker or how Synology handles users/groups since it is done by `synouser` and `synogroup` commands. I've had permission errors with the symbolic link too and was better off changing the group owner of the `docker.sock` to the `docker` group via `chown root:docker /var/run/docker.sock` and creating a task scheduler for it since things would usually break on update or restart.

Might be best to change it from an install guide to a troubleshooting guide for Synology users in case people still run into it or things change on an update.

**Comment by boexler** [comment]
Here is my `docker-compose.yml`. I'm runing a `DS918+` with `DSM 6.2`

```
version: '2'
services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: v2tec/watchtower
    environment: 
    - TZ=Europe/Berlin
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1000 --cleanup --label-enable
```
