### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by nickelghost** [containrrr/watchtower#257]
Hi, I just installed watchtower for the first time, but it does not want to update my private container from docker registry. I'm getting the following error:
```
time="2019-02-27T22:24:08Z" level=info msg="Unable to update container /nickelghost, err='Error response from daemon: pull access denied for nickelghost/nickelghost.com, repository does not exist or may require 'docker login''. Proceeding to next."
```
multiple times when I want to see the logs. Everything works fine if I use docker from cli. This is the watchtower part of my docker-compose:
```
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
```

**Comment by matthewhaworth** [comment]
I'm also having this issue.

**Comment by Grouen** [comment]
try start watchtower with those environment parameters  REPO_USER='username', REPO_PASS='password'.

**Comment by matthewhaworth** [comment]
I'll give that a go, but it doesn't feel very secure :(

**Comment by matthewhaworth** [comment]
It worked! Just a shame I have to have password details on the command line.

**Comment by simonaronsson** [comment]
As stated in the readme, if you're using that setup; you also need to make sure that you use the full image name on your containers that are using private images.

Example from https://github.com/containrrr/watchtower#usage:
```
version: "3"
services:
  cavo:
    image: index.docker.io/<org>/<image>:<tag>
    ports:
      - "443:3443"
      - "80:3080"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
```

If you've already tried that and still are unable to get it to work; let me know.
