### ISSUE TITLE
Supported params in drud/watchtower

### ISSUE THREAD

**Issue by TheCodeDestroyer** [containrrr/watchtower#27]
Hey!

So far I have only seen that it supports --debug, I tried interval, but it doesn't seem to work.
Is this image stripped of the params the common params or am I doing something wrong?

P.S.: I tried to search for drud/watchtower repo and I couldn't find it, altho I have seen PRs from that one...

**Comment by leftcoastgeek** [comment]
+1 I've tried interval and it did not work for me either
running  `docker-compose -f docker-compose-watchtower.yml up --remove-orphans`

```yaml
watchtower:
  image: centurylink/watchtower
  environment:
    - REPO_USER="user" 
    - REPO_PASS="pass" 
    - REPO_EMAIL="email@email.com"
  command: >  
    mongo
    testprivaterepo
    --interval "30"
    --cleanup
    --debug
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
```
