### ISSUE TITLE
No logs and containers not being updated

### ISSUE THREAD

**Issue by Nottt** [containrrr/watchtower#288]
Hi, I use a ansible role to deploy watchtower to my server, however I notice there is no logs with `docker logs watchtower`, zero output. 

And my containers are not also being updated... I know this because one of the dockers I use changed their dockerfile and it did not update.

```
- name: Create container
  docker_container:
    name: watchtower
    image: "containrrr/watchtower"
    pull: yes
    command: “--cleanup --stop-timeout 90s --debug”
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - watchtower
    purge_networks: yes
    restart_policy: always
    state: started
```

What could be causing this?
