### ISSUE TITLE
Email via internal SMTP Server

### ISSUE THREAD

**Issue by truncsphere** [containrrr/watchtower#338]
I have an internal SMTP server that I'm attempting to use for email, but it is failing to send. Are IP's as SMTP servers supported? 
The error is: `Failed to send notification email:  dial tcp :25: connect: connection refused`

Config:

```yaml
version: "3"
services:
 watchtower:
  image: containrrr/watchtower
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  restart: unless-stopped
  container_name: watchtower
  command: --cleanup
  environment:
   - WATCHTOWER_NOTIFICATIONS=email
   - WATCHTOWER_NOTIFICATIONS_EMAIL_FROM=email@email
   - WATCHTOWER_NOTIFICATIONS_EMAIL_TO=email@email
   - WATCHTOWER_NOTIFICATIONS_EMAIL_SERVER=192.168.X.X
   - WATCHTOWER_NOTIFICATIONS_EMAIL_SERVER_PORT=25
```
