### ISSUE TITLE
Unable to Update Containers - Timeout

### ISSUE THREAD

**Issue by IwanSE** [containrrr/watchtower#361]
Hi, I have the same problems with #192
We use Nexus OSS 3.17.0-01
```
time="2019-08-06T04:15:04Z" level=debug msg="Error pulling image 172.22.130.59:8083/docker-repository/frontend:1.0.1-SNAPSHOT, Error response from daemon: Get http://172.22.130.59:8083/v2/docker-repository/frontend/manifests/1.0.1-SNAPSHOT: dial tcp 172.22.13
0.59:8083: i/o timeout"
time="2019-08-06T04:15:04Z" level=info msg="Unable to update container /frontend. Proceeding to next."
time="2019-08-06T04:15:04Z" level=debug msg="Error response from daemon: Get http://172.22.130.59:8083/v2/docker-repository/frontend/manifests/1.0.1-SNAPSHOT: dial tcp 172.22.130.59:8083: i/o timeout"
time="2019-08-06T04:15:34Z" level=debug msg="Got image name: 172.22.130.59:8083/docker-repository/master-data:1.0.1-SNAPSHOT"
time="2019-08-06T04:16:04Z" level=debug msg="Error pulling image 172.22.130.59:8083/docker-repository/master-data:1.0.1-SNAPSHOT, Error response from daemon: Get http://172.22.130.59:8083/v2/docker-repository/master-data/manifests/1.0.1-SNAPSHOT: dial tcp 172
time="2019-08-06T04:35:49Z" level=debug msg="Error pulling image 172.22.130.59:8083/ts-docker-repository/ts-auth-service:1.0.1-SNAPSHOT, Error response from daemon: Get http://172.22.130.59:8083/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
.22.130.59:8083: i/o timeout"
```
My Dockerfile and docker-compose.yml
```
FROM containrrr/watchtower

ARG webhook

ENV WATCHTOWER_NOTIFICATIONS=slack
ENV WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${webhook}
ENV WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower
ENV WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#my-channel

ADD config.json /
```
```yml
  watchtower:
    image: 172.22.130.59:8083/docker-repository/watchtower
    container_name: watchtower
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: frontend master-data --cleanup --interval 60
```
Changed timeout to 180 in Nexus
This did not solve the problem 
`time="2019-08-06T04: 15: 04Z "level = info msg =" Unable to update container /frontend. Proceeding to next."`
Any ideas to solve this problem? Many messages come to Slack:
```
watchtowerAPP 9:23 AM
Unable to update container / api-gateway. Proceeding to next.
Unable to update container / authentication-service. Proceeding to next.
Unable to update container / frontend. Proceeding to next.
```

**Comment by unstephenk** [comment]
I am also seeing this error. I do believe watchtower also updated recently. This should be high priority. What broke?

**Comment by simonaronsson** [comment]
@iwanhsky thank you for your report! if you run watchtower directly without using your own Dockerfile - do you still get the same error? That is, using containrrr/watchtower:latest instead.

> I am also seeing this error. I do believe watchtower also updated recently. This should be high priority. What broke?

The last release was July 2nd. Have you been experiencing this since then? Any more details?

**Comment by unstephenk** [comment]
@simskij I am not currently using a Dockerfile to run WT. I am using the docker run command in the docs with a restart always tag.

**Comment by simonaronsson** [comment]
@Unstephenk yeah, that part was not aimed towards you. Still cueious when it started happening for you though

**Comment by unstephenk** [comment]
Started over the weekend when no one was in office at 2am. It had been running great for 5 days prior. All of a sudden, got a ton of messages on slack for each container saying `Unable to update container /watchtower. Proceeding to next` so there was still an internet connection present.

**Comment by simonaronsson** [comment]
I've just run through a couple of complete runs, both with and without having any updates available and sadly, I can't provoke any error messages to appear. Everything just seems to work. The config I'm using in my local lab:

```
watchtower:
    <<: *keep-up
    container_name: watchtower
    image: index.docker.io/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/watchtower/config.json:/config.json
    command: --interval 30 --label-enable --cleanup
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/x/y/z
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower
```

where keep-up is:
```
  x-common: &keep-up
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```
One thing I come to think of is that the image pulls are actually performed by the docker daemon rather than by watchtower, while the notifications are being sent directly from watchtower. Are you able to pull images directly from your docker host?

A restart of the host could be a way to resolve this. I understand though if a restart isn't feasible if you run watchtower in a server environment. Also, any other changes or updates to the actual docker host?

One thing to note is that Docker Engine 19.03.1 was released little more than a week ago. One of the known issues of that release ([source here](https://docs.docker.com/engine/release-notes/#19031)) is described like this:

> Traffic cannot egress the HOST because of missing Iptables rules in the FORWARD chain The missing rules are :
>
> `/sbin/iptables --wait -C FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`
>
> `/sbin/iptables --wait -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`
>
> Workaround: Add these rules back using a script and cron definitions. The script must contain ‘-C’ commands to check for the presence of a rule and ‘-A’ commands to add rules back. Run the script on a cron in regular intervals, for example, every minutes.

And I'm still on 18.09.6, which might explain why it works flawlessly for me.
