### ISSUE TITLE
docker-compose  Best Practices ?

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#369]

**Comment by ghost** [comment]
Docker version 19.03.1, build 74b1e89
macos mojave 10.14.6




my docker-compose.yml

```
version: "3"
services:
  xxxx1:
    image: registry.xxx.com/xxx/xxxx1
    ports:
      - "443:443"
      - "80:80"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --debug
```

my docker `config.json`

```
{
	"auths": {
		"registry.xxx.com": {
			"Username": "xxxx",
			"Secret": "xxxxx"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.1 (darwin)"
	},
	"credsStore": "osxkeychain"
}

```


i got error
```
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="Checking containers for updated images"
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="Retrieving running containers"
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="Pulling containrrr/watchtower:latest for /docker2drone_watchtower_1"
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="No credentials for containrrr in /config.json"
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="Got auth value: "
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="Got image name: containrrr/watchtower:latest"
watchtower_1  | time="2019-08-14T11:11:07Z" level=debug msg="No authentication credentials found for containrrr/watchtower:latest"
watchtower_1  | time="2019-08-14T11:11:13Z" level=debug msg="No new images found for /docker2drone_watchtower_1"
watchtower_1  | time="2019-08-14T11:11:13Z" level=debug msg="Pulling registry.xxx.com/xxx/xxxx1:latest for /docker2drone_xxxx1_1"
watchtower_1  | time="2019-08-14T11:11:13Z" level=debug msg="Loaded auth credentials {    registry.xxx.com  } from /config.json"
watchtower_1  | time="2019-08-14T11:11:13Z" level=debug msg="Got auth value: eyJzZXJ2ZCJhZGRyZXNzIjoiccmVnaXN0ccuY24taGFaZ3pob3UuYWxpeXVuY3MuY29tIn0="
watchtower_1  | time="2019-08-14T11:11:13Z" level=debug msg="Got image name: registry.xxx.com/xxx/xxxx1:latest"
watchtower_1  | time="2019-08-14T11:11:14Z" level=debug msg="Error pulling image registry.xxx.com/xxx/xxxx1:latest, Error response from daemon: pull access denied for registry.xxx.com/xxx/xxxx1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
watchtower_1  | time="2019-08-14T11:11:14Z" level=info msg="Unable to update container /docker2drone_xxxx1_1. Proceeding to next."
watchtower_1  | time="2019-08-14T11:11:14Z" level=debug msg="Error response from daemon: pull access denied for registry.xxx.com/xxx/xxxx1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
watchtower_1  | time="2019-08-14T11:11:14Z" level=debug msg="This is the watchtower container /docker2drone_watchtower_1"
watchtower_1  | time="2019-08-14T11:11:14Z" level=debug msg="Scheduled next run: 2019-08-14 11:11:37 +0000 UTC"
```
