### ISSUE TITLE
Gotify notifications and docker-compose

### ISSUE THREAD

**Issue by foxbit19** [containrrr/watchtower#390]
I've used watchtower with gotify notifications and docker-compose. The documentation shows how to write env variables' values, expecially URLs, using double quotes.
This not working as expected with docker-compose, due the nature of YAML file.

With gotify notifications, watchtower shows me an error:
```bash
Gotify URL must start with \"http://\" or \"https://\"
```

(the `\"` escape doesn't work as expected in docker-compose logs)

I suggest to refactor the prefix check method on gotify notification extension. Maybe we could trim down double quotes chars.

As an alternative, we could add a little section on top of the notifications doc page to avoid ambiguity between cmdline and docker-compose runs.

This is a low level priority improvement that I can handle.

**Comment by simonaronsson** [comment]
Thank you for the report!
Feel free to go with whichever direction you prefer. With that said: As the notification feature as a whole will be replaced with shoutrrr in the upcoming future, adding a nota bene to the documentation might be a reasonable choice.

**Comment by foxbit19** [comment]
#392

**Comment by simonaronsson** [comment]
Closing due to lack of activity. Feel free to make sure your feature request is covered in shoutrrr, as we're migrating all notifications as soon as possible.

**Comment by AtlanGon** [comment]
I have got the same problem.

**Comment by timdonovanuk** [comment]
@foxbit19 so how do you get this working in compose? An example would be helpful.

Edit: solved.

Ok so I did see the notice about not using " around vars but the error specifically says:

`Gotify URL must start with \"http://\" or \"https://\""`

But the code checks:

`else if !(strings.HasPrefix(gotifyURL, "http://") || strings.HasPrefix(gotifyURL, "https://")) {`

The error message is truly baffling, I'm not sure what hot mess this is supposed to be telling the users in the warning **\\"http://\\"** but if you just do 

`WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://192.168.1.1:9020`

it works. Thanks.

**Comment by timdonovanuk** [comment]
I've even tried "\\\http:\/\/\\\ - it should not be this hard to add a variable into a compose file :) Please just parse this var like normal!

**Comment by AtlanGon** [comment]
This worked for me:
```
version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      #- WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://<URL>/
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=...
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
