### ISSUE TITLE
Watchtower Proxy server

### ISSUE THREAD

**Issue by matt-horwood-mayden** [containrrr/watchtower#394]
Afternoon,

I have Watchtower setup on a host that has access to the docker hub via a proxy server, docker is now working with the proxy server. but Watchtower has an error.

```
time="2019-10-21T11:40:35Z" level=info msg="Unable to update container /machinelearning_sapiofrontend_1. Proceeding to next."
time="2019-10-21T11:40:36Z" level=info msg="Unable to update container /machinelearning_sapiointerventioninsights_1. Proceeding to next."
time="2019-10-21T11:45:35Z" level=info msg="Unable to update container /machinelearning_sapiofrontend_1. Proceeding to next."
time="2019-10-21T11:45:36Z" level=info msg="Unable to update container /machinelearning_sapiointerventioninsights_1. Proceeding to next."
time="2019-10-21T11:50:35Z" level=info msg="Unable to update container /machinelearning_sapiofrontend_1. Proceeding to next."
time="2019-10-21T11:50:36Z" level=info msg="Unable to update container /machinelearning_sapiointerventioninsights_1. Proceeding to next."
time="2019-10-21T11:55:35Z" level=info msg="Unable to update container /machinelearning_sapiofrontend_1. Proceeding to next."
time="2019-10-21T11:55:36Z" level=info msg="Unable to update container /machinelearning_sapiointerventioninsights_1. Proceeding to next." 
```

I dont know if the error is the result of a private repo or the proxy server.

The compose lines
```
  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      - http_proxy=http://<IP>:3128
      - https_proxy=http://<IP>:3128
      - HTTP_PROXY=http://<IP>:3128
      - HTTPs_PROXY=http://<IP>:3128
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/<user>/.docker/config.json:/config.json
```

config.json
```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "<AUTH_KEY>"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.3 (linux)"
        },
        "proxies": {
                "default": {
                        "httpProxy": "http://<IP>:3128",
                        "httpsProxy": "http://<IP>:3128"
                }
        }
}
```
