### ISSUE TITLE
unable to update container with a hard image reference

### ISSUE THREAD

**Issue by jwaes** [containrrr/watchtower#396]
When i use a 'hard reference to an image in my docker-compose file

```
version: '2'
services:
  web:
    image: sha256:5ee30a7dd6fb5c9581af1f42fd9bfb9164bae461dbf7f5dc8a36f87a528eb21a

```
I get this info message polluting my logs:

`time="2019-10-25T08:26:44Z" level=info msg="Unable to update container /odoo_web_1. Proceeding to next."`

I think this is redundant as with a hard reference it is logical and intended that it cannot be updated.
