### ISSUE TITLE
Updating portainer

### ISSUE THREAD

**Issue by kevindd992002** [containrrr/watchtower#402]
**Describe the bug**
Everytime the portainer/portainer:latest docker image gets updated, I get this error in the watchtower email notification logs:

2019-10-12 06:01:12 (info): Found new portainer/portainer:latest image (sha256:4cda95efb0e455c3044d727988c36c5947a4287f77db96e799199b349b3d523c)
2019-10-12 06:01:15 (info): Executing pre-update command.
2019-10-12 06:01:15 (error): Command exited with code 126.
2019-10-12 06:01:15 (error): OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
2019-10-12 06:01:15 (info): Stopping /portainer (3e0704fb85d1141eadeccbea7fb074f0f498d466e1e73edde4a5373e0256b022) with SIGTERM
2019-10-12 06:01:22 (info): Creating /portainer
2019-10-12 06:01:22 (info): Removing image sha256:2b4ddf654e1c413b21c7253125aa0f34a4ff74154558940fa689f8754ec853c5

But everything seems to be working properly with portainer. What does this mean and why is there an error? 

**Expected behavior**
No errors.

**Environment**
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by kevindd992002** [comment]
Any help here?

**Comment by simonaronsson** [comment]
Thank you for the report! 🙏🏼 I'll have a look at this as soon as possible. The error seems to be because of a pre-update command being executed.

Would you mind pasting relevant parts of your docker-compose.yml or the docker run command you're using to create the containers? Preferably for both watchtower and portainer. We fixed a bug related to lifecycle hooks recently, but I don't think it;s been released yet.

**Comment by kevindd992002** [comment]
Thanks! Sure, here you go:

```
  portainer:
    image: portainer/portainer
    container_name: portainer
    depends_on:
      - pihole
    volumes:
      - /home/kevin/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Manila
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    depends_on:
      - pihole
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --debug
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Manila
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${MAILFROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${MAILTO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${MAILSERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${MAILUSERNAME}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${MAILPASSWORD}
```
