### ISSUE TITLE
Unable to update container when a container raise error 

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#407]
sorry my english is not well

**Describe the bug**
i have 3 containers

# docker-compose.yml

```
version: "3"
services:
  aa: 
    image: registry-xxxx.com/xxx/aa
    restart: always
    expose:
      - 8000/tcp
  bb:
    image: registry-xxxx.com/xxx/bb
    restart: always
    expose:
      - 8009/tcp
  cc:
    image: registry-xxxx.com/xxx/cc
    restart: always
    expose:
      - 8005/tcp
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/aaa/.docker/config.json:/config.json
    command: --interval 30
```
 
when one container raise error, then   this container can't to update 

**To Reproduce**
1. when i push a new bad code to  container aa (the new bad code will be raise a error)
  **like this:**
![image](https://user-images.githubusercontent.com/6580897/68990803-6fabd100-0892-11ea-893e-98b0fe50d4ed.png)

2. then i push a new right code to container aa (the new code is  right), but watchtower can't update the container aa
 

**Expected behavior**
i hope that when  container raise error, then when i push a new right code , watchtower can to get new container

 
**Environment**
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 8
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-54-generic
 Operating System: Ubuntu 18.04.1 LTS
 OSType: linux
 Architecture: x86_64

 
chinese version:
你好， 我有3个容器，分别是aa，bb，cc

一开始这3个容器工作的很好

但是我当推送了错误的代码到容器aa，导致容器aa 因为错误而退出了

接着，我立刻推送了新的正确代码到容器aa，可是 watchtower 却无法 拉取到新的容器aa

我希望，当容器aa遇到错误代码崩溃后，还是可以在后台不断请求 新的容器aa 

因为在新的容器aa上，我解决了 错误
