### ISSUE TITLE
Do not send emails every time watchtower is up?

### ISSUE THREAD

**Issue by auanasgheps** [containrrr/watchtower#443]
Hi all,
Since last update, Watchtower sends an email every time it is started and running. **I do not want this**. My server turns off and on multiple times a day and I get spammed with emails that have no utility. My goal is to go back to the previous state: send an email **only** when updates are found.

Here's is my docker-compose file. Am I missing something?
Thanks

```
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
    environment:
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=<PRIVATE>
        - WATCHTOWER_NOTIFICATION_EMAIL_TO=<PRIVATE>
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=<PRIVATE>
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=<PRIVATE>
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<PRIVATE>
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
        - WATCHTOWER_SCHEDULE=0 0 0 * * *
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_TIMEOUT=30s
        - WATCHTOWER_NOTIFICATIONS_LEVEL=info
    networks:
        default:
networks:
    default:
        external: 
            name: mynet  
```
