### ISSUE TITLE
Help identifying this error please

### ISSUE THREAD

**Issue by xbmcnut** [containrrr/watchtower#458]
Hi there,
I've been using WT for a while now in a compose file and while it works most of the time, occassionally I get the following as I did this morning.
```
2020-02-27 17:55:34 (info): Unable to update container /unifi. Proceeding to next.
2020-02-27 17:55:39 (info): Unable to update container /home-assistant. Proceeding to next.
2020-02-27 17:55:54 (info): Unable to update container /tasmoadmin. Proceeding to next.
2020-02-27 17:55:59 (info): Unable to update container /eclipse-mosquitto. Proceeding to next.
```
Upon running docker logs watchtower, I see lots of errors:
```
time="2020-02-27T21:10:19Z" level=debug msg="Retrieving running containers"
time="2020-02-27T21:10:19Z" level=debug msg="Pulling jacobalberty/unifi:latest for /unifi"
time="2020-02-27T21:10:19Z" level=debug msg="No credentials for jacobalberty in /config.json"
time="2020-02-27T21:10:19Z" level=debug msg="Got auth value: "
time="2020-02-27T21:10:19Z" level=debug msg="Got image name: jacobalberty/unifi:latest"
time="2020-02-27T21:10:19Z" level=debug msg="No authentication credentials found for jacobalberty/unifi:latest"
time="2020-02-27T21:10:22Z" level=debug msg="No new images found for /unifi"
time="2020-02-27T21:10:22Z" level=debug msg="Pulling homeassistant/home-assistant:latest for /home-assistant"
time="2020-02-27T21:10:22Z" level=debug msg="No credentials for homeassistant in /config.json"
time="2020-02-27T21:10:22Z" level=debug msg="Got auth value: "
time="2020-02-27T21:10:22Z" level=debug msg="Got image name: homeassistant/home-assistant:latest"
time="2020-02-27T21:10:22Z" level=debug msg="No authentication credentials found for homeassistant/home-assistant:latest"
time="2020-02-27T21:10:26Z" level=debug msg="No new images found for /home-assistant"
```
Anyone know what is going on? My config.json file is empty.

Here is my compose file running on a Synology NAS
```
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --debug true --cleanup true eclipse-mosquitto home-assistant tasmoadmin unifi #--label-enable #--interval 30
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
```
Any advice would be appreciated.
