### ISSUE TITLE
no-startup-message ignored with run-once

### ISSUE THREAD

**Issue by aneisch** [containrrr/watchtower#472]
**Describe the bug**
Startup log still shown when --run-once used in conjunction with --no-startup-message

**To Reproduce**
1. Use --no-startup-message
2. Use --run-once

**Expected behavior**
One-shot run with no startup message

**Environment**
 - Platform
 - Architecture
 - Docker version 

**Logs from running watchtower with the `--debug` option**

**Additional context**

**Comment by mbrandau** [comment]
@aneisch What message are you seing? Is it `Running a one time update.`?

**Comment by aneisch** [comment]
Docker log:
```
Recreating watchtower ... done
Attaching to watchtower
watchtower           | time="2020-03-26T10:47:42-05:00" level=info msg="Running a one time update."
watchtower exited with code 0
```

Email notification:
```
2020-03-26 10:47:42 (info): Running a one time update.
```
Compose config:
```
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
        restart: 'no'
        environment:
          - WATCHTOWER_NO_STARTUP_MESSAGE=true
          - WATCHTOWER_MONITOR_ONLY=true
          - WATCHTOWER_NOTIFICATIONS_LEVEL=info
          #- WATCHTOWER_DEBUG=true
          - WATCHTOWER_INCLUDE_STOPPED=true
          - WATCHTOWER_NOTIFICATIONS=email
          - WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXX
          - WATCHTOWER_NOTIFICATION_EMAIL_TO=XXX
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXX
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXX
          - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
        command: --no-startup-message --run-once
```
