### ISSUE TITLE
Failed to send notification email:  504 5.7.4 Unrecognized authentication type

### ISSUE THREAD

**Issue by deeztek** [containrrr/watchtower#474]
trying to get e-mail notifications to work with the following config:

```
version: '3'

services:
   watchtower:
      container_name: watchtower
      restart: always
      image: containrrr/watchtower
      environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=someone@domain.tld
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=someelse@domain.tld
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=host.domain.tld
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=email_username
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=email_password
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - TZ=America/New_York
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      command: --debug --interval 300 --cleanup --label-enable
```

However I'm getting the following error:
`Failed to send notification email:  504 5.7.4 Unrecognized authentication type`

I'm guessing this is a smtp auth TLS type of issue. I didn't see an option to set TLS or SSL in watchtower.

I would appreciate some help.
