### ISSUE TITLE
WATCHTOWER_MONITOR_ONLY=true still pulls latest image

### ISSUE THREAD

**Issue by aneisch** [containrrr/watchtower#478]
**Describe the bug**
Despite WATCHTOWER_MONITOR_ONLY=true environmental variable, watchtower still pulls new image. 

**To Reproduce**
compose file:
```
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
        restart: 'no'
        environment:
          - WATCHTOWER_NO_STARTUP_MESSAGE=true
          - WATCHTOWER_MONITOR_ONLY=true
          - WATCHTOWER_NOTIFICATIONS_LEVEL=info
          - WATCHTOWER_DEBUG=true
          - WATCHTOWER_INCLUDE_STOPPED=true
        command: --schedule "00 00 * * * *"
```
**Expected behavior**
Notification of new image available in repo, not a pull of the image

**Screenshots**

**Environment**
 - Platform
 - Architecture
 - Docker version 

**Logs from running watchtower with the `--debug` option**

**Additional context**
