### ISSUE TITLE
Error "incorrect username or password" when pulling a private repo from docker hub

### ISSUE THREAD

**Issue by thomaslule** [containrrr/watchtower#496]
Hello 👋 

**Describe the bug**
When watchtower tries to pull a private repo from docker-hub, authentication doesnt work by sharing the `.docker/config.json` file.

It works using the `REPO_USER` / `REPO_PASS` env variables with same username/password.

**To Reproduce**
1. `docker login --username <your docker id>`
2. check that the `.docker/config.json` file is created with the correct value under `"auths"."https://index.docker.io/v1/"`
3. watchtower docker-compose config:
```
  watchtower:
    image: containrrr/watchtower:latest
    command: --interval 60 --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/.docker/config.json:/config.json
  my-private-service:
    image:  index.docker.io/thomaslule/my-private-image:latest
```
4. Image is not pulled, in logs we can read:
```
level=debug msg="Loaded auth credentials {thomaslule [REDACTED] https://index.docker.io/v1/  } from /config.json",
level=debug msg="Got image name: index.docker.io/thomaslule/my-private-image:latest",
level=debug msg="Got auth value: [REDACTED]",
level=debug msg="Error pulling image index.docker.io/thomaslule/my-private-image:latest, Error response from daemon: Get https://registry-1.docker.io/v2/thomaslule/my-private-image/manifests/latest: unauthorized: incorrect username or password",
level=info msg="Unable to update container /raspi_my-private-service_1. Proceeding to next.",
level=debug msg="Error response from daemon: Get https://registry-1.docker.io/v2/thomaslule/my-private-image/manifests/latest: unauthorized: incorrect username or password",
```

**Expected behavior**
It should auto-pull new images.

**Environment**
 - Platform: Linux raspbian
 - Architecture: ARM
 - Docker version: 19.03.8

**Additional context**
Workaround: instead of sharing the `config.json` file, I set the `REPO_USER` / `REPO_PASS` env variables, this way it works.
