### ISSUE TITLE
Watchtower is stuck - "Waiting for running update to be finished"

### ISSUE THREAD

**Issue by auanasgheps** [containrrr/watchtower#498]
**Describe the bug**
Watchtower prints in logs `Waiting for running update to be finished...` and does nothing. I know there are containers to be updated, but it's stuck.

I've tried killing/stopping/rebooting the container, it doesn't help. It just prints again the same error.

The issue is "fixed" by recreating the container and deleting its internal data.

My docker-compose

```yaml
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
    environment:
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=foo
        - WATCHTOWER_NOTIFICATION_EMAIL_TO=bar
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=thebestsmtpserver
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=blip
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=blop
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
        - WATCHTOWER_SCHEDULE=0 0 0 * * *
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_TIMEOUT=30s
        - WATCHTOWER_NOTIFICATIONS_LEVEL=info
        - WATCHTOWER_NO_STARTUP_MESSAGE=true
        - TZ=Europe/Rome
```

**To Reproduce**
I don't really know how to reproduce, I think it's a random issue.

**Expected behavior**
Watchtower should not be stuck.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/20586878/78944974-819b4400-7abf-11ea-9552-4ac7981b6d73.png)

**Environment**
 - Platform: Debian 10
 - Architecture: x64
 - Docker version: 19.03.8

**Logs from running watchtower with the `--debug` option**

**Additional context**
I think it's not the first time that happens.
