### ISSUE TITLE
Failed to send notification email

### ISSUE THREAD

**Issue by ogmueller** [containrrr/watchtower#508]
**Describe the bug**
When adding a postfix container as an SMTP, watchtower is not able to connect to it, even though other containers are. The log entry is:
```Failed to send notification email:  dial tcp 172.25.0.2:25: connect: connection refused```

**To Reproduce**
Just start up this docker-compose.yml and the error occurs. It also occurs with watchtower v0.3.11 and others.
```
version: "3.7"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      WATCHTOWER_MONITOR_ONLY: "true"
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: from@example.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: to@example.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: postfix
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postfix

  postfix:
    image: freinet/postfix-relay:latest
    expose:
      - 25
    environment:
      MAILNAME: mail.example.com
```

**Expected behavior**
No connection error.

**Environment**
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
```
 # docker --version
Docker version 19.03.8, build afacb8b7f0
```

**Logs from running watchtower with the `--debug` option**
```
# docker logs -f watchtower
time="2020-04-19T13:13:03+02:00" level=info msg="Running a one time update."
time="2020-04-19T13:13:03+02:00" level=debug msg="Checking containers for updated images"
time="2020-04-19T13:13:03+02:00" level=debug msg="Retrieving running containers"
Failed to send notification email:  dial tcp 172.25.0.2:25: connect: connection refused
time="2020-04-19T13:13:03+02:00" level=debug msg="Pulling containrrr/watchtower:latest for /watchtower"
time="2020-04-19T13:13:03+02:00" level=debug msg="No credentials for containrrr in /config.json"
time="2020-04-19T13:13:03+02:00" level=debug msg="Got image name: containrrr/watchtower:latest"
time="2020-04-19T13:13:03+02:00" level=debug msg="Got auth value: "
time="2020-04-19T13:13:05+02:00" level=debug msg="No new images found for /watchtower"
time="2020-04-19T13:13:05+02:00" level=debug msg="Pulling freinet/postfix-relay:latest for /watchtower_postfix_1"
time="2020-04-19T13:13:05+02:00" level=debug msg="No credentials for freinet in /config.json"
time="2020-04-19T13:13:05+02:00" level=debug msg="Got image name: freinet/postfix-relay:latest"
time="2020-04-19T13:13:05+02:00" level=debug msg="Got auth value: "
time="2020-04-19T13:13:06+02:00" level=debug msg="No new images found for /watchtower_postfix_1"
```

**Additional context**
Really important is, that if you are attaching another container to the network and try to send email via telnet, it does work.

Here is an example if it:

1. start netshoot container and attach to watchtower network
```docker run -it --rm --network container:watchtower nicolaka/netshoot```
2. connect to postfix
```
→ telnet postfix 25
Connected to postfix
220 mail.example.com ESMTP
```
3. send email with
```
helo test.com
mail from: <test@example.com>
rcpt to: <oliver@teqneers.de>
250 2.1.5 Ok
data
some text
.
```
Here is the output of that:
```
→ telnet postfix 25
Connected to postfix
220 mail.example.com ESMTP
helo test.com
250 mail.example.com
mail from: <test@example.com>
250 2.1.0 Ok
rcpt to: <some@example.com>
250 2.1.5 Ok
data
354 End data with <CR><LF>.<CR><LF>
some text
.
250 2.0.0 Ok: queued as 3E8F92DA7
```
It works, so I assume the general postfix and network setup should be ok.

**Comment by kevdogg** [comment]
@ogmueller - Have you tried sending mail on the command line from the watchtower container through the postfix email forwarder?

**Comment by ogmueller** [comment]
As far as I saw, there is no shell nor other tools in the image to actually try that out.

**Comment by simonaronsson** [comment]
> As far as I saw, there is no shell nor other tools in the image to actually try that out.

Correct. That would require you to customize the dockerfile to use alpine and build it yourself.

**Comment by ogmueller** [comment]
Ok, I've found the problem. Our certificates didn't match the docker container name and a connection was refused by the message:
`Failed to send notification email:  x509: certificate is valid for *.domain.com, not postfix`

It worked once I've added a network alias to the postfix container
```
    networks:
      watchtower:
        aliases:
          - smtp.domain.com
```
and used that alias in the watchtower container
```
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.domain.com
```

Even though I had turned on WATCHTOWER_DEBUG, this message was not shown. I had to build my own container using `dockerfiles/Dockerfile.dev-self-contained`. That one finally gave me the right hint.

I don't know the differences between the "normal" and "dev-self-contained" build version, but it would be very helpful to output those kind of errors with a normal (latest) version as well.
