### ISSUE TITLE
Failed to Send Notification via Gmail

### ISSUE THREAD

**Issue by kevdogg** [containrrr/watchtower#513]
Honestly I feel like I'm being a pain posting this here, however I didn't know where to post.

I'm using docker watchtower lastest version on an ubuntu host.
I have a registered gmail account and generated an app specific password.

On staring the watchtower docker container with email notifications, I getting the following error:
```
# docker logs watchtower
time="2020-04-24T11:26:10-05:00" level=info msg="First run: 2020-04-24 12:00:00 -0500 CDT"
Failed to send notification email:  530 5.7.0 Authentication Required. Learn more at
5.7.0  https://support.google.com/mail/?p=WantAuthError g133sm3995009qke.73 - gsmtp
```

Here is my docker-compose file with a few of the parameters changed.  I'm not sure if there is a typo but I've gone over the compose file a few times
```
  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    restart: always
    networks:
      - net
    command: --schedule "0 0 */4 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - DOCKER_AP_VERSION="1.40"
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=user@gohilton.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=user@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_SERVER_USER=user@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<app specific password>
```

Thanks for looking at the issue.
