### ISSUE TITLE
Does watchtower support setting password from docker secrets file?

### ISSUE THREAD

**Issue by kevdogg** [containrrr/watchtower#532]
Due to some of my other containers now requiring sensitive data be  passed through docker secret variables, I was wondering if watchtower supported use of docker secrets -- specifically:

Is there an equivalent of
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<password>  

with something similar to
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD_FILE=/run/secret/watchtower_notification_email_server_password_secret

From my testing, it doesn't seem like my notation with the docker secrets file specified works as I get an error message from the container that username/password not accepted by the smtp server.

**Comment by simonaronsson** [comment]
Hi @kevdogg,

Not currently, but I would be more than happy to assist with reviews and suggestions in case anyone would like to have a stab at providing a PR.

Best,
Simme

**Comment by tammert** [comment]
I will look into this! @kevdogg, would the `/run/secret/watchtower_notification_email_server_password_secret` file contain the plaintext password or do you expect a different format there?

**Comment by kevdogg** [comment]
It would contain the plaintext format.

**Comment by tammert** [comment]
PR is up :partying_face:

**Comment by kevdogg** [comment]
PR is up? Sorry I don't understand the meaning however I did checkout your link.  I believe this addition is still awaiting approval? I tried the following:

 ```
secrets:
  watchtower_notification_email_server_secret:
    file: ./watchtower_notification_email_server.secret

services:
  watchtower:
    image: containrrr/watchtower:latest
    ...
    ...
    environment:
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=/run/secrets/watchtower_notification_email_server_secret

```

but it didn't seem to work
