### ISSUE TITLE
docker-compose images aren't properly looked up

### ISSUE THREAD

**Issue by Miosame** [containrrr/watchtower#534]
Containers that got spawned via docker-compose, always have a folder prepended to their name, it seems watchtower assumes container / service name = image name, which obviously doesn't work, e.g.:

```
Error pulling image duplicati_duplicati:latest, Error response from daemon: pull access denied for duplicati_duplicati, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

"duplicati" being both the folder and the service name.

**Comment by victorcmoura** [comment]
Could you provide your docker-compose? I have never used Watchtower without docker-compose and it has been working correctly

**Comment by victorcmoura** [comment]
If you need an example, the docker-compose setup provided as an example in one of our docs is how I usually use Watchtower: https://github.com/containrrr/watchtower/blob/master/docs/http-api-mode.md

**Comment by Miosame** [comment]
It's not about the watchtower compose itself, it's detecting external containers that run in compose with their container names, assuming it's their image name, to be looked up in docker hub. 

I will post my docker compose of watchtower itself in a bit, once I am at my desktop, but I doubt that's the issue.

**Comment by victorcmoura** [comment]
If it fits your setup, it is ok to add watchtower in your compose, it doesn't require a separate one and will temporarily solve your problem. 

But I'll try to reproduce the bug anyway

**Comment by Miosame** [comment]
Isn't the point of watchtower to be able to keep all images up to date, adding it to all compose files seems.. odd?

**Comment by Miosame** [comment]
Here's my compose for watchtower

```
version: '3.3'
services:
  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      networks:
        ext-default:
            ipv4_address: xxxxxxx
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      environment:
        - WATCHTOWER_NOTIFICATIONS=gotify
        - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://xxxx
        - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=xxxx
        - WATCHTOWER_DEBUG=true
        - WATCHTOWER_RUN_ONCE=true
      labels:
        - "docker.group=xxx"

networks:
  ext-default:
    external:
      name: xxx
```

**Comment by victorcmoura** [comment]
> Isn't the point of watchtower to be able to keep all images up to date, adding it to all compose files seems.. odd?

It would detect multiple running instances and clean up all except the last. You are right, it was just a suggestion to solve your problem temporarily.

**Comment by victorcmoura** [comment]
I tried a setup with 2 composes:
```
version: '3'

services:
  python-watchtower-test:
    image: victorcmoura/python-watchtower-deployable
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
and
```
version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

Just ran both and it worked as expected:

```
watchtower_1  | time="2020-05-05T17:25:32Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
watchtower_1  | time="2020-05-05T17:25:33Z" level=debug msg="Retrieving running containers"
watchtower_1  | time="2020-05-05T17:25:33Z" level=debug msg="There are no additional watchtower containers"
watchtower_1  | time="2020-05-05T17:25:33Z" level=info msg="Starting Watchtower and scheduling first run: 2020-05-05 17:26:03 +0000 UTC m=+30.818342574"
watchtower_1  | time="2020-05-05T17:26:03Z" level=debug msg="Checking containers for updated images"
watchtower_1  | time="2020-05-05T17:26:03Z" level=debug msg="Retrieving running containers"
watchtower_1  | time="2020-05-05T17:26:03Z" level=debug msg="Pulling victorcmoura/python-watchtower-deployable:latest for /watchtower-experiment-1_python-watchtower-test_1"
watchtower_1  | time="2020-05-05T17:26:03Z" level=debug msg="No credentials for victorcmoura in /config.json"
watchtower_1  | time="2020-05-05T17:26:03Z" level=debug msg="Got image name: victorcmoura/python-watchtower-deployable:latest"
watchtower_1  | time="2020-05-05T17:26:03Z" level=debug msg="Got auth value: "
watchtower_1  | time="2020-05-05T17:26:05Z" level=debug msg="No new images found for /watchtower-experiment-1_python-watchtower-test_1"
watchtower_1  | time="2020-05-05T17:26:05Z" level=debug msg="Scheduled next run: 2020-05-05 17:26:33 +0000 UTC"
```

Then, I noticed you used `container_name` in your Watchtower compose. So I assumed this could also be happening in your application's compose and it could cause the bug. I changed my application compose as it follows:

```
version: '3'

services:
  python-watchtower-test:
    container_name: mycontainer
    image: victorcmoura/python-watchtower-deployable
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

But it also worked as expected:

```
watchtower_1  | time="2020-05-05T17:34:35Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
watchtower_1  | time="2020-05-05T17:34:36Z" level=debug msg="Retrieving running containers"
watchtower_1  | time="2020-05-05T17:34:36Z" level=debug msg="There are no additional watchtower containers"
watchtower_1  | time="2020-05-05T17:34:36Z" level=info msg="Starting Watchtower and scheduling first run: 2020-05-05 17:35:06 +0000 UTC m=+30.780700474"
watchtower_1  | time="2020-05-05T17:35:06Z" level=debug msg="Checking containers for updated images"
watchtower_1  | time="2020-05-05T17:35:06Z" level=debug msg="Retrieving running containers"
watchtower_1  | time="2020-05-05T17:35:06Z" level=debug msg="Pulling victorcmoura/python-watchtower-deployable:latest for /mycontainer"
watchtower_1  | time="2020-05-05T17:35:06Z" level=debug msg="No credentials for victorcmoura in /config.json"
watchtower_1  | time="2020-05-05T17:35:06Z" level=debug msg="Got image name: victorcmoura/python-watchtower-deployable:latest"
watchtower_1  | time="2020-05-05T17:35:06Z" level=debug msg="Got auth value: "
watchtower_1  | time="2020-05-05T17:35:08Z" level=debug msg="No new images found for /mycontainer"
watchtower_1  | time="2020-05-05T17:35:08Z" level=debug msg="Scheduled next run: 2020-05-05 17:35:36 +0000 UTC"
```
I also used `container_name` in Watchtower's compose just to be sure. Still couldn't reproduce the bug.

Is there any chance that your Watchtower's image version isn't the latest? I am using the latest available.
