### ISSUE TITLE
is watchtower working with portainer stack?

### ISSUE THREAD

**Issue by sgiannulli** [containrrr/watchtower#557]
Hello,
I have started today using watchtower through portainer stack with compose file below; everything seems working except that watchtower does not detect newer images on docker hub. Is this some kind of known problem with portainer?
The scope is to just have an email notification when a new image is released.
Thank you

```
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Rome
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      - WATCHTOWER_CLEANUP=false
      - DOCKER_API_VERSION=1.24
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_NO_PULL=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=false
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=myemail@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=abc@xyz.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myemail@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=myapppwd
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    restart: unless-stopped
```

from the log:
```
time="2020-05-27T23:56:47+02:00" level=debug msg="Scheduled next run: 2020-05-27 23:59:47 +0200 CEST"
time="2020-05-27T23:59:47+02:00" level=debug msg="Checking containers for updated images"
time="2020-05-27T23:59:47+02:00" level=debug msg="Retrieving containers including stopped and exited"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /watchtower_watchtower_1"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /diun"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /nextcloud"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /letsencrypt"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /mariadb"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /droppy"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /transmission"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /sickchill"
time="2020-05-27T23:59:47+02:00" level=debug msg="Skipping image pull."
time="2020-05-27T23:59:47+02:00" level=debug msg="No new images found for /portainer"
time="2020-05-27T23:59:47+02:00" level=debug msg="Scheduled next run: 2020-05-28 00:02:47 +0200 CEST"
```
