### ISSUE TITLE
Running watchtower without specific containers in params will not detect other containers

### ISSUE THREAD

**Issue by defhead** [containrrr/watchtower#583]
**Describe the bug**
If I don't write the containers I want to "watch" , watchtower will detect no containers

**To Reproduce**
here is my docker-compose file
```
---
version: "2"
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /test/portainer:/data
  nginx:
    image: nginx
    container_name: nginx
    links:
      - portainer
    ports:
      - 9999:9999
    volumes:
      - /test/nginx/config/proxy_params:/etc/nginx/proxy_params
      - /test/nginx/config/portainer.conf:/etc/nginx/conf.d/portainer.conf
      - /test/nginx/ssl:/etc/nginx/ssl
    command: /bin/bash -c "rm -f /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    restart: always
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Europe/Paris"
    command: --interval 60 --cleanup true --debug true
    restart: always
```

and I'll get these logs:
```
 > docker logs watchtower -f
time="2020-06-16T20:25:16+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-06-16T20:25:17+02:00" level=debug msg="Retrieving running containers"
time="2020-06-16T20:25:17+02:00" level=debug msg="There are no additional watchtower containers"
time="2020-06-16T20:25:17+02:00" level=info msg="Starting Watchtower and scheduling first run: 2020-06-16 20:26:17 +0200 CEST m=+60.410132793"
time="2020-06-16T20:26:17+02:00" level=debug msg="Checking containers for updated images"
time="2020-06-16T20:26:17+02:00" level=debug msg="Retrieving running containers"
time="2020-06-16T20:26:17+02:00" level=debug msg="Scheduled next run: 2020-06-16 20:27:17 +0200 CEST"
♥
```

If I change to `command:  --interval 60 --cleanup true --debug true portainer nginx`, it will work perfectly.

**Expected behavior**
No containers in 'command' should "watch" all containers
