### ISSUE TITLE
Default WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG to hostname

### ISSUE THREAD

**Issue by ptr727** [containrrr/watchtower#586]
I run the same docker compose file on multiple hosts.
I'd like email notifications to tell me which host is sending the email.

Docker compose does support environment variables, but apparently it does not work in compose environment variables.
`WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=${HOSTNAME}`
Results in `WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=`

Am I using this incorrectly, or is this a compose limitation?

I could dynamically create the compose file for every server, but it would be much easier if the default value for `WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG` could default to the container hostname.

Example compose file:
```yaml
version: '3.7'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: ${HOSTNAME}
    domainname: home.foo.net
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=logs@foo.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=logs@foo.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.home.foo.net
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=${HOSTNAME}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_TIMEOUT=60
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
```

**Comment by victorcmoura** [comment]
Hi, @ptr727! 

I managed to reproduce your issue. It is actually frustrating not to see it working haha. As a workaround, I suggest running
```
env HOSTNAME=$HOSTNAME docker-compose [...]
```
So it forces docker-compose to see ${HOSTNAME} as your shell's $HOSTNAME.

Similarly, you can use a `.env` to place your compose variables, so running `echo "HOSTNAME=${HOSTNAME}" > .env` in your compose folder, for each host, could be another clunky option with a similar result =S

Regarding the default value, it may require some discussion to see how it can impact current users. @simskij, can you help us with this?

**Comment by zoispag** [comment]
Hi there,

This looks like a limitation of the array notation of yaml. Try to use the object notation for your env vars in your compose file:

Example from my compose file:
```yml
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: ${TIMEZONE_LOCATION}
      WATCHTOWER_CLEANUP: 1
      ...
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: ${HOST}
```

_Beware of differences in boolean values if you use any._

**Comment by ptr727** [comment]
It still does not seem to work:

```yaml
version: '3.7'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower-${HOSTNAME}
    domainname: home.insanegenius.net
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      WATCHTOWER_NOTIFICATIONS: email
...
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: ${HOSTNAME}
      WATCHTOWER_CLEANUP: 1
      WATCHTOWER_INCLUDE_STOPPED: 1
      WATCHTOWER_TIMEOUT: 60
      WATCHTOWER_SCHEDULE: '0 0 2 * * *'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
```

```
root@server-2:# echo ${HOSTNAME}
server-2
```

From Portainer:
```
TZ | America/Los_Angeles
WATCHTOWER_NOTIFICATIONS | email
...
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT | 25
WATCHTOWER_NOTIFICATION_EMAIL_DELAY | 2
WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG |  
WATCHTOWER_CLEANUP | 1
...
```

**Comment by zoispag** [comment]
Hey @ptr727, do you have a .env file? Try to add `HOST=${HOST}` in your .env and please let me know.

**Comment by ptr727** [comment]
I should have addressed that, sorry; the compose files are called from ansible, to dynamically create .env file or to use an ansible shell command with -e instead of the docker_compose command is extra work.

If this is a docker-compose limitation, even when using "object notation", I would rather convert my ansible task to a native docker_compose task vs. calling a compose file. I prefer calling compose files as I can use them from ansible or from the shell.

Any other ideas on how to get the environment variable recognized?

**Comment by zoispag** [comment]
I can try to reproduce it, but can you please share your playbook or at least the docker-compose module part of your ansible command?

**Comment by ptr727** [comment]
This works:
```yaml
- name: 'Install Watchtower'
  docker_compose:
    project_name: watchtower
    definition:
        version: '3.7'
        services:
          watchtower:
            image: containrrr/watchtower
            container_name: watchtower
            hostname: watchtower-{{ ansible_hostname }}
            domainname: home.insanegenius.net
            restart: unless-stopped
            environment:
              TZ: America/Los_Angeles
              WATCHTOWER_NOTIFICATIONS: email
...
              WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
              WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
              WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: "{{ ansible_hostname }}"
              WATCHTOWER_CLEANUP: 1
              WATCHTOWER_INCLUDE_STOPPED: 1
              WATCHTOWER_TIMEOUT: 60
              WATCHTOWER_SCHEDULE: '0 0 2 * * *'
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            network_mode: host
```

This does not work:
```
- name: 'Install Containers'
  docker_compose:
    project_src: '{{ playbook_dir }}/../Docker'
    files: 
      - 'portainer.yml'
      - 'watchtower.yml'
      - 'code-server.yml'
      - 'netdata.yml'
```

I noticed that if I set the hostname, then I really don't need to the set `WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG`, because the email subject includes the unique hostname. e.g. `Watchtower updates on watchtower-server-2`

**Comment by zoispag** [comment]
> I noticed that if I set the hostname, then I really don't need to the set `WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG`, because the email subject includes the unique hostname. e.g. `Watchtower updates on watchtower-server-2`

OK, that's good. So I think the issue is with Ansible docker_compose module and env variables. Let me run a test with this in a playbook. I might come up with something.

**Comment by zoispag** [comment]
@ptr727, the issue is with docker-compose, not with Ansible.

See example file:

```yml
version: '3'

services:
  host:
    image: alpine
    environment:
      HOST: ${HOST}
    command: ["echo", "Host is ${HOST}"]
```

```bash
$ docker-compose up
WARNING: The HOST variable is not set. Defaulting to a blank string.
Creating network "ansible-compose_default" with the default driver
Creating ansible-compose_host_1 ... done
Attaching to ansible-compose_host_1
host_1  | Host is
ansible-compose_host_1 exited with code 0

$ HOST=$HOST docker-compose up
Recreating ansible-compose_host_1 ... done
Attaching to ansible-compose_host_1
host_1  | Host is Zoiss-MacBook-Pro.local
ansible-compose_host_1 exited with code 0
```

In your first playbook, Ansible is "constucting" the docker-compose inline, so the env variables are passed from SHELL to docker-compose. On the second example, the `docker-compose up` command that Ansible is essentially executing is not passing env variables.

Unfortunately I have trouble running the docker-compose module on my localhost, even for my minimal docker-compose.yml file.

```yml
---
- name: Test docker-compose
  hosts: localhost

  tasks:
  - name: 'Hello host'
    docker_compose:
      project_src: '.'
```

I am trying to figure out if there is a way to pass env vars to docker-compose Ansible module but there doesn't seem to be any way.

The next best think I can think, is to use the copy module of Ansible to create a `.env` to be used by docker-compose that includes the HOST variable.

Consider the following **untested** example:

```yml
---
- name: Start docker containers
  hosts: localhost

  tasks:
  - name: Create .env for docker-compose
    copy:
      dest: '{{ playbook_dir }}/../Docker'
      content: |
        HOST={{ lookup('env', 'HOST') }}

  - name: 'Install Containers'
    docker_compose:
      project_src: '{{ playbook_dir }}/../Docker'
      files: 
        - 'portainer.yml'
        - 'watchtower.yml'
        - 'code-server.yml'
        - 'netdata.yml'
```

I hope this helps.

**Comment by ptr727** [comment]
Thank you, I decided to bite the bullet and convert the docker_compose tasks to docker_container tasks, where I specify all the attributes.

```yaml
- name: 'Install Watchtower'
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    hostname: watchtower-{{ ansible_hostname }}
    domainname: home.insanegenius.net
    restart_policy: unless-stopped
    env:
      TZ: "America/Los_Angeles"
      WATCHTOWER_NOTIFICATIONS: "email"
...
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "25"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_TIMEOUT: "90"
      WATCHTOWER_SCHEDULE: "0 0 2 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
```
