### ISSUE TITLE
Bind mount with config.json broken 

### ISSUE THREAD

**Issue by kabrot** [containrrr/watchtower#596]
**Describe the bug**
After updating from docker 18.09 to 19.03, watchtower can no longer see read updated token to in config.json on the host. 
This has been working, and is working, fine on servers that run docker 18.09. 

There has been a similar case: https://github.com/containrrr/watchtower/issues/451 where the solution is to create a symbolic link to config.json, and mount the symbolic link, but this does not fix it for me. 
When changing the file with `nano` the changes are reflected in the watchtower container, but changes made with `vim` or `docker-login` break the bind mount. 

**Environment**
Platform: Amazon Linux AMI 2018.03
Docker version 19.03

**Logs from running watchtower with the --debug option**
time="2020-07-08T13:13:34Z" level=info msg="Unable to update container /frontend_1. Proceeding to next."

**Comment by piksel** [comment]
Changing the file with nano does not change the inode, and so the changes are reflected in the docker container. The symbolic link "hack" does indeed not seem to be working anymore, possibly due to changes in 19.03.  
Another workaround we discovered while investigating this was to mount the config directory instead of the config file, since the directory inode won't change when the file is edited.
To do this, put the config file in an empty directory and mount it instead of the config file. Then set the environment variable `DOCKER_CONFIG` to said directory, like this:  

```yaml
watchtower:
  image: containrrr/watchtower
  environment:
      DOCKER_CONFIG: /config
    volumes:
      - <PATH_TO_YOUR_CONFIG_DIRECTORY>/config/:/config/
      - /var/run/docker.sock:/var/run/docker.sock
```
