### ISSUE TITLE
Error response from daemon: No such container

### ISSUE THREAD

**Issue by markolonius** [containrrr/watchtower#599]
Getting error:
`time="2020-07-10T03:59:48Z" level=error msg="Error response from daemon: No such container: f74860a8f08a3f10127fd6473ce8ab253431638e2948bc23d95cd2ab3c55fb63"`

Seems intermittent, which is likely why previous bug report #213  for this same issue closed due to inactivity.  This issue looks like may be related to environment variable WATCHTOWER_CLEANUP=true since it looks like it removes both vpn and jackett containers.  Jackett container depends on the vpn container's network, however jackett is started first then vpn as you can see in the attached logs below.  In my compose file I did list 'depends_on" vpn container.  Seems watchtower ignore this?  Or maybe need another way to specify container startup order?

**Environment**
-Kernel Version: 5.4.43-sunxi64
-Operating System: Ubuntu 18.04.4 LTS
-OSType: linux
-Architecture: aarch64
-Docker version 19.03.12, build 48a6621

**Logs from running watchtower with the `--debug` option**
see attached debug level log file
[watchtower.log](https://github.com/containrrr/watchtower/files/4903101/watchtower.log)

**Additional context**
Docker-compose v2 for watchtower:
```
watchtower:
    image: containrrr/watchtower:arm64v8-latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE= 0 0 3 * * *
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=*****@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=*****i@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=*****@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=*****
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    restart: always

```
docker-compose for the affected containers:
```
vpn:
    container_name: vpn
    image: dperson/openvpn-client:aarch64
    cap_add:
      - NET_ADMIN # required to modify network interfaces
    restart: always
    security_opt:
      - label:disable
    environment:
      - TZ=America/New_York
      - FIREWALL
    volumes:
      - /dev/net/tun:/dev/net/tun # tun device
      - ~/.config/vpn:/vpn # OpenVPN configuration
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 9117:9117 # jackett port for web UI
      - 58846:58846  # deluge daemon port for HA access
    command: '-r 192.168.2.0/24' # route local network traffic

deluge:
    container_name: deluge
    image: linuxserver/deluge:arm64v8-latest
    depends_on:
      - vpn
    restart: always
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=America/New_York 
    volumes:
      - /media/*****:/data 
      - ~/.config/deluge:/config 

jackett:
    container_name: jackett
    image: linuxserver/jackett:arm64v8-latest
    depends_on:
      - vpn
    restart: always
    network_mode: service:vpn
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=America/New_York # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/*****:/downloads 
      - ~/.config/jackett:/config

```
