### ISSUE TITLE
[Notifications] name instead of ID

### ISSUE THREAD

**Issue by balli1187** [containrrr/watchtower#628]
Hi,

First of all: thanks for this software/image. Really makes it easy to keep Container era updated.

I‘m using email notification to be informed if watchtower updates a container.
In the email subject only the Container ID is given, wich I normally don‘t know. I want to ask to use the container name (if specified) or the image name instead.

Thanks, Stephan

**Comment by m-sedl** [comment]
Hello. As I understand from the code, the subject line contains the hostname of the watchtower, not the updated container. If you want to distinguish between emails from different watchtower instances, then use the _--notification-email-subjecttag_ flag.

I doubt that it will be possible to indicate the name of the changed container in the subject line, because one email can display logs associated with several containers at once.

If I'm wrong, more experienced community members may correct me.

**Comment by balli1187** [comment]
> Hello. As I understand from the code, the subject line contains the hostname of the watchtower, not the updated container. If you want to distinguish between emails from different watchtower instances, then use the notification-email-subjecttag_ flag.
> 
> 
> 
> I doubt that it will be possible to indicate the name of the changed container in the subject line, because one email can display logs associated with several containers at once.
> 
> 
> 
> If I'm wrong, more experienced community members may correct me.

Oh... yes seems you are right.

But what is the purpose of showing  the hostename, if i can set the notification-email-subjecttag_ flag to distinguish between different watchtowers?

So far I got a single email for every updated container, so it could be possible to show the Hostnamen here.

Actually I want to inject the mails in my home automation system.
Is it possible to call a script (with container name/ID as parameter) instead of sending mails or what ever?

**Comment by m-sedl** [comment]
>So far I got a single email for every updated container, so it could be possible to show the Hostnamen here.

Theoretically, if all log entries in an email contain information about one container, then you can get its name/ID from the log entry and add them to the email subject. But I think there is a better way.

> Is it possible to call a script (with container name/ID as parameter) instead of sending mails or what ever?

It is possible that this article can help you. https://containrrr.dev/watchtower/lifecycle-hooks/

**Comment by balli1187** [comment]
> It is possible that this article can help you. https://containrrr.dev/watchtower/lifecycle-hooks/

Hm... yes That could do the job but if I understand right, these Skripts are performed within the container. 
So i think i have to create an own script for every container. Hoped it could've easier....

**Comment by balli1187** [comment]
So... I played a little with the lifecycle hooks but as assumed I ran into sim problems:

- as the scripts are procesed _inside_ the watched Container it was hardly not possible to create one script running in every container.
- as I want to realize a webhook I had to run a curl or wget cmd. Some images (from docker hub) only understand wget, some curl, other neither nor. Some don't even have a shell, so scripts cannot be processed.

**Comment by iFredOS** [comment]
> Hi,
> 
> First of all: thanks for this software/image. Really makes it easy to keep Container era updated.
> 
> I‘m using email notification to be informed if watchtower updates a container.
> In the email subject only the Container ID is given, wich I normally don‘t know. I want to ask to use the container name (if specified) or the image name instead.
> 
> Thanks, Stephan

I completely agree with you! I started to use Watchtower 2 weeks ago and I was really surprise (disappointed) of this notification feature. What is the purpose to received an email with an ID with don't know/we don't remember by heart? It should a basic feature of Watchtower to show the name of the container with or without the ID number.

**Comment by piksel** [comment]
The subject for e-mail notifications should be:
```
[OptionalSubjectTag] Watchtower updates on <Hostname>
```

Could you post an example of what subject you are seeing?

**Comment by simonaronsson** [comment]
> I completely agree with you! I started to use Watchtower 2 weeks ago and I was really surprise (disappointed) of this notification feature. What is the purpose to received an email with an ID with don't know/we don't remember by heart? It should a basic feature of Watchtower to show the name of the container with or without the ID number.

Given that this is a community effort without any commercial backing, we try to use an encouraging tone rather than scolding to keep our contributors motivated. You are more than welcome to contribute if you think something could be improved. Using language like "What is the purpose" and "should be a basic feature" won't help anyone.

Thanks! ✨

**Comment by simonaronsson** [comment]
If you set the `hostname` property for the watchtower container in your docker-compose file, or supply it to `docker run` using `-h`, that is the name that will be used. It is indeed showing the hostname, but if the watchtower container doesn't have this specified, it will just be a random hash.

**Comment by timdonovanuk** [comment]
> If you set the `hostname` property for the watchtower container in your docker-compose file

Is this documented anywhere (apologies if it is but I cannot see it)? I know this thread is about email notifications but the same is true for gotify. `"Watchtower updates on b652df6a234c"`  I don't know what b652df6a234c is.

**Comment by piksel** [comment]
Yes, this is the same for all notifications. Docker sets a randomized hostname for all containers (depending on network setup) unless you pass it with `--hostname` (for `docker run`) or `hostname:` (for docker-compose).

**Comment by timdonovanuk** [comment]
Ah I see, it's at a docker level. Thank you!

**Comment by iodize6399** [comment]
The hostname we are talking about is the `hostname` of the docker host, right?
`"Watchtower updates on b652df6a234c"` would mean "Updates are available on the server called "b652df6a234c", right?
If so, why does Watchtower not pick up the hostname of the bare metal as set using `hostnamectl set-hostname server01`?
I'm sorry if this counts as a basic question, as I am relatively new to docker and trying to understand the system.

Edit: I added `hostname:server01` under the watchtower docker-compose and was able to rename the hostname. However, I still wonder, why the container uses a random string for calling it's host.

**Comment by piksel** [comment]
@physx2494 it depends on the networking mode. If you use  host networking it will share the hostname with the host, but if it's virtualized (which is the docker-compose default), docker will generate a random hostname unless specified.

**Comment by andreapx** [comment]
I'm a bit lost, is there a way to view the containers name in the notifications?

**Comment by piksel** [comment]
@andreapx The name of the watchtower container? No, use `hostname` (docker-compose) or `--hostname` (docker run) to set the "name" displayed in the subject.

**Comment by andreapx** [comment]
> No, use `hostname` (docker-compose)

Hi @piksel , I've done what you suggested and run watchtower, but I still seethe container id in the logs and in the notifications.
My docker-compose.yaml:

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    container_name: fireflyiii-app
    hostname: fireflyiii-app
    restart: unless-stopped
    volumes:
      - /var/docker/firefly_iii/upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - "127.0.0.1:980:80"
    depends_on:
      - db
    networks:
      internal_bridge:
          ipv4_address: "172.33.0.102"
  db:
    image: mariadb
    hostname: fireflyiii-db
    container_name: fireflyiii-db
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=MY-PW
      - MYSQL_DATABASE=firefly
    volumes:
      - /var/docker/firefly_iii/db:/var/lib/mysql
    networks:
      internal_bridge:
          ipv4_address: "172.33.0.103"
  fidi:
    image: fireflyiii/data-importer:latest
    container_name: fireflyiii-importer
    hostname: fireflyiii-importer
    restart: unless-stopped
    env_file: .fidi.env
    ports:
      - "127.0.0.1:981:8080"
    networks:
      internal_bridge:
          ipv4_address: "172.33.0.104"
    depends_on:
      - app

networks:
  internal_bridge:
    external: true
```

And in the log I see:

```
watchtower    | time="2023-03-07T08:03:55Z" level=info msg="Found new fireflyiii/data-importer:latest image (**d56837468c0c**)"
watchtower    | time="2023-03-07T08:03:56Z" level=info msg="Found new fireflyiii/core:latest image (**e74061782978**)"
```

In this case it's really not relevant since I have just 1 instance of Fireflyiii, but when the case is a MySQL db, I've got more then 1 and I can't understand which one needs update.
Thanks!
