### ISSUE TITLE
Cannot update private container, credentials missing

### ISSUE THREAD

**Issue by totti4ever** [containrrr/watchtower#648]
Hi,

from #55 and #68 I figured out, I have to add to my image name, what I did:

```
    image: index.docker.io/private_repo/syncthing:latest

```

But I still get an error:
```
watchtower_1  | time="2020-09-19T04:01:03+02:00" level=debug msg="Pulling index.docker.io/[private_repo]/syncthing:latest for /syncthing"
watchtower_1  | time="2020-09-19T04:01:03+02:00" level=debug msg="No credentials for index.docker.io in /config.json"
watchtower_1  | time="2020-09-19T04:01:03+02:00" level=debug msg="Got image name: index.docker.io/private_repo/syncthing:latest"
watchtower_1  | time="2020-09-19T04:01:04+02:00" level=debug msg="Error pulling image index.docker.io/private_repo/syncthing:latest, Error response from daemon: pull access denied for private_repo/syncthing, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
watchtower_1  | time="2020-09-19T04:01:04+02:00" level=info msg="Unable to update container /syncthing. Proceeding to next."
watchtower_1  | time="2020-09-19T04:01:04+02:00" level=debug msg="Error response from daemon: pull access denied for private_repo/syncthing, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
```

Looking into my config.json, I do find the following:
```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "[some_key]"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.5 (linux)"
        }
```

Message stays the same when I add the following to the json file:
```
                "index.docker.io/": {
                        "auth": "[same_key]="
                }
```

latest version of watchdog on Ubuntu 18

P.S.: a manual docker-compose pull works

**Comment by simonaronsson** [comment]
Hey!

Would you mind posting the command and/or config you use to launch watchtower?

Thanks,
Simme

**Comment by totti4ever** [comment]
```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin

      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_CLEANUP=true
      - "WATCHTOWER_SCHEDULE=0 0 4 * * *"
      - WATCHTOWER_LABEL_ENABLE=false   # only labelled containers
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /root/.docker/config.json:/config.json
```

I thought, it might be because of the last line commented out - but actually, if I remove the comment, I get
```
"Pulling linuxserver/jellyfin:latest for /jellyfin"
"No credentials for linuxserver in /config.json"
```
for every single image?!
