### ISSUE TITLE
Inclusion of docker secrets not working

### ISSUE THREAD

**Issue by kevdogg** [containrrr/watchtower#653]
I'm originally referencing this closed issue:
https://github.com/containrrr/watchtower/issues/532

It was my understanding the use of docker secrets was merged to next release on Jun 10.  Perhaps it was not.

Briefly I'm trying to pass the WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD as a docker secret and not as plaintext within configuration file.

The following will work:

 ```
 watchtower:
    image: containrrr/watchtower:latest-dev
    container_name: watchtower
    restart: always
    networks:
      - net
    command: --schedule "0 0 */4 * * *"
    ....
    ....
    environment:
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=PASSWORDHERE
```

However the inclusion of docker secrets such as below will not:

 ```
secrets:
  watchtower_notification_email_server_secret:
    file: ./watchtower_notification_email_server.secret

 watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    networks:
      - net
    command: --schedule "0 0 */4 * * *"
    secrets:
      - watchtower_notification_email_server_secret
    ....
    ....
    environment:
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD_FILE=/run/secrets/watchtower_notification_email_server_secret
```

I thought this functionality was included???  I tested this against the latest-dev image.
