### ISSUE TITLE
IPv6 connectivity lost

### ISSUE THREAD

**Issue by jwillmer** [containrrr/watchtower#666]
**Describe the bug**

I have an ARM server at home that gets a IPv6 assigned from my router. With this IP it is accessible from the internet. However after some hours I notice that he is not accessible anymore and if I SSH into the server I see that only my IPv6 link-local address is set.

**To Reproduce**

dhcpcd.conf:

```
hostname
clientid
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option interface_mtu
require dhcp_server_identifier
slaac private

interface eth0
static ip_address=192.168.1.5/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.254
```

After startup:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.5  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2003:de:[...]:9780  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::7243:dc77:431d:76eb  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:c5:c9:27  txqueuelen 1000  (Ethernet)
        RX packets 92  bytes 11278 (11.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 116  bytes 16329 (15.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

After some time:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.5  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7243:dc77:431d:76eb  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:c5:c9:27  txqueuelen 1000  (Ethernet)
        RX packets 24261450  bytes 1315486709 (1.2 GiB)
        RX errors 29678  dropped 29678  overruns 0  frame 0
        TX packets 28374527  bytes 2775722882 (2.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Expected behavior**
That my IPv6 will not be removed.

**Environment**
- Pi4
- Raspbian OS
- docker installed

docker-compose part:
```
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    networks:
      - traefik_proxy    
    command: --schedule "45 4 */4 * *" --cleanup --label-enable   
    environment:
      - TZ='${TZ}' 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
```

**Logs from running watchtower with the `--debug` option**

I will start watchtower again now with this option enabled. And will update this section when I get the described issue again.

**Additional context**
I posted this issue first on [superuser](https://superuser.com/questions/1594628/ipv6-connectivity-lost) before I could track it to watchtower.
