### ISSUE TITLE
Unable to update container

### ISSUE THREAD

**Issue by wmbutler** [containrrr/watchtower#68]
## My docker-compose file (in a private repo):
```
version: "3"
services:
  cavo:
    image: adventhp/cavo:docker
    env_file:
      - app.docker.env
    ports:
      - "443:3443"
      - "80:3080"
    entrypoint: ["pm2-docker", "/home/code/process.yml"]
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
```
 I'm starting this as **root** with:
```
docker-compose up
```

My log files show that watchtower is checking for updates every 5 minutes, but instead of pulling the latest image, I see this message in the logfile:

```
watchtower_1  | time="2017-03-16T04:50:32Z" level=info msg="Unable to update container /ubuntu_cavo_1. Proceeding to next."
```

I've verified the location and validity of both volumes.
I have no problem issuing a `docker pull adventhp/cavo:docker` command.

**Comment by stffabi** [comment]
Could you please provide the debug watchtower output by using `--debug`? This should give us a little more information on what's going on.

**Comment by stffabi** [comment]
Is `adventhp/cavo:docker` a private image? Then I suspect you are facing #55. Debug output should clarify the situation...

**Comment by wmbutler** [comment]
Yes, prepending with the registry url solved the issue:
```
version: "3"
services:
  cavo:
    image: index.docker.io/adventhp/cavo:docker
    env_file:
      - app.docker.env
    ports:
      - "443:3443"
      - "80:3080"
    entrypoint: ["pm2-docker", "/home/code/process.yml"]
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
```

I suggested in #55 that you grab this value from the config.json file and prepend it.
