### ISSUE TITLE
 Three days of "Found multiple running watchtower instances. Cleaning up." followed by a new error after re-creating the container

### ISSUE THREAD

**Issue by tehniemer** [containrrr/watchtower#723]
**Describe the bug**
I've been getting the following in my logs for the last three evenings `Found multiple running watchtower instances. Cleaning up.` and no containers were being updated. So I recreated the container and now it doesn't start, just gives the following error, `time="2020-12-23T06:46:51-06:00" level=fatal msg="Error response from daemon: client version 1.4 is too old. Minimum supported API version is 1.12, please upgrade your client to a newer version"`

**To Reproduce**
Honestly don't know, I didn't do anything.

**Expected behavior**
Not this.

**Environment**
 - Debian Buster

Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Logs from running watchtower with the `--debug` option**
```
time="2020-12-23T06:54:37-06:00" level=debug
time="2020-12-23T06:54:37-06:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-12-23T06:54:38-06:00" level=debug msg="Retrieving running, stopped and exited containers"
time="2020-12-23T06:54:38-06:00" level=fatal msg="Error response from daemon: client version 1.4 is too old. Minimum supported API version is 1.12, please upgrade your client to a newer version"
```

**Comment by simonaronsson** [comment]
Hi! 👋 

This is indeed weird. I'm a bit curious as to what client version you're running on the server. Also whether you have something lingering in your path, and how you mount the docker socket.

Best,
Simme

**Comment by tehniemer** [comment]
My docker version info is in the original post. I'm not sure what else you are asking for. Below is the snippet from my compose file.
```
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - proxy
      - socket_proxy
      - database
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_REMOVE_VOLUMES: 'true'
      WATCHTOWER_INCLUDE_STOPPED: 'true'
      WATCHTOWER_NO_STARTUP_MESSAGE: 'false'
      WATCHTOWER_SCHEDULE: '0 0 4 * * *'
      WATCHTOWER_NOTIFICATIONS: 'shoutrrr'
      WATCHTOWER_NOTIFICATION_URL: 'telegram://$OUROBOROS_BOT_TOKEN@telegram?channels=$TGRAM_CHAT_ID'
      WATCHTOWER_NOTIFICATIONS_LEVEL: 'info'
      DOCKER_HOST: 'tcp://socket-proxy:2375'
      DOCKER_API_VERSION: 1.40
```

So after looking at it, I changed `DOCKER_API_VERSION: 1.40` to `DOCKER_API_VERSION: 1.41` and it started. I'll have to see if it actually runs tonight.
