### ISSUE TITLE
Error response from daemon: Container cannot be disconnected from host network or connected to host network

### ISSUE THREAD

**Issue by Robotex** [containrrr/watchtower#73]
Watchtower cannot restart containers after pulling image when network_mode is set to "host", however running manually `sudo docker start <container_id>` works fine.

docker-compose.yml:
```
  test:
    image: renshou/steamcmd
    container_name: test
    userns_mode: "host"
    network_mode: "host"
    tty: true
    restart: unless-stopped
```
watchtower log:
```
watchtower        | time="2017-03-24T10:05:58Z" level=info msg="Stopping /test (00b5fc60f4fd944acb578ada116a920d55c7961929db1b67189cc1c39435a375) with SIGTERM" 
watchtower        | time="2017-03-24T10:05:59Z" level=debug msg="Removing container 00b5fc60f4fd944acb578ada116a920d55c7961929db1b67189cc1c39435a375" 
watchtower        | time="2017-03-24T10:06:00Z" level=info msg="Creating /test" 
watchtower        | time="2017-03-24T10:06:00Z" level=error msg="Error response from daemon: Container cannot be disconnected from host network or connected to host network" 
```
