### ISSUE TITLE
Watchtower fails to start (second part of Shoutrr API token missing)

### ISSUE THREAD

**Issue by rg9400** [containrrr/watchtower#746]
**Describe the bug**
On the latest-dev, Watchtower fails to start up, giving me the below error message. I couldn't figure out what changed since I don't use Shoutrr but the native slack integration instead. Worked before the latest updates.

`Failed to initialize Shoutrrr notifications: error initializing router services: second part of the API token is missing"`

**To Reproduce**
1. Pull the most recent latest-dev image (not sure how to get version, but image digest is `sha256:5a5c9f4da0352793eb13116e14b4f36200358e908958017512d5d02784c310a8`)
2. Use a compose like below with a non-Shoutrr notification
```yaml
  watchtower:
    image: containrrr/watchtower:latest-dev
    container_name: watchtower
    hostname: ${HOSTNAME}
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://discord.com/api/webhooks/${DISCORDWEBHOOK}/slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower
      - "WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=:whale:"
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_URL=https://raw.githubusercontent.com/containrrr/watchtower/master/logo.png
      - DOCKER_CONFIG=/config
    volumes:
      - ${CONFDIR}/watchtower:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
 ```

3. See error

**Expected behavior**
Slack notifications to work as before, and Watchtower to initialize and spin up

**Environment**
 - Platform - Docker
 - Architecture - linux/amd64
 - Docker version - Docker Engine 20.10.2
