### ISSUE TITLE
Not providing a sender address for email notifications gives an error since v1.1.6

### ISSUE THREAD

**Issue by glc650** [containrrr/watchtower#754]
**Describe the bug**
Watchtower fails to start after updating to 1.1.6:

watchtower    | time="2021-01-10T17:23:49-08:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: fromAddress missing from config URL\n"

**To Reproduce**
Update watchtower to 1.1.6 and run with this docker-compose file:
```yaml
version: "3.7"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /root/.docker/config.json:/config.json
    environment:
      - TZ=America/Los_Angeles
      #- WATCHTOWER_CLEANUP=true
      #- WATCHTOWER_REMOVE_VOLUMES=true
      #- WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_SCHEDULE=0 0 10,20 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=myemailaddy
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mysmtpserver
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=myusername
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=mypassword
    networks:
      - watchtower

networks:
  watchtower:
    name: watchtower
```

**Expected behavior**
For watchtower to start properly

**Environment**
Ubuntu 20.04.1 LTS w/Docker 19.03.13

**Additional context**
I have always used email notifications and have never used Shoutrrr notifications (don't even know what that is).  Reverting back to 1.1.5 solves the problem.
