### ISSUE TITLE
watchtower does not start with mattermost notification web hooks since 1.1.6

### ISSUE THREAD

**Issue by tldev-de** [containrrr/watchtower#755]
**Describe the bug**
Since the upgrade to v1.1.6 our watchtower is not starting with the mattermost webhook url as slack hook url:
```
watchtower_1  | time="2021-01-11T12:19:57+01:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: second part of the API token is missing\n"
```

**To Reproduce**
1. run this docker-compose file
```
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://chat.example.com/hooks/thisisrandomandsecure
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#watchtower-dev
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower
```

**Expected behavior**
watchtower should start properly, since mattermost web hooks are compatible to slack web hooks.

**Environment**
 - Platform: Debian 10.7 
 - Architecture:  x86_64
 - Docker version: 20.10.2

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
tobi@worker02:~/watchtower-tmp$ docker-compose up
Recreating watchtower-tmp_watchtower_1 ... done
Attaching to watchtower-tmp_watchtower_1
watchtower_1  | time="2021-01-11T12:24:30+01:00" level=debug
watchtower_1  | time="2021-01-11T12:24:30+01:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: second part of the API token is missing\n"
```

</details>

**Additional context**
downgrade to 1.1.5 fixed the problem.

**Comment by simonaronsson** [comment]
Terribly sorry for the breaking behavior. We're still trimming in the new notifications systems and using the slack service to do mattermost notifications was a use case we weren't really aware of.

Are there any advantages to running it over the slack service compared to using the mattermost service provided by shoutrrr? If you haven't given it a try, it's available [using shoutrrr](https://containrrr.dev/watchtower/notifications/#containrrrshoutrrr) with an URL like `mattermost://[username@]mattermost-host/token[/channel]` (from https://containrrr.dev/shoutrrr/services/overview/)

**Comment by tldev-de** [comment]
Thanks for the fast reply! The usage of the slack service was actually a sample from the docs ;)

I had a look into shoutrrr (which looks pretty nice from what I've seen so far!) and changed the configuration:

```
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=mattermost://watchtower@chat.example.com/thisisrandomandsecure/watchtower-dev
      - WATCHTOWER_DEBUG=true
```
With the new configuration everything works - except the colored notifications in mattermost. To be honest, the old style (with the green or red bar on the left side) is easier/quicker to read and to interpret.

![image](https://user-images.githubusercontent.com/11870921/104186774-3380eb80-5417-11eb-8bde-b8e667f9ccd9.png)

Is there any way to set the color? It looks like the `WATCHTOWER_NOTIFICATION_TEMPLATE` is only used for the text, not the metadata (e.g. color).
