### ISSUE TITLE
Endless "Valid Token Found" messages in output when metrics enabled

### ISSUE THREAD

**Issue by thespad** [containrrr/watchtower#756]
**Describe the bug**
Watchtower log endlessly outputs "Valid token found" messages which it then attempts to send as notifications to any notification endpoints. This appears to be related to the Prometheus metrics being enabled.

**To Reproduce**
1. Run watchtower with http metrics enabled
2. Configure Prometheus to query metrics endpoint
3. Wait

**Expected behavior**
These events should not be logged as info, maybe as debug but even that feels a little overkill, and they certainly shouldn't be sent as notifications every time they're logged.

**Screenshots**
![Screenshot 2021-01-11 131359](https://user-images.githubusercontent.com/8425502/104186821-e1d46300-540e-11eb-964f-e54e63056c7b.jpg)

**Environment**
Ubuntu 20.04.1 x64
Docker 20.10.2

<details>
<summary>Docker Compose</summary>

```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
      - logstack_private
    restart: unless-stopped
    command: --cleanup --interval 21600 --label-enable
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${TGRAMURL} ${DISCORDURL}
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=foobar
      - WATCHTOWER_DEBUG=true

networks:
  public:
    external: true
  logstack_private:
    external: true
```

</details>

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2021-01-10T19:01:46Z" level=info msg="Watchtower HTTP API started."
time="2021-01-10T19:01:46Z" level=info msg="Starting Watchtower and scheduling first run: 2021-01-11 01:01:46 +0000 UTC m=+21600.963425418"
time="2021-01-10T19:01:46Z" level=info msg="Serving HTTP"
time="2021-01-11T01:01:55Z" level=info msg="Found new privatebin/nginx-fpm-alpine:latest image (sha256:1d037619f4e4b3c364e6a694eb66df58c57db43c5110a98c9591cbdfb9bc09c1)"
time="2021-01-11T01:02:06Z" level=info msg="Found new ghcr.io/linuxserver/jackett:latest image (sha256:fa929514985bb63c0fb686d8ae9cd1a2a242252514903f35cb8df211208ecb17)"
time="2021-01-11T01:02:09Z" level=info msg="Stopping /privatebin (da24cf8c37b22931034c303fe865e4ed161eb67525cfd5741871b1e0b08f71c0) with SIGTERM"
time="2021-01-11T01:02:20Z" level=info msg="Stopping /jackett (482198f9edc3df68940dde11aa3b0f1599f3b9e06df4cc5434d361194347b2d2) with SIGTERM"
time="2021-01-11T01:02:25Z" level=info msg="Creating /jackett"
time="2021-01-11T01:02:26Z" level=info msg="Creating /privatebin"
time="2021-01-11T01:02:26Z" level=info msg="Removing image sha256:44839e42b74aba8a52abfcb92126a798f47a42ea88965892ee19671f2e064e64"
time="2021-01-11T01:02:27Z" level=info msg="Removing image sha256:40dfb6a04ffa9a067fd45d1d418591e2dda3e0a44855e33cde462f970e426544"
time="2021-01-11T08:45:56Z" level=info msg="Valid token found."
time="2021-01-11T08:46:01Z" level=info msg="Valid token found."
time="2021-01-11T08:46:06Z" level=info msg="Valid token found."
time="2021-01-11T08:46:11Z" level=info msg="Valid token found."
time="2021-01-11T08:46:16Z" level=info msg="Valid token found."
time="2021-01-11T08:46:21Z" level=info msg="Valid token found."
time="2021-01-11T08:46:26Z" level=info msg="Valid token found."
time="2021-01-11T08:46:31Z" level=info msg="Valid token found."
time="2021-01-11T08:46:36Z" level=info msg="Valid token found."
time="2021-01-11T08:46:41Z" level=info msg="Valid token found."
time="2021-01-11T08:46:46Z" level=info msg="Valid token found."
time="2021-01-11T08:46:51Z" level=info msg="Valid token found."
time="2021-01-11T08:46:56Z" level=info msg="Valid token found."
time="2021-01-11T08:47:01Z" level=info msg="Valid token found."
time="2021-01-11T08:47:06Z" level=info msg="Valid token found."
time="2021-01-11T08:47:11Z" level=info msg="Valid token found."
time="2021-01-11T08:47:16Z" level=info msg="Valid token found."
time="2021-01-11T08:47:21Z" level=info msg="Valid token found."
time="2021-01-11T08:47:26Z" level=info msg="Valid token found."
time="2021-01-11T08:47:31Z" level=info msg="Valid token found."
time="2021-01-11T08:47:36Z" level=info msg="Valid token found."
time="2021-01-11T08:47:41Z" level=info msg="Valid token found."
time="2021-01-11T08:47:46Z" level=info msg="Valid token found."
time="2021-01-11T08:47:51Z" level=info msg="Valid token found."
time="2021-01-11T08:47:56Z" level=info msg="Valid token found."
time="2021-01-11T08:48:01Z" level=info msg="Valid token found."
time="2021-01-11T08:48:06Z" level=info msg="Valid token found."
time="2021-01-11T08:48:11Z" level=info msg="Valid token found."
time="2021-01-11T08:48:16Z" level=info msg="Valid token found."
time="2021-01-11T08:48:21Z" level=info msg="Valid token found."
time="2021-01-11T08:48:26Z" level=info msg="Valid token found."
time="2021-01-11T08:48:31Z" level=info msg="Valid token found."
time="2021-01-11T08:48:36Z" level=info msg="Valid token found."
time="2021-01-11T08:48:41Z" level=info msg="Valid token found."
time="2021-01-11T08:48:46Z" level=info msg="Valid token found."
time="2021-01-11T08:48:51Z" level=info msg="Valid token found."
time="2021-01-11T08:48:56Z" level=info msg="Valid token found."
time="2021-01-11T08:49:01Z" level=info msg="Valid token found."
```

</details>

**Additional context**
