### ISSUE TITLE
Failed to send notification via shoutrrr, broken pipe.

### ISSUE THREAD

**Issue by bytehealer** [containrrr/watchtower#784]
Hello: I have implemented watchtower on my containers to check for updates in UI. But i am getting Failed to send notification via shoutrrr, broken pipe.

Below is my docker-compose configuration:

```
 watchtower:
        container_name: watchtower
        restart: always
        image: containrrr/watchtower
        environment:
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_CLEANUP=TRUE
        - WATCHTOWER_MONITOR_ONLY=true
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=example@gmail.com
        - WATCHTOWER_NOTIFICATION_EMAIL_TO=mannawar.hussain@example.com
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=dbt3zrdsdd@gmail.com
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=abcdef
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587

        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        command: --debug true --cleanup true portainer sails-server sails-worker redis-store postgres-adminer angular postgresql-server

            
networks:
  frontend:
  backend:            
  ```

The error i am receiving in the watctower logs is 

```
Failed to send notification via shoutrrr (url=smtp://dbt3zrdsdd%40gmail.com:example%40123@smtp.gmail.com:587/?auth=Plain&encryption=None&fromaddress=example@gmail.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on 24b93aa76b51&toaddresses=mannawar.hussain@example.com&usehtml=No):  error authenticating: write tcp 152.11.0.2:3555->62.124.30.108:554: write: broken pipe
```

Any thoughts on that
