### ISSUE TITLE
Slack Notifications - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI not working!

### ISSUE THREAD

**Issue by aaronfagan** [containrrr/watchtower#789]
**Describe the bug**
Im creating Watchtower VIA docker-compose version 3.7. When defining `WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI`, the icon does not work.

**To Reproduce**
docker-compose.yml
```
version: '3.7'
services:
# WatchTower
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    env_file:
      - ./.env
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#logs
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_WEBHOOK_URL}
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=":whale:"
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=WatchTower [${HOSTNAME}]
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - ${DIR_HOME_WATCHTOWER}/docker.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: always
```

**Expected behavior**
Slack Webhook icon will be `:whale:` instead of the default.

**Screenshots**
N/A

**Environment**
- MacOS High Sierra (10.13.6)
- Ubuntu Server 20.04 LTS

Passing the above docker-compose gets Watchtower up and running, and webhooks being sent - however, the `WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI` environment variable does not seem to be picked up, or work. I have tried it with quote (as seen), without (docker-compose up throws an error, see below), and nothing I try seems to work.

Error without quotes:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.watchtower.environment contains {"WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=:whale": null}, which is an invalid type, it should be a string
```

**Additional context**
Have the same docker-compose for both MacOS, and Ubuntu Server. Same result on both OS.

**Comment by piksel** [comment]
The icon emoji is not supported in shoutrrr yet unfortunately.

**Update**: It seems to [have been removed](https://stackoverflow.com/a/59400746/910069) from the Slack webhook API, and looking at the notice at the bottom of https://api.slack.com/messaging/webhooks#advanced_message_formatting it's explicitly mentioned that it's not supported anymore.

So that means that shoutrrr (and in turn watchtower) cannot support them either. Sorry.
We should remove the option and update the documentation to reflect this.

And just to clarify the error message, the string you are using as the value ends in `:` (and have no spaces), so docker-compose interprets it as part of the key (with no value), this is probably because it also supports the map syntax:

```yaml
environment:
  WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
```

**Comment by aaronfagan** [comment]
Thanks @piksel !

I attempted to change my `environment` section to the following:
```
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: logs
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${SLACK_WEBHOOK_URL}
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: WatchTower [${HOSTNAME}]
      WATCHTOWER_SCHEDULE: 0 0 2 * * *
      WATCHTOWER_ROLLING_RESTART: "true"
```

However, unfortunately, its still has the same results. The original icon I setup on the web hook is whats displayed.

The odd part is that when I run this directly with `docker run -e ...` it creates it as expected. Its only when I migrated to compose it stopped working.
