### ISSUE TITLE
Non-standard image refs does not map to expected repositories in config.json

### ISSUE THREAD

**Issue by PssbleTrngle** [containrrr/watchtower#796]
**Describe the bug**
I am unable to pull private repositories with mapped `config.json`
```
Unable to update container "/grafana_importer": Error response from daemon: pull access denied for dockergelb/grafana-importer, repository does not exist or may require 'docker login
```

**To Reproduce**
I have mapped the `config.json` in `/root/.docker`, to `/config` in the watchtower container, but it is still failing to pull private repositories, even though the same repos are accessible on the host system.

This is the `docker-compose` file I use, (.env just contains the notification variables):
```
version: "3.3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    env_file: .env
```

**Environment**
 - Platform: Linux/Debian
 - Docker version: 20.10.2
 - Watchtower version: latest
