### ISSUE TITLE
SMTP Notification fail with error enabling StartTLS: x509: certificate is not valid for any names

### ISSUE THREAD

**Issue by Olivier6767** [containrrr/watchtower#797]
**Describe the bug**
Since version 1.1.6, email notifications sent to internal (insecure) SMTP relay fail with error message:
`Failed to send notification via shoutrrr (url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No):  error enabling StartTLS: x509: certificate is not valid for any names, but wanted to match mail.my-domain.com`

**To Reproduce**
Configure Watchtower to send notifications to internal SMTP relay (no Authentication, no TLS, no Certificate):
```
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtover-node1@my-domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=admin@my-domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.my-domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=true
```
Trigger notification
Watchtower attempts to send email and fails with error message:
`Failed to send notification via shoutrrr (url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No):  error enabling StartTLS: x509: certificate is not valid for any names, but wanted to match mail.my-domain.com`

**Expected behavior**
Expectation would be that notifications would be sent to the internal SMTP relay. This was working on version 1.1.5.

**Environment**
Ubuntu 20.04.1 LTS
docker-compose version 1.25.0
Docker version 19.03.8, build afacb8b7f0

**Additional context**
The SMTP relay is a postfix instance running on a Synology NAS. It is internal and does not require Authentication nor TLS.

When looking at the SMTP url:
`environment : url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No`
I can see that `starttls=Yes` is forced.

I wonder if it would help to add an additional parameter  to completely disable TLS. 
For example : `WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_DISABLE=true`
This would completely disable TLS and result in the following SMTP url:
`environment : url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=No&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No`

However, as mentioned, notifications to my internal SMTP relay were working fine in v1.1.5. It stopped working after watchtower was updated to 1.1.6.

**Temporary Fix**
Downgrading back to v1.1.5 resolves this for now.

**Comment by piksel** [comment]
The reason why this happens is because the SMTP server responds that it supports StartTLS, so the mail client tries to use it.

You can use
```yaml
environment:
  - WATCHTOWER_NOTIFICATIONS=shoutrrr
  - "WATCHTOWER_NOTIFICATION_URL=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=No&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No"
```
to disable StartTLS.

The `WATCHTOWER_NOTIFICATION_EMAIL_*` environment variables are only used for backwards compatibility, so I don't think we will be adding any more of those.
Maybe we should map `WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=False` to `Encryption=None` and `StartTLS=No` though...

**Comment by Olivier6767** [comment]
Thank you, I was able to get it work using the 2 shoutrrr environment variables you provided.

However I had to replace all spaces in the `&subject=Watchtower updates on watchtover` section with underscores.
Otherwise I would get: `msg="Failed to initialize Shoutrrr notifications: error initializing router services: unknown service scheme for URL 'updates on watchtover&usehtml=No'\n"`
**NB:** I did enclose the whole string `WATCHTOWER_NOTIFICATION_URL=smtp://...` in double quotes.

I agree that mapping `WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=False` to `Encryption=None` **and** `StartTLS=No` would be a 'cleaner' fix.

**Comment by piksel** [comment]
Ah, yeah, watchtower treats spaces as separators for multiple URLs, you can escape the spaces as `%20` or `+`:
```
smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=No&subject=Watchtower+updates+on+watchtover&toaddresses=admin@my-domain.com&usehtml=No
```

**Comment by Olivier6767** [comment]
Great!
Thanks.

**Comment by herkalurk** [comment]
This is concerning to me too.  Just realized that it's having issues sending me email notifications as well, seeing the starttls errors too.  I've checked and postfix hasn't updated on my mail relay, so I can only think that watchtower has changed and I have the latest build as of 2 weeks ago.  I'm also doing skip verify on the certificate, but that doesn't seem to change anything.

### Compose variables
```
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATIONS_LEVEL: "debug"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: watchtower@domain.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: docker@domain.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "192.168.1.30"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: "true"
      WATCHTOWER_SCHEDULE: "0 0 * * * *"
```

### Watchtower logs

```
time="2021-01-29T21:06:12Z" level=info msg="Starting Watchtower and scheduling first run: 2021-01-29 22:00:00 +0000 UTC"
Failed to send notification via shoutrrr (url=smtp://:@192.168.1.30:25/?auth=None&encryption=None&fromaddress=watchtower@domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on a9ab1f2400bb&toaddresses=docker@domain.com&usehtml=No):  error enabling StartTLS: x509: cannot validate certificate for 192.168.1.30 because it doesn't contain any IP SANs
```

### Postfix logs
```
Jan 29 14:08:35 postfix/smtpd[28031]: connect from unknown[192.168.1.40]
Jan 29 14:08:35 postfix/smtpd[28031]: SSL_accept error from unknown[192.168.1.40]: 0
Jan 29 14:08:35 postfix/smtpd[28031]: warning: TLS library problem: 28031:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:s3_pkt.c:1493:SSL alert number 42:
Jan 29 14:08:35 postfix/smtpd[28031]: lost connection after STARTTLS from unknown[192.168.1.40]
Jan 29 14:08:35 postfix/smtpd[28031]: disconnect from unknown[192.168.1.40]
```

**Comment by piksel** [comment]
No, `tls skip verify` doesn't do anything in v1.1.6, use the following configuration to skip it for now (or turn off StartTLS in your SMTP):
```yaml
environment:
  WATCHTOWER_NOTIFICATIONS: shoutrrr
  WATCHTOWER_NOTIFICATIONS_LEVEL: "debug"
  WATCHTOWER_NOTIFICATION_URL: "smtp://:@192.168.1.30:25/?auth=None&encryption=None&fromaddress=watchtower@domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on a9ab1f2400bb&toaddresses=docker@domain.com&usehtml=No"
```
