### ISSUE TITLE
Scheduler next run log as debug level instead of info

### ISSUE THREAD

**Issue by fizcris** [containrrr/watchtower#801]
**Describe the bug**

When running watchover with the argument `--schedule, -s` the scheduled next run log is under `DEBUG` level. 

It should be as `INFO` level as the end user would not have any clue of the correct execution of the scheduled action if debug mode is not enabled.

`time="2021-01-27T05:33:05+01:00" level=debug msg="Scheduled next run: 2021-01-28 05:33:00 +0100 CET"
`

Otherwise, **an `INFO` log when the cron is started and finished would be as usefull**. But at the moment (without using the --debug option) there is no way to know if watchtower is working as intended.

**Setup using Docker Compose**

```
version: "3"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: "Europe/Madrid"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --cleanup --schedule "0 0 5 * * *"
    #command: --cleanup --schedule "0 0 5 * * *"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
```
