### ISSUE TITLE
I am using private repo and have made config.json file but watctower not retrieving latest image from docker hub and not sending any notification as well

### ISSUE THREAD

**Issue by bytehealer** [containrrr/watchtower#806]
my config for watchtower is as below. I have provided my private registry info inside the directory auto in folder .docker as config.json. Please advice why watchtoweris not retrieving latest image from private repo?

```
watchtower:
        container_name: watchtower
        restart: always
        image: index.docker.io/containrrr/watchtower:latest
        environment:
        - WATCHTOWER_NOTIFICATIONS=shoutrrr
        - "WATCHTOWER_NOTIFICATION_URL=smtp://test1.alcanzarsoft:ssxkpchhicnzkppk@smtp.gmail.com:465/?auth=Plain&encryption=Auto&fromaddress=test1.alcanzarsoft@gmail.com&fromname=Watchtower&starttls=Yes&subject=Watchtower_updates_on_container&toaddresses=mannawar.hussain@alcanzarsoft.com&usehtml=No"

         volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /auto/.docker/config.json:/config.json
        command: --debug true --cleanup true --interval 660

```
