### ISSUE TITLE
Watchtower no longer working with latest Docker version?

### ISSUE THREAD

**Issue by Altycoder** [containrrr/watchtower#852]
Watchtower has been working for me for months but has suddenly stopped working, possibly after a recent Docker update, but I'm not 100% sure.  My logs are now full of the following repeating messages:

```
time="2021-03-15T08:38:33Z" level=debug,
time="2021-03-15T08:38:33Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized.",
time="2021-03-15T08:38:34Z" level=debug msg="Retrieving running, stopped and exited containers",
time="2021-03-15T08:38:34Z" level=debug msg="There are no additional watchtower containers",
time="2021-03-15T08:38:34Z" level=debug msg="Watchtower HTTP API skipped.",
time="2021-03-15T11:14:16Z" level=info msg="Waiting for running update to be finished...",
time="2021-03-15T11:14:33Z" level=debug,
```

My config (no recent changes made):

```
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=<redacted>
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=<redacted>
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=<redacted>
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=<redacted>
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<redacted>
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NO_RESTART=true
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_CLEANUP=false
      - WATCHTOWER_DEBUG=true
```

Host:
 - Arch x64 host runng 5.10.x LTS kernel
 - Docker version: 20.10.5, build 55c4c88966
