### ISSUE TITLE
Log Spam via Email due to rate limit?

### ISSUE THREAD

**Issue by r2ixuz** [containrrr/watchtower#861]
**Describe the bug**
I am a private user who updates his 9 Docker containers (all from hub.docker.com registry) through Watchtower every saturday (so only once a week). Since several month I see a lot of this message in the report email:

Could not do a head request, falling back to regular pull.

As I understand it correctly, this should already be fixed via issue as described here: #715. So I am using already the latest version. Why I still get this message spam? Is this due to the rate limit which hub.docker.com introduced a while ago?

This "HEAD" warn message appears instantly for the first container which Watchtower tries to update.

**To Reproduce**
Let Watchtower update all containers weekly.

**Expected behavior**
I should only see in the report email, which containers were updated as it was some month ago.

**Screenshots**
--

**Environment**
 - Platform: gentoo stable
 - Architecture: amd64
 - Docker version: 19.03.15

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```

```

</details>

**Additional context**

**Comment by simonaronsson** [comment]
Hi,

We need to see the command (or compose file) you used to launch watchtower, as well as any logs you have that might help bring clarity to the issue.

Best,
Simme

**Comment by r2ixuz** [comment]
So here is my docker-compose file:

```
version: '2'
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xyz@domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xyz@domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=192.168.1.254
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 6 * * 6
      - TZ=Europe/Berlin
    hostname: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
I just tried the new version 1.2.0 but the container is only restarting with:

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by simonaronsson** [comment]
Thank you for the swift report! I've just released `v1.2.1` which should fix this issue. Please let me know whether it resolves it for you.

**Comment by DannyBoyKN** [comment]
I still do get the message "_Could not do a head request, falling back to regular pull._", last yesterday evening 2021-04-01 without any container updates. I restart watchtower this morning again, but the log only reports:  

`time="2021-04-02T07:57:14Z" level=info msg="Watchtower v0.0.0-unknown\nUsing notifications: pushover\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-04-02 19:57:14 +0000 UTC\nNote that the first check will be performed in 11 hours, 59 minutes, 59 seconds"
`

Why ```v0.0.0-unknown``` ?
How do I know that version 1.2.1 is effectively being executed ?

This is my compose file:
```
version: "3.6"
services:
  watchtower:
    image: containrrr/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - "WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:<devicetag>@<usertag>/?devices=<device>"
      - "WATCHTOWER_NOTIFICATION_TEMPLATE={{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
    command: --interval 43200 --cleanup
    restart: unless-stopped
```
