### ISSUE TITLE
Discord watchtower / shoutrrr failing after 1.2.1

### ISSUE THREAD

**Issue by tombomb** [containrrr/watchtower#865]
**Describe the bug**
Just got the new update and now the app is failing to send discord messages via shoutrrr (This might belong in shoutrrr's github but I'm not sure where the underlining error is). Webhook url was working till latest update.

**Image of it working before update**
![image](https://user-images.githubusercontent.com/544509/112770561-32faf880-8ff5-11eb-82f0-cb70246b53e1.png)

**To Reproduce**
1. Start container with `WATCHTOWER_NOTIFICATION_URL`
2. Get 400 error in logs  

**Expected behavior**
Message to send

**Screenshots**
![image](https://user-images.githubusercontent.com/544509/112770485-db5c8d00-8ff4-11eb-9275-7fa76f5c58fe.png)

**Environment**
 - Platform
 - Architecture
 - Docker version 

The section from my docker-compose stack pertaining to watchtower (redacted some of the webhook as to not give it out)

```
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - default
      - socket_proxy
    depends_on:
      - socket-proxy
    volumes:
      - $DOCKERDIR/watchtower:/config
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "0 30 12 * * *" # Everyday at 12:30 # "*/30 * * * *" # Every 10 mins
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://Q1p02j@7701"
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
      DOCKER_HOST: tcp://socket-proxy:2375
      DOCKER_CONFIG: /config
      DOCKER_API_VERSION: "1.40"
```

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2021-03-28T18:36:06-04:00" level=info msg="Watchtower v0.0.0-unknown\nUsing notifications: discord\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-03-29 12:30:00 -0400 EDT\nNote that the first check will be performed in 17 hours, 53 minutes, 53 seconds"


Failed to send notification via shoutrrr (url=discord://Q1p02jQGqJukmFo2ninybgxqIFUm8CADBmQIcMjgbiWCM_ZwqISIbEHmHqZvUGRDmOZV@770128369572118529):  failed to send discord notification: response status code 400 Bad Request
```

</details>

**Additional context**
