### ISSUE TITLE
Problem with docker-hub private repo

### ISSUE THREAD

**Issue by euberdeveloper** [containrrr/watchtower#893]
**Describe the bug**
With docker-hub private repos, config.json file works only with a user/repo. But I do not think that it is the right behaviour.

**To Reproduce**
I have this config.json:

```json
{
    "auths": {
        "https://index.docker.io/v1/": {
            "auth": "XXX"
        },
        "https://index.docker.io/v2/": {
            "auth": "XXX"
        },
        "registry.hub.docker.com": {
            "auth": "XXX"
        }
    },
    "HttpHeaders": {
        "User-Agent": "Docker-Client/19.03.8 (linux)"
    }
}
```

And I run watchtower inside a `docker-compose.yml`:

```yml
watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_DEBUG: 'true'
      REPO_USER: carlinux
      REPO_USER: Coldfire5249Paganella
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /PATH/.docker/config.json:/config.json
```

**Expected behavior**
Having provided my credentials for DockerHub, it should work also with my private repo `myusername/myrepo`.

Instead, in the debug, I get sometihng such as "credentials for myuser not found".

It works instead if I add another auth with `myuser/myrepo`:

```json
{
    "auths": {
        "https://index.docker.io/v1/": {
            "auth": "XXX"
        },
        "https://index.docker.io/v2/": {
            "auth": "XXX"
        },
        "registry.hub.docker.com": {
            "auth": "XXX"
        },
        "myuser/myrepo": {
            "auth": "XXX"
        }
    },
    "HttpHeaders": {
        "User-Agent": "Docker-Client/19.03.8 (linux)"
    }
}
```
After that it works

**Environment**
 - Platform Linux
 - Architecture x64
 - Docker version 19.03
