### ISSUE TITLE
Error grabbing logs: unexpected EOF

### ISSUE THREAD

**Issue by bastienlandry1** [containrrr/watchtower#898]
Hello,

I am currently using WatchTower to watch a container with a NodeJS application. The container works fine, however when it is restarted by WatchTower, after a little moment (and a few logs), an error occurs:
`Error grabbing logs: unexpected EOF`

The container stills works fine except for the logs which are not showing up in the console any more. 
When I restart the container manually without using WatchTower, there is no log issue. Is there some flags I should use in the docker-compose file in order to make it work ?

Thank you in advance,
B.

docker-compose.yml :
```
version: "3.7"

services:
  nodejs-back:
    image: xxx
    restart: always
    logging:
       driver: "json-file"
       options:
          max-file: "3"
          max-size: "10m"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable --interval 300
```
