### ISSUE TITLE
Watchtower receives 401 Unauthorized when checking private repository package docker.pkg.github.com

### ISSUE THREAD

**Issue by DavidPetrov406785** [containrrr/watchtower#905]
**Describe the bug**
I cannot authenticate watchtower to check a pkg image. It doesn't work with the credentials in the /.docker/config.json or with REPO_USER and REPO_PASS. I can still do docker-compose pull and everythings works fine and if I go to the address https://docker.pkg.github.com/v2/edorado-ui/nautical-map/nautical-map/manifests/latest and log in with the username and password it returns a result.

REPO_PASS = "***" is set to my github token with all permissions allowed

**With environmental variables:**

docker-compose
```
  nautical-map:
    image: docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest
    container_name: map
    ports:
      - "3001:3001"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - REPO_USER="edorado-ui"
      - REPO_PASS="***"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config
    command: 
      --interval 30 -d
      map
```

Debug
```
time="2021-04-16T11:09:10Z" level=debug msg="Checking containers for updated images"
time="2021-04-16T11:09:10Z" level=debug msg="Retrieving running containers"
time="2021-04-16T11:09:10Z" level=debug msg="Trying to load authentication credentials." container=/map image="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T11:09:10Z" level=debug msg="Loaded auth credentials for user \"Edorado-UI\" on registry docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T11:09:10Z" level=debug msg="Got image name: docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T11:09:10Z" level=debug msg="Credentials loaded"
time="2021-04-16T11:09:10Z" level=debug msg="Checking if pull is needed" container=/map image="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T11:09:10Z" level=debug msg="Building challenge URL" URL="https://docker.pkg.github.com/v2/"
time="2021-04-16T11:09:10Z" level=debug msg="Got response to challenge request" header="Basic realm=\"GitHub Package Registry\"" status="401 Unauthorized"
time="2021-04-16T11:09:10Z" level=debug msg="Parsing image ref" host=docker.pkg.github.com image=edorado-ui/nautical-map/nautical-map normalized="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest" tag=latest
time="2021-04-16T11:09:10Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://docker.pkg.github.com/v2/edorado-ui/nautical-map/nautical-map/manifests/latest"
time="2021-04-16T11:09:10Z" level=debug msg="Could not do a head request, falling back to regular pull."
time="2021-04-16T11:09:10Z" level=debug msg="Reason: registry responded to head request with &{401 Unauthorized 401 HTTP/1.1 1 1 map[Access-Control-Allow-Methods:[GET, HEAD, OPTIONS] Access-Control-Allow-Origin:[*] Content-Length:[205] Content-Security-Policy:[default-src 'none';] Content-Type:[text/plain; charset=utf-8] Date:[Fri, 16 Apr 2021 11:09:10 GMT] Docker-Distribution-Api-Version:[registry/2.0] Server:[GitHub Registry] Strict-Transport-Security:[max-age=31536000;] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Github-Request-Id:[F253:6B0F:C6CAE:F12AF:60797056] X-Xss-Protection:[1; mode=block]] {} 205 [] false false map[] 0xc00018a500 0xc00030a000}"
time="2021-04-16T11:09:10Z" level=debug msg="Pulling image" container=/map image="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T11:09:11Z" level=debug msg="Error pulling image docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest, Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured."
time="2021-04-16T11:09:11Z" level=info msg="Unable to update container \"/map\": Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.. Proceeding to next."
time="2021-04-16T11:09:11Z" level=debug msg="Scheduled next run: 2021-04-16 11:09:40 +0000 UTC"
```

**With config.json**

docker-compose
```
  nautical-map:
    image: docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest
    container_name: map
    ports:
      - "3001:3001"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config
    command: 
      --interval 30 -d
      map
```

Debug
```
time="2021-04-16T12:29:46Z" level=debug msg="Checking containers for updated images"
time="2021-04-16T12:29:46Z" level=debug msg="Retrieving running containers"
time="2021-04-16T12:29:46Z" level=debug msg="Trying to load authentication credentials." container=/map image="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T12:29:46Z" level=debug msg="No credentials for docker.pkg.github.com found" config_file=/config.json
time="2021-04-16T12:29:46Z" level=debug msg="Got image name: docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T12:29:46Z" level=debug msg="Checking if pull is needed" container=/map image="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T12:29:46Z" level=debug msg="Building challenge URL" URL="https://docker.pkg.github.com/v2/"
time="2021-04-16T12:29:46Z" level=debug msg="Got response to challenge request" header="Basic realm=\"GitHub Package Registry\"" status="401 Unauthorized"
time="2021-04-16T12:29:46Z" level=debug msg="Could not do a head request, falling back to regular pull."
time="2021-04-16T12:29:46Z" level=debug msg="Reason: no credentials available"
time="2021-04-16T12:29:46Z" level=debug msg="Pulling image" container=/map image="docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest"
time="2021-04-16T12:29:46Z" level=debug msg="Error pulling image docker.pkg.github.com/edorado-ui/nautical-map/nautical-map:latest, Error response from daemon: Head https://docker.pkg.github.com/v2/edorado-ui/nautical-map/nautical-map/manifests/latest: no basic auth credentials"
time="2021-04-16T12:29:46Z" level=info msg="Unable to update container \"/map\": Error response from daemon: Head https://docker.pkg.github.com/v2/edorado-ui/nautical-map/nautical-map/manifests/latest: no basic auth credentials. Proceeding to next."
time="2021-04-16T12:29:46Z" level=debug msg="Scheduled next run: 2021-04-16 12:30:16 +0000 UTC"
```

Please tell me what I am doing wrong as I have spent hours and can't find a solution.
