### ISSUE TITLE
Notification configuration (including credentials) written to stdout upon startup

### ISSUE THREAD

**Issue by BeyondVertical** [containrrr/watchtower#906]
**Describe the bug**
Since an update a few weeks ago it seems, that the output of the log is a little corrupted or weird.
There is also the password for the smtp account visible in there. Not good.

**To Reproduce**
Start watchtower (version 1.2.1) in docker, then the output is the following:

```
smtp://FROM_MAIL_USER:MAIL_PASSWORD@MAIL_SERVER:587/?auth=Plain&encryption=Auto&fromaddress=FROM_MAIL_ADDRESS&fromname=Watchtower&starttls=Yes&subject=%5BMailcow%5D+Watchtower+updates+on+a6d00da12cee&toaddresses=TO_MAIL_USER&usehtml=No
time="2021-04-16T19:32:15+02:00" level=info msg="Watchtower v0.0.0-unknown\nUsing notifications: smtp\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-04-17 05:00:00 +0200 CEST\nNote that the first check will be performed in 9 hours, 27 minutes, 44 seconds"
```

I have censored the output a little and removed the mail server, the mail addresses and the mail password.
The output version in the logs is very weird. I have pulled the 1.2.1 image, multiple times. Same output.

Here is my docker compose file - obviously also censored:

```
version: '3'

services:
  watchtower:
    image: containrrr/watchtower:1.2.1
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 5 * * *" --cleanup
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=FROM_MAIL_ADDRESS
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=TO_MAIL_ADDRESS
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=MAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=FROM_MAIL_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=MAIL_PASSWORD
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=[Mailcow]
    networks:
      - proxy

networks:
  proxy:
    external: true
```

**Expected behavior**
The log output before was simply the time at which watchtower is running next - no further output.
Also the line breaks worked as expected.

**Environment**
 - Platform: Ubuntu 20.04.02 LTS
 - Architecture: x86_64
 - Docker version: 20.10.6, build 370c289
