### ISSUE TITLE
Watchtower not being (re)launched every WATCHTOWER_POLL_INTERVAL seconds

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [containrrr/watchtower#940]
**Describe the bug**

Although a timeframe of 180 seconds has been passed as env var during watchtower deployment, this seems to be idle for (at least) 3 hours

**To Reproduce**

Install watchtower with the following ansible task

```
    - name: Start docker watchtower
      community.docker.docker_container:
        name: watchtower-container
        image: containrrr/watchtower
        env:
          WATCHTOWER_NOTIFICATIONS: "slack"
          WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ slack_webhook_url }}"
          WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "{{ slack_channel }}"
          WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
          WATCHTOWER_POLL_INTERVAL: "180" # 3 minutes
          WATCHTOWER_CLEANUP: true
        mounts:
          - source: "/var/run/docker.sock"
            target: "/var/run/docker.sock"
            type: bind
      become: yes
```

**Expected behavior**

Watchtower should be starting every 3 mins checking for container chages.

**Screenshots**

**Environment**

```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
# docker --version
Docker version 20.10.6, build 370c289
```

**Additional context**

```
root@ip-192-168-1-20:~# docker logs -f f23e06db49b1
time="2021-04-26T18:54:12Z" level=info msg="Watchtower 1.3.0\nUsing notifications: slack\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-04-26 18:57:12 +0000 UTC\nNote that the first check will be performed in 2 minutes, 59 seconds"
time="2021-04-26T18:55:33Z" level=info msg="Waiting for running update to be finished..."
root@ip-192-168-1-20:~# date
Mon Apr 26 21:58:22 UTC 2021
root@ip-192-168-1-20:~# docker ps -a | grep -i watchtower
f23e06db49b1   containrrr/watchtower   "/watchtower"            3 hours ago   Exited (1) 3 hours ago                                                         watchtower-container
```
