### ISSUE TITLE
Cannot send http request from node.js container to watchtower running HTTP API mode

### ISSUE THREAD

**Issue by DavidPetrov406785** [containrrr/watchtower#950]
For the life of me I cannot send an http request from my node.js container to my watchtower containter which is in http api mode to trigger it.

In my node website I am sending this through a button click and It just times out.
```
    fetch('http://localhost:8080/v1/update', {
        method: 'POST',
        headers: {
            Authorization : 'Bearer mytoken'
        }
    })
```
And this is my docker-compose
```
  dashboard:
    image: docker.pkg.github.com/edorado-ui/dashboard/dashboard:latest
    container_name: dashboard
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      test-network:
        ipv4_address: 172.19.0.6

  wt:
    image: containrrr/watchtower
    container_name: wt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - E:/University/3rd_Year/Intership/watchtower/config.json:/config.json
    command: 
      -d --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
    ports:
      - "8080:8080"
    networks:
      test-network:
        ipv4_address: 172.19.0.10

        
networks:
  test-network:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
```

In the button I currently send to localhost but I have also tried http://172.19.0.10:8080/v1/update and http://wt:8080/v1/update
and they get timed out. I tried doing it with the default network, with links, nothing. I can ping watchtower from dashboard so they have a connection I just have no idea where it is.

When I make watchtower run on a different network and I try ip http://localhost:8080/v1/update it is the only time when I actually get a responce and it is rejected **CORS error: PreflightMissingAllowOriginHeader** which from what I found is a problem in the backend aka watchtower somehow? In all cases I don't get anything in the watchtower console so nothing is getting to it.

To top it all off if I send the request to http://localhost:8080/v1/update with the Authorization Header: Bearer mytoken through cUrl, Insomnia, PostMan it works without a problem and the watchtower updates the containers.
HELP!
