### ISSUE TITLE
Unable to get it to work with ECR 

### ISSUE THREAD

**Issue by kanishkatn** [containrrr/watchtower#957]
**Describe the bug**

Not working with ECR images. 

**To Reproduce**

1. Follow the guide at https://containrrr.dev/watchtower/private-registries/#credential_helpers
2. Create docker containers with ECR images
3. Start watchtower

My docker-compose.yml
```yaml
version: "3.4"
services:
 watchtower:
   image: containrrr/watchtower:latest
   container_name: watchtower
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/ubuntu/.docker/config.json:/config.json
     - helper:/go/bin
     - /home/ubuntu/.aws:/./aws
   environment:
     - HOME=/
     - PATH=$PATH:/go/bin
     - AWS_REGION=us-southeast-1
   command: --interval 30
volumes:
 helper:
   external: true
```

**Expected behavior**
Should be able to watch and update containers from ECR images. 

**Actual behaviour**

I get an error saying 
`time="2021-05-08T15:05:34Z" level=info msg="Unable to update container \"/[container-name]\": Error response from daemon: Get https://[redacted].dkr.ecr.ap-southeast-1.amazonaws.com/v2/[ecr-repo]/manifests/latest: no basic auth credentials. Proceeding to next."`

**Environment**

 - Platform: Ubuntu
 - Docker version: 19.03.5, build 633a0ea838
