### ISSUE TITLE
Email notifications stopped working - failed to send using smtp: timed out

### ISSUE THREAD

**Issue by OliverHi** [containrrr/watchtower#959]
I am running the latest version of watchtower via docker-compose. The relevant file looks like this:
```
version: "3"
services:
    watchtower:
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - TZ=${TZ}
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_NOTIFICATIONS=email
          - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
          - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}
```
I have a .env file in the same directory with all those server configurations. This worked perfectly well for some time. Then around March 29th the emails stopped. I just noticed now and checked the docker logs:
`Failed to send notification via shoutrrr (url=smtp://homeserver%40mydomain.de:abcdefg@smtp.strato.de:587/?auth=Plain&fromaddress=homeserver%40mydomain.de&fromname=Watchtower&subject=Watchtower+updates+on+8d91213263dd&toaddresses=dsagfes6m4%40pomail.net):  failed to send using smtp: timed out
` (I replaced my domain name and the smtp password). I did not change these variables or the email account during the time when it stopped working,.

Is there a way to get more information about what is failing here? I tried to ping or nslookup from inside the container but they are both not in the path. Has anything been changed with a recent update of watchtower? Let me know if I can provide any additional information.
