### ISSUE TITLE
Re: Multiple containers using the same image makes cleanup throw an error

### ISSUE THREAD

**Issue by schklom** [containrrr/watchtower#966]
Same issue as #963 but this time, I got debug logs :P

**To reproduce**
docker-compose.yml (relevant part)
```
services:
  app:
    container_name: ttrss
    image: schklom/ttrss-app:with-filelogging-latest
    environment: &ttrssenv
      - TTRSS_DB_TYPE=pgsql
      - TTRSS_DB_HOST=ttrss_db
      - TTRSS_DB_NAME=abcd
      - TTRSS_DB_USER=abcd
      - TTRSS_DB_PASS=abcd
      - TTRSS_SELF_URL_PATH=http://localhost:8280/tt-rss
    volumes: &ttrssvols
      - app:/var/www/html
  
  ttrss_updater:
    container_name: ttrss_updater
    image: schklom/ttrss-app:with-filelogging-latest
    depends_on:
      - app
    environment: *ttrssenv
    volumes: *ttrssvols
    networks: *ttrssnetw
    command: /opt/tt-rss/updater.sh

  ttrss_db:
    container_name: ttrss_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=abcd
      - POSTGRES_USER=abcd
      - POSTGRES_PASSWORD=abcd
    volumes:
      - db:/var/lib/postgresql/data

  ttrss_web_nginx:
    image: image: schklom/ttrss-web-nginx
    container_name: ttrss_web_nginx
    ports:
      - 8280:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app
  
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    container_name: watchtower
    environment:
      TZ: ${TZ}
      WATCHTOWER_RUN_ONCE: "true"
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_TIMEOUT: 15
    ...

volumes:
  app:
  db:
```
(The ttrss services originate from https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/static-dockerhub/docker-compose.yml and https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/static-dockerhub/.env-dist if anyone is interested.)

Relevant logs:
<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2021-05-24T02:46:00+02:00" level=debug
time="2021-05-24T02:46:00+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2021-05-24T02:46:01+02:00" level=debug msg="Making sure everything is sane before starting"
time="2021-05-24T02:46:01+02:00" level=debug msg="Checking containers for updated images"
time="2021-05-24T02:46:01+02:00" level=debug msg="Retrieving running containers"
time="2021-05-24T02:46:08+02:00" level=debug msg="Trying to load authentication credentials." container=/ttrss image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T02:46:08+02:00" level=debug msg="No credentials for schklom found" config_file=/config.json
time="2021-05-24T02:46:08+02:00" level=debug msg="Got image name: schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T02:46:08+02:00" level=debug msg="Checking if pull is needed" container=/ttrss image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T02:46:08+02:00" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-05-24T02:46:08+02:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-05-24T02:46:08+02:00" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-05-24T02:46:08+02:00" level=debug msg="Setting scope for auth token" image=schklom/ttrss-app scope="repository:schklom/ttrss-app:pull"
time="2021-05-24T02:46:08+02:00" level=debug msg="No credentials found."
time="2021-05-24T02:46:08+02:00" level=debug msg="Parsing image ref" host=index.docker.io image=schklom/ttrss-app normalized="docker.io/schklom/ttrss-app:with-filelogging-latest" tag=with-filelogging-latest
time="2021-05-24T02:46:08+02:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/schklom/ttrss-app/manifests/with-filelogging-latest"
time="2021-05-24T02:46:09+02:00" level=debug msg="Found a remote digest to compare with" remote="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295"
time="2021-05-24T02:46:09+02:00" level=debug msg=Comparing local="sha256:f5553633b910a4fbb9ce0a67dc943cc304f46b896ca6b11740978d7f439e4fb5" remote="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295"
time="2021-05-24T02:46:09+02:00" level=debug msg="Digests did not match, doing a pull."
time="2021-05-24T02:46:09+02:00" level=debug msg="Pulling image" container=/ttrss image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T02:46:36+02:00" level=info msg="Found new schklom/ttrss-app:with-filelogging-latest image (e71f98d1f9b7)"
......(other containers updated)
time="2021-05-24T02:46:48+02:00" level=info msg="Stopping /ttrss (b5ca029a52c2) with SIGTERM"
time="2021-05-24T02:46:51+02:00" level=debug msg="Removing container b5ca029a52c2"
time="2021-05-24T02:47:14+02:00" level=debug msg="This is the watchtower container /watchtower"
time="2021-05-24T02:47:14+02:00" level=info msg="Creating /ttrss"
time="2021-05-24T02:47:17+02:00" level=debug msg="Starting container /ttrss (b6d75d85410f)"
time="2021-05-24T02:47:29+02:00" level=info msg="Removing image 767fec1cfb92"
time="2021-05-24T02:47:29+02:00" level=error msg="Error response from daemon: conflict: unable to delete 767fec1cfb92 (cannot be forced) - image is being used by running container 3fe59bcda983"
time="2021-05-24T02:47:29+02:00" level=debug msg="Session done: 16 scanned, 1 updated, 0 failed"
```

</details>

<details>
 <summary><b> 2nd set of logs from running watchtower again a few minutes later with the <code>--debug</code> option </b></summary>

```
time="2021-05-24T03:43:11+02:00" level=debug
time="2021-05-24T03:43:12+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2021-05-24T03:43:13+02:00" level=debug msg="Making sure everything is sane before starting"
time="2021-05-24T03:43:13+02:00" level=debug msg="Checking containers for updated images"
time="2021-05-24T03:43:13+02:00" level=debug msg="Retrieving running containers"
time="2021-05-24T03:43:13+02:00" level=debug msg="Trying to load authentication credentials." container=/ttrss image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:43:13+02:00" level=debug msg="No credentials for schklom found" config_file=/config.json
time="2021-05-24T03:43:13+02:00" level=debug msg="Got image name: schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:43:13+02:00" level=debug msg="Checking if pull is needed" container=/ttrss image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:43:13+02:00" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-05-24T03:43:14+02:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-05-24T03:43:14+02:00" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-05-24T03:43:14+02:00" level=debug msg="Setting scope for auth token" image=schklom/ttrss-app scope="repository:schklom/ttrss-app:pull"
time="2021-05-24T03:43:14+02:00" level=debug msg="No credentials found."
time="2021-05-24T03:43:15+02:00" level=debug msg="Parsing image ref" host=index.docker.io image=schklom/ttrss-app normalized="docker.io/schklom/ttrss-app:with-filelogging-latest" tag=with-filelogging-latest
time="2021-05-24T03:43:15+02:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/schklom/ttrss-app/manifests/with-filelogging-latest"
time="2021-05-24T03:43:16+02:00" level=debug msg="Found a remote digest to compare with" remote="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295"
time="2021-05-24T03:43:16+02:00" level=debug msg=Comparing local="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295" remote="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295"
time="2021-05-24T03:43:16+02:00" level=debug msg="Found a match"
time="2021-05-24T03:43:16+02:00" level=debug msg="No pull needed. Skipping image."
time="2021-05-24T03:43:16+02:00" level=debug msg="No new images found for /ttrss"
......
time="2021-05-24T03:45:22+02:00" level=debug msg="Trying to load authentication credentials." container=/ttrss_updater image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:45:22+02:00" level=debug msg="No credentials for schklom found" config_file=/config.json
time="2021-05-24T03:45:22+02:00" level=debug msg="Got image name: schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:45:22+02:00" level=debug msg="Checking if pull is needed" container=/ttrss_updater image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:45:22+02:00" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-05-24T03:45:22+02:00" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-05-24T03:45:22+02:00" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-05-24T03:45:22+02:00" level=debug msg="Setting scope for auth token" image=schklom/ttrss-app scope="repository:schklom/ttrss-app:pull"
time="2021-05-24T03:45:22+02:00" level=debug msg="No credentials found."
time="2021-05-24T03:45:22+02:00" level=debug msg="Parsing image ref" host=index.docker.io image=schklom/ttrss-app normalized="docker.io/schklom/ttrss-app:with-filelogging-latest" tag=with-filelogging-latest
time="2021-05-24T03:45:22+02:00" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/schklom/ttrss-app/manifests/with-filelogging-latest"
time="2021-05-24T03:45:23+02:00" level=debug msg="Found a remote digest to compare with" remote="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295"
time="2021-05-24T03:45:23+02:00" level=debug msg=Comparing local="sha256:f5553633b910a4fbb9ce0a67dc943cc304f46b896ca6b11740978d7f439e4fb5" remote="sha256:7df0ea6baf242e3530c8d3d76edba6e3b7d8c171dc71abf753e967b05cb4a295"
time="2021-05-24T03:45:23+02:00" level=debug msg="Digests did not match, doing a pull."
time="2021-05-24T03:45:23+02:00" level=debug msg="Pulling image" container=/ttrss_updater image="schklom/ttrss-app:with-filelogging-latest"
time="2021-05-24T03:45:24+02:00" level=info msg="Found new schklom/ttrss-app:with-filelogging-latest image (e71f98d1f9b7)"
......
time="2021-05-24T03:45:55+02:00" level=info msg="Stopping /ttrss_updater (3fe59bcda983) with SIGTERM"
time="2021-05-24T03:45:55+02:00" level=error msg="Error response from daemon: Cannot kill container: 3fe59bcda98341529033f5a330a636ed07960c42aeceae371f7a63fa6fa5a758: No such container: 3fe59bcda98341529033f5a330a636ed07960c42aeceae371f7a63fa6fa5a758"
......
time="2021-05-24T03:46:12+02:00" level=info msg="Creating /ttrss_updater"
time="2021-05-24T03:46:12+02:00" level=error msg="Error response from daemon: Conflict. The container name \"/ttrss_updater\" is already in use by container \"857d7165a6351637e3c7f1a20c1394e8e572a56ba96bbbcc116ae182ea0f8dc6\". You have to remove (or rename) that container to be able to reuse that name."
......
time="2021-05-24T03:46:16+02:00" level=info msg="Removing image e14cb9e9fed5"
time="2021-05-24T03:46:21+02:00" level=info msg="Removing image 6ad8eab63126"
time="2021-05-24T03:46:28+02:00" level=info msg="Removing image 98e33de5d3f3"
time="2021-05-24T03:46:28+02:00" level=info msg="Removing image 767fec1cfb92"
time="2021-05-24T03:46:30+02:00" level=info msg="Removing image 1f079eb8752a"
time="2021-05-24T03:46:30+02:00" level=info msg="Removing image 18c3100d0424"
time="2021-05-24T03:46:31+02:00" level=info msg="Removing image 3e38aded896a"
time="2021-05-24T03:46:34+02:00" level=debug msg="Session done: 29 scanned, 5 updated, 2 failed"
```

</details>

**Additional context**
Watchtower scanned all 16 containers the 1st time, then 29 containers.
The error made the process stop for some reason.
In the end, I had to remove and restart `ttrss_updater`.

Question: how can I fix this behaviour?

I appreciate any help you can offer 👍 

EDIT: Removed `WATCHTOWER_SCHEDULE` from the environment variables, I forgot to remove it from my docker-compose for some reason.

**Comment by piksel** [comment]
At an initial glance, this seems likely to cause an issue:
```yaml
  app:
    image: schklom/ttrss-app:with-filelogging-latest
```
```yaml
  ttrss_updater:
    image: schklom/ttrss-app:with-filelogging-latest
    depends_on:
      - app
```
Could you include the logs regarding `ttrss_updater` (cut out in `......(other containers updated)`)?
The error is probably not *causing* the other container to not get updated, but rather something is causing it to not consider the second one stale...

> Watchtower scanned all 16 containers the 1st time, then 29 containers.

Yeah, sorry, I presumed wrongly that the counters resets between runs, but it doesn't, so the log message reflects that confusion. 

How are you running watchtower btw?
This compose entry looks odd:
```yaml
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    container_name: watchtower
    environment:
      WATCHTOWER_RUN_ONCE: "true"
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE}
```
With `run once` it runs immediately on `docker compose up`, and ignores the schedule. It also doesn't update itself (or check for other running updates). Not sure if it contains anything relevant right now, but you should probably not have `WATCHTOWER_NO_STARTUP_MESSAGE: "true"` set when debugging, since it contains a summary of how it's configured.
