### ISSUE TITLE
Using Proxy Server for HEAD Requests

### ISSUE THREAD

**Issue by skuep** [containrrr/watchtower#980]
Hi everyone,
Been using watchtower for a long time and it works very well.
Recently, HEAD requests have been implemented to alleviate rate-limiting issues, as I understand correctly.
However, all of our servers are behind a whitelisted proxy server for outgoing connections (which docker already uses for pulling). 

After implementing the HEAD request feature, watchtower regularly reports :
``Could not do a head request for "containrrr/watchtower:latest", falling back to regular pull.
Reason: Get "https://index.docker.io/v2/": dial tcp 34.195.201.174:443: i/o timeout``

After some digging, it seems like the request to above mentioned host is not done through our proxy server, which causes it (correctly) to fail. I guess the question now is, how to make watchtower use our proxy server? 
I already added environment entries for the watchtower docker-container in docker-compose.yml:
````
        image: containrrr/watchtower
        command: --schedule "0 0 4 * * *" --cleanup --label-enable
        container_name: watchtower
        restart: always
        labels:
            com.centurylinklabs.watchtower.enable: true
        environment:
            - http_proxy: http://<proxy.url>
            - https_proxy: http://<proxy.url>
            - HTTP_PROXY: http://<proxy.url>
            - HTTPS_PROXY: http://<proxy.url>
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
````

But it still fails with the same problem. I suspect that the problem might be here:
https://github.com/containrrr/watchtower/blob/dec6f84a7085e5d24716da10b4d4781a9c3d47d0/pkg/registry/auth/auth.go#L35

No transport information is given, in contranst to here:
https://github.com/containrrr/watchtower/blob/dec6f84a7085e5d24716da10b4d4781a9c3d47d0/pkg/registry/digest/digest.go#L86

Do you have maybe an idea, what we could try to make HEAD requests work via proxy? After watchtower reverts to the regular pull method, everything updates properly. However the above given warning is issued.

**Comment by skuep** [comment]
Okay, nevermind. After opening an issue because I was pulling my hair out for hours...
It seems like the problem was having to do with ``environment`` syntax in docker-compose. Now it works!

**Comment by piksel** [comment]
@skuep Yeah, I always recommend the dict/map syntax for environment variables due to this. It still have some caveats, but it's at least just common YAML syntax, not some parsing rules inside docker-compose that does something unexpected.
For reference:
```yaml
        environment:
            http_proxy: "http://my.proxy.tld:8080"
            https_proxy: "http://my.httpsProxy.tld:8080"
```
